### PR TITLE
Search for and provide domain in horizon check

### PR DESCRIPTION
**Pull request by sigmavirus24**
In multi-domain deployments of RPC OpenStack, Horizon will require the
user to enter a domain name. As such, we need to provide that
information when posting our login request to Horizon in our MaaS check
plugin.

To detect the multi-domain case, we search for an input field named
"domain" and only then do we provide it. To make the check slightly more
efficient we also refactor it to just parse the HTML once instead of 2
or 3 times.

Connects #1262

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/staging.horse/build-9b6e14f131/docs/private-cloud/release-notes/)

**Comment by sigmavirus24** [comment]
recheck_ceph - ssh timeout in tempest

**Comment by sigmavirus24** [comment]
recheck_ugprade - failed to install elasticsearch-curator

**Comment by sigmavirus24** [comment]
recheck_upgrade - failed to install elasticsearch-curator

**Comment by sigmavirus24** [comment]
recheck_upgrade - Hugh fixed the elasticsearch-curator bug in the gate

**Comment by sigmavirus24** [comment]
recheck_upgrade - failed galera checks (innodb deadlock0

**Comment by Apsu** [comment]
I don't like your XPaths, but that's just a matter of taste. Best tool for the job sadly. 👍

**Comment by cloader89** [comment]
👍 LGTM.

**Pull request merged**
