### PR TITLE
Update OSA Submodule to head of Liberty

### PR DESCRIPTION
**Pull request by hughsaunders**
My motivation for moving forwards is that
362828cea9b831ed7d0cd6f43725fa80f073bbc6 is required for  defcore tests.
However we may as well move to head of Liberty rather than just that commit.

### CODE REVIEW

**Comment by hughsaunders** [comment]
Also related: #852

**Comment by hughsaunders** [comment]
recheck - no master swift/full job started.

**Comment by prometheanfire** [comment]
:+1:

**Comment by prometheanfire** [comment]
iirc, this was being held back by https://github.com/rcbops/rpc-openstack/issues/864 is that in contained within this update?

**Pull request merged**
