### PR TITLE
Update liberty-12.1 SHA to HEAD of liberty.

### PR DESCRIPTION
**Pull request by d34dh0r53**
Update liberty-12.1 SHA to HEAD of liberty as of 04-04-2016.  Includes
typo fix and MySQL retry logic.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Shouldn't this be titled "Update liberty-12.1 SHA to HEAD of liberty"?

**Comment by d34dh0r53** [comment]
Doh, good catch

**Comment by prometheanfire** [comment]
this is very yes :+1:

**Comment by d34dh0r53** [comment]
@prometheanfire another good catch, thanks!

**Comment by prometheanfire** [comment]
re :+1: with reservations (getting this out more important than perfect commit message apparently :P)

**Comment by d34dh0r53** [comment]
recheck_upgrade

**Comment by stevelle** [comment]
gating: http://i1.kym-cdn.com/photos/images/facebook/000/289/958/515.gif
change :+1:

**Comment by prometheanfire** [comment]
that's two

**Pull request merged**
