### PR TITLE
Force TLS-1.2 for haproxy connections

### PR DESCRIPTION
**Pull request by prometheanfire**
Issue: [RI-567](https://rpc-openstack.atlassian.net/browse/RI-567)

### CODE REVIEW

**Comment by prometheanfire** [comment]
recheck_xenial_no_artifacts_swift_deploy
recheck_bionic_no_artifacts_swift_deploy

**Comment by prometheanfire** [comment]
recheck_xenial_no_artifacts_swift_deploy
recheck_bionic_no_artifacts_swift_deploy

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by prometheanfire** [comment]
recheck_xenial_no_artifacts_swift_deploy
recheck_bionic_no_artifacts_swift_deploy

**Comment by prometheanfire** [comment]
recheck_xenial_no_artifacts_swift_deploy

**Pull request merged**
