### PR TITLE
Extract maas tasks targeting hosts only

### PR DESCRIPTION
**Pull request by mancdaz**
Refactor to make it easier to read and follow what is going on in maas
installs.

Fixes issue #167

(cherry picked from commit a78cebf02aa8c6d29825f8238f24e576c7337be7)

### CODE REVIEW

**Comment by git-harry** [comment]
@mancdaz https://github.com/rcbops/rpc-openstack/pull/198

**Comment by prometheanfire** [comment]
:+1:

**Comment by mancdaz** [comment]
@git-harry as discussed I added commit 545bfb8260a1579084ba881b3be7ea0a726f4f14 to this PR (from #198)

**Comment by mattt416** [comment]
:+1:

**Comment by prometheanfire** [comment]
ok, fix from #197 being backported here

Closes #197

**Pull request merged**
