### PR TITLE
Fix bash linting errors

### PR DESCRIPTION
**Pull request by ameserole**
This commit fixes errors that came up when running the new bashate
linting test script. The errors fixed were simple syntax fixes in
the deploy.sh and f5-monitor.sh files. This needs to be merged
in order for the bashate linting script to pass the Travis CI
build gating tests.

addresses pull request #1189

### CODE REVIEW

**Comment by ameserole** [comment]
Once this passes and merges the Travis CI build tests on https://github.com/rcbops/rpc-openstack/pull/1189 will pass.

**Comment by alextricity25** [comment]
+1

**Comment by Frank-ZhangXin** [comment]
👍

**Comment by Apsu** [comment]
RPC-AIO-Ceph-Liberty-PR: Pass

**Comment by Apsu** [comment]
RPC-AIO-Liberty-PR: Pass

**Comment by major** [comment]
:+1: Looks good to me and tests are passing.

**Pull request merged**
