### PR TITLE
Set Host sshd_config MaxSessions option to 100

### PR DESCRIPTION
**Pull request by prometheanfire**
The sshd role imported by OSA was used for this.  I did create a
new role so that we could run this early, as this is host setup.

Fixes: #1070
Connected #1070

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/staging.horse/build-33131df31d/docs/private-cloud/release-notes/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/staging.horse/build-f38781233e/docs/private-cloud/release-notes/)

**Comment by odyssey4me** [comment]
:-1: I don't really understand why a new role is required when there is already one that can do the job for you which is already included in the ansible-role-requirements. https://github.com/willshersystems/ansible-sshd

That role is well tested and using it will allow a lot more configurability for support than just the one thing.

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/staging.horse/build-d1bc66f59b/docs/private-cloud/release-notes/)

**Comment by prometheanfire** [comment]
@odyssey4me ok, updated, but keep in mind this now clobbers osa-security stuff every time it runs.

**Comment by prometheanfire** [comment]
also, link is failing due to that role...

**Comment by odyssey4me** [comment]
@prometheanfire I was simply suggesting an alternative. Note that every single setting you could possibly want in sshd_config is configurable if you give it the vars - so if you want to preserve something, give the role the right vars!

Otherwise, instead of using the heavy-handed approach you first took - just add a lineinfile task into the support role or a playbook. A whole role to edit one line seems a vast overkill.

**Comment by prometheanfire** [comment]
Adding the role is more so when requests that will inevitably come down the line for more host customization do come, we are prepared.  Also, I can't do a simple line in file because of the way sshd_config is formatted (optional sections).  I do think my original way is better and still have the patch if people agree.

**Comment by cloader89** [comment]
recheck_all

**Comment by cloader89** [comment]
recheck_all

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/staging.horse/build-c76f50e270/docs/private-cloud/release-notes/)

**Comment by cloader89** [comment]
recheck_upgrade

**Comment by mattt416** [comment]
👎 From the parent issue it feels like we were going to remove overriding of ansible forks (which happens in a few places in rpc-openstack) and making relevant doc changes.  I didn't get the impression that we were proceeding with this new role.

**Comment by odyssey4me** [comment]
:-1: +461 LOC just to change a setting I truly believe should be implemented by a kick system and not by us. I am strongly against merging this.

**Comment by BjoernT** [comment]
MaxSessions is important to get the roles working correctly, especially the swift one which seem to fail quite often, if not always, once you increase the forks. From that standpoint I'm in favor of just setting MaxSession inside the SSHd config, nothing else. The SSHD ansible role would maintain the whole config which we don't have control over since customer run their own config management. 
And that conflicts using the SSHD role. So personally I would prefer to add the one liner to fix most out of the box deployments since we only have KIR (kick in the rack) only available on the minority of hosts. Most hosts are managed in customer environments now.
Additionally documentation needs to be provided for customer completely overwriting the config and  we are all aware of it.

Perhaps another way may be to start SSHD with the -o MaxSessions=100 option etc but I'm generally in favor of this PR since if fixes a fundamental problem and I'm personally not seeing this different from what we already do with all the sysctl changes or installing packages.
If the RPC-O needs a operating system condition met to install the product we either check on it or make it happen, i.e. installing packages, maintaining kernel settings etc. etc.

**Comment by b3rnard0** [comment]
@git-harry @mattt416 @odyssey4me Can you please look into @BjoernT response so we can get additional feedback.

**Comment by odyssey4me** [comment]
As previously suggested, and reiterated. The patch can be vastly simplified to a simple lineinfile task in the support role. This will cover what's required and build far less tech debt.

**Comment by prometheanfire** [comment]
@odyssey4me lineinfile doesn't work on formatted sshd config files @major can you explain why, since you have more experience with it.

@odyssey4me also, putting it in the support role will not prevent this issue from occuring during initial deployments, as the support role is one of the last to run, that is why I created an 'early run' version of it.

**Comment by b3rnard0** [comment]
@mancdaz Can you please make sure we get feedback from the UK folks on Monday? Thanks.

**Comment by evrardjp** [comment]
Agreed with @odyssey4me, we can simplify to either:
- own the complete file, because it's an inherent part of our process
- reduce to a few tasks.

Here would be the tasks:
```
  - name: Find for Match in ssh server config
    command: egrep -n '^Match' /etc/ssh/sshd_config
    register: match_in_sshd_config
    failed_when: false
    changed_when: false

  #Set MaxSessions to 100 to allow for more multiplexing
  - name: Ensure MaxSessions is defined to our standards (Match clause)
    lineinfile:
      line: 'MaxSessions 100'
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^(#)?MaxSessions'
      insertbefore: "^Match"
      validate: '/usr/sbin/sshd -T -f %s'
    when: match_in_sshd_config.rc == 0

  - name: Ensure MaxSessions is defined to our standards (no Match clause)
    lineinfile:
      line: "MaxSessions 100"
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^(#)?MaxSessions'
      insertafter: "EOF"
      validate: '/usr/sbin/sshd -T -f %s'
    when: match_in_sshd_config.rc == 1

```

**Comment by prometheanfire** [comment]
@evrardjp the reason why `before` does not work with `lineinfile`

https://github.com/rcbops/rpc-openstack/issues/1070#issuecomment-258866368

**Comment by mattt416** [comment]
@prometheanfire OK, but this is a solved problem right?  As far as I understand it, openstack-ansible-security is already handling sshd_config so can we not extract the bits that creates the marker etc. so that multiple playbooks/roles can do it in a consistent way?

**Comment by prometheanfire** [comment]
@mattt416 yes, it's solved in that I am using the same method used in osa-security.  In order to solve the bug though (which is about deployment issues) this needs to run first.  If we want only one marker that's fine, but it'd have to go upstream, I'm not sure @odyssey4me or @andymcc would want that in osa itself (also, given how early this needs to run I'm not sure where to put it).

**Comment by mattt416** [comment]
@prometheanfire Generally speaking this looks OK to me (haven't tested, still need to do).  However, I do still think there may be a need for a separate role/plugin that either lives in OpenStack or elsewhere that can be used by both rpc-openstack and openstack-ansible-security.  If OpenStack, it'll take some time for rpc-openstack to be able to consume that so perhaps outside of OSA would work best in this situation?  Would be good to get everyone else's thoughts here but I don't see any massive issues merging this and then removing it when we have something shared to use.

**Comment by mattt416** [comment]
👎 Until deploy.sh is updated so we can exercise this in the gate.

**Comment by prometheanfire** [comment]
ya, readded that, dunno how that was missed, maybe it was dropped because of a conflict when @cloader89 resubmitted it.

**Pull request closed without merging**
