### PR TITLE
[Backport - Newton] create distro specific maas process check symlink

### PR DESCRIPTION
**Pull request by alextricity25**
Xenial and Trusty both support different levels of cgroup functionality.
This has caused us to need different behavior for checking the status of
processes within containers.  In this commit we allow for both ways,
using a symlink to link to the correct version based on the Ubuntu
version installed.

Connects https://github.com/rcbops/u-suk-dev/issues/1101
(cherry picked from commit 3887f127673bfd960f8d14dadb133b33288ea15b)

### CODE REVIEW

**Comment by alextricity25** [comment]
Trusty maas job: http://jenkins.propter.net/job/JJB-RPC-AIO_newton-swift-periodic/50/
Xenial maas job: http://jenkins.propter.net/job/JJB-RPC-AIO_newton-xenial-periodic/45/
Both must pass before this can merge.

**Comment by alextricity25** [comment]
This backport needs to merge first before this one goes in: https://github.com/rcbops/rpc-openstack/pull/1791

**Comment by alextricity25** [comment]
Trusty maas job: http://jenkins.propter.net/job/JJB-RPC-AIO_newton-swift-periodic/52/
Xenial maas job: cantu/issue/1101/newton

**Comment by alextricity25** [comment]
recheck_all

**Comment by alextricity25** [comment]
Trusty maas job: http://jenkins.propter.net/job/JJB-RPC-AIO_newton-swift-periodic/53/
Xenial maas job: http://jenkins.propter.net/job/JJB-RPC-AIO_newton-xenial-periodic/48/

**Comment by alextricity25** [comment]
recheck_swift

**Comment by alextricity25** [comment]
Blocked by: https://github.com/rcbops/rpc-openstack/pull/1801

**Comment by alextricity25** [comment]
Trusty maas job: http://jenkins.propter.net/job/JJB-RPC-AIO_newton-swift-periodic/55/
Xenial maas job: http://jenkins.propter.net/job/JJB-RPC-AIO_newton-xenial-periodic/49/

**Comment by mattt416** [comment]
This should really be one script so we can avoid dropping symlinks into the git checkout, but this unblocks the period gate so happy to 👍 for now.

**Pull request merged**
