### PR TITLE
change the default config_drive_format to vfat

### PR DESCRIPTION
**Pull request by prometheanfire**
this will allow migrations to work
https://github.com/openstack/nova/blob/c9c0b1b4b5acc1ea3c2bbb694aa79d7e4a7087e3/nova/virt/libvirt/driver.py#L6237-L6251

Connects #783

### CODE REVIEW

**Comment by hughsaunders** [comment]
recheck

**Comment by BjoernT** [comment]
:+1:  We do this change quite often at customer environments who want to retain the live migration and config drives. But there is one known issue. Images with coreos are not able to mount vfat filesystems (at least stock) so we probably add a release note about those restrictions.

**Comment by d34dh0r53** [comment]
I think we will need release notes around Windows images as well.

**Comment by d34dh0r53** [comment]
Note to self, added `impacts-gating` as we may want to add a live migration test to the AIO.

**Comment by BjoernT** [comment]
Yeah, Windows seem to rely more on EC2 metadata than config drive but that depends on the used cloud-init agent. But it's true we need to include this information too

**Comment by prometheanfire** [comment]
@d34dh0r53 it looks like we can do this if we build nova in containers, but then we wouldn't be able to test cinder.  Both testing this (and cinder) might be better for when we do our multi-node test-release process.

**Comment by prometheanfire** [comment]
recheck

**Comment by prometheanfire** [comment]
Talked more with support and it seems like this is something that's already being done sometimes.

**Comment by prometheanfire** [comment]
so, what are the obstacles to getting this merged?

**Comment by BjoernT** [comment]
Support has no issues as long as we document this enough

**Comment by d34dh0r53** [comment]
:+1:

**Comment by prometheanfire** [comment]
recheck_upgrade

**Comment by git-harry** [comment]
I've closed this to keep the repo in good order. The pull request is referenced in https://github.com/rcbops/u-suk-dev/issues/245, which is the new issue tracking this work so when it becomes approved this code is available for use/reference.

**Pull request closed without merging**
