### PR TITLE
Change rpc-release to r11.1.0rc0

### PR DESCRIPTION
**Pull request by d34dh0r53**
This PR creates the r11.1.0rc0 release candidate for the kilo branch.

### CODE REVIEW

**Comment by prometheanfire** [comment]
:+1:

**Comment by sigmavirus24** [comment]
I thought our release documentation said we had to have things tested before creating an RC ;)

:+1: anyway

**Comment by prometheanfire** [comment]
qe needs a tag iirc, this is a place where reality and docs differ methinks

**Comment by claco** [comment]
Also, rc1  :-P

**Comment by sigmavirus24** [comment]
@claco we're programmers not pre-discovery-of-the-concept-of-zero Europeans

**Comment by byronmccollum** [comment]
can i get my grubby hands on this or what...?!?

**Comment by prometheanfire** [comment]
no, rc1 first

**Pull request merged**
