### PR TITLE
Update OSA SHA to tip of stable/mitaka

### PR DESCRIPTION
**Pull request by git-harry**
This update is required in preparation of the release of r13.0.0rc1.
The update includes the latest stable/mitaka SHA, which addresses:

- https://github.com/rcbops/u-suk-dev/issues/378
- https://github.com/rcbops/u-suk-dev/issues/417

In addtion this includes two fixes we weren't tracking that are needed:

- Use correct version when creating backup dir
  (622fc94a7e8f95a9391eb0fbe85e7a449fc35f85)
- load variables as a simple var for upgrades
  (42b2a79c816f289060a0abd35d3ef3924eb46852)

Connected https://github.com/rcbops/u-suk-dev/issues/442

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/staging.horse/build-5685bada09/docs/private-cloud/release-notes/)

**Comment by git-harry** [comment]
recheck_swift

**Comment by git-harry** [comment]
recheck_ceph

**Comment by mattt416** [comment]
👍 once gates finish

**Comment by mancdaz** [comment]
👍  pending gate

**Comment by git-harry** [comment]
recheck_swift

**Comment by mancdaz** [comment]
recheck_all

**Comment by prometheanfire** [comment]
I tested this manually on an AIO, worked there (swift specifically)

:+1:

**Comment by alextricity25** [comment]
recheck_all

**Comment by alextricity25** [comment]
My AIO didn't pass verify-maas.yml, There was some discussion in IRC, @mattt416 discovered some corrupted pacakge in rpc-repo, causing the nova-compute service to fail, and in in turn, causing the nova compute MaaS check to fail. From my understanding that should of been fixed now. We'll see if this fixes the gate!

**Comment by alextricity25** [comment]
recheck_swift

**Pull request merged**
