### PR TITLE
Update openstack-ansible SHA

### PR DESCRIPTION
**Pull request by git-harry**
This commit updates the openstack-ansible SHA in preparation for the
next release.

The following issues are addressed by this change:

Connects https://github.com/rcbops/rpc-openstack/issues/1112
(cherry picked from commit 5a5b9dc37796950f284bd62913fdff28fa60ece7)

### CODE REVIEW

**Comment by mancdaz** [comment]
Straight cherry pick 👍

**Comment by git-harry** [comment]
recheck_upgrade

**Comment by git-harry** [comment]
recheck_upgrade

**Comment by git-harry** [comment]
recheck_upgrade

**Comment by git-harry** [comment]
recheck_upgrade

**Pull request merged**
