### PR TITLE
update OSA to fix the pyparsing issue.

### PR DESCRIPTION
**Pull request by weezer**
https://bugs.launchpad.net/openstack-ansible/+bug/1660110

Configuration for using pyparsing 2.1.10

### CODE REVIEW

**Comment by weezer** [comment]
wrong branch

**Comment by weezer** [comment]
bring it up at the time when master been merged.

**Comment by cloader89** [comment]
@major it just merged.

**Comment by weezer** [comment]
my bad, i think i can drop it and make a new request. tks @major @cloader89

**Pull request closed without merging**
