### PR TITLE
Update MaaS scripts to use Keystone v3

### PR DESCRIPTION
**Pull request by sigmavirus24**
Now that os-ansible-deployment uses Keystone v3 by default, we need to
upgrade MaaS to use v3 as well. v3 is necessary for Keystone
Federation/ADFS happening usptream which we will be consuming, so we
need to upgrade our monitoring scripts to adjust for that.

Addresses #273

### CODE REVIEW

**Comment by mancdaz** [comment]
@sigmavirus24 I tested all the plugins on a master deployment, using this patch.  Some of the plugins also need updating where they are parsing the auth_ref themselves (mainly to grab the tenant/project id).  Here's a diff of changes I had to make:

```
diff --git a/maas/heat_api_local_check.py b/maas/heat_api_local_check.py
index 2c24fd1..e0ae90a 100755
--- a/maas/heat_api_local_check.py
+++ b/maas/heat_api_local_check.py
@@ -54,7 +54,7 @@ def check(args, tenant_id):

 def main(args):
     auth_ref = get_auth_ref()
-    tenant_id = auth_ref['token']['tenant']['id']
+    tenant_id = auth_ref['project']['id']
     check(args, tenant_id)


diff --git a/maas/nova_api_local_check.py b/maas/nova_api_local_check.py
index 9b3798a..b286e99 100755
--- a/maas/nova_api_local_check.py
+++ b/maas/nova_api_local_check.py
@@ -27,15 +27,13 @@ SERVER_STATUSES = ['ACTIVE', 'STOPPED', 'ERROR']

 def check(args):
     auth_ref = get_auth_ref()
-    auth_token = auth_ref['token']['id']
-    tenant_id = auth_ref['token']['tenant']['id']
+    tenant_id = auth_ref['project']['id']

     COMPUTE_ENDPOINT = 'http://{ip}:8774/v2/{tenant_id}' \
                        .format(ip=args.ip, tenant_id=tenant_id)

     try:
-        nova = get_nova_client(auth_token=auth_token,
-                               bypass_url=COMPUTE_ENDPOINT)
+        nova = get_nova_client(bypass_url=COMPUTE_ENDPOINT)
         is_up = True
     except exc.ClientException:
         is_up = False
@@ -51,7 +49,8 @@ def check(args):

         # gather some metrics
         status_count = collections.Counter(
-            [s.status for s in nova.servers.list(search_opts={'all_tenants': 1})]
+            [s.status for s in nova.servers.list(
+             search_opts={'all_tenants': 1})]
         )

     status_ok()
diff --git a/maas/nova_service_check.py b/maas/nova_service_check.py
index 71ea7dd..8cfa920 100755
--- a/maas/nova_service_check.py
+++ b/maas/nova_service_check.py
@@ -21,14 +21,13 @@ from maas_common import (get_auth_ref, get_nova_client, status_err, status_ok,

 def check(args):
     auth_ref = get_auth_ref()
-    auth_token = auth_ref['token']['id']
-    tenant_id = auth_ref['token']['tenant']['id']
+    tenant_id = auth_ref['project']['id']

     COMPUTE_ENDPOINT = 'http://{hostname}:8774/v2/{tenant_id}' \
                        .format(hostname=args.hostname, tenant_id=tenant_id)
+
     try:
-        nova = get_nova_client(auth_token=auth_token,
-                               bypass_url=COMPUTE_ENDPOINT)
+        nova = get_nova_client(bypass_url=COMPUTE_ENDPOINT)

     # not gathering api status metric here so catch any exception
     except Exception as e:
diff --git a/maas/service_api_local_check.py b/maas/service_api_local_check.py
index 5f1a5ca..cc0b45b 100755
--- a/maas/service_api_local_check.py
+++ b/maas/service_api_local_check.py
@@ -29,9 +29,9 @@ def check(args):
         auth_ref = get_auth_ref()
         keystone = get_keystone_client(auth_ref)
         auth_token = keystone.auth_token
-        tenant_id = keystone.tenant_id
+        project_id = keystone.project_id
         headers['auth_token'] = auth_token
-        path_options['tenant_id'] = tenant_id
+        path_options['project_id'] = project_id

     scheme = args.ssl and 'https' or 'http'
     endpoint = '{scheme}://{ip}:{port}'.format(ip=args.ip, port=args.port,
@@ -81,7 +81,7 @@ if __name__ == "__main__":
         parser.add_argument('--path', default='',
                             help='Service API path, this should include '
                                  'placeholders for the version "{version}" and '
-                                 'tenant ID "{tenant_id}" if required.')
+                                 'project ID "{project_id}" if required.')
         parser.add_argument('--auth', action='store_true', default=False,
                             help='Does this API check require auth?')
         parser.add_argument('--ssl', action='store_true', default=False,
```

**Comment by sigmavirus24** [comment]
@mancdaz good catch. I hadn't tested all of them last night but I had tested a good handful. I'll update this ASAP. Thanks.

**Comment by sigmavirus24** [comment]
@xeregin would you also like to give these a spin?

**Comment by nrb** [comment]
The code looks good to me. I'm curious to hear if @xeregin has tested this again in his labs.

**Comment by prometheanfire** [comment]
ya, I'd like a final confirmation as well

**Comment by claco** [comment]
I don't believe they're going to test this until it's in an rc. @sigmavirus24, did you test this in a cluster last week?

**Comment by sigmavirus24** [comment]
I tested against an AIO by running the scripts manually instead of setting up MaaS for the AIO because it was the easiest way to test -> fix -> test -> fix -> repeat

**Comment by prometheanfire** [comment]
fair enough :+1:

**Pull request merged**
