### PR TITLE
RabbitMQ status alarm uses wrong metric names.

### LINKED ISSUE #606: MaaS: rabbitmq_status check, metric "rabbitmq_socket_used" is not available
The actual metric names should be `rabbitmq_sockets_used` and `rabbitmq_sockets_total`.

### PR DESCRIPTION
**Pull request by byronmccollum**
Fixes #606

### CODE REVIEW

**Comment by byronmccollum** [comment]
Rebased

**Comment by stevelle** [comment]
:+1: looks good. Added research notes to the issue so it can be labeled appropriately

**Comment by sigmavirus24** [comment]
:+1:

**Comment by sigmavirus24** [comment]
:metal: @byronmccollum

**Pull request merged**
