### PR TITLE
Deploy ARA

### PR DESCRIPTION
**Pull request by hughsaunders**
Install the Ansible Run Analyser callback. This is used to gather task
failure information in gate jobs. A junit stream is created from failed
tasks, this is reported to jenkins so that failed tasks are reported as
failed unit tests. This allows a user to quickly see a list of failed
tasks rather than digging through logs.

Connects rcbops/u-suk-dev#318

### CODE REVIEW

**Comment by hughsaunders** [comment]
👎  This breaks newton as installing ara in the openstack-ansible runtime venv upgrades ansible to 2.2, which is too new for the newton version of openstack-ansible-plugins. 

```
14:11:37 + /opt/ansible-runtime/bin/pip install ara
14:11:38 Collecting ara
... Other deps omitted ...
14:11:39 Collecting ansible>=2.1.0.0 (from ara)
14:11:40   Using cached ansible-2.2.2.0.tar.gz
```

```
14:13:50 TASK [pip_install : Drop pip config] *******************************************
14:13:50 An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'Task' object has no attribute 'first_available_file'
14:13:50 fatal: [rameo-2-b15f]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

https://github.com/openstack/openstack-ansible-plugins/commit/2f6cac2cf6ddebf462e21c70da7f60fa334b5f1e

**Comment by hughsaunders** [comment]
This could be useful: https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-upgrade-strategy

**Comment by hughsaunders** [comment]
`--upgrade-strategy only-if-needed` seems to have the desired effect. Will wait for the run to complete before removing WIP tag though. 
```
07:36:04 + /opt/ansible-runtime/bin/pip install --upgrade-strategy only-if-needed ara
07:36:04 Collecting ara
07:36:04   Downloading ara-0.12.4.tar.gz (3.1MB)
07:36:07 Requirement not upgraded as not directly required: ansible>=2.1.0.0 in /opt/ansible-runtime/lib/python2.7/site-packages (from ara)
```

https://rpc.jenkins.cit.rackspace.net/job/RPC-AIO_master-experimental-ondemand/3/consoleFull

**Comment by hughsaunders** [comment]
recheck_cit_all

**Comment by hughsaunders** [comment]
recheck_cit_ceph

**Comment by hughsaunders** [comment]
Ready for review again.

**Comment by mattt416** [comment]
recheck_cit_swift

**Comment by mattt416** [comment]
recheck_swift

**Pull request merged**
