### PR TITLE
UG-624 Revert container storage checks in mitaka

### PR DESCRIPTION
**Pull request by mattt416**
This commit reverts 19ef129 and 386db42 as these checks are causing issues on a multi-node deployment since it expects LXC python libs to be installed on every physical host, which is not the case.

Note that these checks appear to be correct in the standalone rpc-maas role, and will re-introduce these checks into rpc-openstack once rpco is updated to use that role.

Additionally, these checks were added after the last mitaka-13.1 tag was cut, so no deployment should be using them at present.

### CODE REVIEW

**Comment by mattt416** [comment]
recheck_cit_majorupgrade

**Comment by mattt416** [comment]
recheck_cit_majorupgrade

**Comment by mattt416** [comment]
recheck_cit_trusty_deploy_swift
recheck_cit_trusty_majorupgrade_ceph
recheck_cit_trusty_majorupgrade_swift

**Comment by mattt416** [comment]
recheck_cit_trusty_majorupgrade_ceph
recheck_cit_trusty_majorupgrade_swift

**Comment by mattt416** [comment]
recheck_cit_trusty_majorupgrade_ceph
recheck_cit_trusty_majorupgrade_swift
recheck_cit_trusty_deploy_ceph

**Comment by mattt416** [comment]
recheck_cit_trusty_deploy_ceph

**Comment by alextricity25** [comment]
recheck_cit_trusty_majorupgrade_ceph
recheck_cit_trusty_majorupgrade_swift

**Comment by mattt416** [comment]
Bah, forgot the [liberty patch](https://github.com/rcbops/rpc-openstack/pull/2331) needs to merge before this one will gate successfully.

**Comment by alextricity25** [comment]
recheck_cit_trusty_majorupgrade_ceph
recheck_cit_trusty_majorupgrade_swift

**Pull request merged**
