### PR TITLE
[WIP] Testing unstable maas agent

### PR DESCRIPTION
**Pull request by mattt416**
Testing, please do not merge!

### CODE REVIEW

**Comment by mattt416** [comment]
recheck

**Comment by mattt416** [comment]
recheck_all

**Comment by git-harry** [comment]
@mattt416 I don't think this has worked

Liberty
```
01:25:13.242 TASK: [rpc_maas | Ensure container packages are installed] ******************** 
01:25:17.718 [0;33mchanged: [jrpcaioiad-4e8] => (item=rackspace-monitoring-agent,mariadb-client)[0m
```

Mitaka
```
03:26:43.541 TASK: [rpc_maas | Ensure container packages are installed] ******************** 
03:26:46.014 ok: [jrpcaioiad-4e8] => (item=rackspace-monitoring-agent,mariadb-client)
```

It looks like the [install task](https://github.com/rcbops/rpc-openstack/blob/mitaka-13.1/rpcd/playbooks/roles/rpc_maas/tasks/package_install.yml#L19) only ensures the package is present and not up to date.

**Comment by git-harry** [comment]
This is blocked until the issue is approved on the board.

**Comment by major** [comment]
@mattt416 Does this need to hang around?

**Comment by mattt416** [comment]
Closing, I don't even remember what issue we were trying to address here!

**Pull request closed without merging**
