### PR TITLE
[RLM-917] Add the ability to gate without artifacts

### PR DESCRIPTION
**Pull request by cloudnull**
With PR rcbops/rpc-gating#584 the option to
gate without artifacts has been added. This provides rpc-openstack the
bility to understand this action and set the required options.

> While this option has been added to the gating purposes additional
  work will needed to be added to allow RPC-OpenStack Newton to deploy
  without artifacts. The DEPLOY_ARTIFACTING environment variable is AIO
  specific at this time.

Signed-off-by: Kevin Carter <kevin.carter@rackspace.com>

Issue: [RLM-917](https://rpc-openstack.atlassian.net/browse/RLM-917)

### CODE REVIEW

**Comment by cloudnull** [comment]
recheck_cit_all

**Comment by cloudnull** [comment]
@mattt416 I'm not sure where or how this PR is causing a Python flake8 error; this is an addition in bash. Maybe this is something that we need to fix within the "newton" branch generally before any more patches can roll through?

**Comment by cloudnull** [comment]
@claco I think we can use the general pub cloud image for ubuntu 16.04 however that would need to be changed in the gating repo. Maybe I can add that to https://github.com/rcbops/rpc-gating/pull/584 if that's at all possible.

**Comment by cloudnull** [comment]
@claco done. Now when the no_actifact code path is hit, we'll run a dist upgrade.

**Comment by antonym** [comment]
@cloudnull think the flake8 error is just the commit title is too long:

hacking/rpco_checks.py:1:1: R802  git commit title ('[RLM-917] Add the ability to gate without artifacts') should be under 50 chars

**Comment by Frank-ZhangXin** [comment]
recheck_cit_xenial_swift_deploy

**Comment by Frank-ZhangXin** [comment]
recheck_cit_release
recheck_cit_trusty_ironic_deploy_no_artifacts
recheck_cit_xenial_ironic_deploy_no_artifacts

**Comment by Frank-ZhangXin** [comment]
recheck_cit_issue_link

**Pull request merged**
