### PR TITLE
Update OSA SHA to tip of stable/mitaka

### PR DESCRIPTION
**Pull request by git-harry**
This commit addresses the following issues:

- https://github.com/rcbops/rpc-openstack/issues/1356
- https://github.com/rcbops/u-suk-dev/issues/375
- https://github.com/rcbops/rpc-openstack/issues/1335

Connected https://github.com/rcbops/u-suk-dev/issues/379

### CODE REVIEW

**Comment by git-harry** [comment]
recheck_all

**Comment by evrardjp** [comment]
Why not wait a little more and have the sha updated to 24db19efc4476abf546a99e1da11d81656a98a40, this way we can have https://github.com/rcbops/rpc-openstack/issues/1326 fixed too?

**Comment by sigmavirus24** [comment]
@git-harry is this still a "don't merge" PR?

**Comment by git-harry** [comment]
@evrardjp yup I've already marked the issue as blocked. I didn't notice that issue until after I'd created this pull request and to included it required me to do an upstream patch first https://github.com/rcbops/u-suk-dev/issues/382

@sigmavirus24 yes, still blocked. I need to revise the SHA.

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/staging.horse/build-d405be3931/docs/private-cloud/rpc/release-notes/). :bow:

**Comment by sigmavirus24** [comment]
👍 pending checks.

**Comment by prometheanfire** [comment]
:+1: once passing

**Pull request merged**
