### PR TITLE
Change from Ubuntu to Ubuntu operating system

### PR DESCRIPTION
**Pull request by cyrichardson**

### CODE REVIEW

**Comment by cyrichardson** [comment]
@BjoernT Please review this PR and merge it. We are being asked by the Rackspace Legal Dept to make this change. Thanks

**Comment by cyrichardson** [comment]
@kenperkins  Please review this PR and merge it. We are being asked by the Rackspace Legal Dept to make this change. Thanks.

**Comment by cyrichardson** [comment]
@kenperkins Deadline is in January.

**Comment by BjoernT** [comment]
This project is no longer maintained, nor in use since Stein. 
This PR is not necessaey

**Comment by cyrichardson** [comment]
Thank you, @BjoernT, for responding. Please let me know what repo houses the docs today. Thank you!

**Comment by cyrichardson** [comment]
Closing based on Bjoern's comment.

**Pull request closed without merging**
