### PR TITLE
update OSA sha to fix absolute requirements

### PR DESCRIPTION
**Pull request by prometheanfire**
This includes a needed fix from 'Fix typo in upgrade script'.

### CODE REVIEW

**Comment by d34dh0r53** [comment]
:+1:

**Comment by tomc603** [comment]
:+1:

**Comment by d34dh0r53** [comment]
Do not merge, I want to get https://review.openstack.org/#/c/293821/4 into master

**Comment by d34dh0r53** [comment]
Supersceded by #957

**Pull request closed without merging**
