### PR TITLE
This fix will add new pip dependencies for the pccommon script

### PR DESCRIPTION
**Pull request by BjoernT**
This fix will add new pip dependencies for the pccommon script
Closes-Bug: #525

### CODE REVIEW

**Comment by git-harry** [comment]
@BjoernT I can't see the openstack client being used in the pccommon script. Why is it a dependency?

**Comment by BjoernT** [comment]
The new version will, it's currently in works

**Comment by stevelle** [comment]
the above explains the reason for this.  LGTM +1 when it is rebased

**Comment by d34dh0r53** [comment]
:+1:

**Pull request merged**
