### PR TITLE
Enabled OSA callback_plugins

### PR DESCRIPTION
**Pull request by BjoernT**
The current callback will add playbook runtime statistics

Closes-Bug: #809

### CODE REVIEW

**Comment by d34dh0r53** [comment]
`cirros` image timeout.

**Comment by d34dh0r53** [comment]
recheck

**Comment by BjoernT** [comment]
recheck

**Comment by prometheanfire** [comment]
@BjoernT conflicts, please rebase

**Comment by odyssey4me** [comment]
You want the performance statistics enabled on a production deployment? This takes up CPU time on the deployment host, re-orders the task output and is specifically only enabled in OSA for gating for these reasons. I'm not sure I understand the benefit of using this in production.

**Comment by BjoernT** [comment]
Rebased. Also we want this information to see where playbooks take time, even in production systems.
Additionally our deployment hosts have 16 cores and over 128GB ram so no problem here, I take the slight delay in sorting and peparing the callback information over added playbook visibility

**Comment by prometheanfire** [comment]
As this is something support knows the downsides of I'm OK with it.  I am interested in what support wants to do with that playbook runtime information though.

**Comment by BjoernT** [comment]
@prometheanfire  Simple , file more bugs. This stuff is too slow ;-)

**Comment by prometheanfire** [comment]
@BjoernT closed workedindev

**Comment by prometheanfire** [comment]
:+1:

**Comment by d34dh0r53** [comment]
:+1:

**Pull request merged**
