### PR TITLE
Remove ceph fact library

### PR DESCRIPTION
**Pull request by cloudnull**
This lib is now located within the RPC-MaaS git repo and has no reaason
to be here.

Depends-On: https://github.com/rcbops/rpc-maas/pull/234
Signed-off-by: Kevin Carter <kevin.carter@rackspace.com>

Issue: [UG-651](https://rpc-openstack.atlassian.net/browse/UG-651)

### CODE REVIEW

**Comment by alextricity25** [comment]
recheck_cit_all

**Comment by cloudnull** [comment]
recheck_cit_all

**Comment by prometheanfire** [comment]
this need a recheck?

**Comment by odyssey4me** [comment]
It looks like this may need a rebase.

**Pull request merged**
