### PR TITLE
Add osquery to the standard rpco deployment

### PR DESCRIPTION
**Pull request by cloudnull**
The osquery stack is being added to the standard rpco deployment. This
change enhances our ability to operate clouds by providing a means to
query environments via CLI and UI as well as to report security
characteristics of an environment to our ELK stack.

Signed-off-by: Kevin Carter <kevin.carter@rackspace.com>
(cherry picked from commit 87433e4487648e8ca021f2a2b75c0be0a85dc877)
Signed-off-by: Kevin Carter <kevin.carter@rackspace.com>

### CODE REVIEW

**Comment by prometheanfire** [comment]
recheck_xenial_no_artifacts_swift_deploy

**Comment by prometheanfire** [comment]
recheck_xenial_no_artifacts_swift_deploy

**Comment by d34dh0r53** [comment]
`11:46:43 failed: [localhost] (item=site-fleet.yml) => {"changed": true, "cmd": ["/root/ansible25/bin/ansible-playbook", "-e", "@/etc/openstack_deploy/user_rpco_secrets.yml", "-e", "@/etc/openstack_deploy/user_aio_variables.yml", "-e", "@/etc/openstack_deploy/user_secrets.yml", "site-fleet.yml"], "delta": "0:00:02.999384", "end": "2018-11-01 16:46:43.122441", "failed": true, "item": "site-fleet.yml", "msg": "non-zero return code", "rc": 250, "start": "2018-11-01 16:46:40.123057", "stderr": " [WARNING]: While constructing a mapping from /opt/openstack-ansible-\nops/osquery/vars/variables.yml, line 1, column 1, found a duplicate dict key\n(osquery_debug_packages_install). Using last defined value only.\nERROR! Unexpected Exception, this is probably a bug: 'module' object has no attribute 'MAGIC_VARIABLE_MAPPING'", "stderr_lines": [" [WARNING]: While constructing a mapping from /opt/openstack-ansible-", "ops/osquery/vars/variables.yml, line 1, column 1, found a duplicate dict key", "(osquery_debug_packages_install). Using last defined value only.", "ERROR! Unexpected Exception, this is probably a bug: 'module' object has no attribute 'MAGIC_VARIABLE_MAPPING'"], "stdout": "\nPLAY [Install MariaDB Galera Cluster] ******************************************\nto see the full traceback, use -vvv", "stdout_lines": ["", "PLAY [Install MariaDB Galera Cluster] ******************************************", "to see the full traceback, use -vvv"]}`

**Comment by cjloader** [comment]
closing for #3449

**Pull request closed without merging**
