### PR TITLE
Sync with support's f5-config.py

### PR DESCRIPTION
**Pull request by prometheanfire**
This fully syncs us with support.  This is a script that will work
for dev / qe AND support, to test what we ship.

Connects https://github.com/rcbops/u-suk-dev/issues/1244

### CODE REVIEW

**Comment by prometheanfire** [comment]
results of running this (note the errors at the bottom)
https://gist.github.com/prometheanfire/641b188f1238095629851bddeaa0cd11

what remains to be sync'd
https://gist.github.com/95aca87b21a4baf01906d74dd5e1ee4f

**Comment by major** [comment]
Are these failing due to a missing certificate?
```
Creating Virtual Server ... [RPC_PUB_SSL_VS_CINDER_API] .... [Error]
Creating Virtual Server ... [RPC_PUB_SSL_VS_HEAT_API] .... [Error]
Creating Virtual Server ... [RPC_PUB_SSL_VS_NOVA_API_OS_COMPUTE] .... [Error]
Creating Virtual Server ... [RPC_PUB_SSL_VS_GLANCE_API] .... [Error]
Creating Virtual Server ... [RPC_PUB_SSL_VS_HEAT_API_CFN] .... [Error]
Creating Virtual Server ... [RPC_PUB_SSL_VS_KEYSTONE_SERVICE] .... [Error]
Creating Virtual Server ... [RPC_PUB_SSL_VS_KIBANA_SSL] .... [Ok]
Creating Virtual Server ... [RPC_PUB_SSL_VS_NEUTRON_SERVER] .... [Error]
Creating Virtual Server ... [RPC_PUB_SSL_VS_HEAT_API_CLOUDWATCH] .... [Error]
```

**Comment by alextricity25** [comment]
recheck_all

**Comment by prometheanfire** [comment]
@major that's since been fixed :D

**Comment by alextricity25** [comment]
recheck_swift

**Comment by dpham-rs** [comment]
Ran this on a customer build.

Ran into a few snags:
* create auth partition /RPC/ should not have slashes.
* curl for the ext-mon needs a space between "/config/monitors/RPC-MON-EXT-ENDPOINT.monitor" and "https://raw.githubusercontent"
  * Also, the curl for the monitor can use the rcbops repo instead of my fork.

**Comment by prometheanfire** [comment]
Thanks, thought I fixed the create auth partition thing, but apparently I only fixed that in the lab and not the PR.

The curl stuff is now fixed as well

**Comment by dpham-rs** [comment]
Re-ran the build with 8594200, both snags have been taken care of.

Looks good :)

**Comment by hughsaunders** [comment]
recheck all

**Comment by prometheanfire** [comment]
recheck all

**Comment by prometheanfire** [comment]
recheck all

**Comment by prometheanfire** [comment]
recheck_all

**Comment by prometheanfire** [comment]
this has been checked by both support and dev now, can we get this merged into master?

**Pull request merged**
