### PR TITLE
[Backport - Mitaka] Various MaaS fixes

### PR DESCRIPTION
**Pull request by antonym**
Backports MaaS fixes to Mitaka. 

Commit 6f50bdeb418c90845bef38ae3e99cb533f7d6fbb altered and notated to drop python-magnumclient.

### CODE REVIEW

**Comment by antonym** [comment]
@mattt416 

17:56:26 fatal: [jramcp-85-10893] => error while evaluating conditional: inventory_hostname in groups['lxc_hosts']

Did that group not exist in Mitaka?

**Comment by major** [comment]
@antonym This may help: https://github.com/openstack/openstack-ansible/blob/stable/mitaka/playbooks/lxc-hosts-setup.yml#L19

You'll probably have to do something like `inventory_hostname in lxc_host_group` if I remember correctly.

**Comment by antonym** [comment]
@major gave that a try but it didn't seem to exist.  I'm inclined just to install lxc-python2 on all hosts.

**Comment by antonym** [comment]
recheck_cit_upgrade

**Comment by antonym** [comment]
recheck_cit_upgrade

**Comment by antonym** [comment]
recheck_cit_upgrade

**Comment by antonym** [comment]
recheck_cit_swift

**Comment by antonym** [comment]
recheck_cit_upgrade

**Comment by antonym** [comment]
recheck_cit_upgrade
recheck_cit_swift

**Comment by mkam** [comment]
recheck_cit_upgrade

**Comment by mkam** [comment]
recheck_cit_upgrade

**Comment by mkam** [comment]
recheck_cit_upgrade

**Comment by mattt416** [comment]
recheck_cit_upgrade

**Comment by mattt416** [comment]
This upgrade job failed on:

```
TASK: [Local MaaS Checks] ***************************************************** 
failed: [ramup-96-bf5b] => {"attempts": 5, "changed": false, "cmd": ". /openstack/venvs/maas-r13.1.4/bin/activate\n /opt/rpc-openstack/scripts/rpc-maas-tool.py verify-local", "delta": "0:00:33.260154", "end": "2017-04-28 18:09:37.586113", "failed": true, "failed_when_result": true, "rc": 1, "start": "2017-04-28 18:09:04.325959", "stdout_lines": ["The following metrics are required by alarms but not produced by any checks: set(['beaver_process_status'])"], "warnings": []}
stdout: The following metrics are required by alarms but not produced by any checks: set(['beaver_process_status'])

FATAL: all hosts have already failed -- aborting
```

I've been having similar issues w/ beaver failures on https://rpc.jenkins.cit.rackspace.net/job/RPC-AIO_mitaka-upgrade-periodic/ and noticed that we're not removing the beaver MaaS checks after we upgrade from liberty->mitaka.

I've since created https://github.com/rcbops/rpc-openstack/pull/2239 to address that.  Once #2239 merges, we should be able to get this one to merge.

**Comment by mattt416** [comment]
recheck_cit_upgrade - #2239 has merged

**Comment by mkam** [comment]
recheck_cit_upgrade

**Comment by mattt416** [comment]
recheck_cit_upgrade

**Comment by mattt416** [comment]
recheck_cit_upgrade

**Comment by mattt416** [comment]
recheck_cit_upgrade

**Comment by mattt416** [comment]
recheck_cit_majorupgrade

**Comment by mattt416** [comment]
recheck_cit_majorupgrade

**Pull request merged**
