### PR TITLE
[Backport - Mitaka] Install sos report tooling on physical hosts

### PR DESCRIPTION
**Pull request by antonym**
Backports SOS reporting commits.  Commits modified to avoid flavor and magnum conflicts in master.

Connects rcbops/u-suk-dev#1422
Connects rcbops/u-suk-dev#1477

### CODE REVIEW

**Comment by antonym** [comment]
recheck_cit_swift
recheck_cit_upgrade

**Comment by antonym** [comment]
recheck_cit_upgrade

**Comment by antonym** [comment]
recheck_cit_upgrade

**Comment by mattt416** [comment]
recheck_cit_upgrade

**Comment by odyssey4me** [comment]
Closed, re-opened in order to re-trigger all tests.

**Comment by odyssey4me** [comment]
@alextricity25 @antonym This has passed all the tests it can, so if you still want it to be merged, then that can happen.

**Pull request merged**
