### PR TITLE
[WIP] Use osa/run-playbooks in rpc deploy script

### PR DESCRIPTION
**Pull request by hughsaunders**
Reduce duplication by making use of osa/run-playbooks in rpc/deploy.
Related: #691

### CODE REVIEW

**Comment by hughsaunders** [comment]
recheck - failed on cirros image not becoming active

**Comment by hughsaunders** [comment]
recheck stuck on ssh to horizon container

**Comment by hughsaunders** [comment]
recheck

**Comment by hughsaunders** [comment]
recheck failed on join rabbit cluster

**Comment by hughsaunders** [comment]
recheck failed on image not active

**Comment by hughsaunders** [comment]
image not active failures were due to lack of swift :see_no_evil:

**Comment by hughsaunders** [comment]
recheck - failed on syntax error in jenkins job script

**Comment by hughsaunders** [comment]
recheck

**Comment by tomc603** [comment]
recheck - curl timed out on `curl http://169.254.169.254/latest/meta-data/public-ipv4`

**Pull request closed without merging**
