### PR TITLE
search through all pids and their children for process checks

### PR DESCRIPTION
**Pull request by prometheanfire**
cgroup.procs only displays one layer, sometimes containers will have
child cgroups that we want to check.  This change allows us to switch
to a check that checks all descendants of a parent as well.

Connects https://github.com/rcbops/u-suk-dev/issues/1001

### CODE REVIEW

**Comment by alextricity25** [comment]
FYI - We have to ensure this has a passing xenial job with maas deployed. PR triggered jobs don't do this by default, so we'll have to trigger it manually off this branch.
I've already fired one off: http://jenkins.propter.net/job/JJB-RPC-AIO_master-xenial-periodic/34/

**Comment by prometheanfire** [comment]
ah, thanks

**Comment by prometheanfire** [comment]
recheck_all

I think we need to recheck because the branches were broken...  Just to be safe I'm going to rebase on master.

**Comment by alextricity25** [comment]
@prometheanfire You're going to have to install the lxc module in the maas venv to move forward with this. The error I'm seeing in the gate jobs is:
```
Traceback (most recent call last):\\n  File \"/usr/lib/rackspace-monitoring-agent/plugins/process_check.py\", line 17, in <module>\\n    import lxc\\nImportError: No module named lxc\\n'), ('filebeat_process_check--jramcp-148-4562-memcached-container-dae3f8f5', 'Traceback (most recent call last):\\n  File \"/usr/lib/rackspace-monitoring-agent/plugins/process_check.py\", line 17, in <module>\\n    import lxc\\nImportError: No module named lxc\\n')
```

**Comment by alextricity25** [comment]
The xenial maas job is here:
http://jenkins.propter.net/job/JJB-RPC-AIO_master-xenial-periodic/37/console
I'm going to block this until we see a passing xenial job with maas enabled.

**Pull request merged**
