### PR TITLE
[ISU-98] [LA-314] Bring the ability to use influxdb (#2388)

### PR DESCRIPTION
**Pull request by evrardjp**
RPC-Maas is able to push metrics to influx, we should expose
this facility to our users, which includes our gates.

On top of it, we should bring the facility to deploy influx, if
need be.

RPC-Maas is able to push metrics to influx, we should expose
this facility to our users, which includes our gates.

Issue: [LA-314](https://rpc-openstack.atlassian.net/browse/LA-314)
Issue: [ISU-98](https://rpc-openstack.atlassian.net/browse/ISU-98)

### CODE REVIEW

**Comment by evrardjp** [comment]
Backport

**Comment by odyssey4me** [comment]
This will probably also need some more backported, for example the removal of the role from ansible-role-requirements and perhaps some other bits that haven't been ported back to this branch.

**Comment by evrardjp** [comment]
This is supposedly a straight replacement that introduces the feature. We should probably have a depends on: on the patch that introduces maas into this branch.

**Comment by evrardjp** [comment]
@cloudnull I don't see a patch for maas into this branch, is that normal?

**Comment by evrardjp** [comment]
TODO: This depends on new maas inclusion into this branch.

**Comment by evrardjp** [comment]
depends on https://github.com/rcbops/rpc-openstack/pull/2399

**Comment by cloudnull** [comment]
recheck_cit_all

**Comment by evrardjp** [comment]
Depends on https://github.com/rcbops/rpc-openstack/pull/2399

**Comment by evrardjp** [comment]
This will need a rebase when the #2399 will be merged, as conflicts will appear. It would then be a good time to update it with latest standards from master.

**Comment by evrardjp** [comment]
@odyssey4me This should be ready for review. I've removed the rpc_maas role, as it was not used.

**Comment by evrardjp** [comment]
recheck_cit_trusty_deploy_swift

**Comment by evrardjp** [comment]
transient apt package fetching issue

**Comment by cjloader** [comment]
LGTM, 👍

**Pull request merged**
