### PR TITLE
Update OSA SHA to tip of stable/mitaka

### PR DESCRIPTION
**Pull request by prometheanfire**
This update is required in preparation of the release of r13.0.0rc1.
The update includes the latest stable/mitaka SHA, which addresses:

- https://github.com/rcbops/u-suk-dev/issues/378
- https://github.com/rcbops/u-suk-dev/issues/417

In addtion this includes two fixes we weren't tracking that are needed:

- Use correct version when creating backup dir
  (622fc94a7e8f95a9391eb0fbe85e7a449fc35f85)
- load variables as a simple var for upgrades
  (42b2a79c816f289060a0abd35d3ef3924eb46852)

Connected https://github.com/rcbops/u-suk-dev/issues/442

(cherry picked from commit d029ab8ad3e3b9c7da15de0cfe0066a6277ea38e)
Signed-off-by: Matthew Thode <mthode@mthode.org>

### CODE REVIEW

**Comment by mancdaz** [comment]
@prometheanfire linting issues

**Comment by prometheanfire** [comment]
@mancdaz how do we have linting issues on a backport like this?

**Comment by prometheanfire** [comment]
recheck_all

**Comment by prometheanfire** [comment]
recheck_all

**Comment by mancdaz** [comment]
@prometheanfire maybe because you're trying to use a commit from OSA mitaka on the liberty-12.2 branch...?

**Pull request closed without merging**
