### PR TITLE
Only create support keypair is nova service is present. Only create s…

### PR DESCRIPTION
**Pull request by prometheanfire**
…upport security group if neutron service is present.

(cherry picked from commit e739459a1cd1fc97de103fd92f390b514be61fdd)

### CODE REVIEW

**Comment by d34dh0r53** [comment]
What's up with the commit message on this one? :-1: (update commit message)

**Comment by prometheanfire** [comment]
it was a cherry pick, the commit message is the same as the one that merged before...

**Comment by d34dh0r53** [comment]
Uggh :+1:

**Comment by git-harry** [comment]
+1

**Pull request merged**
