### PR TITLE
Update OSA SHA to bring in zero weight swift fix

### PR DESCRIPTION
**Pull request by prometheanfire**
Kilo is the first to get a release/tag with the fix in it (from OSA)
OSA Liberty is having requirements issues.

Related: #878

### CODE REVIEW

**Comment by git-harry** [comment]
recheck_all

**Comment by prometheanfire** [comment]
recheck_swift
recheck_ceph

**Comment by git-harry** [comment]
recheck_swift
recheck_ceph

**Comment by git-harry** [comment]
recheck_swift
recheck_ceph

**Comment by prometheanfire** [comment]
recheck_swift
recheck_ceph

**Comment by git-harry** [comment]
recheck_swift
recheck_ceph

**Comment by git-harry** [comment]
recheck_swift
recheck_ceph

**Comment by git-harry** [comment]
OSA tag 11.2.14 has openstack_release set to '11.2.13' [1] which is the previous release. This is causing the checks to fail because 11.2.13 does not exist on rpc-repo although obviously that should only be used by the 11.2.13 release. OSA are currently in the process of releasing 11.2.15 and so we should delay/update this patch once it is released.

[1] - https://github.com/openstack/openstack-ansible/blob/11.2.14/playbooks/inventory/group_vars/all.yml#L17

**Comment by git-harry** [comment]
The upstream review [1] for 11.2.15

[1] - https://review.openstack.org/#/c/313028/

**Comment by git-harry** [comment]
@prometheanfire 11.2.15 has been released in OSA. I've kicked of a repo build in rpc-repo [1]. Can you keep an eye on this and update this pull request once it's done.

[1] - http://rpc-repo.rackspace.com:8080/job/Repo-Build-Kilo/73/

**Comment by prometheanfire** [comment]
sure

**Comment by prometheanfire** [comment]
recheck_swift
recheck_ceph

**Comment by prometheanfire** [comment]
This seems like something we already solved...

`19:06:29 msg: Task failed as maximum retries was encountered
19:06:29 changed: [jrpcaioiad-cc9_utility_container-882ca256] => (item=python-swiftclient)
19:06:29 ok: [jrpcaioiad-cc9_utility_container-882ca256] => (item=python-memcached)
19:06:29 ok: [jrpcaioiad-cc9_utility_container-882ca256] => (item=pycrypto)`

**Comment by sigmavirus24** [comment]
I think the relevant part of the logs is:

```
19:08:22 TASK: [Install pip packages] ************************************************** 
19:08:22 failed: [jrpcaioiad-580_utility_container-caf141a7] => (item=python-openstackclient) => {"attempts": 5, "cmd": "/usr/local/bin/pip install python-openstackclient", "failed": true, "item": "python-openstackclient"}
19:08:22 msg: Task failed as maximum retries was encountered
19:08:22 failed: [jrpcaioiad-580_utility_container-caf141a7] => (item=python-ceilometerclient) => {"attempts": 5, "cmd": "/usr/local/bin/pip install python-ceilometerclient", "failed": true, "item": "python-ceilometerclient"}
19:08:22 msg: Task failed as maximum retries was encountered
19:08:22 failed: [jrpcaioiad-580_utility_container-caf141a7] => (item=python-cinderclient) => {"attempts": 5, "cmd": "/usr/local/bin/pip install python-cinderclient", "failed": true, "item": "python-cinderclient"}
19:08:22 msg: Task failed as maximum retries was encountered
19:08:22 failed: [jrpcaioiad-580_utility_container-caf141a7] => (item=python-glanceclient) => {"attempts": 5, "cmd": "/usr/local/bin/pip install python-glanceclient", "failed": true, "item": "python-glanceclient"}
19:08:22 msg: Task failed as maximum retries was encountered
19:09:07 failed: [jrpcaioiad-580_utility_container-caf141a7] => (item=python-heatclient) => {"attempts": 5, "cmd": "/usr/local/bin/pip install python-heatclient", "failed": true, "item": "python-heatclient"}
19:09:07 msg: Task failed as maximum retries was encountered
19:09:07 failed: [jrpcaioiad-580_utility_container-caf141a7] => (item=python-keystoneclient) => {"attempts": 5, "cmd": "/usr/local/bin/pip install python-keystoneclient", "failed": true, "item": "python-keystoneclient"}
19:09:07 msg: Task failed as maximum retries was encountered
19:09:07 failed: [jrpcaioiad-580_utility_container-caf141a7] => (item=python-neutronclient) => {"attempts": 5, "cmd": "/usr/local/bin/pip install python-neutronclient", "failed": true, "item": "python-neutronclient"}
19:09:07 msg: Task failed as maximum retries was encountered
19:09:07 failed: [jrpcaioiad-580_utility_container-caf141a7] => (item=python-novaclient) => {"attempts": 5, "cmd": "/usr/local/bin/pip install python-novaclient", "failed": true, "item": "python-novaclient"}
19:09:07 msg: Task failed as maximum retries was encountered
```

Which indicates it's failing to install:

- python-openstackclient
- python-ceilometerclient
- python-cinderclient
- python-glanceclient
- python-heatclient
- python-keystoneclient
- python-neutronclient
- python-novaclient

Which is quite bizarre.

**Comment by prometheanfire** [comment]
I'm wondering if we are having a conflict with maas again

**Comment by sigmavirus24** [comment]
@prometheanfire how do you mean?

**Comment by prometheanfire** [comment]
iirc, maas and the clients had issues with not being able to install in the same environment

**Comment by sigmavirus24** [comment]
That shouldn't affect the utility container though. The maas bits don't get installed there.

**Comment by prometheanfire** [comment]
I thought we installed helper bits there

**Comment by git-harry** [comment]
The new release [1] contains newer version of packages than OSA itself uses. I can't see the cause of this. The build [2] that generated that list of packages doesn't contain a great deal of detail.

[1] http://rpc-repo.rackspace.com/os-releases/11.2.15/
[2] http://rpc-repo.rackspace.com:8080/job/Repo-Build-Kilo/73/

**Comment by git-harry** [comment]
@cloudnull can you offer any suggestions on this?

**Comment by git-harry** [comment]
recheck_swift
recheck_ceph

**Comment by d34dh0r53** [comment]
:+1:

**Comment by major** [comment]
:+1:

**Pull request merged**
