### PR TITLE
Removed solutions tab, horizon_extensions subtree

### PR DESCRIPTION
**Pull request by cloudnull**
This commit removes the horizon-extensions subtree,
as well as the bits in the horizon_extenstions playbook
related to deploying the solutions tab.

Closes-Bug: #1996
(cherry picked from commit 88859c2a9e005cf53a331ce5de7c0be2582a76ba)
Signed-off-by: Kevin Carter <kevin.carter@rackspace.com>

### CODE REVIEW

**Comment by alextricity25** [comment]
recheck_cit_upgrade

**Comment by cloudnull** [comment]
recheck_cit_upgrade

**Comment by major** [comment]
recheck-cit-upgrade

```
failed: [ramup-73-9093] => {"attempts": 10, "changed": false, "failed": true, "failed_when_result": true, "rc": 1, "stdout_lines": ["--- 2017-04-24 21:55:14.972401 ---", "Checks and Alarms with failures:", " - Entity:enHa43nl70:ramup-73-9093", "   ! Check:agent.plugin:ch8YXYPd3o:container_storage_check--ramup-73-9093: Completed:False Status:Plugin exited with non-zero status code (code=-127)", "     ! Alarm:alxhfs6b4F:container_storage_percent_used--ramup-73-9093:CRITICAL"]}
stderr: OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 172.29.236.100 closed.

stdout: --- 2017-04-24 21:55:14.972401 ---
Checks and Alarms with failures:
 - Entity:enHa43nl70:ramup-73-9093
   ! Check:agent.plugin:ch8YXYPd3o:container_storage_check--ramup-73-9093: Completed:False Status:Plugin exited with non-zero status code (code=-127)
     ! Alarm:alxhfs6b4F:container_storage_percent_used--ramup-73-9093:CRITICAL
```

**Comment by major** [comment]
recheck_cit_upgrade

```
failed: [ramup-73-9093] => {"attempts": 10, "changed": false, "failed": true, "failed_when_result": true, "rc": 1, "stdout_lines": ["--- 2017-04-24 21:55:14.972401 ---", "Checks and Alarms with failures:", " - Entity:enHa43nl70:ramup-73-9093", "   ! Check:agent.plugin:ch8YXYPd3o:container_storage_check--ramup-73-9093: Completed:False Status:Plugin exited with non-zero status code (code=-127)", "     ! Alarm:alxhfs6b4F:container_storage_percent_used--ramup-73-9093:CRITICAL"]}
stderr: OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 172.29.236.100 closed.

stdout: --- 2017-04-24 21:55:14.972401 ---
Checks and Alarms with failures:
 - Entity:enHa43nl70:ramup-73-9093
   ! Check:agent.plugin:ch8YXYPd3o:container_storage_check--ramup-73-9093: Completed:False Status:Plugin exited with non-zero status code (code=-127)
     ! Alarm:alxhfs6b4F:container_storage_percent_used--ramup-73-9093:CRITICAL
```

**Comment by mattt416** [comment]
recheck_cit_upgrade

**Comment by alextricity25** [comment]
recheck_cit_upgrade

**Comment by cloudnull** [comment]
recheck_cit_upgrade

**Pull request merged**
