### PR TITLE
rename rpc-extras to rpc-openstack

### PR DESCRIPTION
**Pull request by prometheanfire**

### CODE REVIEW

**Comment by d34dh0r53** [comment]
+1

**Comment by cloudnull** [comment]
:+1:

**Comment by mancdaz** [comment]
Closes: https://github.com/rcbops/rpc-openstack/issues/143

**Comment by mancdaz** [comment]
@prometheanfire does this need back/side/forward ported to master?

**Comment by odyssey4me** [comment]
@mancdaz This went into master in https://github.com/rcbops/rpc-openstack/pull/160

**Pull request merged**
