### PR TITLE
Clean up MaaS and local scripts for Flake8

### PR DESCRIPTION
**Pull request by sigmavirus24**
Fix all reported hacking errors

Related to #272
Related to #240

### CODE REVIEW

**Comment by nrb** [comment]
+1

**Comment by nrb** [comment]
Looks like this needs a rebase.

**Comment by sigmavirus24** [comment]
Rebased.

**Comment by prometheanfire** [comment]
conflicts :(

**Comment by nrb** [comment]
@sigmavirus24 Mind taking a look at the conflicts here?

**Comment by nrb** [comment]
+1

**Comment by rackertom** [comment]
I'll :+1: this. Looks good.

**Pull request merged**
