### PR TITLE
FLEEK-130 Add documentation on handling legacy ELK

### PR DESCRIPTION
**Pull request by cloudnull**
Add docs and setup files to RPCO in an effort to support the
elk_metrics_6x project.

To resolve an on going pip issue in the utility container the
openstack-* playbooks have been updated to support master OSA.

Issue: https://rpc-openstack.atlassian.net/browse/FLEEK-130
(cherry picked from commit bc5762df906747f50d8a2b00621b14b5554ae209)
Signed-off-by: Kevin Carter <kevin.carter@rackspace.com>

Issue: [FLEEK-130](https://rpc-openstack.atlassian.net/browse/FLEEK-130)

### CODE REVIEW

**Comment by mattt416** [comment]
recheck_release

**Comment by mattt416** [comment]
recheck_release

**Comment by mattt416** [comment]
https://github.com/rcbops/rpc-openstack/pull/3157 will need to merge and this rebased in order for the `CIT/release` job to pass.

**Comment by cloudnull** [comment]
recheck_cit_xenial_no_artifacts_swift_deploy

**Comment by cloudnull** [comment]
recheck_xenial_no_artifacts_swift_deploy

**Pull request merged**
