### PR TITLE
[Backport - Mitaka] MaaS: Modify ceph alarm evaluations

### PR DESCRIPTION
**Pull request by antonym**
Changes ceph_cluster_stats and ceph_mon_stats WARN alarms
to critical.

Connects rcbops/u-suk-dev#1403

### CODE REVIEW

**Comment by antonym** [comment]
recheck_cit_upgrade
recheck_swift

**Comment by antonym** [comment]
recheck_cit_upgrade

**Comment by antonym** [comment]
recheck_cit_upgrade

**Comment by major** [comment]
recheck_cit_upgrade

**Comment by cjloader** [comment]
recheck_cit_upgrade

**Comment by major** [comment]
`failed: [ramup-53-eced] => {"failed": true}
msg: Zero entities with the label ramup-53-eced exist. Entities should be created as part of the hardware provisioning process, if missing, please consult the internal documentation for associating one with the device.`

**Comment by antonym** [comment]
rechech_cit_upgrade

**Comment by antonym** [comment]
recheck_cit_upgrade

**Comment by cloudnull** [comment]
recheck_cit_upgrade

**Comment by antonym** [comment]
recheck_cit_upgrade

**Comment by mattt416** [comment]
recheck_cit_upgrade

**Comment by mattt416** [comment]
recheck_cit_upgrade

**Comment by odyssey4me** [comment]
Closed, re-opened in order to re-trigger all tests.

**Comment by hughsaunders** [comment]
This must be re-proposed against the `mitaka` branch if still required.

**Pull request closed without merging**
