### PR TITLE
Enable active-active balancing of repo servers

### PR DESCRIPTION
**Pull request by nategraf**
Change f5-config.py to configure pools in least-connections mode
instead of fastest-node mode to avoid error where all traffic
goes to single node

Connects #190

### CODE REVIEW

**Comment by nategraf** [comment]
This PR is very much so a WIP. I just wanted to put some code up here to get comments. 

The original issue mentions the repo server pool specifically, but I wasn't sure if the problem was specific to the repo server, or if it all pools should be changed to use least-connections-node mode. The code here does the heavy handed approach of changing all pools. Here are two sample outputs of the pool nodes when the script ran. (They came from the debug statement on line 681)

Before: http://paste.openstack.org/show/547867/
After: http://paste.openstack.org/show/547868/

**Comment by Apsu** [comment]
RPC-AIO-Ceph-Liberty-PR: Fail

**Comment by Mudpuppy12** [comment]
https://devcentral.f5.com/questions/least-connections-member-and-least-connections-node

**Comment by Apsu** [comment]
RPC-AIO-Liberty-PR: Fail

**Comment by Apsu** [comment]
RPC-AIO-Ceph-Liberty-PR: Fail

**Comment by Apsu** [comment]
RPC-AIO-Liberty-PR: Fail

**Comment by ameserole** [comment]
Failing because of the repo

16:11:18 TASK: [lxc_hosts | Install apt packages] ************************************** 
16:11:37 failed: [jrpcaioiad-288] => (item=apparmor,apparmor-utils,bridge-utils,cgmanager,cgroup-lite,debootstrap,dnsmasq,git,irqbalance,language-pack-en,liblxc1,lxc,lxc-dev,lxc-templates,python-dev,python3-lxc) => {"attempts": 5, "failed": true, "item": "apparmor,apparmor-utils,bridge-utils,cgmanager,cgroup-lite,debootstrap,dnsmasq,git,irqbalance,language-pack-en,liblxc1,lxc,lxc-dev,lxc-templates,python-dev,python3-lxc"}
16:11:37 stderr: E: Failed to fetch http://mirror.rackspace.com/ubuntu/pool/main/q/qemu/qemu-utils_2.0.0+dfsg-2ubuntu1.26_amd64.deb  404  Not Found

**Comment by Frank-ZhangXin** [comment]
16:11:18 TASK: [lxc_hosts | Install apt packages] ************************************** 
16:11:37 failed: [jrpcaioiad-288] => (item=apparmor,apparmor-utils,bridge-utils,cgmanager,cgroup-lite,debootstrap,dnsmasq,git,irqbalance,language-pack-en,liblxc1,lxc,lxc-dev,lxc-templates,python-dev,python3-lxc) => {"attempts": 5, "failed": true, "item": "apparmor,apparmor-utils,bridge-utils,cgmanager,cgroup-lite,debootstrap,dnsmasq,git,irqbalance,language-pack-en,liblxc1,lxc,lxc-dev,lxc-templates,python-dev,python3-lxc"}
16:11:37 stderr: E: Failed to fetch http://mirror.rackspace.com/ubuntu/pool/main/q/qemu/qemu-utils_2.0.0+dfsg-2ubuntu1.26_amd64.deb  404  Not Found
16:11:37 
16:11:37 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
16:11:37 
16:11:37 stdout: Reading package lists...
16:11:37 Building dependency tree...
16:11:37 Reading state information...
16:11:37 The following extra packages will be installed:
16:11:37   cloud-image-utils distro-info distro-info-data dnsmasq-base euca2ools
16:11:37   genisoimage libaio1 libmnl0 libnetfilter-conntrack3 librados2 librbd1
16:11:37   libseccomp2 libxslt1.1 python-distro-info python-lxml python-pkg-resources
16:11:37   python-requestbuilder python-setuptools qemu-utils sharutils uidmap
16:11:37 Suggested packages:
16:11:37   cgmanager-utils shunit2 wodim cdrkit-doc btrfs-tools lxctl qemu-user-static
16:11:37   python-lxml-dbg python-distribute python-distribute-doc
16:11:37 The following NEW packages will be installed:
16:11:37   cgmanager cloud-image-utils debootstrap distro-info distro-info-data dnsmasq
16:11:37   dnsmasq-base euca2ools genisoimage libaio1 liblxc1 libmnl0
16:11:37   libnetfilter-conntrack3 librados2 librbd1 libseccomp2 libxslt1.1 lxc lxc-dev
16:11:37   lxc-templates python-distro-info python-lxml python-pkg-resources
16:11:37   python-requestbuilder python-setuptools python3-lxc qemu-utils sharutils
16:11:37   uidmap
16:11:37 0 upgraded, 29 newly installed, 0 to remove and 22 not upgraded.
16:11:37 Need to get 414 kB/5275 kB of archives.
16:11:37 After this operation, 21.4 MB of additional disk space will be used.
16:11:37 Err http://mirror.rackspace.com/ubuntu/ trusty-updates/main qemu-utils amd64 2.0.0+dfsg-2ubuntu1.26
16:11:37   404  Not Found
16:11:37 Err http://mirror.rackspace.com/ubuntu/ trusty-security/main qemu-utils amd64 2.0.0+dfsg-2ubuntu1.26
16:11:37   404  Not Found
16:11:37 
16:11:37 msg: Task failed as maximum retries was encountered
16:11:37 
16:11:37 FATAL: all hosts have already failed -- aborting
16:11:37 
16:11:37 PLAY RECAP ******************************************************************** 
16:11:37            to retry, use: --limit @/jenkins/setup-hosts.retry
16:11:37 
16:11:37 jrpcaioiad-288             : ok=155  changed=72   unreachable=0    failed=1   

recheck_all

**Comment by nategraf** [comment]
Made some edits to clean things up and get it ready for review. I am going to verify basic functionality and then open it up to reviews.

**Comment by Apsu** [comment]
RPC-AIO-Ceph-Liberty-PR: Fail

**Comment by nategraf** [comment]
After speaking with Edgar on support, the new configuration checks out. Removing the WIP tag. I'd appreciate any and all feedback.

**Comment by nategraf** [comment]
After I went home and thought about this a bit more I realized that although this patch would work, there is a better solution. I am looking into a new approach.

**Comment by nategraf** [comment]
After further research, so that I could fully understand the problem at hand, I have come to the conclusion that changing to least-connections strategy for load balancing is not necessary or preferable to solve this issue. Instead the prioritization or repo servers can simply be deactivated. 

Below is the new commit message
/==========================
Prior to this commit repo servers were configured in an F5 pool
which assigns a unique priority to each server. This means
that all requests are forwarded to the first server in the pool
until that server become unavailible. This is active-passive
load balancing.

This commit disables prioritization of of repo servers, which
enables active-active load balancing and forwards connections
under the fastest-connection policy. All servers in the pool
are now treated equally. This change is benificial in that the
load is now spread throughout the repo servers and the
deployment can benifit from the combined power.

**Comment by mancdaz** [comment]
👍  good logic, good change

**Comment by Apsu** [comment]
Yeah, LGTM as well.

**Comment by sigmavirus24** [comment]
👎 the commit message is not formatted as we require it to be.

**Comment by nategraf** [comment]
Fixed the commit message and changed the PR title to match

Enable active-active loadbalancing of repo servers

**Comment by mancdaz** [comment]
👍

**Comment by Apsu** [comment]
RPC-AIO-Liberty-PR: Fail

**Comment by sigmavirus24** [comment]
👍 from me too. Will merge when the gate passes

**Comment by BjoernT** [comment]
@nategraf Will active active load balancing not cause issues, during initial repo build, where all packages are not synced across all containers ?

**Comment by nategraf** [comment]
@BjoernT To my knowledge the unsynced repo servers are removed from the pool until they are ready, but this is from what I have been told, not personal investigation. Unfortunately I no longer have the hardware resources to test this, so I'm forced to defer the confirmation of this back to you and the dev team.

**Comment by sigmavirus24** [comment]
@BjoernT you should probably talk to the same people @nategraf talked to (see https://github.com/rcbops/rpc-openstack/issues/190#issuecomment-240080414)

**Comment by mancdaz** [comment]
@BjoernT @nategraf this commit https://github.com/openstack/openstack-ansible-repo_server/commit/b457f3bda65a418884e1847759e6bfa26a7ed5ab disables the unsynced repo-servers until they are synced, by stopping nginx on the repo container until the sync has finished. This means that the containers effectively take themselves out of whatever load balancer is being used (haproxy, f5 etc) until they are ready.

**Comment by BjoernT** [comment]
@mancdaz ok thanks

**Pull request merged**
