### PR TITLE
Add script to handle changing osad git tag

### LINKED ISSUE #218: Standardize osad tagging procedure.
When updating to new tags of os-ansible-deployment, it would be useful to have a standard tagging format, so we can quickly search for the commit should the need arise.

### PR DESCRIPTION
**Pull request by nrb**
This script will change the SHA used by the os-ansible-deployment
submodule to match a tag from the upstream repository. It will also
provide a commit message template that can be edited by the commiter.

Fixes #218

### CODE REVIEW

**Comment by odyssey4me** [comment]
Looks fine to me. Has this been tested? We had some shenanigans with sha's a few weeks ago.

**Comment by nrb** [comment]
This is what I've been using to tag each time, so yeah, tested.

I think the shenanigans you were referring to were master and kilo pointing to the same tag? That was intentional, since I don't think we really want our master branch following master of OSAD.

**Comment by odyssey4me** [comment]
LGTM :+1:

**Comment by git-harry** [comment]
-1 this needs updating to openstack-ansible. There is a merge commit that should be removed and the branch rebased instead.

**Comment by stevelle** [comment]
bump?

**Comment by hughsaunders** [comment]
:-1: uses bashisms but specifies interpreter as sh

**Pull request closed without merging**
