### PR TITLE
Revert "Add MaaS checks for processes status (#1366)"

### PR DESCRIPTION
**Pull request by cloader89**
Reverts rcbops/rpc-openstack#1491

### CODE REVIEW

**Comment by sigmavirus24** [comment]
You're failing the commit message checks

**Comment by hughsaunders** [comment]
Why?

**Comment by sigmavirus24** [comment]
@hughsaunders because this was not supposed to merge prior to r13.1.0 being released and it was merged by accident on Friday. 

I'm 👍. We'll revert the revert after r13.1.0 is finalized.

**Comment by d34dh0r53** [comment]
:+1: for recursive reversion

**Pull request merged**
