### PR TITLE
Clarify voting on backported patches

### LINKED ISSUE #921: Can a clean cherry-picked backport be voted on by the backporter?
##### What version (commit) do you encounter this issue on?
backports

##### What type of issue is this (bug, feature, documentation, regression)?
documentation

##### What is the expected behavior?
unknown

##### What is actually happening?
limbo

##### How can we reproduce this issue?
do a backport

##### How can we verify your issue is addressed?
doc who can vote and in what situations they cannot vote

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
doc

##### What is your evaluation on the importance of this issue, and why?
minor

##### What branches / milestones do you believe this issue should target?
The list below is what is currently supported for backports, remove branches you do not wish to target.
- [ ] Master

### PR DESCRIPTION
**Pull request by prometheanfire**
Closes #921

Signed-off-by: Matthew Thode <mthode@mthode.org>

### CODE REVIEW

**Comment by prometheanfire** [comment]
recheck_upgrade

**Comment by nrb** [comment]
:+1:

**Comment by tomc603** [comment]
This makes sense, and I agree with it. :+1:

**Comment by prometheanfire** [comment]
recheck_upgrade

**Comment by prometheanfire** [comment]
recheck_upgrade

    04:03:45 tempest.api.compute.servers.test_server_actions.ServerActionsTestJSON.test_reboot_server_hard[id-2cb1baf6-ac8d-4429-bf0d-ba8a0ba53e32,smoke]

**Comment by prometheanfire** [comment]
recheck_upgrade

assuming verify_maas failed like it did with #928

**Comment by prometheanfire** [comment]
recheck_upgrade

**Comment by git-harry** [comment]
:+1:

**Pull request merged**
