### PR TITLE
Revert "Create run level links for Beaver"

### PR DESCRIPTION
**Pull request by ameserole**
Reverts rcbops/rpc-openstack#1277

### CODE REVIEW

**Comment by Apsu** [comment]
RPC-AIO-Liberty-Upgrade-PR: Fail

**Comment by git-harry** [comment]
@ameserole is this revert solely because https://github.com/rcbops/rpc-openstack/pull/1277 didn't receive the appropriate level of review i.e two +1's? If that's the case then hopefully we can avoid the need to revert the patch, @mancdaz reviewed https://github.com/rcbops/rpc-openstack/pull/1277 and has given it a +1 which means the merge can stand assuming you identified no other issues with it.

**Comment by ameserole** [comment]
@git-harry Yes I made it just in case someone tested the original bug and found some issues with it.

**Comment by git-harry** [comment]
The commit being reverted in the pull request does not need to be removed.

**Pull request closed without merging**
