### PR TITLE
Enable security hardening by default

### PR DESCRIPTION
**Pull request by major**
This patch enables security hardening by default for all deployments.
Deployers can opt-out of this change by setting the
``DEPLOY_HARDENING`` environment variable to ``no`` prior to running
``deploy.sh``.

Release notes are included.

Connects to https://github.com/rcbops/u-suk-dev/issues/159

### CODE REVIEW

**Comment by git-harry** [comment]
👎 This setting is currently controlled by [deploy.sh][1] and so that should be the only thing you need to change.

[1]: https://github.com/rcbops/rpc-openstack/blob/master/scripts/deploy.sh#L16

**Comment by major** [comment]
Darn -- I totally forgot that we made the change there. I'll get this fixed up.

**Comment by major** [comment]
Just rebased onto latest master to test against Mitaka. This brings in #1174.

**Comment by tomc603** [comment]
Currently testing with AIO

**Comment by git-harry** [comment]
👍

**Comment by evrardjp** [comment]
I trust @Apsu bot for testing this functionality.
I think this is fine, and makes sense to enable on mitaka. 👍

**Pull request merged**
