### PR TITLE
SHA bump for OSAD to match 11.0.3 as of 25/06/2015

### LINKED ISSUE #188: [r11.0.0rc5] Cannot migrate Keystone database schema
Within the `r11.0.0rc5` tag, the RPC-QE team is unable to complete a greenfield `rpc-openstack` installation. The failure occurs during the [Keystone database synchronization](http://jenkins.propter.net/job/release-rpc-openstack-docker/19/console) because of duplicate, versioned scripts present in the pip package that was retrieved earlier in the installation.

The OSAD SHA that's pulled incorrectly [builds the pip repo URL](https://github.com/stackforge/os-ansible-deployment/blob/9a803df33f4f30ccbbf30b8d4359afe6fb8d51b9/playbooks/inventory/group_vars/all.yml#L33-L40). Not only is the `openstack-release` variable set to `master` instead of `11.0.x`, but the base of the address is that of the deployment's internal LB VIP. This is corrected within OSAD's `11.0.3` tag.

Within the `11.0.3` tag, the `openstack-release` variable is [properly set to `11.0.3`](https://github.com/stackforge/os-ansible-deployment/blob/96608eb2242cb55bb5a95b8386d13556153e5632/playbooks/inventory/group_vars/all.yml#L16-L17) and the pip repo URL is [correctly based off of a potential upstream one](https://github.com/stackforge/os-ansible-deployment/blob/96608eb2242cb55bb5a95b8386d13556153e5632/playbooks/roles/pip_lock_down/defaults/main.yml#L27-L29).

Can the SHA be moved up to accommodate these fixes? One thing to note is the addition of a `os-ansible-deployment/etc/openstack_deploy/user_group_vars.yml` file. As a side note, the RPC-QE team's automation already accommodates this configuration change.

### PR DESCRIPTION
**Pull request by nrb**
This bump is done in order to fix a problem with Keystone DB migrations.

Fixes #188

### CODE REVIEW

**Comment by rackertom** [comment]
I confirm the SHA is the same as the 11.0.3 OSAD tag. :+1:

**Comment by odyssey4me** [comment]
:+1: make the go!

**Comment by nrb** [comment]
2 +1s, merging.

**Comment by jacobwagner** [comment]
thanks guys

**Pull request merged**
