### PR TITLE
RLM-220 Bump OA_OPS up for leap fixes

### PR DESCRIPTION
**Pull request by antonym**
Bumps to latest leapfrog fixes @ openstack/openstack-ansible-ops@37ff5563ec7a5a1008211ff6c7231dda1244db63

Issue: [RLM-220](https://rpc-openstack.atlassian.net/browse/RLM-220)

### CODE REVIEW

**Comment by major** [comment]
Can't download the right packages. :/

```
"The following packages have unmet dependencies:", " build-essential : Depends: g++ (>= 4:5.2) but it is not going to be installed"
```

**Comment by antonym** [comment]
recheck_cit_artifact
recheck_cit_trusty_minorupgrade_swift
recheck_cit_xenial_deploy_swift
recheck_cit_xenial_minor_upgrade_swift

**Comment by antonym** [comment]
recheck_cit_xenial_minorupgrade_swift

**Comment by antonym** [comment]
recheck_cit_artifact
recheck_cit_trusty_deploy_swift
recheck_cit_trusty_minorupgrade_swift
recheck_cit_xenial_deploy_swift
recheck_cit_xenial_minorupgrade_swift

**Comment by antonym** [comment]
recheck_cit_xenial_minorupgrade_swift

**Comment by antonym** [comment]
recheck_cit_trusty_deploy_swift

**Comment by antonym** [comment]
recheck_cit_trusty_deploy_swift

**Pull request merged**
