### PR TITLE
Adding Magnum Installation Support to Newton

### PR DESCRIPTION
**Pull request by chrishultin**
See: https://github.com/rcbops/rpc-openstack/issues/1853

### CODE REVIEW

**Comment by odyssey4me** [comment]
At a glance, this looks good. :)

**Comment by cloudnull** [comment]
lgtm! :+1:

**Comment by antonym** [comment]
@alextricity25 did this need to be backported into newton branch?

**Comment by alextricity25** [comment]
@antonym: No, sir. Magnum will not be available in RPCO until 14.1(currently our master branch).

**Pull request merged**
