### PR TITLE
[Backport - Newton] MaaS improvements

### PR DESCRIPTION
**Pull request by major**
This backport includes the following four patches to master:

- 63369c2 MaaS: Improve period/timeout/disabling checks
- f501904 MaaS: Enable agent auto upgrade
- ef1bbae MaaS template fixes
- 20d4ba9 Disable MaaS alarms/checks with regex

Connects rcbops/u-suk-dev#1033
Connects rcbops/u-suk-dev#1050
Connects rcbops/u-suk-dev#1052

### CODE REVIEW

**Comment by antonym** [comment]
recheck_swift
recheck_xenial

**Comment by major** [comment]
recheck_xenial

**Comment by cloudnull** [comment]
Changes LGTM however waiting the gate to approve. In a follow on patch I'd love to see if there's a way to limit all of the repetition though the check yaml files. even though Ansible isn't a programming language and shouldn't be treated as such I feel like we may be able to leverage something like a jinja2 include (http://jinja.pocoo.org/docs/2.9/templates/#include) which would cut down on all of the ``rpcd/playbooks/roles/rpc_maas/templates/*.yaml.j2`` file repetition.

**Comment by major** [comment]
Good point, @cloudnull. That would make things much easier.

**Pull request merged**
