### PR TITLE
Rebuild rpc_release pip links file everytime rather then apending to it

### PR DESCRIPTION
**Pull request by BjoernT**
Rebuild rpc_release pip links file everytime rather then apending to it
Fixes-Issue: #597

### CODE REVIEW

**Comment by d34dh0r53** [comment]
:+1:

**Comment by sigmavirus24** [comment]
:+1:

**Comment by hughsaunders** [comment]
This will cause the template to be marked as changed on every run. Would be better to add regexp: "." to the current lineinfile job. :-1:

**Comment by git-harry** [comment]
-1 I think it would be better to use the copy module, it has a content parameter that can be used to specify the contents of the file. That removes the need for deleting the old file and doesn't require a regexp type search for the line. Using copy is essentially doing the job of a simple template file which would be the other alternative but possibly a bit heavyweight for something so simple.

**Pull request closed without merging**
