### PR TITLE
Update Ceph Branch SHAs

### PR DESCRIPTION
**Pull request by hughsaunders**
This is specifically to bring in @byronmccollum's fix to make the ceph conf dir
and file configurable.

Related: #747
Related: https://github.com/ceph/ceph-ansible/pull/485

### CODE REVIEW

**Comment by byronmccollum** [comment]
SHA bumps are the latest, and ceph-common includes the needed fix. Looks good to me.

**Comment by d34dh0r53** [comment]
This will be taken care of with #770.

**Comment by byronmccollum** [comment]
Did these SHA bumps land in master too?

**Comment by d34dh0r53** [comment]
Master will have updated Ceph SHA's but I'll wait until the galaxy PR ( #578 ) merges before I close this

**Comment by hughsaunders** [comment]
recheck

**Comment by prometheanfire** [comment]
ran of of quota space

**Comment by prometheanfire** [comment]
recheck

**Pull request merged**
