### PR TITLE
Remove unused rpcd group_vars

### PR DESCRIPTION
**Pull request by odyssey4me**
In 35a375c7ff8104578ee93bfd6b1d9d3b612b2e62 a new set of
group_vars was implemented with the vars plugin that
merges both the RPC-O and OSA group vars.

As such, none of these group_vars are used or necessary
any more.

Connects https://github.com/rcbops/u-suk-dev/issues/1659

### CODE REVIEW

**Comment by odyssey4me** [comment]
recheck_cit_all

**Comment by alextricity25** [comment]
Blocked by: https://github.com/rcbops/rpc-openstack/pull/2263

**Comment by odyssey4me** [comment]
recheck_cit_xenial

**Comment by odyssey4me** [comment]
recheck_cit_ceph

**Pull request merged**
