### PR TITLE
use safe methods from the yaml library

### PR DESCRIPTION
**Pull request by prometheanfire**
Fixes: SE-2117

Issue: [SE-2117](https://rpc-openstack.atlassian.net/browse/SE-2117)

### CODE REVIEW

**Comment by prometheanfire** [comment]
lint error isn't my fault?

**Comment by prometheanfire** [comment]
recheck_cit_release

**Comment by prometheanfire** [comment]
recheck_cit_release

**Comment by major** [comment]
recheck_cit_artifact

**Comment by odyssey4me** [comment]
recheck_cit_release

**Comment by prometheanfire** [comment]
so, what's up with the artifacts? are they hard blocking gate?

**Comment by odyssey4me** [comment]
@prometheanfire I don't understand your question. The artifact job is passing in this PR.

recheck_cit_release - the failure is fixed, this patch may need a rebase

**Comment by prometheanfire** [comment]
I was talking about the travis-ci pr and push tests, I'll rebase and see if it helps those though, I thought it depended on some elk changes.

**Comment by prometheanfire** [comment]
oh, those moved to non-required, wfm

**Comment by prometheanfire** [comment]
ya, looks like elk is sad

`/root/.ansible/roles/logstash/tasks/upgrade_logstash_pre.yml:17`

**Comment by odyssey4me** [comment]
@prometheanfire Yes, that's been recorded in https://rpc-openstack.atlassian.net/browse/RO-3145 - if you can assist with getting that resolved it'd be marvellous. Those roles could also do with a test implementation.

**Comment by cloudnull** [comment]
Once this has been rebased it should pass all of the tests.

**Comment by major** [comment]
We've got linting errors on the ELK stuff but that's been fixed in another patch.

**Pull request merged**
