### PR TITLE
Update openstack-ansible SHA

### PR DESCRIPTION
**Pull request by git-harry**
This commit updates the openstack-ansible SHA in preparation for the
next release.

The following issues are addressed by this change:

Connected https://github.com/rcbops/rpc-openstack/issues/1130
Connected https://github.com/rcbops/rpc-openstack/issues/1131
Connected https://github.com/rcbops/rpc-openstack/issues/1134

### CODE REVIEW

**Comment by Apsu** [comment]
RPC-AIO-Liberty-Upgrade-PR: Fail

**Comment by git-harry** [comment]
recheck_upgrade

**Comment by Apsu** [comment]
RPC-AIO-Liberty-Upgrade-PR: Fail

**Comment by git-harry** [comment]
Upgrades are failing due to a change upstream. I've created at [upstream fix](https://review.openstack.org/#/c/342183/1) and am currently testing it with a separate [pull request](https://github.com/rcbops/rpc-openstack/pull/1238)

**Comment by evrardjp** [comment]
👍

**Pull request merged**
