### PR TITLE
RO-4188 Update newton dependencies

### PR DESCRIPTION
**Pull request by rpc-jenkins-svc**
Automated dependency update pull request, see individual commits for details.

Issue: [RO-4188](https://rpc-openstack.atlassian.net/browse/RO-4188)

### CODE REVIEW

**Comment by prometheanfire** [comment]
recheck_trusty_swift_deploy

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by prometheanfire** [comment]
recheck_trusty_swift_deploy
recheck_artifact

**Comment by odyssey4me** [comment]
Assuming it passes tests, https://github.com/rcbops/rpc-openstack/pull/3446 should resolve the artifact build failure.

**Comment by odyssey4me** [comment]
recheck_xenial_swift_deploy ``Could not fetch updated apt files``

**Comment by odyssey4me** [comment]
recheck_trusty_swift_deploy

```
TASK [logstash : Add apt keys] *************************************************
FAILED - RETRYING: TASK: logstash : Add apt keys (5 retries left).
FAILED - RETRYING: TASK: logstash : Add apt keys (4 retries left).
FAILED - RETRYING: TASK: logstash : Add apt keys (3 retries left).
FAILED - RETRYING: TASK: logstash : Add apt keys (2 retries left).
FAILED - RETRYING: TASK: logstash : Add apt keys (1 retries left).
failed: [aio1_logstash_container-ccdf5f1d] (item={u'url': u'https://packages.elastic.co/GPG-KEY-elasticsearch', u'state': u'present'}) => {"failed": true, "item": {"state": "present", "url": "https://packages.elastic.co/GPG-KEY-elasticsearch"}, "msg": "Failed to validate the SSL certificate for packages.elastic.co:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine or you can install the `urllib3`, `pyopenssl`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"}
```

**Comment by odyssey4me** [comment]
recheck_trusty_swift_deploy

**Comment by odyssey4me** [comment]
recheck_trusty_swift_deploy

**Pull request merged**
