### PR TITLE
[RI-475] consolidate and use constraints

### PR DESCRIPTION
**Pull request by prometheanfire**
Issue: [RI-475](https://rpc-openstack.atlassian.net/browse/RI-475)

### CODE REVIEW

**Comment by prometheanfire** [comment]
recheck_cit_release

should work, dulwich is in upper-constraints and 0.19.6 works on 2.7/3.5/3.6

**Comment by prometheanfire** [comment]
recheck_release

**Comment by prometheanfire** [comment]
recheck_xenial_no_artifacts_swift_deploy

**Comment by prometheanfire** [comment]
recheck_release

tested locally, `pip install -r test-requirements.txt -c upper-constraints.txt` works in a new venv...

recheck_xenial_no_artifacts_swift_deploy

failed on `Create the neutron provider networks facts`, notmyfault

**Comment by prometheanfire** [comment]
recheck_cit_release
recheck_cit_xenial_no_artifacts_swift_deploy

**Comment by prometheanfire** [comment]
requires https://github.com/rcbops/rpc-gating/pull/1117 methinks

**Comment by prometheanfire** [comment]
recheck_cit_release

lets see if the dockerfile is updated

**Comment by prometheanfire** [comment]
recheck_cit_release

**Comment by prometheanfire** [comment]
recheck_cit_release

**Comment by odyssey4me** [comment]
recheck_release

**Comment by prometheanfire** [comment]
I did add a tox job that'll do just that

**Comment by prometheanfire** [comment]
reason I think this is happening is because setuptools/pip is old on the os image, just a guess though since I've not been able to reproduce

**Pull request merged**
