### PR TITLE
[mitaka-13.1] Update OSA SHA

### PR DESCRIPTION
**Pull request by alextricity25**
OpenStack-Ansible Diff Generator
================================

This report shows changes from `c37e3c20130031fabedf324e1ed39bc2f10dbf24` to `fbafe397808ef3ee3447fe8fefa6ac7e5c6ff144` in OpenStack-Ansible.

This report also includes the changes that were made in OpenStack projects and OpenStack-Ansible roles between these two OpenStack-Ansible commits.

openstack-ansible
-----------------

6 commits were found in [openstack-ansible](https://github.com/openstack/openstack-ansible) from `c37e3c20` to `fbafe397`:

<table>
<col width="57%" />
<col width="42%" />
<tbody>
<tr class="odd">
<td align="left"><a href="https://github.com/openstack/openstack-ansible/commit/fbafe397808ef3ee3447fe8fefa6ac7e5c6ff144">fbafe397</a></td>
<td align="left">Update all SHAs for 13.3.19</td>
</tr>
<tr class="even">
<td align="left"><a href="https://github.com/openstack/openstack-ansible/commit/2652135578cc4a686bb93427674aa0c87f144a85">26521355</a></td>
<td align="left">Update all SHAs for 13.3.18</td>
</tr>
<tr class="odd">
<td align="left"><a href="https://github.com/openstack/openstack-ansible/commit/1583f24043fd4e60635af9eee1de440c4a3977f8">1583f240</a></td>
<td align="left">Update all SHAs for 13.3.17</td>
</tr>
<tr class="even">
<td align="left"><a href="https://github.com/openstack/openstack-ansible/commit/89043c5a70c87548c8eb8cd0d005776464eaa2ed">89043c5a</a></td>
<td align="left">Enable timeout for http_request</td>
</tr>
<tr class="odd">
<td align="left"><a href="https://github.com/openstack/openstack-ansible/commit/d0e3ecb8a2ee484a96ef57f2ab53ccbde69baede">d0e3ecb8</a></td>
<td align="left">Define haproxy_ssl_bind_options variable.</td>
</tr>
<tr class="even">
<td align="left"><a href="https://github.com/openstack/openstack-ansible/commit/ba1adc4cf13841b40a0f46957213478f442435e7">ba1adc4c</a></td>
<td align="left">Update all SHAs for 13.3.16</td>
</tr>
</tbody>
</table>

Release Notes
-------------

OpenStack-Ansible Roles
-----------------------

### apt\_package\_pinning

No commits were found in [apt\_package\_pinning](https://github.com/openstack/openstack-ansible-apt_package_pinning) between the OpenStack-Ansible commits provided.

### pip\_install

No commits were found in [pip\_install](https://github.com/openstack/openstack-ansible-pip_install) between the OpenStack-Ansible commits provided.

### pip\_lock\_down

No commits were found in [pip\_lock\_down](https://github.com/openstack/openstack-ansible-pip_lock_down) between the OpenStack-Ansible commits provided.

### galera\_client

No commits were found in [galera\_client](https://github.com/openstack/openstack-ansible-galera_client) between the OpenStack-Ansible commits provided.

### galera\_server

No commits were found in [galera\_server](https://github.com/openstack/openstack-ansible-galera_server) between the OpenStack-Ansible commits provided.

### keepalived

No commits were found in [keepalived](https://github.com/evrardjp/ansible-keepalived) between the OpenStack-Ansible commits provided.

### lxc\_container\_create

No commits were found in [lxc\_container\_create](https://github.com/openstack/openstack-ansible-lxc_container_create) between the OpenStack-Ansible commits provided.

### lxc\_hosts

No commits were found in [lxc\_hosts](https://github.com/openstack/openstack-ansible-lxc_hosts) between the OpenStack-Ansible commits provided.

### memcached\_server

No commits were found in [memcached\_server](https://github.com/openstack/openstack-ansible-memcached_server) between the OpenStack-Ansible commits provided.

### openstack-ansible-security

No commits were found in [openstack-ansible-security](https://github.com/openstack/openstack-ansible-security) between the OpenStack-Ansible commits provided.

### openstack\_hosts

No commits were found in [openstack\_hosts](https://github.com/openstack/openstack-ansible-openstack_hosts) between the OpenStack-Ansible commits provided.

### os\_keystone

No commits were found in [os\_keystone](https://github.com/openstack/openstack-ansible-os_keystone) between the OpenStack-Ansible commits provided.

### openstack\_openrc

No commits were found in [openstack\_openrc](https://github.com/openstack/openstack-ansible-openstack_openrc) between the OpenStack-Ansible commits provided.

### os\_aodh

1 commit was found in [os\_aodh](https://github.com/openstack/openstack-ansible-os_aodh) from `35656b53` to `45c0bd4e`:

<table>
<col width="58%" />
<col width="41%" />
<tbody>
<tr class="odd">
<td align="left"><a href="https://github.com/openstack/openstack-ansible-os_aodh/commit/45c0bd4e940a1a53db1cdac8110a30dd6cab668a">45c0bd4e</a></td>
<td align="left">Update paste, policy and rootwrap configurations 2017-03-16</td>
</tr>
</tbody>
</table>

### os\_ceilometer

No commits were found in [os\_ceilometer](https://github.com/openstack/openstack-ansible-os_ceilometer) between the OpenStack-Ansible commits provided.

### os\_cinder

No commits were found in [os\_cinder](https://github.com/openstack/openstack-ansible-os_cinder) between the OpenStack-Ansible commits provided.

### os\_glance

No commits were found in [os\_glance](https://github.com/openstack/openstack-ansible-os_glance) between the OpenStack-Ansible commits provided.

### os\_heat

No commits were found in [os\_heat](https://github.com/openstack/openstack-ansible-os_heat) between the OpenStack-Ansible commits provided.

### os\_horizon

1 commit was found in [os\_horizon](https://github.com/openstack/openstack-ansible-os_horizon) from `3297611e` to `f984441e`:

<table>
<col width="59%" />
<col width="40%" />
<tbody>
<tr class="odd">
<td align="left"><a href="https://github.com/openstack/openstack-ansible-os_horizon/commit/f984441e0ad07d81840cf3e7208a936a3ef408d0">f984441e</a></td>
<td align="left">Use horizon_ssl_protocol variable</td>
</tr>
</tbody>
</table>

### os\_ironic

No commits were found in [os\_ironic](https://github.com/openstack/openstack-ansible-os_ironic) between the OpenStack-Ansible commits provided.

### os\_neutron

1 commit was found in [os\_neutron](https://github.com/openstack/openstack-ansible-os_neutron) from `a8c9d1cf` to `2cce5e6e`:

<table>
<col width="59%" />
<col width="40%" />
<tbody>
<tr class="odd">
<td align="left"><a href="https://github.com/openstack/openstack-ansible-os_neutron/commit/2cce5e6e8fec00125f912baa86890e4302f67f18">2cce5e6e</a></td>
<td align="left">Configure RPC settings for all neutron components</td>
</tr>
</tbody>
</table>

### os\_nova

No commits were found in [os\_nova](https://github.com/openstack/openstack-ansible-os_nova) between the OpenStack-Ansible commits provided.

### os\_swift

No commits were found in [os\_swift](https://github.com/openstack/openstack-ansible-os_swift) between the OpenStack-Ansible commits provided.

### os\_tempest

2 commits were found in [os\_tempest](https://github.com/openstack/openstack-ansible-os_tempest) from `296dbe78` to `3e58cd1d`:

<table>
<col width="59%" />
<col width="40%" />
<tbody>
<tr class="odd">
<td align="left"><a href="https://github.com/openstack/openstack-ansible-os_tempest/commit/3e58cd1dc1bb6be85d75e9ea3afac729eb2ec966">3e58cd1d</a></td>
<td align="left">Skip specific tempest API test</td>
</tr>
<tr class="even">
<td align="left"><a href="https://github.com/openstack/openstack-ansible-os_tempest/commit/582c633d5e3c8f53c98ac43d78ceb3832a086008">582c633d</a></td>
<td align="left">Add configuration options to enable ironic testing</td>
</tr>
</tbody>
</table>

### plugins

No commits were found in [plugins](https://github.com/openstack/openstack-ansible-plugins) between the OpenStack-Ansible commits provided.

### rabbitmq\_server

No commits were found in [rabbitmq\_server](https://github.com/openstack/openstack-ansible-rabbitmq_server) between the OpenStack-Ansible commits provided.

### repo\_build

No commits were found in [repo\_build](https://github.com/openstack/openstack-ansible-repo_build) between the OpenStack-Ansible commits provided.

### repo\_server

No commits were found in [repo\_server](https://github.com/openstack/openstack-ansible-repo_server) between the OpenStack-Ansible commits provided.

### rsyslog\_client

No commits were found in [rsyslog\_client](https://github.com/openstack/openstack-ansible-rsyslog_client) between the OpenStack-Ansible commits provided.

### rsyslog\_server

No commits were found in [rsyslog\_server](https://github.com/openstack/openstack-ansible-rsyslog_server) between the OpenStack-Ansible commits provided.

### sshd

No commits were found in [sshd](https://github.com/willshersystems/ansible-sshd) between the OpenStack-Ansible commits provided.

Connects https://github.com/rcbops/rpc-openstack/issues/2211

### CODE REVIEW

**Comment by alextricity25** [comment]
recheck_cit_all

**Comment by cjloader** [comment]
recheck_cit_swift

**Comment by alextricity25** [comment]
recheck_cit_upgrade

**Comment by alextricity25** [comment]
recheck_cit_upgrade

**Comment by mattt416** [comment]
recheck_cit_upgrade

**Comment by mattt416** [comment]
recheck_cit_upgrade

**Comment by mattt416** [comment]
recheck_cit_upgrade

**Pull request merged**
