### PR TITLE
Update Liberty OpenStack-Ansible SHA

### PR DESCRIPTION
**Pull request by git-harry**
Update OpenStack-Ansible SHA in preparation for the release of r12.2.3.

Connected https://github.com/rcbops/u-suk-dev/issues/287

### CODE REVIEW

**Comment by Apsu** [comment]
RPC-AIO-Liberty-Upgrade-PR: Fail

**Comment by git-harry** [comment]
recheck_upgrade

**Comment by Apsu** [comment]
RPC-AIO-Liberty-Upgrade-PR: Fail

**Comment by sigmavirus24** [comment]
recheck_upgrade

**Comment by Apsu** [comment]
RPC-AIO-Liberty-Upgrade-PR: Fail

**Comment by git-harry** [comment]
recheck_upgrade

**Comment by Apsu** [comment]
RPC-AIO-Liberty-Upgrade-PR: Fail

**Comment by sigmavirus24** [comment]
recheck_upgrade

**Comment by Apsu** [comment]
RPC-AIO-Liberty-Upgrade-PR: Fail

**Comment by git-harry** [comment]
recheck_upgrade

**Comment by Apsu** [comment]
RPC-AIO-Liberty-Upgrade-PR: Fail

**Comment by hughsaunders** [comment]
recheck_upgrade

**Comment by Apsu** [comment]
RPC-AIO-Liberty-Upgrade-PR: Fail

**Comment by hughsaunders** [comment]
recheck_upgrade

**Comment by Apsu** [comment]
RPC-AIO-Liberty-Upgrade-PR: Fail

**Comment by Apsu** [comment]
RPC-AIO-Liberty-Upgrade-PR: Fail

**Comment by git-harry** [comment]
recheck_upgrade

**Comment by sigmavirus24** [comment]
👍

**Comment by d34dh0r53** [comment]
👍

**Pull request merged**
