### PR TITLE
LA-436 Update test resource generation process

### PR DESCRIPTION
**Pull request by git-harry**
`deploy-rpc-playbooks.sh` changes:
- calling `generate-resources.yml` is added to allow the resources to be
  set up before Telegraf is deployed.
- the rpc-maas var `telegraf_plugin_ping_urls` is set with the floating
  IP addresses of the generated resources so they can be monitored
during the upgrade.

`generate-resources.yml` changes:
- to accommodate the requirement to run this playbook in
  `deploy-rpc-playbook.sh` it is moved to `rpcd/playbooks`
- `os-tempest-install.yml` added to removing the need for rpc-gating to
  manage this requirement.
- checks for existing instances created by this playbook and skips if
  there are any given that they only need to be created at the beginning
of an upgrade.

`generate_resources.py` changes:
- updated to make use of the OpenStack Python SDK, this simplifies the
  code
- floating IP addresses are now assigned to the created servers
- a security group is created to ensure the servers can be pinged

`maas_release` is updated to a SHA that includes support for the
Telegraf ping plugin.

Issue: [LA-436](https://rpc-openstack.atlassian.net/browse/LA-436)

### CODE REVIEW

**Comment by claco** [comment]
recheck_cit_trusty_deploy_swift
recheck_cit_trusty_leapfrogupgrade_swift
recheck_cit_trusty_minorupgrade_swift
recheck_cit_xenial_deploy_swift
recheck_cit_xenial_minorupgrade_swift

**Comment by git-harry** [comment]
recheck_cit_trusty_deploy_swift
recheck_cit_trusty_leapfrogupgrade_swift
recheck_cit_trusty_minorupgrade_swift
recheck_cit_xenial_deploy_swift
recheck_cit_xenial_minorupgrade_swift

**Comment by odyssey4me** [comment]
recheck_cit_trusty_deploy_swift
recheck_cit_xenial_deploy_swift

**Comment by odyssey4me** [comment]
recheck_cit_trusty_deploy_swift

```
 > git fetch --tags --progress https://github.com/rcbops/rpc-gating +refs/heads/*:refs/remotes/origin/*
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/rcbops/rpc-gating +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: remote: Counting objects: 3596, done.        
remote: Compressing objects:   8% (1/12)           
remote: Compressing objects:  16% (2/12)           
remote: Compressing objects:  25% (3/12)           
remote: Compressing objects:  33% (4/12)           
remote: Compressing objects:  41% (5/12)           
remote: Compressing objects:  50% (6/12)           
remote: Compressing objects:  58% (7/12)           
remote: Compressing objects:  66% (8/12)           
remote: Compressing objects:  75% (9/12)           
remote: Compressing objects:  83% (10/12)           
remote: Compressing objects:  91% (11/12)           
remote: Compressing objects: 100% (12/12)           
remote: Compressing objects: 100% (12/12), done.        
Receiving objects:   0% (1/3596)   
Receiving objects:   1% (36/3596)   
Receiving objects:   2% (72/3596)   
Receiving objects:   3% (108/3596)   
Receiving objects:   4% (144/3596)   
Receiving objects:   5% (180/3596)   
Receiving objects:   6% (216/3596)   
Receiving objects:   7% (252/3596)   
Receiving objects:   8% (288/3596)   
Receiving objects:   9% (324/3596)   
Receiving objects:  10% (360/3596)   
Receiving objects:  11% (396/3596)   
Receiving objects:  12% (432/3596)   
Receiving objects:  13% (468/3596)   
Receiving objects:  14% (504/3596)   
Receiving objects:  15% (540/3596)   
Receiving objects:  16% (576/3596)   
Receiving objects:  17% (612/3596)   
Receiving objects:  18% (648/3596)   
Receiving objects:  19% (684/3596)   
Receiving objects:  20% (720/3596)   
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1924)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1643)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:71)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:352)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:559)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at ......remote call to long-running-slave-17-48bd(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1537)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
	at hudson.remoting.Channel.call(Channel.java:822)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
	at sun.reflect.GeneratedMethodAccessor602.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
	at com.sun.proxy.$Proxy96.execute(Unknown Source)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1075)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1115)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:109)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:83)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:73)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:221)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cloudnull** [comment]
recheck_cit_trusty_deploy_swift

**Comment by cloudnull** [comment]
recheck_cit_xenial_deploy_swift

**Comment by git-harry** [comment]
recheck_cit_xenial_deploy_swift
recheck_cit_trusty_deploy_swift

**Pull request merged**
