### PR TITLE
RO-4188 Update newton dependencies

### PR DESCRIPTION
**Pull request by rpc-jenkins-svc**
Automated dependency update pull request, see individual commits for details.

Issue: [RO-4188](https://rpc-openstack.atlassian.net/browse/RO-4188)

### CODE REVIEW

**Comment by antonym** [comment]
recheck_all

**Comment by odyssey4me** [comment]
This appears to be a duplicate of a previous PR doing much the same thing: https://github.com/rcbops/rpc-openstack/pull/2942

Were the issues in that one ever triaged?

**Comment by mattt416** [comment]
recheck_cit_trusty_swift_deploy

**Comment by mattt416** [comment]
recheck_cit_trusty_swift_deploy

**Comment by d34dh0r53** [comment]
recheck_cit_xenial_swift_deploy

**Comment by mattt416** [comment]
The actual trusty failure here is:

```
12:07:43 TASK [os_swift : Install apt packages] *****************************************
12:07:44 FAILED - RETRYING: TASK: os_swift : Install apt packages (5 retries left).
12:07:47 FAILED - RETRYING: TASK: os_swift : Install apt packages (4 retries left).
12:07:47 changed: [prontsd-254-16b9] => (item=[u'curl', u'gcc', u'git-core', u'liberasurecode1', u'liberasurecode-dev', u'libffi-dev', u'openssh-server', u'python-dev', u'rsync', u'libssl-dev'])
12:07:50 FAILED - RETRYING: TASK: os_swift : Install apt packages (3 retries left).
12:07:52 FAILED - RETRYING: TASK: os_swift : Install apt packages (2 retries left).
12:07:55 FAILED - RETRYING: TASK: os_swift : Install apt packages (1 retries left).
12:07:57 failed: [prontsd-254-16b9_swift_proxy_container-c6190647] (item=[u'curl', u'gcc', u'git-core', u'liberasurecode1', u'liberasurecode-dev', u'libffi-dev', u'openssh-server', u'python-dev', u'rsync', u'libssl-dev']) => {"failed": true, "item": ["curl", "gcc", "git-core", "liberasurecode1", "liberasurecode-dev", "libffi-dev", "openssh-server", "python-dev", "rsync", "libssl-dev"], "msg": "No package matching 'liberasurecode1' is available"}
```

The reason why we're not seeing this is other PR jobs is because they're using apt artifacts, where-as this build isn't (`RPCO_APT_ARTIFACTS_AVAILABLE="no"` is being set since there are no r14.12.0 artifacts built yet).

It looks like the bump from r14.10.0 to r14.11.0 was force-merged (see https://github.com/rcbops/rpc-openstack/pull/2911), we may need to do something similar here.

**Comment by mattt416** [comment]
As for the actual issue, I don't think containers are getting access to trusty-backports, which is likely the root cause of this problem.  It looks specific to the AIO though, as we're not seeing a similar failure on the MNAIO loose artifact newton jobs.

For the record, the AIO host has this:

```
root@prontsd-256-a97e:~# cat /etc/apt/sources.list.d/trusty-backports.list.list
deb http://mirror.rackspace.com/ubuntu trusty-backports main universe
root@prontsd-256-a97e:~#
```

**Comment by mattt416** [comment]
Believe this failure is a result of https://review.openstack.org/#/c/551260/ -- specifically, bootstrap-host no longer re-writing /etc/apt/sources.list on the host (which subsequently gets sucked into the containers). This isn't an issue on xenial because on xenial liberasurecode1 is in a different component (not -backports).

**Comment by mattt416** [comment]
I need to merge this now to get artifacts built for the morning. I've created https://github.com/rcbops/rpc-openstack/pull/2967 to test add trusty-backports to the host to see if that clears up the trusty failure, but unfortunately that's a ways off from finishing.

**Pull request merged**
