### PR TITLE
Set affinities to 1

### PR DESCRIPTION
**Pull request by hughsaunders**
This should prevent some failure cases (repo sync, keystone catalog
sync). It doesn't reduce test coverage as multiple containers are tested
in OSA.

Related: #814

### CODE REVIEW

**Comment by prometheanfire** [comment]
Changes we make downstream cause me to believe it is not valid logic to trust upstream tests and reduce our coverage downstream.  It would be better to find the cause of the failures downstream and fix it here.  If upstream is not having these issues and we are worries me.

**Comment by hughsaunders** [comment]
So setting all the affinities to 1 didn't work because maas checks that we have 3 containers for some things :( will try reducing keystone to see if it solves the cirros upload issue.

**Comment by hughsaunders** [comment]
recheck - it passed, but I want to see if it passes again..

**Comment by hughsaunders** [comment]
recheck - one more time

**Comment by hughsaunders** [comment]
recheck failed on apt

**Comment by hughsaunders** [comment]
recheck failed sub module checkout, have tweaked Jenkins job config

**Comment by hughsaunders** [comment]
recheck

**Comment by hughsaunders** [comment]
recheck apt fail

**Comment by hughsaunders** [comment]
28 AIOs have run on this patch and none have failed on cirros image upload, so reducing the keystone container affinity seems to solve the problem.

**Comment by odyssey4me** [comment]
If this solves the problem, then all this has done is isolate the root cause into a particular domain. The next step is going to have to be to figure out why this is an issue here, and not in OSA.

**Comment by prometheanfire** [comment]
I agree, particularly as RPC-O and OSA diverge we should keep test coverage.  This was useful for narrowing down the problem though.

**Comment by prometheanfire** [comment]
:-1: would like to test at least somewhat close to what we deploy, also, these don't seem to be causing failures (mostly cirros timeouts now)

**Comment by d34dh0r53** [comment]
recheck - testing cirrros fail

**Comment by nrb** [comment]
-1; I would rather we actually find the issue with multiple instances than simply reducing the affinity if at all possible.

Were this for resource constraint reasons, that might be more convincing for me.

**Comment by hughsaunders** [comment]
I agree. Possible cause: keystone caching, specifically multiple memcaches?

**Comment by prometheanfire** [comment]
given the closure of #814 I'm going to close this as well.  If we wish to continue discussing this we should probably do so in a bug.

**Comment by prometheanfire** [comment]
I left the branch around to reopen, please close if you don't reopen.

**Pull request closed without merging**
