### PR TITLE
Make rpc-o plabooks aware of venvs

### PR DESCRIPTION
**Pull request by evrardjp**
In some of our playbooks/roles in rpc-o we assume venvs are being
used/not being used. This implements the conditional pattern of OSA
to account for either case.

Connects rcbops/u-suk-dev#206

Signed-off-by: Jean-Philippe Evrard <jean-philippe.evrard@rackspace.co.uk>

### CODE REVIEW

**Comment by Apsu** [comment]
RPC-AIO-Liberty-PR: Fail

**Comment by Apsu** [comment]
RPC-AIO-Liberty-PR: Fail

**Comment by evrardjp** [comment]
recheck_swift -- tempest issue

**Comment by Apsu** [comment]
RPC-AIO-Liberty-PR: Fail

**Comment by d34dh0r53** [comment]
recheck_all

**Comment by evrardjp** [comment]
Passing, now I'll focus on the 'TBD' parts.

**Comment by evrardjp** [comment]
TBD paths updated. It should now allow an easy move to subsequent commits for the roles we decide to move to venvs.

**Comment by Apsu** [comment]
RPC-AIO-Ceph-Liberty-PR: Fail

**Comment by git-harry** [comment]
This is being closed in favour of creating separate tasks for the issues identified.

**Pull request closed without merging**
