### PR TITLE
[Backport - Liberty] MaaS: Add Service Checks for Swift Processes

### PR DESCRIPTION
**Pull request by antonym**
Adds service checks for Swift processes. 

Connects rcbops/u-suk-dev#1215

Cherry pick pick collided with filebeat and beaver processes but corrected.

### CODE REVIEW

**Comment by antonym** [comment]
recheck_swift

**Comment by antonym** [comment]
recheck_swift
recheck_ceph

**Comment by cloader89** [comment]
recheck_all

**Comment by antonym** [comment]
recheck_all

**Comment by antonym** [comment]
Seems to not be liking the process checks in the verify-maas run:

```19:29:52 failed: [jralcp-26-28368] => {"attempts": 10, "changed": false, "failed": true, "failed_when_result": true, "rc": 1, "stdout_lines": ["--- 2017-02-22 19:29:50.532778 ---", "Checks and Alarms with failures:", " - Entity:enKg8mbhTI:jralcp-26-28368", "   ! Check:agent.plugin:ch6HD5vAkQ:swift_account_process_check--jralcp-26-28368: Completed:False Status:Plugin exited with non-zero status code (code=-127)", "     ! Alarm:al3qgP1Vav:swift-account-reaper_process_status--jralcp-26-28368:CRITICAL", "     ! Alarm:alciXMXIop:swift-account-replicator_process_status--jralcp-26-28368:CRITICAL", "     ! Alarm:algPG7td9a:swift-account-server_process_status--jralcp-26-28368:CRITICAL", "     ! Alarm:aliioQOhBr:swift-account-auditor_process_status--jralcp-26-28368:CRITICAL", "   ! Check:agent.plugin:chNcCn5LgT:swift_container_process_check--jralcp-26-28368: Completed:False Status:Plugin exited with non-zero status code (code=-127)", "     ! Alarm:al8ZFclsYS:swift-container-replicator_process_status--jralcp-26-28368:CRITICAL", "     ! Alarm:al8jp9RVU0:swift-container-updater_process_status--jralcp-26-28368:CRITICAL", "     ! Alarm:alJEiCrvLj:swift-container-auditor_process_status--jralcp-26-28368:CRITICAL", "     ! Alarm:alszxwrfxK:swift-container-server_process_status--jralcp-26-28368:CRITICAL", "   ! Check:agent.plugin:ch5OaGlCGA:swift_object_process_check--jralcp-26-28368: Completed:False Status:Plugin exited with non-zero status code (code=-127)", "     ! Alarm:al9FtIoIzH:swift-object-server_process_status--jralcp-26-28368:CRITICAL", "     ! Alarm:alBMvwWgq7:swift-object-replicator_process_status--jralcp-26-28368:CRITICAL", "     ! Alarm:alL5ADcb1X:swift-object-updater_process_status--jralcp-26-28368:CRITICAL", "     ! Alarm:alytZ2xFo8:swift-object-auditor_process_status--jralcp-26-28368:CRITICAL"]}
19:29:52 stderr: OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
19:29:52 debug1: Reading configuration data /etc/ssh/ssh_config
19:29:52 debug1: /etc/ssh/ssh_config line 19: Applying options for *
19:29:52 debug1: auto-mux: Trying existing master
19:29:52 debug1: mux_client_request_session: master session id: 2
19:29:52 Shared connection to 172.29.236.100 closed.
19:29:52 
19:29:52 stdout: --- 2017-02-22 19:29:50.532778 ---
19:29:52 Checks and Alarms with failures:
19:29:52  - Entity:enKg8mbhTI:jralcp-26-28368
19:29:52    ! Check:agent.plugin:ch6HD5vAkQ:swift_account_process_check--jralcp-26-28368: Completed:False Status:Plugin exited with non-zero status code (code=-127)
19:29:52      ! Alarm:al3qgP1Vav:swift-account-reaper_process_status--jralcp-26-28368:CRITICAL
19:29:52      ! Alarm:alciXMXIop:swift-account-replicator_process_status--jralcp-26-28368:CRITICAL
19:29:52      ! Alarm:algPG7td9a:swift-account-server_process_status--jralcp-26-28368:CRITICAL
19:29:52      ! Alarm:aliioQOhBr:swift-account-auditor_process_status--jralcp-26-28368:CRITICAL
19:29:52    ! Check:agent.plugin:chNcCn5LgT:swift_container_process_check--jralcp-26-28368: Completed:False Status:Plugin exited with non-zero status code (code=-127)
19:29:52      ! Alarm:al8ZFclsYS:swift-container-replicator_process_status--jralcp-26-28368:CRITICAL
19:29:52      ! Alarm:al8jp9RVU0:swift-container-updater_process_status--jralcp-26-28368:CRITICAL
19:29:52      ! Alarm:alJEiCrvLj:swift-container-auditor_process_status--jralcp-26-28368:CRITICAL
19:29:52      ! Alarm:alszxwrfxK:swift-container-server_process_status--jralcp-26-28368:CRITICAL
19:29:52    ! Check:agent.plugin:ch5OaGlCGA:swift_object_process_check--jralcp-26-28368: Completed:False Status:Plugin exited with non-zero status code (code=-127)
19:29:52      ! Alarm:al9FtIoIzH:swift-object-server_process_status--jralcp-26-28368:CRITICAL
19:29:52      ! Alarm:alBMvwWgq7:swift-object-replicator_process_status--jralcp-26-28368:CRITICAL
19:29:52      ! Alarm:alL5ADcb1X:swift-object-updater_process_status--jralcp-26-28368:CRITICAL
19:29:52      ! Alarm:alytZ2xFo8:swift-object-auditor_process_status--jralcp-26-28368:CRITICAL```

**Comment by major** [comment]
Taking a looksee at this one.

**Comment by antonym** [comment]
Liberty use venvs in checks, so pushed update without them.

**Pull request merged**
