### PR TITLE
adding overrides for remote proceedure call tunables to user_variables

### LINKED ISSUE #220: Please check for the following default values in nova/neutron
We want to consider the following neutron and nova settings around database and RPC pool management as default in RPC. I personally would have seen that in OSAD but I'm pretty sure a bug would have been down voted :-1 there. Lastly we need to either make sure that these settings are set or are actively being set during the installation

keystone_db_max_pool_size: 120
keystone_db_pool_timeout: 30
neutron_db_pool_size: 120
neutron_db_pool_timeout: 30
nova_db_max_pool_size: 120
nova_db_pool_timeout: 30
rpc_conn_pool_size: 180
rpc_response_timeout: 180
rpc_thread_pool_size: 180
nova_rpc_conn_pool_size: '{{rpc_conn_pool_size}}'
nova_rpc_response_timeout: '{{rpc_response_timeout}}'
nova_rpc_thread_pool_size: '{{rpc_thread_pool_size}}'

BTW, the nova_rpc settings have not been implemented yet in OSAD (https://bugs.launchpad.net/openstack-ansible/+bug/1471926)

### PR DESCRIPTION
**Pull request by prometheanfire**
fixes #220

### CODE REVIEW

**Comment by nrb** [comment]
+1

**Comment by prometheanfire** [comment]
rebased

**Comment by nrb** [comment]
+1 again

**Comment by sigmavirus24** [comment]
+W

**Pull request merged**
