### PR TITLE
Configurable options in deploy.sh for verify-maas playbook

### LINKED ISSUE #621: MaaS r11.1.0rc5: `Verify presence of expected alarms` fails
Seems the alarms are not fully created in MaaS before the `Verify presence of expected alarms` task is run. You can see the filesystem alarm for `/srv/node/swift4` on `ee149569-object1` failed, but the other 4 alarms were present:

```
failed: [ee149569-object1] => (item=filesystem_.srv.node.swift4--ee149569-object1) => {"failed": true, "item": "filesystem_.srv.node.swift4--ee149569-object1"}
msg: Expected alarm for check (filesystem_.srv.node.swift4--ee149569-object1) not found
skipping: [ee149569-object1] => (item=filesystem_.srv.node.swift1--ee149569-object1)
skipping: [ee149569-object1] => (item=filesystem_.srv.node.swift2--ee149569-object1)
skipping: [ee149569-object1] => (item=filesystem_.srv.node.swift3--ee149569-object1)
skipping: [ee149569-object1] => (item=filesystem_.srv.node.swift5--ee149569-object1)
```

### Full Task Output
```
TASK: [Verify presence of expected alarms] ************************************ 
failed: [ee149569-object1] => (item=filesystem_.srv.node.swift4--ee149569-object1) => {"failed": true, "item": "filesystem_.srv.node.swift4--ee149569-object1"}
msg: Expected alarm for check (filesystem_.srv.node.swift4--ee149569-object1) not found
failed: [ee149569-object1] => (item=swift_account_server_check--ee149569-object1) => {"failed": true, "item": "swift_account_server_check--ee149569-object1"}
msg: Expected alarm for check (swift_account_server_check--ee149569-object1) not found
failed: [ee149569-object1] => (item=swift_quarantine_check--ee149569-object1) => {"failed": true, "item": "swift_quarantine_check--ee149569-object1"}
msg: Expected alarm for check (swift_quarantine_check--ee149569-object1) not found
skipping: [ee149569-infra1] => (item=conntrack_count--ee149569-infra1)
skipping: [ee149569-infra1] => (item=cpu_check--ee149569-infra1)
skipping: [ee149569-infra1] => (item=disk_utilisation--ee149569-infra1)
skipping: [ee149569-infra1] => (item=filesystem_.--ee149569-infra1)
skipping: [ee149569-infra1] => (item=galera_check--ee149569-infra1_galera_container-0679ccad)
skipping: [ee149569-infra1] => (item=keystone_api_local_check--ee149569-infra1_keystone_container-135bbf6a)
skipping: [ee149569-infra1] => (item=lb_api_check_keystone)
skipping: [ee149569-infra1] => (item=lb_api_check_swift_proxy)
skipping: [ee149569-infra1] => (item=memcached_status--ee149569-infra1_memcached_container-8cd1e7e1)
skipping: [ee149569-infra1] => (item=memory_check--ee149569-infra1)
skipping: [ee149569-infra1] => (item=rabbitmq_status--ee149569-infra1_rabbit_mq_container-91c0c43b)
skipping: [ee149569-infra1] => (item=swift_proxy_server_check--ee149569-infra1_swift_proxy_container-ec9ea791)
skipping: [ee149569-object1] => (item=conntrack_count--ee149569-object1)
skipping: [ee149569-object1] => (item=cpu_check--ee149569-object1)
skipping: [ee149569-object1] => (item=disk_utilisation--ee149569-object1)
skipping: [ee149569-object1] => (item=filesystem_.--ee149569-object1)
skipping: [ee149569-object1] => (item=filesystem_.srv.node.swift1--ee149569-object1)
skipping: [ee149569-object1] => (item=filesystem_.srv.node.swift2--ee149569-object1)
skipping: [ee149569-object1] => (item=filesystem_.srv.node.swift3--ee149569-object1)
skipping: [ee149569-object1] => (item=filesystem_.srv.node.swift5--ee149569-object1)
skipping: [ee149569-object1] => (item=memory_check--ee149569-object1)
skipping: [ee149569-object1] => (item=swift_account_replication_check--ee149569-object1)
skipping: [ee149569-object1] => (item=swift_async_check--ee149569-object1)
skipping: [ee149569-object1] => (item=swift_container_replication_check--ee149569-object1)
skipping: [ee149569-object1] => (item=swift_container_server_check--ee149569-object1)
skipping: [ee149569-object1] => (item=swift_md5_check--ee149569-object1)
skipping: [ee149569-object1] => (item=swift_object_replication_check--ee149569-object1)
skipping: [ee149569-object1] => (item=swift_object_server_check--ee149569-object1)
skipping: [ee149569-object2] => (item=conntrack_count--ee149569-object2)
skipping: [ee149569-object2] => (item=cpu_check--ee149569-object2)
skipping: [ee149569-object2] => (item=disk_utilisation--ee149569-object2)
skipping: [ee149569-object2] => (item=filesystem_.--ee149569-object2)
skipping: [ee149569-object2] => (item=filesystem_.srv.node.swift1--ee149569-object2)
skipping: [ee149569-object2] => (item=filesystem_.srv.node.swift2--ee149569-object2)
skipping: [ee149569-object2] => (item=filesystem_.srv.node.swift3--ee149569-object2)
skipping: [ee149569-object2] => (item=filesystem_.srv.node.swift4--ee149569-object2)
skipping: [ee149569-object2] => (item=filesystem_.srv.node.swift5--ee149569-object2)
skipping: [ee149569-object2] => (item=memory_check--ee149569-object2)
skipping: [ee149569-object2] => (item=swift_account_replication_check--ee149569-object2)
skipping: [ee149569-object2] => (item=swift_account_server_check--ee149569-object2)
skipping: [ee149569-object2] => (item=swift_async_check--ee149569-object2)
skipping: [ee149569-object2] => (item=swift_container_replication_check--ee149569-object2)
skipping: [ee149569-object2] => (item=swift_container_server_check--ee149569-object2)
skipping: [ee149569-object2] => (item=swift_md5_check--ee149569-object2)
skipping: [ee149569-object2] => (item=swift_object_replication_check--ee149569-object2)
skipping: [ee149569-object2] => (item=swift_object_server_check--ee149569-object2)
skipping: [ee149569-object2] => (item=swift_quarantine_check--ee149569-object2)
skipping: [ee149569-logger1] => (item=conntrack_count--ee149569-logger1)
skipping: [ee149569-logger1] => (item=cpu_check--ee149569-logger1)
skipping: [ee149569-logger1] => (item=disk_utilisation--ee149569-logger1)
skipping: [ee149569-logger1] => (item=filesystem_.--ee149569-logger1)
skipping: [ee149569-logger1] => (item=memory_check--ee149569-logger1)
skipping: [ee149569-object3] => (item=conntrack_count--ee149569-object3)
skipping: [ee149569-object3] => (item=cpu_check--ee149569-object3)
skipping: [ee149569-object3] => (item=disk_utilisation--ee149569-object3)
skipping: [ee149569-object3] => (item=filesystem_.--ee149569-object3)
skipping: [ee149569-object3] => (item=filesystem_.srv.node.swift1--ee149569-object3)
skipping: [ee149569-object3] => (item=filesystem_.srv.node.swift2--ee149569-object3)
skipping: [ee149569-object3] => (item=filesystem_.srv.node.swift3--ee149569-object3)
skipping: [ee149569-object3] => (item=filesystem_.srv.node.swift4--ee149569-object3)
skipping: [ee149569-object3] => (item=filesystem_.srv.node.swift5--ee149569-object3)
skipping: [ee149569-object3] => (item=memory_check--ee149569-object3)
skipping: [ee149569-object3] => (item=swift_account_replication_check--ee149569-object3)
skipping: [ee149569-object3] => (item=swift_account_server_check--ee149569-object3)
skipping: [ee149569-object3] => (item=swift_async_check--ee149569-object3)
skipping: [ee149569-object3] => (item=swift_container_replication_check--ee149569-object3)
skipping: [ee149569-object3] => (item=swift_container_server_check--ee149569-object3)
skipping: [ee149569-object3] => (item=swift_md5_check--ee149569-object3)
skipping: [ee149569-object3] => (item=swift_object_replication_check--ee149569-object3)
skipping: [ee149569-object3] => (item=swift_object_server_check--ee149569-object3)
skipping: [ee149569-object3] => (item=swift_quarantine_check--ee149569-object3)
```

### PR DESCRIPTION
**Pull request by byronmccollum**
This change introduces two new environment variables that control the
behavior of the verify-maas playbook: VERIFY_MAAS, and VERIFY_MAAS_DELAY.

VERIFY_MAAS (default 'yes') will control if the verify-maas playbook should
be run, and VERIFY_MAAS_DELAY (default '30') controls the sleep value before
the verify-maas playbook is run.

Fixes #621

### CODE REVIEW

**Comment by git-harry** [comment]
VERIFY_MAAS seems like a reasonable addition but I'm not sure what benefit VERIFY_MAAS_DELAY provides. VERIFY_MAAS_DELAY can only be set before the deploy script runs so, under what circumstances would that variable be changed on a one-off basis? How does one determine, ahead of time, that VERIFY_MAAS_DELAY should be increased?

**Comment by byronmccollum** [comment]
To be honest, adding VERIFY_MAAS_DELAY was for my own needs, where I can set it to something that works for my automated testing, because I know that 30 seconds is not enough time.

We already agree that 30 seconds is arbitrary. We could just set it to an absurdly large arbitrary value, knowing we're probably wasting time, but also knowing that it will work most if not all of the time. But the mere fact that a sleep exists between those two playbooks signifies a much deeper problem. This was just a quick fix, with the least amount of churn. Maybe this is a case where successerator might make a return.

Either way, having VERIFY_MAAS_DELAY default to the same value as the non-configurable value has no discernible difference if you don't care to fiddle with these bits.

**Comment by d34dh0r53** [comment]
I don't mind that `VERIFY_MAAS_DELAY` is configurable, but perhaps a comment indicating what it does or a link to the issue number would be beneficial.

**Comment by byronmccollum** [comment]
@d34dh0r53 Inline comment, or something somewhere else, like rpcdocs? I could add something to README.md about all the environment variables that `deploy.sh` uses. What that be beneficial, and suffice?

**Comment by d34dh0r53** [comment]
@byronmccollum I was just thinking an inline comment, but a section in the readme would be awesome!

**Comment by byronmccollum** [comment]
Added docs in `README.md`

**Comment by hughsaunders** [comment]
I hope #719 will make verify-maas reliable enough that these switches are not needed. The sleep has been removed so at least one isn't needed.

**Comment by byronmccollum** [comment]
Yup...Opening a new PR for the updated README.md document deploy.sh env vars.

**Pull request closed without merging**
