### PR TITLE
Added check to monitor container storage

### PR DESCRIPTION
**Pull request by cloudnull**
This check will notify users when the storage within a container has
reached >= 85%.

Signed-off-by: Kevin Carter <kevin.carter@rackspace.com>
(cherry picked from commit a24fdb160d1cd80870c6f01f3ab383e4dac1948a)
(cherry picked from commit aae2b923c3c5c3171e7ac9218b37cca26db9f7af)

### CODE REVIEW

**Comment by cloudnull** [comment]
recheck_all

**Comment by cloudnull** [comment]
recheck_cit_all

**Comment by cloudnull** [comment]
recheck

**Comment by faridsaad** [comment]
recheck_all

**Comment by mattt416** [comment]
This is failing because of the following:

```
TASK: [rpc_maas | Zero entities with label {{ inventory_hostname }}{{ maas_fqdn_extension }} exist] *** 
failed: [ramup-46-1060] => {"failed": true}
msg: Zero entities with the label ramup-46-1060 exist. Entities should be created as part of the hardware provisioning process, if missing, please consult the internal documentation for associating one with the device.
```

rpcd/playbooks/roles/rpc_maas/templates/container_storage_checks.yaml.j2 references `ansible_host`, perhaps that should be `ansible_hostname`?

**Comment by cloudnull** [comment]
recheck_cit_upgrade

**Comment by cloudnull** [comment]
recheck_cit_upgrade

**Comment by cloudnull** [comment]
recheck_cit_upgrade

**Comment by cloudnull** [comment]
Closed and re-opened seems the gates were wedged.

**Comment by mattt416** [comment]
recheck_cit_upgrade

**Comment by faridsaad** [comment]
recheck_cit_upgrade

**Comment by cloudnull** [comment]
I'm not sure what's causing this to fail. Any assistance from a resident MaaS expert would be greatly appreciated.

**Comment by mattt416** [comment]
@cloudnull I'm not sure why this specific upgrade job failed, but we need this PR to unblock the upgrade job so I'll monitor and make sure it goes through.

**Comment by mattt416** [comment]
recheck_cit_upgrade

**Comment by cloudnull** [comment]
recheck_cit_upgrade

**Comment by mattt416** [comment]
Still don't understand this failure, I'm trying to build the job manually here to see if I can trigger the same failure:

https://rpc.jenkins.cit.rackspace.net/job/RPC-AIO_mitaka-upgrade-periodic/48/

**Comment by hughsaunders** [comment]
The failure in build [72](https://rpc.jenkins.cit.rackspace.net/job/RPC-AIO_mitaka-upgrade-pr/72/console) looks legitimate:
```
TASK: [Verify Check & Alarm Status] ******************************************* 
failed: [ramup-72-948b] => {"attempts": 10, "changed": false, "failed": true, "failed_when_result": true, "rc": 1, "stdout_lines": ["--- 2017-04-24 21:41:46.518996 ---", "Checks and Alarms with failures:", " - Entity:entnm247MU:ramup-72-948b", "   ! Check:agent.plugin:chW5qBsgCp:container_storage_check--ramup-72-948b: Completed:False Status:Plugin exited with non-zero status code (code=-127)", "     ! Alarm:alDPzVaD3E:container_storage_percent_used--ramup-72-948b:CRITICAL"]}
stderr: OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 172.29.236.100 closed.

stdout: --- 2017-04-24 21:41:46.518996 ---
Checks and Alarms with failures:
 - Entity:entnm247MU:ramup-72-948b
   ! Check:agent.plugin:chW5qBsgCp:container_storage_check--ramup-72-948b: Completed:False Status:Plugin exited with non-zero status code (code=-127)
     ! Alarm:alDPzVaD3E:container_storage_percent_used--ramup-72-948b:CRITICAL

msg: Task failed as maximum retries was encountered

FATAL: all hosts have already failed -- aborting
```
I will upgrade the AnsiColor jenkins plugin and then retry to see if the numberformatexception problem recurs.

**Comment by hughsaunders** [comment]
recheck_cit_upgrade

**Comment by hughsaunders** [comment]
Build [76](https://rpc.jenkins.cit.rackspace.net/job/RPC-AIO_mitaka-upgrade-pr/76/) also seems to have failed legitimately:
```
TASK: [Verify Check & Alarm Status] ******************************************* 
failed: [ramup-76-c4d6] => {"attempts": 10, "changed": false, "failed": true, "failed_when_result": true, "rc": 1, "stdout_lines": ["--- 2017-04-25 10:28:46.303639 ---", "Checks and Alarms with failures:", " - Entity:enZf2Hh9t3:ramup-76-c4d6", "   ! Check:agent.plugin:chGHpbxHlf:container_storage_check--ramup-76-c4d6: Completed:False Status:Plugin exited with non-zero status code (code=-127)", "     ! Alarm:al7qDaUZVm:container_storage_percent_used--ramup-76-c4d6:CRITICAL"]}
stderr: OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 172.29.236.100 closed.

stdout: --- 2017-04-25 10:28:46.303639 ---
Checks and Alarms with failures:
 - Entity:enZf2Hh9t3:ramup-76-c4d6
   ! Check:agent.plugin:chGHpbxHlf:container_storage_check--ramup-76-c4d6: Completed:False Status:Plugin exited with non-zero status code (code=-127)
     ! Alarm:al7qDaUZVm:container_storage_percent_used--ramup-76-c4d6:CRITICAL

msg: Task failed as maximum retries was encountered

FATAL: all hosts have already failed -- aborting
```

**Comment by mattt416** [comment]
So this commit didn't fail on master, newton, or liberty, which means the failure here is most likely legitimate and one or more of the containers is using a lot of space.  I ran my own test locally and verify-maas also failed w/ this error, however when I subsequently went to look the script was passing fine.  I'm going to add an override in rpc-gating to set `percent_used_critical_threshold: 95` and once committed will re-check this PR to see if that helps.

**Comment by mattt416** [comment]
recheck_cit_upgrade

**Comment by mattt416** [comment]
recheck_cit_upgrade

**Comment by mattt416** [comment]
ARGH, the upgrade job in https://rpc.jenkins.cit.rackspace.net/job/RPC-AIO_mitaka-upgrade-pr/82/ actually passed but the job failed tearing down the instance!!  :(  Trying again.

**Comment by mattt416** [comment]
recheck_cit_upgrade

**Comment by mattt416** [comment]
recheck_cit_upgrade

**Pull request merged**
