### PR TITLE
MaaS: Fix process checker for psutil 5.x

### PR DESCRIPTION
**Pull request by major**
This patch allows the process checker script to use psutil 1.2.1
(supplied by OpenStack-Ansible) or psutil 5.x (supplied by PyPi).

Connects rcbops/u-suk-dev#1324
Connects rcbops/rpc-openstack#1984

### CODE REVIEW

**Comment by alextricity25** [comment]
I will test this with my AIO in the morning! I'll install both versions, then make sure the plugin runs.

**Comment by alextricity25** [comment]
My testing checks out. The plugin now runs with psutil versions 1.2.1 and 5.x:
```
(maas-r13.1.0rc1) root@cantu-rpco-master01:/usr/lib/rackspace-monitoring-agent/plugins# pip freeze | grep psutil
psutil==5.1.3
(maas-r13.1.0rc1) root@cantu-rpco-master01:/usr/lib/rackspace-monitoring-agent/plugins# ./process_check.py filebeat
status okay
metric filebeat_process_status uint32 1
```
```
(maas-r13.1.0rc1) root@cantu-rpco-master01:/usr/lib/rackspace-monitoring-agent/plugins# pip  freeze | grep psutilpsutil==1.2.1
(maas-r13.1.0rc1) root@cantu-rpco-master01:/usr/lib/rackspace-monitoring-agent/plugins# ./process_check.py filebeatstatus okay
metric filebeat_process_status uint32 1
```

**Comment by xeregin** [comment]
Manually testing this fix seemed to work in our labs.

**Comment by major** [comment]
@xeregin YAY!

**Comment by xeregin** [comment]
I'm getting this in the containers:
```
status error parent_pid=init_pid)\n  File "/usr/lib/rackspace-monitoring-agent/plugins/process_check.py", line 63, in get_processes\n    procs = [x for x in psutil.Process(parent_pid).get_children()]\nAttributeError: 'Process' object has no attribute 'get_children'\n
Traceback (most recent call last):
  File "/usr/lib/rackspace-monitoring-agent/plugins/process_check.py", line 135, in <module>
    main(args)
  File "/usr/lib/rackspace-monitoring-agent/plugins/process_check.py", line 125, in main
    process_names=args.processes)
  File "/usr/lib/rackspace-monitoring-agent/plugins/process_check.py", line 86, in check_process_running
    procs = get_processes(parent_pid=init_pid)
  File "/usr/lib/rackspace-monitoring-agent/plugins/process_check.py", line 63, in get_processes
    procs = [x for x in psutil.Process(parent_pid).get_children()]
AttributeError: 'Process' object has no attribute 'get_children'
```

**Comment by alextricity25** [comment]
@xeregin That will be fixed by: https://github.com/rcbops/rpc-openstack/pull/1993
Once that fix merges, be sure to blow away the venv for the MaaS packages on the hosts. I fear that the psutil package might not downgrade cleanly if you re-run setup-maas.yml with it pinned to 1.2.1

**Pull request merged**
