### PR TITLE
[docs] Add mitaka release notes production build

### PR DESCRIPTION
**Pull request by darrenchan**
This patch enables the release notes in mitaka-13.0
to build in docs Strider CI and  provide release note
previews in PRs.

1. Move deconst-requirements.txt and _deconst.json files to the
source directory
2. Update content ID in _deconst.json for mitaka
3. Change to single page template build in conf.py
4. Add oslosphinx to deconst-requirements.txt
5. Add 13.0 release notes page

Connected https://github.com/rcbops/u-suk-dev/issues/384

### CODE REVIEW

**Comment by darrenchan** [comment]
Addresses https://github.com/rackerlabs/nexus-control/issues/566

CCing @smashwilson @meker12

**Comment by git-harry** [comment]
@darrenchan for the engineering team to manage it's work it uses [this board](https://waffle.io/rcbops/u-suk-dev). We have an approval process to focus our effort on the most important work. All of our tracking relies on issues being created and uses labels to identify status. If you have code that needs to be merged into this repo or you require us to work on something please create an issue. We will prioritise the issue to make sure it completed as soon as we have people available. Also please don't add labels your pull requests/issues, this affects how we track our work.

I have created an issue to track this item, given that the patch into master has already merged I want to make sure that things stay in sync. If there is anything else we need to do as part of this change, please add it to https://github.com/rcbops/u-suk-dev/issues/384.

/cc @b3rnard0

**Comment by sigmavirus24** [comment]
This looks to have broken the `tox -e releasenotes` job

**Comment by sigmavirus24** [comment]
@darrenchan can you also squash this down to one commit?

**Comment by darrenchan** [comment]
Makes more sense to backport https://github.com/rcbops/rpc-openstack/pull/1365 to mitaka-13.0 and edit on top. Closing this.

**Pull request closed without merging**
