### PR TITLE
LA-344 Deploy support role post leap

### PR DESCRIPTION
**Pull request by hughsaunders**
The support role is required as it deploys holland, and we're testing
holland post leap.

Issue: [LA-344](https://rpc-openstack.atlassian.net/browse/LA-344)

### CODE REVIEW

**Comment by hughsaunders** [comment]
Test build: https://rpc.jenkins.cit.rackspace.net/view/AIO/job/mattt-RPC-AIO_newton141-trusty-leapfrogupgrade-swift-periodic/25/

**Comment by mancdaz** [comment]
```
Good signature from \"Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>\"\nERROR: unable to update: http://mirror.rackspace.com/ubuntu/dists/trusty-updates/universe/binary-amd64/Packages.bz2: size check mismatch 417374 != 417171"
```

**Comment by mancdaz** [comment]
recheck_cit_artifact_trusty_apt

**Comment by hughsaunders** [comment]
This is not needed as holland has been removed from https://github.com/rcbops/rpc-gating/pull/276

**Pull request closed without merging**
