### PR TITLE
Add MaaS checks for processes status (#1366)

### PR DESCRIPTION
**Pull request by cloader89**
This adds a MaaS check script to check by fully qualified or basename
if processes are running on a host or within a container on a host.
Additionally, MaaS checks for filebeat, elasticsearch and rsyslog are
added using the process check script.

Connects #1236
(cherry picked from commit 2870f4e)

### CODE REVIEW

**Comment by cloader89** [comment]
recheck_all

**Comment by cloader89** [comment]
recheck_all

**Comment by cloader89** [comment]
recheck_all

**Comment by cloader89** [comment]
recheck_all

**Comment by cloader89** [comment]
recheck_ceph recheck_swift

**Comment by git-harry** [comment]
This can be merged once r13.1.0 is released.

**Pull request closed without merging**
