### PR TITLE
RO-3888 Update master dependencies

### PR DESCRIPTION
**Pull request by rpc-jenkins-svc**
This change is the result of running gating/update_dependencies/*
  See update_dependencies in https://rpc-openstack.atlassian.net/wiki/spaces/RE/pages/19005457/RE+for+Projects for more details.

Issue: [RO-3888](https://rpc-openstack.atlassian.net/browse/RO-3888)

### CODE REVIEW

**Comment by odyssey4me** [comment]
Looks like a legit failure:

```

TASK [elasticsearch : Debian - Ensure elasticsearch is installed] **************

Monday 05 February 2018  15:40:45 +0000 (0:00:00.038)       0:00:51.740 ******* 

fatal: [aio1_elasticsearch_container-3963a49b]: FAILED! => {"cache_update_time": 1517845245, "cache_updated": false, "changed": false, "failed": true, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'elasticsearch=5.6.5'' failed: E: Version '5.6.5' for 'elasticsearch' was not found\n", "rc": 100, "stderr": "E: Version '5.6.5' for 'elasticsearch' was not found\n", "stderr_lines": ["E: Version '5.6.5' for 'elasticsearch' was not found"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information..."]}
```

**Comment by antonym** [comment]
Related to https://github.com/rcbops/rpc-openstack/commit/daef57acfd5ae687f3edfb2b23155c68d4fa514c ?

**Comment by odyssey4me** [comment]
@antonym Maybe, but that passed tests - didn't it? I haven't verified myself, but it's plausible that upstream has updated to a new major/minor version and perhaps doesn't keep their older packages. This is the nature of using upstream repositories - things change. ;)

@d34dh0r53 I don't know the reason for hard-coding the elasticsearch major.minor version, but perhaps a better strategy should be worked out which doesn't do that any more as it will result in deploy failures whenever upstream things change.

**Comment by odyssey4me** [comment]
recheck_cit_artifact

**Comment by odyssey4me** [comment]
Oh, I think I understand what's going on here. There are older r16.1.0 artifacts due to some previous mishaps with the version management. Those artifacts are old and need replacing which is easier to do with this merged. As such, I'll force merge this and deal with the artifact replacement immediately afterwards.

**Pull request merged**
