### PR TITLE
Allow unauthenticated APT Mirror

### PR DESCRIPTION
**Pull request by mancdaz**
Openstack infra provide APT mirrors, but they are not signed. In order
to make use of these for gating it is necessary to disable security
hardening rule V-38462.

Connects rcbops/u-suk-dev#300

(cherry picked from commit 72a51b435cefeacb1e851209d9ed4b66dd931475)

### CODE REVIEW

**Comment by hughsaunders** [comment]
The swift failure shows a bug in the job - it failed on publishing test results, because the job was skipped. 

So two bugs:
1) The build should not have been skipped as files not ending .md were modified
2) Artifact archival / test result publishing should not cause the build to fail.

**Comment by hughsaunders** [comment]
recheck_all - not sure why the other branches didn't hit the same problems?

**Comment by hughsaunders** [comment]
Swift job didn't skip this time despite no code change 😕

**Comment by hughsaunders** [comment]
recheck_all

**Comment by hughsaunders** [comment]
recheck_all failing on maas

**Comment by hughsaunders** [comment]
recheck_upgrade failed on MaaS

**Comment by hughsaunders** [comment]
recheck_upgrade

**Comment by major** [comment]
I'm :+1: if this pleases Jenkins. This is similar to what's done with `tox.ini` in OSA.

**Comment by mancdaz** [comment]
👍

**Pull request merged**
