### PR TITLE
Utilize ansible-lint's new --exclude option

### PR DESCRIPTION
**Pull request by sigmavirus24**
Stop hacking up our repoisotry just to avoid linting ceph-* roles

Addresses #670

### CODE REVIEW

**Comment by tomc603** [comment]
Very nice! :+1:

**Comment by nrb** [comment]
Why was this simply closed?

**Comment by prometheanfire** [comment]
master was renamed to liberty, this will need to be resubmitted

**Comment by tomc603** [comment]
Could it not be rebased? Closed is not the correct status for these.

**Comment by prometheanfire** [comment]
github closes all PRs against a branch that is removed

**Comment by prometheanfire** [comment]
:+1: merging

**Pull request merged**
