### PR TITLE
Test upstream upgrade fix

### PR DESCRIPTION
**Pull request by git-harry**

### CODE REVIEW

**Comment by Apsu** [comment]
RPC-AIO-Liberty-Upgrade-PR: Fail

**Comment by git-harry** [comment]
recheck_upgrade

**Comment by Apsu** [comment]
RPC-AIO-Ceph-Liberty-PR: Fail

**Comment by git-harry** [comment]
The [fix](https://review.openstack.org/#/c/342183) works, once merged upstream it will be included in #1237

**Pull request closed without merging**
