### PR TITLE
Catch ConfigParser.NoSectionError when reading config file.

### LINKED ISSUE #848: Exception from rpc-maas-tool.py
When you run rpc-maas-tool.py and the config file (.raxrc by default) does not contain a `[credentials]` section, a ConfigParser.NoSectionError is returned, but we are currently only catching ConfigParser.NoOptionError before trying the `[api]` section so it bombs out with a stack trace.

- [x] Master
- [x] liberty-12.0
- [x] kilo

### PR DESCRIPTION
**Pull request by prometheanfire**
Fixes #848

(cherry picked from commit 5956c0414f79ae81d9e94784c26fe9a536a639bc)

### CODE REVIEW

**Comment by prometheanfire** [comment]
recheck

**Comment by sigmavirus24** [comment]
:+1: :shipit:

**Comment by git-harry** [comment]
-1

**Comment by git-harry** [comment]
Has this been validated by QE? We can only merge code into this branch if QE have identified it as an issue.

**Comment by d34dh0r53** [comment]
:+1:

**Comment by tomc603** [comment]
Who from QE should we have confirm this passes okay?

**Pull request merged**
