### PR TITLE
Have mitaka-ready horizon extensions in tree

### PR DESCRIPTION
**Pull request by evrardjp**
There is a willingness to go forward with horizon-extensions, and, like
maas, bring its code in tree.

This PR is composed of multiple parts:
- A part for bringing horizon extension to this repo, with history
- A fix of the horizon-extensions code for passing flake8 tests
- A way to enable the new "in-tree" horizon-extensions code.

This first part merges all the files from master branch of the
following repository https://github.com/rcbops/horizon-extensions/
with subtrees and fixes the heat.js AngularJS module to work
with mitaka. The guidelines followed are here:
https://docs.angularjs.org/error/$injector/strictdi

The last part changes the variables used in the repo_build process.
The branch used in these variables is still master by default, which
makes this commit stuck in a chicken and egg situation until the
jenkins configuration is changed to handle the sha instead of master.
The variable changed in the gate should be:
horizon_extensions_git_install_branch.

Connects rcbops/u-suk-dev#207

Signed-off-by: Jean-Philippe Evrard <jean-philippe.evrard@rackspace.co.uk>

### CODE REVIEW

**Comment by sigmavirus24** [comment]
> This commit is the first element of a two part commit to bring horizon
> extensions back to this repository.

I don't think it was ever a part of this repo, so we're not really bringing it back ;)

**Comment by sigmavirus24** [comment]
👍

**Comment by Apsu** [comment]
RPC-AIO-Ceph-Liberty-PR: Fail

**Comment by sigmavirus24** [comment]
This fails flake8 which we can fix in a follow-up patch. GitHub won't let us merge this unless we do manually. Thoughts?

**Comment by Apsu** [comment]
RPC-AIO-Liberty-PR: Fail

**Comment by Apsu** [comment]
RPC-AIO-Ceph-Liberty-PR: Fail

**Comment by evrardjp** [comment]
recheck_all

**Comment by Apsu** [comment]
RPC-AIO-Liberty-PR: Fail

**Comment by Apsu** [comment]
RPC-AIO-Ceph-Liberty-PR: Fail

**Comment by Apsu** [comment]
RPC-AIO-Ceph-Liberty-PR: Fail

**Comment by Apsu** [comment]
RPC-AIO-Liberty-PR: Fail

**Comment by Apsu** [comment]
RPC-AIO-Liberty-PR: Fail

**Comment by Apsu** [comment]
RPC-AIO-Ceph-Liberty-PR: Fail

**Comment by Apsu** [comment]
RPC-AIO-Liberty-PR: Fail

**Comment by hughsaunders** [comment]
👍  depends on  rcbops/jenkins-rpc/pull/612

**Comment by erikmwilson** [comment]
Does this affect end-user docs (for example, how things are installed/configured)?

**Comment by evrardjp** [comment]
recheck_all

**Comment by hughsaunders** [comment]
Current passes are false positive :(

**Comment by Apsu** [comment]
RPC-AIO-Ceph-Liberty-PR: Fail

**Comment by Apsu** [comment]
RPC-AIO-Liberty-PR: Fail

**Comment by git-harry** [comment]
recheck_all

**Comment by git-harry** [comment]
recheck_swift
recheck_ceph

**Comment by git-harry** [comment]
recheck_swift
recheck_ceph

**Comment by hughsaunders** [comment]
recheck_swift

**Comment by Apsu** [comment]
RPC-AIO-Ceph-Liberty-PR: Fail

**Comment by Apsu** [comment]
RPC-AIO-Liberty-PR: Fail

**Comment by evrardjp** [comment]
recheck_all

**Comment by Apsu** [comment]
RPC-AIO-Liberty-PR: Fail

**Comment by Apsu** [comment]
RPC-AIO-Ceph-Liberty-PR: Fail

**Comment by evrardjp** [comment]
Waiting for upstream change: https://review.openstack.org/#/c/343682

**Comment by evrardjp** [comment]
Depends on: https://github.com/rcbops/jenkins-rpc/pull/617

**Comment by evrardjp** [comment]
OSA upstream change merged: https://review.openstack.org/#/c/344220

**Comment by evrardjp** [comment]
rcbops/jenkins-rpc#617 merged, we need to wait for an OSA sha bump that bumps the ansible-requirements of the plugins repo.

**Comment by hughsaunders** [comment]
[testing] recheck_All

**Comment by Apsu** [comment]
RPC-AIO-Liberty-PR: Fail

**Comment by Apsu** [comment]
RPC-AIO-Ceph-Liberty-PR: Fail

**Comment by b3rnard0** [comment]
@evrardjp I moved this back to the backlog so it doesn't take up our WIP. Ideally, we should be pulling these types of tasks once we know that the OSA sha bump is imminent.

**Comment by evrardjp** [comment]
recheck

**Comment by evrardjp** [comment]
recheck_ceph
recheck_swift

**Comment by Apsu** [comment]
RPC-AIO-Liberty-PR: Fail

**Comment by evrardjp** [comment]
recheck_ceph
recheck_swift

**Comment by sigmavirus24** [comment]
Uhm @evrardjp there are 109 commits in this pull request...

**Comment by sigmavirus24** [comment]
Oh, right, sorry, this imports the horizon history in.

There are two +1s in here so I'm going to merge this since the tests are passing.

**Pull request merged**
