### PR TITLE
MaaS: Add support for magnum

### PR DESCRIPTION
**Pull request by Kuwagata**
Adds monitoring support for magnum when magnum is installed.

See #1738.

### CODE REVIEW

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by hughsaunders** [comment]
recheck_all

**Comment by antonym** [comment]
We recently made some changes to how the templates are structured to allow for the check to have some more knobs to configure at deploy time (disable/enable checks, adjust thresholds, etc).  Could you take a look at one of the existing templates in master and alter the templates so that they reflect that newer format?

Example check: https://github.com/rcbops/rpc-openstack/blob/master/rpcd/playbooks/roles/rpc_maas/templates/swift_account_process_check.yaml.j2

**Comment by major** [comment]
@antonym What's missing in these new YAML files? It looks like they have the timeout/period updates, among some of the other updates.

**Comment by antonym** [comment]
Yep, the new changes look good.  Thanks!

**Comment by major** [comment]
@chrishultin @Kuwagata Can one of you do the `newton-14.0` backport?

**Comment by chrishultin** [comment]
@major Last I heard, we weren't planning to backport to `newton-14.0` since we weren't targeting any of this to be available until 14.1.

**Pull request merged**
