### PR TITLE
Use script module instead of shell module to run verify-maas tasks.

### LINKED ISSUE #769: "Verify Checks & Alarms are registered" task fails in multi-node deployments
The new verify-maas tasks rely on `rpc-maas-tool.py`, but in a multi-node deployment, that script only exists on the host where the repo was cloned to.

Needs task to copy the script to each host before running...

```
TASK: [Verify Checks & Alarms are registered] *********************************
ok: [d290d234-infra1]
failed: [d290d234-object2] => {"attempts": 10, "changed": false, "cmd": "/opt/rpc-openstack/scripts/rpc-maas-tool.py verify-created --entity d290d234-object2", "delta": "0:00:00.006072", "end": "2016-01-22 17:06:43.981981", "failed": true
, "failed_when_result": true, "rc": 127, "start": "2016-01-22 17:06:43.975909", "stdout_lines": [], "warnings": []}
stderr: /bin/sh: 1: /opt/rpc-openstack/scripts/rpc-maas-tool.py: not found
msg: Task failed as maximum retries was encountered
failed: [d290d234-object1] => {"attempts": 10, "changed": false, "cmd": "/opt/rpc-openstack/scripts/rpc-maas-tool.py verify-created --entity d290d234-object1", "delta": "0:00:00.006539", "end": "2016-01-22 17:06:43.987639", "failed": true
, "failed_when_result": true, "rc": 127, "start": "2016-01-22 17:06:43.981100", "stdout_lines": [], "warnings": []}
stderr: /bin/sh: 1: /opt/rpc-openstack/scripts/rpc-maas-tool.py: not found
msg: Task failed as maximum retries was encountered
failed: [d290d234-logger1] => {"attempts": 10, "changed": false, "cmd": "/opt/rpc-openstack/scripts/rpc-maas-tool.py verify-created --entity d290d234-logger1", "delta": "0:00:00.006553", "end": "2016-01-22 17:06:44.036226", "failed": true
, "failed_when_result": true, "rc": 127, "start": "2016-01-22 17:06:44.029673", "stdout_lines": [], "warnings": []}
stderr: /bin/sh: 1: /opt/rpc-openstack/scripts/rpc-maas-tool.py: not found
msg: Task failed as maximum retries was encountered
failed: [d290d234-object3] => {"attempts": 10, "changed": false, "cmd": "/opt/rpc-openstack/scripts/rpc-maas-tool.py verify-created --entity d290d234-object3", "delta": "0:00:00.010012", "end": "2016-01-22 17:06:44.963121", "failed": true
, "failed_when_result": true, "rc": 127, "start": "2016-01-22 17:06:44.953109", "stdout_lines": [], "warnings": []}
stderr: /bin/sh: 1: /opt/rpc-openstack/scripts/rpc-maas-tool.py: not found
msg: Task failed as maximum retries was encountered
```

---
# committed
- [x] Master
- [x] Kilo #785

# released
- [ ] Kilo

### PR DESCRIPTION
**Pull request by byronmccollum**
Fixes #769

### CODE REVIEW

**Comment by hughsaunders** [comment]
recheck

**Comment by prometheanfire** [comment]
recheck

**Comment by d34dh0r53** [comment]
:+1:

**Comment by prometheanfire** [comment]
:+1:

**Pull request merged**
