### PR TITLE
Set filter_plugins in ansible.cfg

### PR DESCRIPTION
**Pull request by mattt416**
os-ansible-deployment's pip roles make use of a custom ansible filter.
This commit sets filter_plugins in ansible.cfg accordingly so that
custom filters can be found.

Closes issue #389

### CODE REVIEW

**Comment by mattt416** [comment]
There should be no need to backport this to kilo since the change in os-ansible-deployment is only in master (https://github.com/stackforge/os-ansible-deployment/commit/f91860d3dece7a157df6fb87270ddfa2f290d572), however the filters directory exists in kilo of os-ansible-deployment so there should be no harm if it is backported.

**Comment by git-harry** [comment]
+1

**Comment by d34dh0r53** [comment]
@mattt416 can you rebase your change to the latest `master` branch so that we can merge this?

**Comment by mattt416** [comment]
Done @d34dh0r53 !

**Comment by d34dh0r53** [comment]
:+1:

**Pull request merged**
