### PR TITLE
Finishes the cleanup of the old MaaS files

### PR DESCRIPTION
**Pull request by cloader89**
The MaaS testing files are no longer being used so we are removing them. The entire
MaaS testing directory has been removed.

Connects #1209

### CODE REVIEW

**Comment by git-harry** [comment]
👍 the commit message is a bit light on detail but otherwise it looks fine.

**Comment by Apsu** [comment]
RPC-AIO-Liberty-PR: Fail

**Comment by cloader89** [comment]
recheck_all

**Comment by Apsu** [comment]
RPC-AIO-Ceph-Liberty-PR: Fail

**Comment by Apsu** [comment]
RPC-AIO-Ceph-Liberty-PR: Fail

**Comment by cloader89** [comment]
recheck_ceph

**Comment by Apsu** [comment]
RPC-AIO-Ceph-Liberty-PR: Fail

**Comment by Apsu** [comment]
RPC-AIO-Ceph-Liberty-PR: Fail

**Comment by cloader89** [comment]
recheck_ceph

**Comment by major** [comment]
:+1: Looks good here. Tests pass.

**Pull request merged**
