### PR TITLE
ASC-475 Cherry-pick system gate from master

### PR DESCRIPTION
**Pull request by johnduarte**
This PR pulls in the commits from the master branch that add the `system` action as a gating parameter in order to run rpc-openstack-system-tests on an MNAIO deploy.

Issue: [ASC-406](https://rpc-openstack.atlassian.net/browse/ASC-406)

### CODE REVIEW

**Comment by johnduarte** [comment]
recheck_cit_artifact

**Comment by johnduarte** [comment]
The artifact check is encountering the following apt error deploying percona-server:
```
[apt] fatal: [localhost]: FAILED! => {"changed": true, "cmd": "aptly publish snapshot -distribution=\"r14.14.0-trusty\" miko-r14.14.0-trusty integrated", "delta": "0:00:07.684747", "end": "2018-05-21 14:33:25.972005", "failed": true, "failed_when_result": true, "rc": 1, "start": "2018-05-21 14:33:18.287258", "stderr": "ERROR: unable to publish: unable to process packages: error linking file to /var/www/artifacts/apt/public/integrated/pool/main/p/percona-server-5.5/libperconaserverclient18_5.5.59-rel38.11-1.trusty_amd64.deb: file already exists and is different", "stdout": "Loading packages...\nGenerating metadata files and linking package files...", "stdout_lines": ["Loading packages...", "Generating metadata files and linking package files..."], "warnings": []}
```

**Comment by odyssey4me** [comment]
@johnduarte Bother, it seems that they've republished a package again with a different SHA. I'll try and get that resolved asap - just dealing with the MNAIO test failures first.

**Comment by odyssey4me** [comment]
@johnduarte Register https://rpc-openstack.atlassian.net/browse/RO-4222 for this issue. The republishing is in progress. I'll recheck the PR when it's done.

**Comment by odyssey4me** [comment]
recheck_cit_artifact

**Comment by odyssey4me** [comment]
https://rpc.jenkins.cit.rackspace.net/job/RPC-Artifact-Build_newton-pr/555/ testing this PR and passed.

**Pull request merged**
