### PR TITLE
Update openstack-ansible SHA

### PR DESCRIPTION
**Pull request by git-harry**
Update the OSA SHA, this is required to address an issue where the
version of paramiko has changed causing bootstrap-ansible.sh to fail.
See OSA commit 37419b119ba637f3dcfdf072336398256f5945e3 for further
details.

Issue: https://github.com/rcbops/rpc-openstack/issues/1037

### CODE REVIEW

**Comment by git-harry** [comment]
recheck_all

**Comment by git-harry** [comment]
recheck_upgrade

**Comment by tomc603** [comment]
👍  for SHA bump

**Comment by prometheanfire** [comment]
I'd actually suggest we close this in favor of #1054 as that one also includes the sha updates and closes a few other bugs.

**Pull request closed without merging**
