### PR TITLE
SHA bump for OSAD to match kilo as of 22/07/2015 This SHA bump is largely to grab some important fixes for the upcoming 11.0.0 release.

### LINKED ISSUE #269: Upgrades broken with RabbitMQ upgrade error
Filed upstream in OSAD: https://bugs.launchpad.net/openstack-ansible/+bug/1474992

We need to bump the OSAD sha to consume the fix for this.

### PR DESCRIPTION
**Pull request by claco**
Of major concern is fixing RabbitMQ upgrade failures.
(https://bugs.launchpad.net/openstack-ansible/+bug/1474992)

Fixes #269

### CODE REVIEW

**Comment by nrb** [comment]
SHA matches head of OSAD's Kilo - I thought I spotted an 11.0.0rc3 reference somewhere in a variable file, so i'm checking for that now. If it's present, we should update that with this PR, too.

**Comment by nrb** [comment]
Ok - it's in `rpcd/playbooks/group_vars/all.yml`, called `rpc_release`. For master, we can leave it. For kilo, we need to bump to rc8.

I am +1 on this PR as is.

**Comment by odyssey4me** [comment]
While I think an appropriate update of rpc_release should be included every time the SHA is bumped, considering the timelines I'm happy to :+1: this for testing purposes.

**Comment by sigmavirus24** [comment]
2 +1s already, so merging.

**Comment by nrb** [comment]
@odyssey4me You're right, but in master it's always `master`. Same as OSAD

**Pull request merged**
