### PR TITLE
RO-4194 Update pike dependencies

### PR DESCRIPTION
**Pull request by rpc-jenkins-svc**
Automated dependency update pull request, see individual commits for details.

Issue: [RO-4194](https://rpc-openstack.atlassian.net/browse/RO-4194)

### CODE REVIEW

**Comment by cjloader** [comment]
https://github.com/openstack/openstack-ansible/commit/03adca70dcc2c8befe597e2f2dd12bbeb7d88720

My latest fix for Pike

**Comment by mancdaz** [comment]
recheck_xenial_no_artifacts_swift_deploy

**Comment by cjloader** [comment]
I will check it out in the morning

**Comment by odyssey4me** [comment]
There is unfortunately a legitimate failure here:

```
2019-01-22T04:02:59-0600 + ansible -m setup -a gather_subset=network,hardware,virtual all
2019-01-22T04:03:09-0600 + export ANSIBLE_LOG_PATH=/openstack/log/ansible-logging/setup-infrastructure.log
2019-01-22T04:03:09-0600 + ANSIBLE_LOG_PATH=/openstack/log/ansible-logging/setup-infrastructure.log
2019-01-22T04:03:09-0600 + openstack-ansible setup-infrastructure.yml -e osa_gather_facts=False
2019-01-22T04:03:09-0600 Variable files: "-e @/etc/openstack_deploy/user_secrets.yml -e @/etc/openstack_deploy/user_variables.yml "
2019-01-22T04:03:13-0600 ERROR! the role 'ceph-defaults' was not found in /opt/openstack-ansible/playbooks/roles:/etc/ansible/roles:/opt/openstack-ansible/playbooks/roles:/etc/ansible/roles/ceph-ansible/roles:/opt/openstack-ansible/playbooks
2019-01-22T04:03:13-0600 
2019-01-22T04:03:13-0600 The error appears to have been in '/opt/openstack-ansible/playbooks/ceph-install.yml': line 88, column 7, but may
2019-01-22T04:03:13-0600 be elsewhere in the file depending on the exact syntax problem.
2019-01-22T04:03:13-0600 
2019-01-22T04:03:13-0600 The offending line appears to be:
2019-01-22T04:03:13-0600 
2019-01-22T04:03:13-0600   roles:
2019-01-22T04:03:13-0600     - role: ceph-defaults
2019-01-22T04:03:13-0600       ^ here
2019-01-22T04:03:13-0600 
2019-01-22T04:03:13-0600 EXIT NOTICE [Playbook execution failure] **************************************
2019-01-22T04:03:13-0600 ===============================================================================
```

**Comment by odyssey4me** [comment]
This has been merged with https://github.com/rcbops/rpc-openstack/pull/3459

**Pull request closed without merging**
