### PR TITLE
Fix incorrect file name in step 2.5

### PR DESCRIPTION
**Pull request by tomc603**
Step should refer to `openstack_user_config.yml*` not `openstack_user_variables.yml*`

### CODE REVIEW

**Comment by prometheanfire** [comment]
:+1:

**Comment by prometheanfire** [comment]
@git-harry forget your vote?

**Comment by git-harry** [comment]
@prometheanfire I figured that was implied.

**Comment by prometheanfire** [comment]
@git-harry it is, but better to be explicit then implicit (or so I've been told :P)

**Pull request merged**
