### PR TITLE
SHA bump for OSAD to match 11.0.4 as of 07/07/2015

### LINKED ISSUE #225: Update osad SHA to 11.0.4

### PR DESCRIPTION
**Pull request by nrb**
Fixes #225

### CODE REVIEW

**Comment by andymcc** [comment]
LGTM - sha points to 11.0.4 fine.

**Comment by mattt416** [comment]
Isn't this the cherry-picked kilo sha?

**Comment by nrb** [comment]
Yeah - I purposefully took the 11.0.4 tag for both kilo and master of rpc-openstack, which was cut from the kilo branch.

I'm not sure if tracking master makes sense in rpc-openstack, but I'm open to arguments for doing so.

**Comment by mattt416** [comment]
I see.  Sounds like we can discuss this further later!

**Comment by nrb** [comment]
Thanks Matt!

**Pull request merged**
