### PR TITLE
Set `ssl_check` to `true` to match previous behavior of check getting…

### PR DESCRIPTION
**Pull request by byronmccollum**
… created by default.

(cherry picked from commit d45273095d48b6f8d6b362915a34a15033f0b750)

### CODE REVIEW

**Comment by byronmccollum** [comment]
Kilo backport of #337

**Comment by prometheanfire** [comment]
rebase

**Comment by prometheanfire** [comment]
rebase

**Comment by byronmccollum** [comment]
rebased

**Comment by prometheanfire** [comment]
:+1:

**Comment by d34dh0r53** [comment]
:+1:

**Comment by rackertom** [comment]
I'm 99% sure I did the exact same bug a long time ago. :+1:

**Comment by nrb** [comment]
\o/

**Pull request merged**
