### PR TITLE
use safe methods from the yaml library

### PR DESCRIPTION
**Pull request by prometheanfire**
Fixes: SE-2117

Issue: [SE-2117](https://rpc-openstack.atlassian.net/browse/SE-2117)

### CODE REVIEW

**Comment by prometheanfire** [comment]
recheck_cit_artifact

**Comment by prometheanfire** [comment]
recheck_cit_artifact

**Comment by major** [comment]
recheck_cit_artifact

**Comment by prometheanfire** [comment]
recheck_cit_artifact

**Comment by prometheanfire** [comment]
recheck_cit_artifact

**Comment by cloudnull** [comment]
recheck_cit_artifact

**Comment by prometheanfire** [comment]
recheck_cit_artifact

huh, thought this merged...

**Comment by prometheanfire** [comment]
cit_container_bashate_tox-test

**Comment by prometheanfire** [comment]
recheck_cit_container_bashate_tox-test

**Comment by prometheanfire** [comment]
recheck_cit_container_ansible-lint_tox-test
recheck_cit_container_flake8_tox-test
recheck_cit_container_release-script_tox-test 
recheck_cit_container_releasenotes_tox-test

**Pull request merged**
