### PR TITLE
[Newton] RO-1912 Remove site.yml

### PR DESCRIPTION
**Pull request by major**
This patch removes the site.yml, which was unmaintained and unused.

Issue: [RO-1912](https://rpc-openstack.atlassian.net/browse/RO-1912)

### CODE REVIEW

**Comment by major** [comment]
recheck_cit_trusty_leapfrogupgrade_swift

**Comment by major** [comment]
recheck_cit_trusty_minorupgrade_swift

**Comment by cjloader** [comment]
recheck_cit_trusty_leapfrogupgrade_swift

**Comment by major** [comment]
recheck_cit_trusty_leapfrogupgrade_swift

**Comment by prometheanfire** [comment]
recheck_cit_trusty_leapfrogupgrade_swift

**Comment by cjloader** [comment]
recheck_cit_trusty_leapfrogupgrade_swift

**Pull request merged**
