### PR TITLE
Move OSAD SHA forward, and remove carried patches

### PR DESCRIPTION
**Pull request by nrb**
This change allows us to include upstream patches that were being
carried in-tree.

Addresses #386

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
I deployed this patch in an AIO without any problems. :+1:

**Comment by cloudnull** [comment]
:+1: I approve of this

**Comment by nrb** [comment]
2 votes, merging and beginning backport.

**Comment by d34dh0r53** [comment]
Running this with ceilometer fails with a bad dependency:
````
/usr/local/bin/pip install ceilometermiddleware
Ignoring indexes: https://pypi.python.org/simple
Requirement already up-to-date: ceilometermiddleware in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: pbr<2.0,>=0.11 in /usr/local/lib/python2.7/dist-packages (from ceilometermiddleware)
Requirement already up-to-date: pycadf>=0.8.0 in /usr/local/lib/python2.7/dist-packages (from ceilometermiddleware)
Requirement already up-to-date: oslo.context>=0.2.0 in /usr/local/lib/python2.7/dist-packages (from ceilometermiddleware)
Requirement already up-to-date: Babel>=1.3 in /usr/local/lib/python2.7/dist-packages (from ceilometermiddleware)
Collecting oslo.messaging>=1.8.0 (from ceilometermiddleware)
  Downloading http://172.29.236.100:8181/os-releases/11.1.0/oslo.messaging-1.8.3-py2-none-any.whl (214kB)
    100% |████████████████████████████████| 217kB 52.1MB/s
Requirement already up-to-date: six>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from ceilometermiddleware)
Requirement already up-to-date: oslo.utils>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from ceilometermiddleware)
Collecting oslo.config>=1.11.0 (from ceilometermiddleware)
  Could not find a version that satisfies the requirement oslo.config>=1.11.0 (from ceilometermiddleware) (from versions: 1.9.3)
No matching distribution found for oslo.config>=1.11.0 (from ceilometermiddleware)
````

Looking into this now :-1:

**Comment by nrb** [comment]
@d34dh0r53 What version of oslo.config is in your repo server I wonder? Looks like 1.9.3.

**Comment by d34dh0r53** [comment]
yeah, I'm getting 1.9.3, trying a fresh greenfield now

**Comment by d34dh0r53** [comment]
@nrb @miguelgrinberg fresh greenfield from master is getting the same error, I have the following on my repo server:
````
# find ./ -name oslo.config\*
./11.2.0/oslo.config-1.9.3-py2.py3-none-any.whl
./11.0.2/oslo.config-1.9.3-py2.py3-none-any.whl
./11.1.0/oslo.config-1.9.3-py2.py3-none-any.whl
./11.0.0/oslo.config-1.12.1-py2.py3-none-any.whl
./11.0.4/oslo.config-1.9.3-py2.py3-none-any.whl
./11.1.2/oslo.config-1.9.3-py2.py3-none-any.whl
./kilo/oslo.config-1.9.3-py2.py3-none-any.whl
./11.1.1/oslo.config-1.9.3-py2.py3-none-any.whl
./master/oslo.config-2.2.0-py2.py3-none-any.whl
./11.0.3/oslo.config-1.9.3-py2.py3-none-any.whl
./11.0.1/oslo.config-1.9.3-py2.py3-none-any.whl
````

**Comment by miguelgrinberg** [comment]
@d34dh0r53 I inspected working my ceilometer containers in more detail.

I've also got oslo.config 1.9.3 installed. The version of ceilometermiddleware that I have is 0.1.0, and these are its dependencies:

    Requires-Dist: oslo.config (>=1.6.0)
    Requires-Dist: oslo.context (>=0.1.0)
    Requires-Dist: oslo.messaging (>=1.4.0,!=1.5.0)
    Requires-Dist: oslo.utils (>=1.2.0)
    Requires-Dist: pbr (>=0.6,!=0.7,<1.0)
    Requires-Dist: pycadf (>=0.6.0)
    Requires-Dist: six (>=1.7.0)
    Requires-Dist: Babel (>=1.3)

So my install is happy with 1.9.3. What release of the middleware do you have?

**Pull request merged**
