### PR TITLE
Change OSA SHA to HEAD of stable/mitaka

### PR DESCRIPTION
**Pull request by alextricity25**
Bump OSA SHA, and integrate haproxy_extra_services variable.

This commit also removes the haproxy playbook and role.
Kibana and Elasticsearch HAProxy settings will now be
configured using the OSA haproxy role, via the
haproxy_extra_services variable implemented in this PS:
https://review.openstack.org/#/c/404328/1

Connects https://github.com/rcbops/u-suk-dev/issues/997
Connects https://github.com/rcbops/rpc-openstack/issues/1674
Connects #1663

### CODE REVIEW

**Comment by alextricity25** [comment]
recheck_ceph

**Comment by alextricity25** [comment]
recheck_ceph

**Comment by alextricity25** [comment]
recheck_swift

**Comment by alextricity25** [comment]
recheck_all

**Comment by alextricity25** [comment]
Blocked by https://github.com/rcbops/rpc-openstack/pull/1679

**Comment by alextricity25** [comment]
Unblocked now.
recheck_all

**Comment by alextricity25** [comment]
recheck_all

**Comment by alextricity25** [comment]
This is currently blocked by https://github.com/rcbops/rpc-openstack/issues/1663

**Comment by alextricity25** [comment]
recheck_upgrade

**Comment by alextricity25** [comment]
@cloader89: This also removes the haproxy role per https://github.com/rcbops/rpc-openstack/pull/1675/commits/a6ac6fff0b25cc0dc1f1203ebff8fa25bc533deb

**Comment by cloader89** [comment]
okay, thanks for the clarification.

**Pull request merged**
