### PR TITLE
Search for and provide domain in horizon check

### PR DESCRIPTION
**Pull request by Frank-ZhangXin**
In multi-domain deployments of RPC OpenStack, Horizon will require the
user to enter a domain name. As such, we need to provide that
information when posting our login request to Horizon in our MaaS check
plugin.

To detect the multi-domain case, we search for an input field named
"domain" and only then do we provide it. To make the check slightly more
efficient we also refactor it to just parse the HTML once instead of 2
or 3 times.

Connects #1262
(cherry picked from commit b87c025c4befa6242daf70d79bf793f6fc76dcf7)

### CODE REVIEW

**Comment by Frank-ZhangXin** [comment]
recheck_all

**Comment by Frank-ZhangXin** [comment]
recheck_upgrade

**Comment by sigmavirus24** [comment]
recheck_ceph - No maas entity for host

```
04:00:07 failed: [jrpcaioiad-f07] => {"failed": true}
04:00:07 msg: Zero entities with the label jrpcaioiad-f07 exist. Entities should be created as part of the hardware provisioning process, if missing, please consult the internal documentation for associating one with the device.
```

**Comment by sigmavirus24** [comment]
I'm only restarting ceph because it looks as though swift and upgrade failed for the same reason. Want to see if this is resolved before causing extra load on Jenkins by restarting all jobs.

**Comment by Frank-ZhangXin** [comment]
recheck_swift
recheck_upgrade

**Comment by alextricity25** [comment]
I tested and reviewed the PR. The code looks good and it works as expected.

My testing included:
1. Deploying an AIO from this branch with ``horizon_keystone_multidomain_support: True``
2. Ensuring the dashboard showed an input box for ``Domain``
3. Deploy MaaS using my cloud10 subaccount
4. Verify changes are in place
5. Ensure the horizon check is healthy
```
root@cantu-test1476:/usr/lib/rackspace-monitoring-agent/plugins# ./run_plugin_in_venv.sh horizon_check.py 172.29.236.189 "openstack dashboard"
status okay
metric horizon_local_status uint32 1
metric splash_status_code uint32 200 http_code
metric splash_milliseconds double 31.005 ms
metric login_status_code uint32 200 http_code
metric login_milliseconds double 665.071 ms
```
I know this is only a backport, but It was a good learning op for me :)
:+1:

**Comment by tomc603** [comment]
Backport 👍

**Pull request merged**
