### PR TITLE
Sync f5-config.py with support

### PR DESCRIPTION
**Pull request by dpham-rs**

### CODE REVIEW

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by alextricity25** [comment]
ok to test

**Comment by major** [comment]
Flake8 check is upset:

```
hacking/rpco_checks.py:1:1: R803  git commit title ('Update copyright date.') should not end with period
```

**Comment by dpham-rs** [comment]
Git title updated, period removed.

**Comment by prometheanfire** [comment]
Just so others know when they look at this.  This is likely to be the PR that will be submitted from support to us that'll at least start the sync of their f5-config script to ours.

**Comment by major** [comment]
@dpham-rs You'll need to amend the commit itself and re-push. The commit still has a period at the end:

https://github.com/rcbops/rpc-openstack/pull/1874/commits

**Comment by dpham-rs** [comment]
Git commit title amended.

**Comment by dpham-rs** [comment]
New Sync PR #1921

**Pull request closed without merging**
