### PR TITLE
Purge ceph from RPC-O

### PR DESCRIPTION
**Pull request by cloudnull**
This change removes the ceph installation framework we have in rpc-o.
This is being done because future ceph work will be owned and operated
by a different team. Furthermore, if ceph is needed to be deployed by
the RPC-O team we have ceph integrations being developed and maintained
upstream within OpenStack-Ansible.

Signed-off-by: Kevin Carter <kevin.carter@rackspace.com>

Issue: [UG-651](https://rpc-openstack.atlassian.net/browse/UG-651)

### CODE REVIEW

**Comment by cloudnull** [comment]
NOTE: it is not likely that this PR will pass until we purge the ceph gate first.

**Comment by cloudnull** [comment]
recheck_cit_all

**Comment by odyssey4me** [comment]
It looks like this may need a rebase.

**Comment by major** [comment]
I'll close this for now @cloudnull but feel free to reopen it if you're ready to work on this again.

**Pull request closed without merging**
