### PR TITLE
[LA-316] [LA-317] Leapfrog with rpc

### PR DESCRIPTION
**Pull request by evrardjp**
Previous commit included the flexible leapfrog features. This
leverages it to load our own scripts to leap RPC, and redeploy
RPC bits (currently ELK and MaaS).

### CODE REVIEW

**Comment by evrardjp** [comment]
@hughsaunders @odyssey4me Your comments on previous commit should be addressed here.

**Comment by odyssey4me** [comment]
@evrardjp OK, just bear in mind that commit history lives beyond other systems which have details, for example JIRA. It's best to comment in the code (it's easiest to find information in context) or to describe what/why in the commit message to provide context. I do feel like the stuff being done in these commits requires more context than I have, making it difficult to do anything other than a syntax/spelling/sanity check.

**Comment by evrardjp** [comment]
@odyssey4me Fair point. I'll have to rebase, so I'll include commit message changes at the same time.

**Comment by evrardjp** [comment]
recheck_cit_swift
recheck_cit_trusty_leapfrogupgrade_swift

**Comment by evrardjp** [comment]
as you can see, the trusty-leapfrogupgrade-swift works \o/

**Comment by evrardjp** [comment]
CIT/ceph
Old job, expected to fail

CIT/leapfrogupgrade 
Old job, expected to fail

CIT/swift
Old job, expected to fail

CIT/trusty-leapfrogupgrade-ceph
ceph doesn't deploy on N. This job will disappear in the future

CIT/xenial
Old job, expected to fail

CIT/xenial-leapfrogupgrade-swift
kilo doesn't deploy on xenial. This job will disappear in the future.

So everything is fine!

**Pull request merged**
