### PR TITLE
Error handling for rpc-maas-tool.py with local checks

### PR DESCRIPTION
**Pull request by BjoernT**
Error handling is added to support local MaaS checks without
arguments like hp_monitoring.py

Connects #1575

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/staging.horse/build-f9f523aa9d/docs/private-cloud/release-notes/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/staging.horse/build-5237cfdfa0/docs/private-cloud/release-notes/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/staging.horse/build-fdb7b34a0c/docs/private-cloud/release-notes/)

**Comment by BjoernT** [comment]
recheck_ceph

**Comment by BjoernT** [comment]
recheck_upgrade

**Comment by BjoernT** [comment]
@alextricity25 Can I get feedback so we can get this merged. Thanks

**Comment by hughsaunders** [comment]
👍  Looks like a reasonable fix. I don't like the mixture of whitespace/formatting changes with the bugfix though.

**Pull request merged**
