### PR TITLE
[WIP] Create upgrade script for gating purposes

### PR DESCRIPTION
**Pull request by mattt416**
This hasn't been tested; it's being updated so we can start to hash it
out in earnest.

TBD: 1. What should this script be called?  Will it be used by jenkins
        only?
     2. How do we handle the upgrade of rcp-openstack bits?  In liberty
        version this was done by running scripts/deploy.sh.
     3. Do we need to run pip-lockdown.yml?  We will need to test this
        without running that.
     4. Is there any reason why we'd need to re-run the ceph playbooks
        when we're not changing ceph roles or the deployed version of
        ceph?
     5. Should this be a script or playbook?  This can easily be
        converted to a playbook but this is largely just documenting
        the manual steps required to perform the upgrade.
     6. The variable munging stuff can potentially be moved out into a
        separate playbook/script which can then be included here and by
        support, but we will need to wait to determine how exactly this
        is going to be run (do we use --danger DANGER or not?) before
        we do that work.

BLOCKERS: 1. migrate-yaml.py is stil being worked on and at present
             will not create 100% usable variables files.

TODO: 1. This script should get confirmation from the user before
         starting the upgrade.  This is dangerous command and not
         getting validation from the user before running could be
         catastrophic.
      2. Since openstack-ansible's run-upgrade.sh also runs
         bootstrap-ansible.sh, we need to find a way to skip that
         when we run it here.

Connected https://github.com/rcbops/u-suk-dev/issues/357
Connected https://github.com/rcbops/rpc-openstack/issues/1345
Connected https://github.com/rcbops/u-suk-dev/issues/347

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Should this move #357 into needs review?

**Comment by alextricity25** [comment]
> 2. How do we handle the upgrade of rcp-openstack bits? In liberty
   version this was done by running scripts/deploy.sh.

I'm not sure why we would call deploy.sh. Essentially, if we re-run that with DEPLOY_OA='false', the difference between that and site.yml are: 
* Run pw-token-gen.py on user_osa_secrets.yml and user_rpco_secrets.yml (not sure if it would overwrite what's already there)
* Run verify-mass.yml

I'd say there is nothing wrong with site.yml. It's a little more clear IMO.

**Comment by sigmavirus24** [comment]
@alextricity25 I believe there was an issue to get rid of `site.yml`.

**Comment by mattt416** [comment]
@alextricity25 @sigmavirus24 One issue I know of is that a deploy may not have MaaS deployed.  What confuses me though is that in https://github.com/rcbops/rpc-openstack/blob/liberty-12.2/scripts/upgrade.sh we did not set DEPLOY_MAAS so that script would never upgrade the MaaS bits.  Anyone know how we handled this?

**Comment by alextricity25** [comment]
@mattt416 That's a good catch. I'm not sure about that one TBH, but what you said makes perfect sense. It doesn't look like the MaaS bits were ever upgraded.

**Comment by alextricity25** [comment]
@mattt416 probably explains why support included that as part of their maintenance plan:
https://github.com/rsoprivatecloud/Maintenance-Plans/blob/master/RPC%2011.x:%20Upgrade%20to%20RPC%2012.x#L268

**Comment by sigmavirus24** [comment]
> Anyone know how we handled this?

Upgrades for 12.2 were tricky w/r/t MaaS. We changed how MaaS worked and thus needed separate playbooks for upgrading MaaS

**Comment by alextricity25** [comment]
This worked on a basic L->M upgrade for me(no MaaS, no ceph, no openstack resources provisioned). @mattt416, i've given my answers to your questions below:

> TBD: 1. What should this script be called? Will it be used by jenkins
    only?

If this script is only meant to be run by devs or the gate, then test-upgrade.sh is fine

> How do we handle the upgrade of rcp-openstack bits? In liberty
    version this was done by running scripts/deploy.sh.

In my opinion we shouldn't be using deploy.sh for upgrading he RPCO bits. Things could go wrong if people have some left over environment variables set or forget to set the right ones(i.e DEPLOY_OA). I don't see anything wrong with just invoking the playbooks included in site.yml, and wrapping setup-maas.yml around a conditional checking if DEPLOY_MAAS is set.

> Do we need to run pip-lockdown.yml? We will need to test this
    without running that.

I'll test that now. I'll edit this answer once it's finished.

> Is there any reason why we'd need to re-run the ceph playbooks
when we're not changing ceph roles or the deployed version of
ceph?

I think we should worry about that once we get https://github.com/rcbops/u-suk-dev/issues/209 in the queue :)

> Should this be a script or playbook? This can easily be
converted to a playbook but this is largely just documenting
the manual steps required to perform the upgrade.

Keep a script for now, and see how important is to convert it to a playbook later. 

> The variable munging stuff can potentially be moved out into a
separate playbook/script which can then be included here and by
support, but we will need to wait to determine how exactly this
is going to be run (do we use --danger DANGER or not?) before
we do that work.

I honestly don't think this should be automated at all in practice. For the sake of testing though, using --danger for now is okay.

**Comment by git-harry** [comment]
@mattt416 @sigmavirus24 @alextricity25 if you look at site.yml, it does not match what is in deploy.sh. In addition, deploy.sh uses environment variables which site.yml cannot understand, the use of site.yml and deploy.sh are not equivalent. We have a slightly muddled interface for enabling different parts of the product, we have to set env and conf bits for Ansible but then also have additional variables used by the scripts. I think that deploy.sh and the upgrade process should use the same method to run the RPCO playbooks.

@mattt416 if you are going to solving everything in the one commit, please make sure to add additional cards to the backlogs for the things that need to be revisited to make them more support friendly.

**Comment by mattt416** [comment]
Closing this as the expectation is that this work is done in smaller chunks.

**Pull request closed without merging**
