### PR TITLE
[MaaS] Backport improvements to Liberty

### PR DESCRIPTION
**Pull request by major**
This is a backport of all MaaS improvements through 2017-02-06.

Connects rcbops/u-suk-dev#1175

### CODE REVIEW

**Comment by antonym** [comment]
We should backport e67944f0f7ef758ccefd36eed55bb3a2a4ff5791 as Liberty as well.  Do you want to cherry pick it?

**Comment by major** [comment]
Good catch, @antonym. I'll add it.

**Comment by antonym** [comment]
Also 009b1f3f71a30a0812d34e567755a13c9e733076 (updated readme) and 89a638966c00d68c69d151574a953da5b0a182a3 (moves the plugins into the role if needed)

**Comment by major** [comment]
@antonym Added.

**Comment by major** [comment]
Fixed the bad merge conflict resolution in `defaults/main.yml`.

**Comment by antonym** [comment]
recheck_swift
recheck_ceph

**Comment by major** [comment]
Going to try to backport these in smaller chunks.

**Pull request closed without merging**
