### PR TITLE
Add upgrade playbook for r13.1

### PR DESCRIPTION
**Pull request by sigmavirus24**
All upgrade related playbooks and tasks will be launched from this one
over-arching playbook to make running and testing upgrades simpler.

Connects rcbops/u-suk-dev#292

### CODE REVIEW

**Comment by sigmavirus24** [comment]
cc @rcbops/support-feedback

**Comment by d34dh0r53** [comment]
Lint failing with `ERROR: expecting dict; got: osa-after-upgrade.yml, error in /home/travis/build/rcbops/rpc-openstack/rpcd/playbooks/roles/post-upgrade/tasks/main.yml`

**Comment by d34dh0r53** [comment]
@sigmavirus24 I think you may need to add `---` and a comment or a dummy var to make these valid YAML files.

**Comment by Apsu** [comment]
RPC-AIO-Liberty-PR: Fail

**Comment by Apsu** [comment]
RPC-AIO-Ceph-Liberty-PR: Fail

**Comment by hughsaunders** [comment]
recheck_all

**Comment by sigmavirus24** [comment]
@mattt416 was curious what this was for. To answer his question:

We've had several discussions with our support team and they strongly dislike and distrust upgrade bash scripts. They would be more confident if they had upgrade playbooks to do the work that the bash scripts tend to do. This is the start of the work towards that end.

**Comment by mattt416** [comment]
Sorry @sigmavirus24, I understand the reasoning behind converting the bash script to ansible, but I was more curious if we need actual roles for this versus just having individual playbooks.

**Comment by sigmavirus24** [comment]
Ah, so we could. I think we've just tended towards roles for organizational purposes.

**Comment by sigmavirus24** [comment]
Gah, forgot to update the commit message.

**Comment by sigmavirus24** [comment]
Based on this morning's mitaka stand-up. We're not going to use roles but instead we're going to use playbooks and factor those into roles as necessary

**Comment by Apsu** [comment]
RPC-AIO-Liberty-PR: Fail

**Comment by Apsu** [comment]
RPC-AIO-Liberty-PR: Fail

**Comment by Apsu** [comment]
RPC-AIO-Ceph-Liberty-PR: Fail

**Comment by sigmavirus24** [comment]
recheck_all

**Comment by git-harry** [comment]
👍 @evrardjp, @mattt416 would you please review this.

**Comment by mattt416** [comment]
LGTM, but I think one of the first tasks to go into this is to prompt to proceed, or something of that nature.

**Pull request merged**
