### PR TITLE
Update openstack-ansible SHA

### PR DESCRIPTION
**Pull request by git-harry**
This commit updates the openstack-ansible SHA to the tag 11.2.17 in
preparation for the next RPCO release.

Issues addressed by updating OSA SHA:

Connects https://github.com/rcbops/rpc-openstack/issues/1112

### CODE REVIEW

**Comment by Apsu** [comment]
RPC-AIO-Kilo-PR

**Comment by Apsu** [comment]
RPC-AIO-Ceph-Kilo-PR: Fail

**Comment by git-harry** [comment]
recheck_all

**Comment by git-harry** [comment]
recheck_all

**Comment by git-harry** [comment]
recheck_ceph
recheck_swift

**Comment by evrardjp** [comment]
It seems it's the good sha (the EOL-one).
👍

**Comment by hughsaunders** [comment]
👍

**Pull request merged**
