### PR TITLE
Adding missing nova db settings

### PR DESCRIPTION
**Pull request by tomc603**
Backport from #862

Closes-Bug: #861

### CODE REVIEW

**Comment by prometheanfire** [comment]
recheck

**Comment by prometheanfire** [comment]
lgtm :+1:

**Comment by prometheanfire** [comment]
recheck

    18:04:12 TASK: [Build all known python packages requirements] ************************** 
    18:04:12 failed: [jrpcaioiad-be7_repo_container-62d3c08f] => {"changed": true, "cmd": "yaprt --quiet build-wheels --report-file /var/www/repo/reports/release-rpc-r11.1.5-report.json --storage-pool \"/var/www/repo/pools\" --link-dir \"/var/www/repo/rpc-releases/r11.1.5\" --pip-extra-link-dirs \"/var/www/repo/links\" --pip-index \"http://rpc-repo.rackspace.com/pools\" --pip-extra-index \"https://pypi.python.org/simple/\" --pip-bulk-operation --build-output \"/tmp/rpc-wheel-output\" --build-dir \"/tmp/rpc-builder\" --build-requirements --force-clean", "delta": "0:01:18.052433", "end": "2016-03-09 18:04:12.571182", "rc": 1, "start": "2016-03-09 18:02:54.518749", "warnings": []}
    18:04:12 stderr:   DEPRECATION: Failed to find 'beaver' at http://rpc-repo.rackspace.com/pools/beaver/. It is suggested to upgrade your index to support normalized names as the name in /simple/{name}.
    18:04:12 /usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
    18:04:12   InsecurePlatformWarning
    18:04:12   Could not find a version that satisfies the requirement beaver==33.3.0 (from -r /var/www/repo/rpc-releases/r11.1.5/build_reqs.txt (line 1)) (from versions: )
    18:04:12 No matching distribution found for beaver==33.3.0 (from -r /var/www/repo/rpc-releases/r11.1.5/build_reqs.txt (line 1))
    18:04:12 /usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.

**Comment by d34dh0r53** [comment]
:+1:

**Pull request merged**
