### PR TITLE
RO-4491 Update newton dependencies

### PR DESCRIPTION
**Pull request by rpc-jenkins-svc**
Automated dependency update pull request, see individual commits for details.

Issue: [RO-4491](https://rpc-openstack.atlassian.net/browse/RO-4491)

### CODE REVIEW

**Comment by antonym** [comment]
recheck_trusty_swift_deploy

**Comment by cjloader** [comment]
2019-01-24T09:36:18-0600 failed: [aio1_logstash_container-166e019c] (item={u'url': u'https://packages.elastic.co/GPG-KEY-elasticsearch', u'state': u'present'}) => {"failed": true, "item": {"state": "present", "url": "https://packages.elastic.co/GPG-KEY-elasticsearch"}, "msg": "Failed to validate the SSL certificate for packages.elastic.co:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine or you can install the `urllib3`, `pyopenssl`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"}

**Comment by cjloader** [comment]
recheck_trusty_swift_deploy

**Comment by odyssey4me** [comment]
FWIW in OSA upstream we've switched to vendoring in the GPG keys to the role to prevent issues with https/SNI when trying to retrieve the key, and to also cut out issues in proxy environments. See https://review.openstack.org/#/q/topic:vendor-gpg-keys

**Comment by odyssey4me** [comment]
recheck_trusty_swift_deploy

Trusty has really old SSL libs, so I'm not surprised it's failing. Perhaps something should be fixed in the roles that're being executed?

**Comment by antonym** [comment]
Seems like previous jobs were pulling from the rpc-o repo:

```
2019-01-23T16:48:49-0600 TASK [logstash : Add apt keys] *************************************************
2019-01-23T16:48:52-0600 ok: [aio1_logstash_container-bbbdac5f] => (item={u'url': u'http://rpc-repo.rackspace.com/apt-mirror/rcbops-release-signing-key.asc', u'state': u'present', u'hash_id': u'52AA252F'})
2019-01-23T16:48:52-0600 
2019-01-23T16:48:52-0600 TASK [logstash : Add apt repositories] *****************************************
2019-01-23T16:48:53-0600 ok: [aio1_logstash_container-bbbdac5f] => (item={u'repo': u'deb http://rpc-repo.rackspace.com/apt-mirror/integrated/ r14.22.0-trusty main', u'state': u'present', u'filename': u'rpco'})
```

Is it not using this anymore?

https://github.com/rcbops/rpc-openstack/blob/newton/group_vars/all/apt.yml#L112

**Comment by odyssey4me** [comment]
@antonym Good find. As far as I can see, nothing has changed in RPC-O - but I've only given it a cursory glance. Figuring out why that's not using the right var is key to figuring out what's causing this failure. Let me know if you guys need assistance.

**Comment by antonym** [comment]
recheck_trusty_swift_deploy

The last successful Newton merge was Dec 13 and the one previous to this was merged in with the same failure.  I'm not seeing really anything in Newton that looks like it would change that behavior.  Any changes on that gating side that could have impacted how Ansible reads the group_vars variables environmentally?

**Comment by odyssey4me** [comment]
OK, I understand what's going on here. This is a change of ``rpc_release``, so the build process removes all the artifacting configuration because there are no artifacts yet, until this merges. That's why this failure is not showing up in any of the PM's or any other PR's.

To resolve this we're going to have to work out how to make Ansible be capable of supporting SNI.

**Comment by cjloader** [comment]
recheck_trusty_swift_deploy

**Comment by cjloader** [comment]
Tried to not include all hosts for pip_install, but filebeats is not able to verify SSL, so I readded the pip_install back into filebeats install (which does all hosts).

**Pull request merged**
