### PR TITLE
Fixed nova_spice_console pool generation

### PR DESCRIPTION
**Pull request by busterswt**
Fixed the following error that kept the Nova spice pool from being generated: Inventory group "nova_console" not found, skipping.

### CODE REVIEW

**Comment by nrb** [comment]
`nova_spice_console` was renamed. See https://github.com/rcbops/rpc-openstack/issues/86

Do we need to adjust something in the F5s?

**Comment by busterswt** [comment]
Not necessarily. We were using this script for all deployments (including v10) as there is no Juno branch. If you changed the name of the inventory group for v11, then that explains what's going on here. Feel free to disregard cec4bab. The one-liner, though, at a39f1e6 is still useful.

**Comment by nrb** [comment]
Yeah, the juno branch is in upstream OSAD. https://github.com/stackforge/os-ansible-deployment/blob/juno/scripts/f5-config.py

However, since the f5-config script isn't a vital component of OSAD, it was considered a RAX-ism and moved into rpc-openstack in Kilo.

**Comment by prometheanfire** [comment]
I think we are using maas_common now, can this be closed or rebased as needed?

**Comment by rackertom** [comment]
Any input @nrb and @busterswt? The original PR is from July, so we should probably update or abandon this.

**Comment by nrb** [comment]
I'm good with the a39f1e6 commit going in, if it helps our consumers.

The PR will need to be rebased and the other one removed, though - if @busterswt can do it that's awesome, if not we can close this PR and maybe grab that commit from his fork.

**Comment by busterswt** [comment]
Hey guys, sorry I've been mute on this. Not sure if it's still a problem or not. Feel free to do whatever; I don't have Internet access :(

Sent from my iPhone

On Oct 22, 2015, at 8:05 PM, Nolan Brubaker <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm good with the a39f1e6<https://github.com/rcbops/rpc-openstack/commit/a39f1e6870314c87b82de0c17f99afc7e1727834> commit going in, if it helps our consumers.

The PR will need to be rebased and the other one removed, though - if @busterswt<https://github.com/busterswt> can do it that's awesome, if not we can close this PR and maybe grab that commit from his fork.

-

**Comment by hughsaunders** [comment]
Networking people (@Apsu @rackertom) is this a good commit? I have no means of testing. Abandon by Jan 2016 if no response.

**Comment by busterswt** [comment]
This commit:

https://github.com/rcbops/rpc-openstack/commit/a39f1e6870314c87b82de0c17f99afc7e1727834

… allows the F5 engineer to copy/paste the F5 configuration without having to interact with the text editor on the F5. If you want to abandon this commit, we can submit a new PR with additional changes.


James Denton
Network Architect
Rackspace Private Cloud
james.denton@rackspace.com

**Comment by hughsaunders** [comment]
@busterswt thanks for clarifying, but we still need a review from someone else who understands F5 config.

**Comment by rackertom** [comment]
Wow this is an oldie. :+1: The change is very simple. I don't have an F5 to test it on, but it's so simple that I don't think we need one.

**Comment by hughsaunders** [comment]
closing as I've put [a39f1e6](https://github.com/rcbops/rpc-openstack/commit/a39f1e6870314c87b82de0c17f99afc7e1727834) in new pr #654.

**Pull request closed without merging**
