### PR TITLE
Do not setup Ceph monitoring when Ceph is not present

### LINKED ISSUE #492: Option for turning off Ceph monitoring
I might just be missing this variable somewhere, but on r11.0.1, setup-maas.yml tries to discover ceph facts even though I'm not using ceph in this deployment. I don't see any way to turn this off in user_extras_variables.yml or anywhere else. In a deployment that is not using ceph how is setup-maas.yml supposed to complete?

TASK: [rpc_maas | Discover Ceph facts] ****************************************
fatal: [compute01] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_nova_scheduler_container-638e2856] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_horizon_container-f3df59bf] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_horizon_container-422f2991] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_utility_container-0276d803] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_keystone_container-2d73e396] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_keystone_container-0d7a4d0c] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_nova_cert_container-6f5a612d] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_repo_container-cb57e740] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_neutron_server_container-2336cf92] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_glance_container-df8f6782] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_cinder_scheduler_container-45595f8a] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_repo_container-64a71607] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_neutron_agents_container-80cc6d88] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_nova_api_os_compute_container-ca331872] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_nova_api_metadata_container-e444e98d] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_memcached_container-7df01f14] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_nova_conductor_container-3891b9ad] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_galera_container-2c14a508] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_cinder_api_container-97bb86b8] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_rsyslog_container-95b449dc] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_rabbit_mq_container-19de8a9a] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_rabbit_mq_container-db8160a0] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_heat_apis_container-429e480d] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_galera_container-dea4ed6c] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_heat_engine_container-09eb5ad5] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_galera_container-285a0792] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_rabbit_mq_container-ffa9d583] => error while evaluating conditional: inventory_hostname in groups['ceph_all']
fatal: [infra01_nova_console_container-0a481d09] => error while evaluating conditional: inventory_hostname in groups['ceph_all']

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/setup-maas.retry

compute01                  : ok=153  changed=41   unreachable=1    failed=0
infra01                    : ok=144  changed=29   unreachable=1    failed=0
infra01_cinder_api_container-97bb86b8 : ok=119  changed=4    unreachable=1    failed=0
infra01_cinder_scheduler_container-45595f8a : ok=119  changed=4    unreachable=1    failed=0
infra01_galera_container-285a0792 : ok=120  changed=4    unreachable=1    failed=0
infra01_galera_container-2c14a508 : ok=120  changed=5    unreachable=1    failed=0
infra01_galera_container-dea4ed6c : ok=120  changed=5    unreachable=1    failed=0
infra01_glance_container-df8f6782 : ok=122  changed=8    unreachable=1    failed=0
infra01_heat_apis_container-429e480d : ok=125  changed=12   unreachable=1    failed=0
infra01_heat_engine_container-09eb5ad5 : ok=116  changed=0    unreachable=1    failed=0
infra01_horizon_container-422f2991 : ok=119  changed=4    unreachable=1    failed=0
infra01_horizon_container-f3df59bf : ok=119  changed=4    unreachable=1    failed=0
infra01_keystone_container-0d7a4d0c : ok=119  changed=4    unreachable=1    failed=0
infra01_keystone_container-2d73e396 : ok=119  changed=4    unreachable=1    failed=0
infra01_memcached_container-7df01f14 : ok=119  changed=4    unreachable=1    failed=0
infra01_neutron_agents_container-80cc6d88 : ok=134  changed=24   unreachable=1    failed=0
infra01_neutron_server_container-2336cf92 : ok=119  changed=4    unreachable=1    failed=0
infra01_nova_api_metadata_container-e444e98d : ok=119  changed=4    unreachable=1    failed=0
infra01_nova_api_os_compute_container-ca331872 : ok=119  changed=4    unreachable=1    failed=0
infra01_nova_cert_container-6f5a612d : ok=119  changed=4    unreachable=1    failed=0
infra01_nova_conductor_container-3891b9ad : ok=119  changed=4    unreachable=1    failed=0
infra01_nova_console_container-0a481d09 : ok=122  changed=8    unreachable=1    failed=0
infra01_nova_scheduler_container-638e2856 : ok=119  changed=4    unreachable=1    failed=0
infra01_rabbit_mq_container-19de8a9a : ok=119  changed=4    unreachable=1    failed=0
infra01_rabbit_mq_container-db8160a0 : ok=119  changed=4    unreachable=1    failed=0
infra01_rabbit_mq_container-ffa9d583 : ok=120  changed=4    unreachable=1    failed=0
infra01_repo_container-64a71607 : ok=116  changed=0    unreachable=1    failed=0
infra01_repo_container-cb57e740 : ok=116  changed=0    unreachable=1    failed=0
infra01_rsyslog_container-95b449dc : ok=116  changed=0    unreachable=1    failed=0
infra01_utility_container-0276d803 : ok=118  changed=0    unreachable=1    failed=0

### PR DESCRIPTION
**Pull request by byronmccollum**
Fixes #492

### CODE REVIEW

**Comment by andymcc** [comment]
This is already fixed in the feature branch we are doing for MaaS refactor so you shouldn't need this one.

**Comment by stevelle** [comment]
fix from the feature branch has been merged to master and a PR is open to backport to kilo #531

**Comment by byronmccollum** [comment]
Since the MaaS refactor isn't going into Kilo, should this PR be retargeted to Kilo?

**Comment by byronmccollum** [comment]
Retargeted to Kilo in PR #555

**Pull request closed without merging**
