### PR TITLE
ASC-340 add swagger client

### PR DESCRIPTION
**Pull request by zreichert**
Issue: [ASC-340](https://rpc-openstack.atlassian.net/browse/ASC-340)

### CODE REVIEW

**Comment by prometheanfire** [comment]
Is there a reason this isn't published to pypi?

**Comment by ryan-rs** [comment]
@prometheanfire The package is from [qTest](https://api.qasymphony.com/#/) which they only host on their site. We've requested that they upload the package to PyPI, but we're waiting on a response.

**Comment by zreichert** [comment]
@prometheanfire  Well its owned by QASymphony (they make qTest).  We are not sure why they have not published this to PyPI but we are reaching out to them to ask if they are willing to publish or if they are willing to allow us to publish.  The repo contains no license file 🤷‍♂️ .  While we wait for their response we want to go back to installing from git.

**Comment by ryan-rs** [comment]
recheck_cit_xenial_no_artifacts_swift_deploy
recheck_cit_container_ansible-lint_tox-test
recheck_cit_container_ansible-syntax_tox-test

**Pull request merged**
