### PR TITLE
Update OSA SHA to tip of stable/mitaka

### PR DESCRIPTION
**Pull request by git-harry**
This update addresses the following issues:

- https://github.com/rcbops/rpc-openstack/issues/1483
- https://github.com/rcbops/u-suk-dev/issues/517
- https://github.com/rcbops/rpc-openstack/issues/1432

Connected https://github.com/rcbops/u-suk-dev/issues/579

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/staging.horse/build-c5136e9fab/docs/private-cloud/release-notes/)

**Comment by alextricity25** [comment]
recheck_upgrade

**Comment by git-harry** [comment]
recheck_upgrade Task Failed: horizon_all / horizon_extensions / Collect and compress static files

**Comment by git-harry** [comment]
recheck_upgrade

**Comment by git-harry** [comment]
recheck_upgrade Task Failed: Verify MaaS setup / Verify Check & Alarm Status

**Comment by alextricity25** [comment]
:+1:

**Comment by mancdaz** [comment]
👍 

Confirmed:

#1483 is fixed by https://review.openstack.org/#/c/389795/ (OSA commit 2840b23fc413c7808fed6d2bd0c79e4eb0a71077)
rcbops/u-suk-dev#517 is fixed by https://review.openstack.org/#/c/391398/ (OSA commit 6f14768e983ec06aa417186fe82e3aecca96727a)
#1432 is fixed by https://review.openstack.org/#/c/389064/ (OSA commit 02701e3bf8370c15132e542c0fdec34c0dd31d60)

and all 3 of these commits are included in the new sha:

```
 ~/working/.../rpc-openstack/openstack-ansible [(detached from 2d0c46a)]
 $ git log --pretty=oneline | egrep '^2840b23|^6f14768e|^02701e3b'
2840b23fc413c7808fed6d2bd0c79e4eb0a71077 Remove the old rabbitmq queues
6f14768e983ec06aa417186fe82e3aecca96727a Stop all but one RabbitMQ node prior to upgrade
02701e3bf8370c15132e542c0fdec34c0dd31d60 Work around bad libvirt-python wheel
```

**Pull request merged**
