### PR TITLE
remove dead code (scripts/release.py)

### PR DESCRIPTION
**Pull request by prometheanfire**

### CODE REVIEW

**Comment by odyssey4me** [comment]
recheck_cit_release

**Comment by prometheanfire** [comment]
recheck_cit_release
recheck_cit_artifact

**Comment by cloudnull** [comment]
release job failures are known issues when using an internal branch instead of a fork because the failures are unrelated to this change :+1: .

**Comment by prometheanfire** [comment]
ah, right, forgot about that

**Pull request merged**
