### PR TITLE
Configure infra to preview and publish release notes

### PR DESCRIPTION
**Pull request by darrenchan**
Configuration to preview release note builds on
https://staging.developer.rackspace.com/, and eventually
publish to https://developer.rackspace.com

### CODE REVIEW

**Comment by darrenchan** [comment]
After rackerlabs/nexus-control#51 and this PR are merged:  @rackernexus will provide a build preview link in PRs with a release note file. For example: rackerlabs/docs-rpc#407.

**Comment by darrenchan** [comment]
CCing @smashwilson @meker12 @kallimachos

**Comment by Apsu** [comment]
RPC-AIO-Liberty-PR: Fail

**Comment by prometheanfire** [comment]
This looks good to me but I don't know how we'd check if this works (given external reqs).

**Comment by sigmavirus24** [comment]
I'm not sure how to verify this is correct either, but based on switching from the UTF-8 quotes to regular `"`s, and a few other things, this looks *safe* to merge to me.

**Comment by Apsu** [comment]
RPC-AIO-Ceph-Liberty-PR: Fail

**Comment by darrenchan** [comment]
@prometheanfire @sigmavirus24 how do I resolve the RPC-AIO-Ceph-Liberty-PR build fail?

**Comment by prometheanfire** [comment]
looks unrelated

    22:31:36 tempest.scenario.test_server_basic_ops.TestServerBasicOps.test_server_basic_ops[compute,id-7fff3fb3-91d8-4fd0-bd7d-0204f1f180ba,network,smoke]

recheck_ceph

**Comment by prometheanfire** [comment]
@darrenchan looks like it's working now

:+1: good to merge (have been told the outside pieces have been put in place for build notes)

**Comment by sigmavirus24** [comment]
👍 merging

**Pull request merged**
