### PR TITLE
Adding Magnum support to Logstash and Filebeat

### PR DESCRIPTION
**Pull request by chrishultin**

### CODE REVIEW

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/staging.horse/build-fe8a66ba33/docs/private-cloud/release-notes/).

**Comment by git-harry** [comment]
@chrishultin thanks for the contribution, for it to be reviewed we need an [issue](https://github.com/rcbops/rpc-openstack/issues/new). Please create one so that this work is appropriately prioritised.

**Comment by chrishultin** [comment]
Issue:
https://github.com/rcbops/rpc-openstack/issues/1526

**Comment by alextricity25** [comment]
Closing per https://github.com/rcbops/rpc-openstack/pull/1573/

**Pull request closed without merging**
