### PR TITLE
Enable Kilo to Liberty upgrades, closes #896

### LINKED ISSUE #896: Kilo to Liberty upgrades fail when using upgrade.sh
##### What version (commit) do you encounter this issue on?
57aa062721d0fe0e3eeb5114e4684ddc65a01829 for Kilo
ea9953730a602c027b93e2c5440c5617cdb12792 for Liberty
##### What type of issue is this (bug, feature, documentation, regression)?
bug/feature
##### What is the expected behavior?
Running upgrade.sh should make the changes required to update an Kilo RPCO deployment to a Liberty RPCO deployment.
##### What is actually happening?
The script fails due to a missing directory
##### How can we reproduce this issue?
On a Kilo deployment checkout master and run ./scripts/upgrade.sh
##### How can we verify your issue is addressed?
./scripts/upgrade.sh will successfully complete.
##### What is your evaluation on the importance of this issue, and why?
This issue is critical to a successful 12.1.0 release because upgrades is a required component.
##### What branches / milestones do you believe this issue should target?
The list below is what is currently supported for backports, remove branches you do not wish to target.
- [ ] Master #893

### PR DESCRIPTION
**Pull request by git-harry**
This commit includes the changes required to get scripts/upgrade.sh to complete successfully. It does not make any changes to alter/improve the upgrade experience.

Move openstack-ansible SHA to include the Liberty upgrade code.

Replace references to rpc_deploy directory with openstack_deploy.
rpc_deploy was a Juno-specific directory.

Fix the ansible-galaxy command in scripts/upgrade.sh by escaping the
newline character separating the two halves of the command.

Remove the directory /root/.pip from the hosts in the group
repo_container. The directory is created by the playbook
repo-pip-setup.yml on a Kilo deployment. It restricts the repo server to
using packages it already has access to which prevents the repo server
from upgrading based on Liberty requirements.

Closes-Issue: https://github.com/rcbops/rpc-openstack/issues/896

### CODE REVIEW

**Comment by stevelle** [comment]
no issue number?

**Comment by git-harry** [comment]
@stevelle, my bad, I've added one.

**Comment by stevelle** [comment]
cloned the priority label from the linked issue.

**Comment by nrb** [comment]
I've tried this, but the call to the openstack-ansible upgrade script never seems to happen - it proceeds from the patcher to the support playbook. Overall runtime was about 2 minutes.

**Comment by git-harry** [comment]
@nrb check for /etc/openstack_deploy/upgrade-kilo. If you've already run the script once on that box it will skip everything without adding anything to the log.

**Comment by nrb** [comment]
Doesn't appear to be there - my first and 2nd runs of the script had the same runtime (give or take a few seconds).

```
root@nolan-ord-nolan-aio2:/etc/openstack_deploy# ls
ansible_facts                   conf.d  openstack_environment.yml    openstack_inventory.json   user_extras_secrets.yml      user_extras_variables.yml  user_secrets.yml.tar
backup_openstack_inventory.tar  env.d   openstack_hostnames_ips.yml  openstack_user_config.yml  user_extras_secrets.yml.tar  user_secrets.yml           user_variables.yml
```

I ran it with `./scripts/upgrade.sh` from `/opt/rpc-openstack/`, which I believe was the proper invocation.

**Comment by nrb** [comment]
I see what I did - I did not update the openstack-ansible module again after checking out this PR's branch. The `run-upgrade.sh` script just had the prereq checks, none of the actual upgrade logic. My mistake.

**Comment by nrb** [comment]
After properly updating my submodule, the script ran to completion without error.

I *have not* tested running networks, storage, or VMs on top it yet, though.

**Comment by prometheanfire** [comment]
I'm building kilo and am going to upgrade it

using https://github.com/cloudnull/osa-multi-node-aio but for RPC-O

**Comment by prometheanfire** [comment]
I upgraded, there is an issue with swift and one with neutron, but they are separate I think

:+1: for now

**Pull request merged**
