### PR TITLE
Resolve issues discovered in the leapfrog upgrade process

### PR DESCRIPTION
**Pull request by odyssey4me**
This PR resolves issues discovered while testing the leapfrog upgrade process.

Issue: [LA-444](https://rpc-openstack.atlassian.net/browse/LA-444)

Issue: [LA-449](https://rpc-openstack.atlassian.net/browse/LA-449)

### CODE REVIEW

**Comment by odyssey4me** [comment]
Cinder failing:

```
TASK [Perform online data migrations] ******************************************
fatal: [rantdsp-102-15bd_cinder_api_container-72e2f2a6]: FAILED! => {"changed": false, "cmd": ["/openstack/venvs/cinder-r14.2.0/bin/cinder-manage", "db", "online-data-migrations"], "delta": "0:00:02.689556", "end": "2017-08-29 16:52:28.031214", "failed": true, "rc": 2, "start": "2017-08-29 16:52:25.341658", "stderr": "usage: cinder-manage db [-h] {purge,sync,version} ...\ncinder-manage db: error: argument action: invalid choice: 'online-data-migrations' (choose from 'purge', 'sync', 'version')", "stdout": "", "stdout_lines": [], "warnings": []}
```

The online migrations were only introduced in Ocata, so they should be removed from the cinder process for Newton.

**Comment by odyssey4me** [comment]
As the ``os_cinder`` role in its current state will do the migrations without any trouble, I've removed it from the original patch.

**Comment by prometheanfire** [comment]
This did not work

    ERROR (Conflict): Not all flavors have been migrated to the API database (HTTP 409) (Request-ID: req-9dc70e2e-3368-4a80-af6f-c90ae87c763c)

**Comment by prometheanfire** [comment]
`ansible-role-requirements.yml` is not defined anywhere in the leap upgrade scripting, so this doesn't help.

**Comment by prometheanfire** [comment]
`ansible-role-requirements.yml` of the osa checkout (14.2.7, 14.2.8, whatever) as done by osa-ops needs the fix, not rpc-openstack.  http://sprunge.us/iGRf is my current patch.  I think later definitions in `ansible-role-requirements.yml` override earlier definitions.

**Comment by evrardjp** [comment]
The log here SHOWS that the ANSIBLE_ROLE_PATH was NOT fixed by previous patch.
This patch is not at cause.

**Comment by odyssey4me** [comment]
@prometheanfire If the leap process is not making use of the RPC-O bootstrap, then it will be executing playbooks using roles and variables which are probably not correct for the artifacts being used, resulting in an unpredictable result. The correct approach here is to add a facility to allow customisation of where the bootstrap is run from so that we can run our own. This has been done by @evrardjp here: https://review.openstack.org/499102

**Comment by odyssey4me** [comment]
This is blocked until some patches merge upstream, and this PR is modified to make use of the upstream fixes.

**Comment by odyssey4me** [comment]
recheck_cit_artifact

**Comment by odyssey4me** [comment]
recheck_trusty_deploy_swift - weird tempest test failure (unrelated)

**Comment by odyssey4me** [comment]
recheck_cit_trusty_leapfrogupgrade_swift - kibana selenium test failure

**Comment by claco** [comment]
Same outcome again. Everything passed but the cleanup part of recheck_trusty_deploy_swift

**Comment by evrardjp** [comment]
recheck_trusty_deploy_swift

**Comment by odyssey4me** [comment]
recheck_cit_trusty_leapfrogupgrade_swift - kibana selenium test failure

**Comment by odyssey4me** [comment]
FYI https://github.com/rcbops/rpc-gating/pull/403 is being implemented to prevent the cleanup causing a job failure. Once that's merged we can recheck the trusty-deploy-swift job to verify that it's working.

**Comment by odyssey4me** [comment]
recheck_cit_trusty_deploy_swift - now that the gating change is implemented

**Pull request merged**
