### PR TITLE
revert change to nova_console variable change to nova_spice_console

### PR DESCRIPTION
**Pull request by prometheanfire**

### CODE REVIEW

**Comment by prometheanfire** [comment]
as noted in #427 this change made it into master and should not have

**Comment by d34dh0r53** [comment]
:+1:

**Comment by git-harry** [comment]
I don't think the commit is accurate, as I understood the issue the change to nova_console was never made in master.

**Comment by prometheanfire** [comment]
then how can it apply here?  It obviously changed.

**Comment by git-harry** [comment]
+1

**Pull request merged**
