### PR TITLE
Add MaaS checks for processes status (#1366)

### PR DESCRIPTION
**Pull request by cloader89**
This adds a MaaS check script to check by fully qualified or basename
if processes are running on a host or within a container on a host.
Additionally, MaaS checks for beaver, elasticsearch and rsyslog are
added using the process check script.

Connects #1236
(cherry picked from commit 2870f4e)

### CODE REVIEW

**Comment by alextricity25** [comment]
Hi @cloader89.
Kilo is EOL so I don't think there is a need to backport this PR to Kilo.

**Comment by alextricity25** [comment]
Turns out I was wrong about Kilo being EOL. Sorry about that.
If support deems it necessary to have this in Kio, then it should be in Kilo.
Sorry again for the confusion :)

**Comment by git-harry** [comment]
👎 The commit message does not reference the original commmit.

To cherry-pick a commit into your current branch you should do:

```
git cherry-pick -x commit
```

Adding '-x' appends a line to the commit message referencing the original commit.

**Comment by cloader89** [comment]
recheck_all

**Comment by cloader89** [comment]
recheck_swift

**Comment by cloader89** [comment]
recheck_swift

**Comment by cloader89** [comment]
recheck_swift

**Comment by cloader89** [comment]
18:29:54 Build timed out (after 30 minutes). Marking the build as aborted.
18:29:54 Build was aborted 

recheck_swift

**Comment by cloader89** [comment]
21:30:48 TASK: [Verify Check & Alarm Status] ******************************************* 
22:00:48 Build timed out (after 30 minutes). Marking the build as aborted.
22:00:48 Build was aborted
recheck_swift

**Comment by cloader89** [comment]
recheck_swift verify maas timeout

**Comment by cloader89** [comment]
recheck_swift maas timeout

**Comment by cloader89** [comment]
recheck_swift maas timeout

**Comment by d34dh0r53** [comment]
Will need to be squashed, but other than that LGTM 👍

**Comment by cloader89** [comment]
recheck_all

**Comment by Frank-ZhangXin** [comment]
recheck_ceph

**Comment by Frank-ZhangXin** [comment]
passed all tests and LGTM 👍

**Comment by sigmavirus24** [comment]
👍

**Pull request merged**
