### PR TITLE
 Adding new default values for neutron/nova/keystone DB/RPC pools

### PR DESCRIPTION
**Pull request by BjoernT**
Adding new default values for neutron/nova/keystone SQLAlchemy/Olso Thread Pool Settings for bug #724

### CODE REVIEW

**Comment by prometheanfire** [comment]
nova_cross_az_attach: False was removed?

**Comment by BjoernT** [comment]
nova_cross_az_attach should be set already

**Comment by claco** [comment]
Isn't the default in Kilo True, which we don't want?

http://docs.openstack.org/kilo/config-reference/content/list-of-compute-config-options.html

**Comment by BjoernT** [comment]
Yes but we set it on purpose to false via https://github.com/rcbops/rpc-openstack/blob/master/rpcd/etc/openstack_deploy/user_variables.yml#L17, which was not back ported to kilo.
The reason for this is, if the customer places cinder in different DCs, he can't allocate nova instance and cinder volumes across DCs. That's why the cinder AZs should line up with nova. In case when it's not we have to enable it

**Comment by claco** [comment]
That's my confusion. Once this patchset goes in, we will no longer be setting it to false as that line is being removed? https://github.com/rcbops/rpc-openstack/pull/759/files#diff-7507cc9de5006d33bbff4104099c0955L17

**Comment by BjoernT** [comment]
I see, I just fixed that. Thanks for checking

**Comment by prometheanfire** [comment]
lgtm :+1:

**Comment by claco** [comment]
Good catch @prometheanfire!

**Comment by prometheanfire** [comment]
they say I'm 'detail oriented', no clue which direction that is though.

**Comment by tomc603** [comment]
Looks good. Nice catch @prometheanfire. :+1:

**Comment by prometheanfire** [comment]
two :+1: , merging

**Pull request merged**
