### PR TITLE
Fix holland_preinstall to build wheels for the holland plugins.

### PR DESCRIPTION
**Pull request by d34dh0r53**
The variable name for the holland plugins in main.yml was slightly
incorrect causing the wheel builder to skip over them.  This fix
corrects the variable name and modifies the preinstall play to
install the pluigins from the local repo.

Fixes: #777

### CODE REVIEW

**Comment by mancdaz** [comment]
:+1: winning, nice patch.

tested locally by applying the patch to an AIO that had not yet installed holland in the galera containers, then ran the repo-build and repo-pip-install plays, and then the rpc-support play.  Much success:

```
TASK: [rpc_support | Install pip repo plugins] ********************************
...
changed: [kilo_galera_container-a7d7e279] => (item={'path': 'plugins', 'package': 'holland.lib.common'})
changed: [kilo_galera_container-87757b6c] => (item={'path': 'plugins', 'package': 'holland.lib.common'})
changed: [kilo_galera_container-a17d1502] => (item={'path': 'plugins', 'package': 'holland.lib.common'})
changed: [kilo_galera_container-a7d7e279] => (item={'path': 'plugins', 'package': 'holland.lib.mysql'})
changed: [kilo_galera_container-87757b6c] => (item={'path': 'plugins', 'package': 'holland.lib.mysql'})
changed: [kilo_galera_container-a17d1502] => (item={'path': 'plugins', 'package': 'holland.lib.mysql'})
changed: [kilo_galera_container-a7d7e279] => (item={'path': 'plugins', 'package': 'holland.backup.xtrabackup'})
changed: [kilo_galera_container-87757b6c] => (item={'path': 'plugins', 'package': 'holland.backup.xtrabackup'})
changed: [kilo_galera_container-a17d1502] => (item={'path': 'plugins', 'package': 'holland.backup.xtrabackup'})
...
```

**Comment by hughsaunders** [comment]
recheck

**Comment by cloudnull** [comment]
:+1:

**Comment by tomc603** [comment]
:+1:

**Pull request merged**
