### PR TITLE
Update openstack-ansible SHA for Mitaka

### PR DESCRIPTION
**Pull request by git-harry**
Issues addressed:

- https://github.com/rcbops/u-suk-dev/issues/187
- https://github.com/rcbops/rpc-openstack/issues/1311
- https://github.com/rcbops/rpc-openstack/issues/1128
- https://github.com/rcbops/u-suk-dev/issues/313

Connected https://github.com/rcbops/u-suk-dev/issues/363

### CODE REVIEW

**Comment by evrardjp** [comment]
Latest mitaka it is!
👍

**Comment by andymcc** [comment]
pending gate - happy to merge

**Comment by sigmavirus24** [comment]
👍 but I can't tell if tests have finished. GitHub status indicators are confused here. @hughsaunders thoughts?

**Comment by major** [comment]
Here's a detailed diff of what we're bringing in: https://gist.github.com/anonymous/90ae4c01e34664862cdfa574a2bb7091

**Comment by major** [comment]
:+1: LGTM pending Jenkins.

**Comment by hughsaunders** [comment]
@sigmavirus24 this PR hit rcbops/u-suk-dev#365, and will need recheck_all to get the jobs going.

**Comment by sigmavirus24** [comment]
recheck_all

**Pull request merged**
