### PR TITLE
Bump OSA SHA to tip of stable/mitaka

### PR DESCRIPTION
**Pull request by alextricity25**
Connects https://github.com/rcbops/u-suk-dev/issues/1061

### CODE REVIEW

**Comment by alextricity25** [comment]
recheck_ceph

**Comment by major** [comment]
recheck_ceph

Looks like ssh shenanigans during tempest testing:
```
19:20:27     tempest.lib.exceptions.SSHTimeout: Connection to the 172.29.248.9 via SSH timed out.
19:20:27     User: cirros, Password: rebuildPassw0rd
```

**Comment by cloader89** [comment]
recheck_upgrade

**Comment by alextricity25** [comment]
recheck_upgrade

**Comment by alextricity25** [comment]
The upgrade jobs seems to be failing on waiting for elasticsearch. https://github.com/rcbops/u-suk-dev/issues/1065 will need to be looked at before this can move on. Marking this as blocked until it's resolved.

**Comment by cloader89** [comment]
recheck_upgrade

**Comment by alextricity25** [comment]
recheck_upgrade

**Comment by major** [comment]
Engage

**Pull request merged**
