### PR TITLE
Update SHA to allow Swift to clean up nodes

### PR DESCRIPTION
**Pull request by prometheanfire**
This SHA update includes an update to Swift that allows it to remove
zero weight object nodes.

Related-Bug: #878

### CODE REVIEW

**Comment by prometheanfire** [comment]
recheck_upgrade

**Comment by prometheanfire** [comment]
recheck_upgrade

**Comment by git-harry** [comment]
Closing in favour of https://github.com/rcbops/rpc-openstack/pull/1057 based on the upgrade failure this pull request is experiencing, see https://github.com/rcbops/rpc-openstack/issues/1058.

**Comment by prometheanfire** [comment]
recheck_upgrade

**Comment by mattt416** [comment]
👍

**Pull request merged**
