### PR TITLE
remove setuptools pin upstream stated fix in 19.6.2

### PR DESCRIPTION
**Pull request by prometheanfire**

### CODE REVIEW

**Comment by prometheanfire** [comment]
build timeout?

21:41:54 Build timed out (after 20 minutes). Marking the build as aborted.

**Comment by prometheanfire** [comment]
lesigh, another build timeout

21:41:54 Build timed out (after 20 minutes). Marking the build as aborted.

**Comment by prometheanfire** [comment]
and the other build timed out too

21:58:00 Build timed out (after 20 minutes). Marking the build as aborted.

**Comment by prometheanfire** [comment]
recheck

**Comment by prometheanfire** [comment]
(it did get to maas though, so I think we are fine)

    21:38:00 + run_ansible verify-maas.yml

**Comment by mancdaz** [comment]
:+1:  fix released in setuptools upstream. This was only a temporary fix, so happy to remove it now.

**Comment by prometheanfire** [comment]
recheck

**Comment by d34dh0r53** [comment]
:+1:

**Pull request merged**
