### PR TITLE
Update openstack-ansible stable/mitaka SHA

### PR DESCRIPTION
**Pull request by git-harry**
This commit updates the openstack-ansible submodule to the tip of the
branch stable/mitaka. This change pulls in fixes for the following known
issues:

- https://github.com/rcbops/u-suk-dev/issues/402
- https://github.com/rcbops/u-suk-dev/issues/404
- https://github.com/rcbops/rpc-openstack/issues/1437

Connected https://github.com/rcbops/u-suk-dev/issues/468

(cherry picked from commit 9f53427b8feec0f2faf1cb1e1581aaaf9ea6fb11)

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-c656c54ea9/docs/private-cloud/release-notes/v13/)

**Comment by git-harry** [comment]
recheck_ceph

**Comment by alextricity25** [comment]
:+1:

**Comment by mattt416** [comment]
👍

**Pull request merged**
