### PR TITLE
Updated spice-html5 git repository URL

### PR DESCRIPTION
**Pull request by cloudnull**
Signed-off-by: Kevin Carter <kevin.carter@rackspace.com>

### CODE REVIEW

**Comment by mattt416** [comment]
Seeing this in the `artifact` job:

```
[Ubuntu 14.04.5 LTS prepared for RPC deployment] TASK [ansible-hardening : Check audit package contents for alterations with rpm (for V-38637)] ***
[Ubuntu 14.04.5 LTS prepared for RPC deployment] skipping: [aio1] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
[git] failed: [localhost] (item={u'name': u'spice-html5', u'project_group': u'nova_console', u'fragment': None, u'url': u'https://github.com/SPICE/spice-html5', u'version': u'54cc41299bea8cd681ed0262735e0fd821cd774a', u'original': u'git+https://github.com/SPICE/spice-html5@54cc41299bea8cd681ed0262735e0fd821cd774a#egg=spice_html5&gitname=spice-html5&projectgroup=nova_console', u'egg_name': u'spice_html5'}) => {"cmd": "/usr/bin/git ls-remote https://github.com/SPICE/spice-html5 -h refs/heads/54cc41299bea8cd681ed0262735e0fd821cd774a", "failed": true, "item": {"egg_name": "spice_html5", "fragment": null, "name": "spice-html5", "original": "git+https://github.com/SPICE/spice-html5@54cc41299bea8cd681ed0262735e0fd821cd774a#egg=spice_html5&gitname=spice-html5&projectgroup=nova_console", "project_group": "nova_console", "url": "https://github.com/SPICE/spice-html5", "version": "54cc41299bea8cd681ed0262735e0fd821cd774a"}, "msg": "fatal: could not read Username for 'https://github.com': No such device or address", "rc": 128, "stderr": "fatal: could not read Username for 'https://github.com': No such device or address\n", "stdout": "", "stdout_lines": []}
```

and:

```
[Ubuntu 16.04.2 LTS prepared for RPC deployment] failed: [aio1_repo_container-9362cba9] (item={u'_ansible_parsed': True, u'_ansible_no_log': False, u'ansible_job_id': u'643132810048.7130', u'started': 1, u'_ansible_item_result': True, u'item': {u'name': u'spice-html5', u'project_group': u'nova_console', u'fragment': None, u'url': u'https://github.com/SPICE/spice-html5', u'version': u'54cc41299bea8cd681ed0262735e0fd821cd774a', u'original': u'git+https://github.com/SPICE/spice-html5@54cc41299bea8cd681ed0262735e0fd821cd774a#egg=spice_html5&gitname=spice-html5&projectgroup=nova_console', u'egg_name': u'spice_html5'}, u'finished': 0, u'results_file': u'/var/www/.ansible_async/643132810048.7130'}) => {"ansible_job_id": "643132810048.7130", "changed": false, "cmd": "/usr/bin/git ls-remote https://github.com/SPICE/spice-html5 -h refs/heads/54cc41299bea8cd681ed0262735e0fd821cd774a", "failed": true, "finished": 1, "item": {"ansible_job_id": "643132810048.7130", "finished": 0, "item": {"egg_name": "spice_html5", "fragment": null, "name": "spice-html5", "original": "git+https://github.com/SPICE/spice-html5@54cc41299bea8cd681ed0262735e0fd821cd774a#egg=spice_html5&gitname=spice-html5&projectgroup=nova_console", "project_group": "nova_console", "url": "https://github.com/SPICE/spice-html5", "version": "54cc41299bea8cd681ed0262735e0fd821cd774a"}, "results_file": "/var/www/.ansible_async/643132810048.7130", "started": 1}, "msg": "fatal: could not read Username for 'https://github.com': No such device or address", "rc": 128, "stderr": "fatal: could not read Username for 'https://github.com': No such device or address\n", "stdout": "", "stdout_lines": []}
```

**Comment by mattt416** [comment]
@cloudnull do we have to override this in https://github.com/rcbops/rpc-openstack/blob/newton/scripts/artifacts-building/user_rcbops_artifacts_building.yml also?

I'm not sure what the fix for the `release` job is since that uses straight upstream, we'll probably need to find a way to wrangle that so it doesn't use the old repo location.

**Comment by mattt416** [comment]
osa_differ /rpc_differ have a `  --skip-projects` option, can we try skipping spice-html5?

**Comment by mendeni** [comment]
@mattt416 @odyssey4me Could you review/comment @cloudnull's updated change to user variables?

**Comment by mattt416** [comment]
@odyssey4me Tto get artifacts to build, could we just pass in `-e nova_spicehtml5_git_repo=https://gitlab.freedesktop.org/spice/spice-html5` [here](https://github.com/rcbops/rpc-openstack/blob/newton/scripts/artifacts-building/git/build-git-artifacts.sh#L53)?

I had a look at the release job to see if we could pre-clone https://gitlab.freedesktop.org/spice/spice-html5 to /root/.osa-differ/spicehtml5, but it didn't seem to work. :(

I'm starting to wonder if it'd be cleaner to just fork openstack-ansible?

**Comment by odyssey4me** [comment]
@mattt416 The py_pkgs lookup only inspects the ``user_*.yml`` overrides files in ``/etc/openstack_deploy``, so passing ``-e`` won't work. And ``osa-differ`` does not understand overrides at all, so yes - the simplest and fastest approach here is to fork the ``openstack-ansible`` repo and adjust it accordingly, then change our submodule to use it.

**Comment by odyssey4me** [comment]
Closed as this is superseded by https://github.com/rcbops/rpc-openstack/pull/3051 which implements the fork as agreed.

**Pull request closed without merging**
