### PR TITLE
RO-3972 Update pike dependencies

### PR DESCRIPTION
**Pull request by rpc-jenkins-svc**
This change is the result of running gating/update_dependencies/*
  See update_dependencies in https://rpc-openstack.atlassian.net/wiki/spaces/RE/pages/19005457/RE+for+Projects for more details.

Issue: [RO-3972](https://rpc-openstack.atlassian.net/browse/RO-3972)

### CODE REVIEW

**Comment by odyssey4me** [comment]
recheck_cit_all

**Comment by mattt416** [comment]
@odyssey4me What's the deal w/ the release failure?

```
03:03:40 Traceback (most recent call last):
03:03:40   File "/usr/local/bin/rpc-differ", line 11, in <module>
03:03:40     sys.exit(run_rpc_differ())
03:03:40   File "/usr/local/lib/python2.7/dist-packages/rpc_differ/rpc_differ.py", line 361, in run_rpc_differ
03:03:40     rpc_product=args.rpc_product)
03:03:40   File "/usr/local/lib/python2.7/dist-packages/rpc_differ/rpc_differ.py", line 165, in get_osa_commit
03:03:40     return repo.submodules['openstack-ansible'].hexsha
03:03:40   File "/usr/local/lib/python2.7/dist-packages/git/repo/base.py", line 317, in submodules
03:03:40     return Submodule.list_items(self)
03:03:40   File "/usr/local/lib/python2.7/dist-packages/git/util.py", line 937, in list_items
03:03:40     out_list.extend(cls.iter_items(repo, *args, **kwargs))
03:03:40   File "/usr/local/lib/python2.7/dist-packages/git/objects/submodule/base.py", line 1191, in iter_items
03:03:40     "Gitmodule path %r did not exist in revision of parent commit %s" % (p, parent_commit))
03:03:40 git.exc.InvalidGitRepositoryError: Gitmodule path u'scripts/artifacts-building' did not exist in revision of parent commit HEAD
```

**Comment by odyssey4me** [comment]
@mattt416 https://rpc-openstack.atlassian.net/browse/RE-1190 (also see related cards)

**Comment by mattt416** [comment]
@odyssey4me yeah, this wasn't changing last week so something's changed.  Was https://github.com/rcbops/rpc-openstack/blob/pike/.gitmodules left behind by mistake?

**Comment by odyssey4me** [comment]
@mattt416 Dammit, I thought that was included. Yeah - I guess that needs removal.

**Comment by mattt416** [comment]
@odyssey4me I'll get it removed, also just realised that PR to remove this stuff was merged on Friday. That'd explain it.  :)

**Comment by odyssey4me** [comment]
recheck_cit_release

**Comment by odyssey4me** [comment]
Please see https://github.com/rcbops/rpc_differ/pull/17 for the rpc-differ fix which will make the release job work.

**Comment by d34dh0r53** [comment]
recheck_cit_release

**Comment by odyssey4me** [comment]
recheck_cit_release

**Comment by odyssey4me** [comment]
Given the release test is failing due to a known failure which is being worked on, force merging this.

**Pull request merged**
