### PR TITLE
Fix release notes build failure and PR preview

### PR DESCRIPTION
**Pull request by darrenchan**
1. Moved deconst-requirements.txt and _deconst.json files to the source
directory
2. Update content ID in  _deconst.json
3. Change to single page template build in conf.py
4. Add oslosphinx to deconst-requirements.txt

Addresses https://github.com/rackerlabs/nexus-control/issues/555

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/staging.horse/build-0b5a286b96/docs/private-cloud/rpc/release-notes/)

**Comment by darrenchan** [comment]
@meker12 it works! :)

**Comment by darrenchan** [comment]
@git-harry @b3rnard0 can we merge this PR? Thanks!

**Comment by sigmavirus24** [comment]
@git-harry should this have a swimlane? It's in needs-review

**Comment by hughsaunders** [comment]
👍  LGTM

**Comment by sigmavirus24** [comment]
👍 Thanks @darrenchan

**Pull request merged**
