### PR TITLE
Creating beaver pid directory when missing

### PR DESCRIPTION
**Pull request by BjoernT**
#564 Fixing Beaver PID handling
- Creating Beaver PID directory when missing
- Cleaning Beaver PID after shutting it down

### CODE REVIEW

**Comment by mancdaz** [comment]
Hi @BjoernT - thanks for the PR.

Would you mind removing the github issue number from the commit message title, and perhaps add an independent description of the bug being fixed in the commit message? This makes it easier to see what's changed when parsing the commit history.

Thanks!

**Comment by BjoernT** [comment]
@mancdaz That's fine by me i'll change it later

**Comment by BjoernT** [comment]
Updated beaver_pre_install.yml to remove the pid dir

**Comment by prometheanfire** [comment]
premature backport, please wait til merged with master then cherrypick

:-1:

**Comment by d34dh0r53** [comment]
:+1: straightforward backport

**Comment by git-harry** [comment]
@BjoernT please use git cherry-pick -x for this backport

**Comment by d34dh0r53** [comment]
@BjoernT what @git-harry said :)

**Comment by hughsaunders** [comment]
Opened #657 to continue this PR, as its been >2 weeks since a cherry-pick -x was requested.

**Pull request closed without merging**
