### PR TITLE
UG-646 Handle config within RPCO [Backport: Newton-14.1]

### PR DESCRIPTION
**Pull request by hughsaunders**
Currently the rpc-gating scripts drop some RPCO config overrides,
some are always added, others are scenario dependant. This is
problematic as those overrides may not work for every branch of RPCO
and it creates a tight and inflexible coupling between RPCO and gating.

This commit adds the overrides that gating currently drops into
the boostrap-aio.yml playbook. These overrides are conditionally
applied based on environment variables that indicate the type of
build that is required.

This duplicates gating functionality so must not be merged until it's
counterpart in rpc-gating is merged:
  https://github.com/rcbops/rpc-gating/pull/266

(cherry picked from commit 4435dda995de74894017ba48eeced19a3ebe4715)

Issue: [UG-646](https://rpc-openstack.atlassian.net/browse/UG-646)

### CODE REVIEW

**Comment by mattt416** [comment]
recheck_cit_trusty_deploy_swift

**Comment by mattt416** [comment]
recheck_cit_trusty_deploy_swift

**Comment by hughsaunders** [comment]
recheck_cit_trusty_deploy_swift failed on tempest server basic ops.

**Comment by hughsaunders** [comment]
recheck_cit_trusty_deploy_swift failed on tempest server basic ops.

**Comment by hughsaunders** [comment]
Good spot @mattt416, removed.

**Comment by hughsaunders** [comment]
recheck_cit_trusty_leapfrogupgrade_swift

**Comment by odyssey4me** [comment]
recheck_cit_trusty_leapfrogupgrade_swift

**Comment by hughsaunders** [comment]
Changes should be resubmitted to the newton branch

**Pull request closed without merging**
