### PR TITLE
Update master SHA to HEAD of liberty.

### PR DESCRIPTION
**Pull request by d34dh0r53**
Update master SHA to HEAD of liberty as of 04-04-2016.  Includes
typo fix and MySQL retry logic.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
:+1: pending gate success

**Comment by d34dh0r53** [comment]
recheck_upgrade

**Comment by prometheanfire** [comment]
:+1: pending gate

**Comment by prometheanfire** [comment]
recheck_upgrade

**Comment by mancdaz** [comment]
:+1:

**Pull request merged**
