### PR TITLE
RE-87 Implement pre_merge_test hook (master)

### PR DESCRIPTION
**Pull request by odyssey4me**
This patch implements the RPC Release Engineering pre_merge_hook
as documented in [1] making use of the existing job definition
in the rpc-gating repo.

For the most part it intentionally does not change how the job
is executed - it is meant to be a simple transfer of all logic
from rpc-gating into the rpc-openstack repository so that the
RPC-O team can own the entire test execution in a branched
repository.

The Jenkinsfile is removed as it is unused.

The job which uses this hook is defined in https://github.com/rcbops/rpc-gating/pull/462

[1] https://rpc-openstack.atlassian.net/wiki/spaces/RE/pages/19005457/RE+for+Projects

Issue: [RE-87](https://rpc-openstack.atlassian.net/browse/RE-87)

Issue: [RLM-232](https://rpc-openstack.atlassian.net/browse/RLM-232)

### CODE REVIEW

**Comment by odyssey4me** [comment]
recheck_cit_all

**Comment by odyssey4me** [comment]
recheck_cit_xenial_swift_deploy

**Comment by odyssey4me** [comment]
I moved the kibana-selenium venv prep into the 'pre' stage, then also implemented the workaround for https://github.com/pypa/virtualenv/issues/1029 as the test hit that issue.

**Comment by duaneking** [comment]
I just had a build fail this morning due to this issue.. may I ask for an ETA of this fix?

**Comment by odyssey4me** [comment]
@duaneking Which issue would that be? If you're referring to https://github.com/pypa/virtualenv/issues/1029 then I'd suggest that you address it there. A workaround is also suggested in the comments.

**Comment by antonym** [comment]
recheck_cit_xenial_deploy_swift

**Comment by antonym** [comment]
recheck_cit_xenial_swift_deploy

**Comment by odyssey4me** [comment]
xenial-deploy-swift (existing test)failure:

```

root: ERROR: Setup failed... Message: 
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/RPC-AIO_master-xenial-deploy-swift-pr/kibana-selenium/testrepo/kibana/kibana.py", line 71, in setUp
    ec.title_contains("Home dashboard"))
  File "/var/lib/jenkins/workspace/RPC-AIO_master-xenial-deploy-swift-pr/kibana-selenium/.venv/local/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
TimeoutException: Message: 

--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
XML: /var/lib/jenkins/workspace/RPC-AIO_master-xenial-deploy-swift-pr/kibana-selenium/nosetests.xml
----------------------------------------------------------------------
Ran 2 tests in 79.173s

FAILED (errors=2)
script returned exit code 1
```

xenial_swift_deploy (new test) failure looks genuine:

```
+ export 'PASSWORD=/etc/openstack_deploy/user_rpco_secrets.yml:kibana_password: secrete'
+ PASSWORD='/etc/openstack_deploy/user_rpco_secrets.yml:kibana_password: secrete'
+ python conf-gen.py --secure --password /etc/openstack_deploy/user_rpco_secrets.yml:kibana_password: secrete --vip-file /etc/openstack_deploy/openstack_user_config.yml
usage: conf-gen.py [-h] [--password-file PASSWORD_FILE] [--vip-file VIP_FILE]
                   [--password PASSWORD] [--vip VIP] [--secure]
conf-gen.py: error: unrecognized arguments: secrete
```

**Comment by odyssey4me** [comment]
I corrected the extraction of the password for Kibana for the xenial_swift_deploy test.

**Comment by odyssey4me** [comment]
Both tests are now failing with the same result which is unrelated to this PR:

```
root: ERROR: Setup failed... Message: 
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/RPC-AIO_master-xenial-deploy-swift-pr/kibana-selenium/testrepo/kibana/kibana.py", line 71, in setUp
    ec.title_contains("Home dashboard"))
  File "/var/lib/jenkins/workspace/RPC-AIO_master-xenial-deploy-swift-pr/kibana-selenium/.venv/local/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
TimeoutException: Message: 
```

**Comment by odyssey4me** [comment]
The ``xenial_swift_deploy`` test result was executed using the adjusted jobs from https://github.com/rcbops/rpc-gating/pull/462 to show that this PR delivers a like-for-like test set.

**Comment by odyssey4me** [comment]
recheck_cit_xenial_deploy_swift - perhaps not using telegraf any more will result in a successful test

**Comment by odyssey4me** [comment]
As noted in https://rpc-openstack.atlassian.net/browse/RO-2781 it appears that this issue has been present since at least 29 Sep 2017.

**Comment by odyssey4me** [comment]
Blocked on https://rpc-openstack.atlassian.net/browse/RO-2781

**Comment by cloudnull** [comment]
Moving this forward. ATM Kibana tests are blocking this change and in order to move forward we're going to be disabling them until we have a maintainer for our ELK stack.

**Pull request merged**
