### PR TITLE
Add bash completion to openstack clients 

### PR DESCRIPTION
**Pull request by Alfano93**
Adds bash completion to: 
  
  Cinder
  Glance
  Heat
  Keystone
  Neutron
  Nova

All needed packages for bash completion to work have been added to the rpc_support playbooks. 

Closes-Bug:#1465723

### CODE REVIEW

**Comment by claco** [comment]
Could probably just squash these into 1. But :+1: otherwise. Cool!

**Comment by BjoernT** [comment]
Please install it on the infra nodes as well, as we run most commands from these hosts.
Additionally the neutron completion should be installed inside the neutron agents container

**Comment by nrb** [comment]
@BjoernT Is there any reason we shouldn't just remove the `when:` line on the include and install these everywhere?

**Comment by odyssey4me** [comment]
I'm not fond of the idea of carrying the templates, forcing us to update them whenever a project releases an update. Are these files not already in the source we checkout, or located in the installed wheel? If there's a way that we can pull them from a known and consistent location then we should ideally try to do so.

**Comment by BjoernT** [comment]
@odyssey4me Those are generic bash scripts and not likely going to change from Juno to Kilo etc, in fact not at all. The only upcoming change is once the openstack client takes over and all the other python clients die. I don't see that happening in the near future.

@nrb Not really but I prefer to prevent clutter when possible and not installing it everywhere.

**Comment by prometheanfire** [comment]
generally in favour of this, but we need an issue to attach it to and to possibly track kilo backports on

**Comment by nrb** [comment]
+1 to prometheanfire's comment on an issue. I think this originated from a LaunchPad request.

It's also likely this will get backported to Juno.

**Comment by Alfano93** [comment]
Would it be safe to close this request, and resubmit after some more TLC has been given to this?

**Comment by prometheanfire** [comment]
I think it's fine, if as was said this will not change much if at all.

we just need a tracking issue

**Comment by git-harry** [comment]
@Alfano93 I'd like to look at getting this merged in. To do that the pull request could do with some attention. I'd like you to take a look at the following points:
- create an issue in the repo and reference this pull request against it
- rebase the commits
- squash the commits down to one commit
- remove the reference to the launchpad bug from the commit message
- all the templates don't look like they have any jinja code in them, if that's the case I think it would be better to use the copy module.

**Comment by git-harry** [comment]
Replaced by https://github.com/rcbops/rpc-openstack/pull/470

**Pull request closed without merging**
