### PR TITLE
force removal of aodh and ceilometer conf files

### PR DESCRIPTION
**Pull request by prometheanfire**
exits 0 when the file is not found, which is just fine here

Fixes https://github.com/rcbops/rpc-openstack/issues/842

(cherry picked from commit 0dd4f9ff80fe3fa93deb5c98f8fad1fb29bcb6a3)

### CODE REVIEW

**Comment by prometheanfire** [comment]
recheck - jenkins needs a kick for PRs to branches...

**Comment by tomc603** [comment]
A simple fix. :+1:

**Comment by byronmccollum** [comment]
Passes my tests...

**Comment by prometheanfire** [comment]
fixes #842

**Comment by nrb** [comment]
-1;

Not sure we actually need this - if the conf.d files/groups are not defined, they shouldn't be created. So removing these files actually creates drift between rpc-openstack/OSA that's not actually needed.

**Comment by nrb** [comment]
+1 for this backport.

**Comment by prometheanfire** [comment]
soo, I'm not hitting the merge button because it's my commit.  This has two :+1: is anyone going to hit it?

**Comment by tomc603** [comment]
Merged.


--
Tom Cameron



________________________________

**Pull request merged**
