### PR TITLE
ISU-103 Update OSA SHA

### PR DESCRIPTION
**Pull request by odyssey4me**
Update the OSA SHA for Ocata.

Issue: [AR-206](https://rpc-openstack.atlassian.net/browse/AR-206)

### CODE REVIEW

**Comment by evrardjp** [comment]
@odyssey4me What do you think of rolling back the feature to auto publish apt artifacts when the artifacts for that tag don't exist? Maybe we need to serialize the apt git python and containers into one pipeline back too, including for PRs.
Else, we'd probably need to manually build this pipeline all the time manually...

**Comment by evrardjp** [comment]
That would mean changing:
https://github.com/rcbops/rpc-gating/blob/5b5c589205f6c33805ea7e840901bec29887d73e/rpc_jobs/rpc_artifact_build.yml#L37
and
https://github.com/rcbops/rpc-gating/blob/5b5c589205f6c33805ea7e840901bec29887d73e/rpc_jobs/rpc_artifact_build.yml#L77

Because the scripts now have the detection themselves, they will only push if REPLACE_ARTIFACTS is forced to yes or if there is no artifacts already.

We could just change the apt behavior, and it removes a few extra vars in gating.

**Comment by odyssey4me** [comment]
@evrardjp I don't understand what you're suggesting, or why you're suggesting it.

The CIT/artifact-xenial-Container job failed with this:

```
TASK [ceph_client : include] ***************************************************
Friday 21 July 2017  14:24:47 +0000 (0:00:00.007)       0:04:48.991 *********** 
ERROR! Unexpected Exception: list index out of range
to see the full traceback, use -vvv
```

**Comment by evrardjp** [comment]
@odyssey4me Never mind. It's not important to this PR.

**Comment by odyssey4me** [comment]
OK, so here's the full traceback:

```
TASK [ceph_client : include] ***************************************************
task path: /etc/ansible/roles/ceph_client/tasks/ceph_all.yml:52
Thursday 27 July 2017  10:11:44 +0000 (0:00:00.006)       0:04:41.188 *********
ERROR! Unexpected Exception: list index out of range
the full traceback was:

Traceback (most recent call last):
  File "/opt/ansible-runtime/bin/ansible-playbook", line 103, in <module>
    exit_code = cli.run()
  File "/opt/ansible-runtime/local/lib/python2.7/site-packages/ansible/cli/playbook.py", line 159, in run
    results = pbex.run()
  File "/opt/ansible-runtime/local/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 154, in run
    result = self._tqm.run(play=play)
  File "/opt/ansible-runtime/local/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 282, in run
    play_return = strategy.run(iterator, play_context)
  File "/opt/ansible-runtime/local/lib/python2.7/site-packages/ansible/plugins/strategy/linear.py", line 234, in run
    task_vars = self._variable_manager.get_vars(loader=self._loader, play=iterator._play, host=host, task=task)
  File "/opt/ansible-runtime/local/lib/python2.7/site-packages/ansible/vars/__init__.py", line 373, in get_vars
    all_vars['ansible_delegated_vars'] = self._get_delegated_vars(loader, play, task, all_vars)
  File "/opt/ansible-runtime/local/lib/python2.7/site-packages/ansible/vars/__init__.py", line 448, in _get_delegated_vars
    items = lookup_loader.get(task.loop, loader=loader, templar=templar).run(terms=loop_terms, variables=vars_copy)
  File "/opt/ansible-runtime/local/lib/python2.7/site-packages/ansible/plugins/lookup/random_choice.py", line 38, in run
    return [ random.choice(terms) ]
  File "/usr/lib/python2.7/random.py", line 275, in choice
    return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
IndexError: list index out of range
```

That means that the error is likely coming from https://github.com/openstack/openstack-ansible-os_nova/blob/31500234b0f8f77f2b0a676b0018413c6433539c/tasks/main.yml#L114-L129 where the with_random_choice lookup is used.

**Comment by evrardjp** [comment]
We need another vote...

**Pull request merged**
