### PR TITLE
Added recognition of Openmanage v8.3.0 and v8.4.0

### PR DESCRIPTION
**Pull request by xeregin**
This will allow the hardware checks to report correctly in Dell labs with Openmanage version 8.3.0

### CODE REVIEW

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/staging.horse/build-25cfd856e8/docs/private-cloud/release-notes/).

**Comment by hughsaunders** [comment]
recheck_all

**Comment by BjoernT** [comment]
@xeregin and 8.4.0 came ..... so we need look at that version now too

**Comment by alextricity25** [comment]
Hi, @xeregin. Could you please submit an issue card for this PR here: https://github.com/rcbops/rpc-openstack/issues.
If you have already submitted one, please link this PR to that issue by adding this line in the description:
"Connects #<PR Number>"
Thank you!

**Comment by alextricity25** [comment]
recheck_all

**Comment by major** [comment]
recheck_ceph

Looks like an unrelated failure:
```
16:16:29 Captured traceback:
16:16:29 ~~~~~~~~~~~~~~~~~~~
16:16:29     Traceback (most recent call last):
16:16:29       File "/opt/tempest_untagged/tempest/scenario/manager.py", line 108, in delete_wrapper
16:16:29         delete_thing(*args, **kwargs)
16:16:29       File "/opt/tempest_untagged/tempest/lib/services/compute/floating_ips_client.py", line 62, in delete_floating_ip
16:16:29         resp, body = self.delete(url)
16:16:29       File "/opt/tempest_untagged/tempest/lib/common/rest_client.py", line 290, in delete
16:16:29         return self.request('DELETE', url, extra_headers, headers, body)
16:16:29       File "/opt/tempest_untagged/tempest/lib/services/compute/base_compute_client.py", line 53, in request
16:16:29         method, url, extra_headers, headers, body)
16:16:29       File "/opt/tempest_untagged/tempest/lib/common/rest_client.py", line 645, in request
16:16:29         resp, resp_body)
16:16:29       File "/opt/tempest_untagged/tempest/lib/common/rest_client.py", line 764, in _error_checker
16:16:29         message=message)
16:16:29     tempest.lib.exceptions.ServerFault: Got server fault
16:16:29     Details: Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.
16:16:29     <class 'nova.exception.InstanceInfoCacheNotFound'>
```

**Comment by major** [comment]
recheck_ceph

**Comment by BjoernT** [comment]
👎  8.3.0 is already outdated, current we install/upgrade to  8.4.0 when updating hosts. We may as well just check for version 8.x ?

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/staging.horse/build-0e81b8e9ac/docs/private-cloud/release-notes/)

**Comment by major** [comment]
@BjoernT Let's get this merged for now to get us over the hump and we can revisit adding a regex there instead.

**Comment by d34dh0r53** [comment]
I agree with @major, let's get this out of the way.

**Comment by xeregin** [comment]
Was v8.4.0 verified to have the same output formatting? Is every version is v8.x guaranteed to have the same formatting?

**Comment by BjoernT** [comment]
I did spot test it and the output format is the same. I would assume that the output format is the same within the same major version but I would just rely on QE here to make sure the alarms are clear after a release

**Pull request merged**
