### PR TITLE
Update OSA SHA to tip of liberty branch

### PR DESCRIPTION
**Pull request by git-harry**
This commit pulls in the latest upstream fixes for Liberty in
preparation for the release of r12.2.6.

Connected https://github.com/rcbops/u-suk-dev/issues/472

### CODE REVIEW

**Comment by major** [comment]
It failed on a neutron migration, but there weren't any relevant neutron patches that would have had an effect there (that I can find): https://gist.github.com/anonymous/075cca50bebe608855d0a0bc091e67be

**Comment by major** [comment]
recheck_upgrade

**Comment by git-harry** [comment]
@major the check failed because of an upstream bug with nova migrations, see https://github.com/rcbops/u-suk-dev/issues/476 for details, and so won't pass until the SHA is updated with the fix.

**Comment by git-harry** [comment]
recheck_upgrade mirror failure

**Comment by git-harry** [comment]
recheck_upgrade

**Comment by hughsaunders** [comment]
👍

**Comment by tomc603** [comment]
SHA matches Liberty tip. 👍

**Pull request merged**
