### PR TITLE
RE-155 Add rpco apt source to lxc base cache

### PR DESCRIPTION
**Pull request by odyssey4me**
Prior to https://github.com/rcbops/rpc-openstack/commit/70b86f6a1759f92ef789e3d7028bb3e75ad6e722 the rpco.list file was copied into the container cache
and worked fine because the deploy node and lxc host were the same.
With that patch, this no longer happens and the cache prep dies.

In order for the lxc cache prep process to make use
of the extra rpco apt source we need to ensure that
the repo source file is copied into the cache prior
to doing any package actions. This patch ensures
that the repo config is there.

The OSA SHA is also updated to ensure that the
unbound variable bug is fixed when installing pip.
ref: https://review.openstack.org/489191

Issue: [RE-155](https://rpc-openstack.atlassian.net/browse/RE-155)

Issue: [RE-174](https://rpc-openstack.atlassian.net/browse/RE-174)

Issue: [RE-173](https://rpc-openstack.atlassian.net/browse/RE-173)

### CODE REVIEW

**Comment by odyssey4me** [comment]
Travis tests will fail until https://github.com/rcbops/rpc-openstack/pull/2449 merges.

**Comment by cjloader** [comment]
Version '2.4.1' for 'elasticsearch' was not found -- CIT/xenial-deploy-swift

**Comment by odyssey4me** [comment]
Alright, I've rebuild the apt artifacts for master based on this branch, so the ELK stack will hopefully deploy now.

**Comment by odyssey4me** [comment]
New error:

```
TASK [kibana : Deploy Kibana configuration files] ******************************
Thursday 03 August 2017 10:44:11 +0000 (0:00:00.345) 0:03:13.893 ******* 
fatal: [ramxdsp-275-9505_kibana_container-cd9f9202]: FAILED! =>
{"changed": true, "failed": true, "msg": "Destination directory /opt/kibana/config does not exist"}
```

I'm building an instance to see what the issue is - I suspect that a newer version of kibana is being installed which doesn't use the same folder structure. I'll try to verify that, then figure out a patch to get it working.

**Comment by odyssey4me** [comment]
Confirmed that kibana 5.1.1 is being deployed, so we'll have to work around this.

**Comment by odyssey4me** [comment]
The artifact jobs are currently expected to fail. This PR does require the xenial-deploy-swift job to pass though.

**Comment by odyssey4me** [comment]
recheck_cit_artifact

**Comment by odyssey4me** [comment]
recheck_cit_artifact

**Comment by odyssey4me** [comment]
The selenium tests are failing. @mkam do you know much about these tests - can you help to diagnose the failure?

**Comment by odyssey4me** [comment]
I have validated that the ELK stack everything is working as expected by logging into kibana and seeing events, graphs, etc. So it appears that this may be an issue with the selenium tests themselves.

**Comment by mkam** [comment]
@odyssey4me I haven't seen that particular issue before, but selenium can be finicky, especially when there's a chain of actions (like clicking dropdowns and waiting for them to load and then verifying that the element is there). A retry might be enough to get a passing run, but we could also try to put in retries to the tests too.

**Comment by mkam** [comment]
recheck_cit_xenial_deploy_swift

**Comment by odyssey4me** [comment]
@mkam OK, we'll have to figure it out because without this patch master is broken. So either we need to update the selenium test, or we need to remove it. Obviously the latter is less desirable.

**Pull request merged**
