### PR TITLE
Update openstack-ansible stable/mitaka SHA

### PR DESCRIPTION
**Pull request by git-harry**
This commit updates the openstack-ansible submodule to the tip of the
branch stable/mitaka. This change pulls in fixes for the following known
issues:

- https://github.com/rcbops/u-suk-dev/issues/402
- https://github.com/rcbops/u-suk-dev/issues/404
- https://github.com/rcbops/rpc-openstack/issues/1437

Connected https://github.com/rcbops/u-suk-dev/issues/468

(cherry picked from commit 9f53427b8feec0f2faf1cb1e1581aaaf9ea6fb11)

### CODE REVIEW

**Comment by git-harry** [comment]
recheck_upgrade

**Comment by claco** [comment]
recheck_upgrade

**Comment by alextricity25** [comment]
Before running the playbook:
```
ansible galera_all -m shell -a "pip freeze | grep holland"
cantu-testup-ceph18_galera_container-65073c04 | success | rc=0 >>
holland==1.0.10
holland.backup.xtrabackup===1.0.10dev-r0
holland.lib.common===1.0.10dev-r0
holland.lib.mysql===1.0.10dev-r0Warning: cannot find svn location for holland.backup.xtrabackup===1.0.10dev-r0
Warning: cannot find svn location for holland.lib.mysql===1.0.10dev-r0
Warning: cannot find svn location for holland.lib.common===1.0.10dev-r0

cantu-testup-ceph18_galera_container-4e45d7ea | success | rc=0 >>
holland==1.0.10
holland.backup.xtrabackup===1.0.10dev-r0
holland.lib.common===1.0.10dev-r0
holland.lib.mysql===1.0.10dev-r0Warning: cannot find svn location for holland.backup.xtrabackup===1.0.10dev-r0
Warning: cannot find svn location for holland.lib.mysql===1.0.10dev-r0
Warning: cannot find svn location for holland.lib.common===1.0.10dev-r0

cantu-testup-ceph18_galera_container-99a4f544 | success | rc=0 >>
holland==1.0.10
holland.backup.xtrabackup===1.0.10dev-r0
holland.lib.common===1.0.10dev-r0
holland.lib.mysql===1.0.10dev-r0Warning: cannot find svn location for holland.backup.xtrabackup===1.0.10dev-r0
Warning: cannot find svn location for holland.lib.mysql===1.0.10dev-r0
Warning: cannot find svn location for holland.lib.common===1.0.10dev-r0
```
After running it:
```
root@cantu-testup-ceph18:/opt/rpc-openstack/rpcd/playbooks# ansible galera_all -m shell -a "pip freeze | grep holland"
cantu-testup-ceph18_galera_container-99a4f544 | success | rc=0 >>
holland.backup.xtrabackup===1.0.10dev-r0Warning: cannot find svn location for holland.backup.xtrabackup===1.0.10dev-r0

cantu-testup-ceph18_galera_container-4e45d7ea | success | rc=0 >>
holland.backup.xtrabackup===1.0.10dev-r0Warning: cannot find svn location for holland.backup.xtrabackup===1.0.10dev-r0

cantu-testup-ceph18_galera_container-65073c04 | success | rc=0 >>
holland.backup.xtrabackup===1.0.10dev-r0Warning: cannot find svn location for holland.backup.xtrabackup===1.0.10dev-r0
```
Maybe we should also delete ``holland.backup.xtrabackup``?

**Comment by evrardjp** [comment]
This seem to properly include the osa sha bump which itself seems to contain the proper sha bump for neutron.

**Comment by evrardjp** [comment]
recheck_upgrade

**Comment by git-harry** [comment]
recheck_upgrade

**Comment by git-harry** [comment]
recheck_upgrade

**Comment by alextricity25** [comment]
This upgrade job failed on trying to verify maas checks and alarms. The ``retry`` and ``delay`` values for these tasks was decreased in an earlier patch set. Since they are now configurable, the right thing to do IMO would be to override their values to something higher for the upgrade jobs. In the meantime I'll do another recheck.
recheck_upgrade

**Comment by git-harry** [comment]
recheck_upgrade

**Comment by git-harry** [comment]
recheck_upgrade

**Comment by alextricity25** [comment]
I'm not exactly sure what is causing the MaaS alarms to stay in CRITICAL status on the upgrade job, but I'm currently looking into it.

**Comment by git-harry** [comment]
recheck_upgrade

**Pull request merged**
