### PR TITLE
Remove the patcher role and playbook

### PR DESCRIPTION
**Pull request by cloudnull**
This role has no purposes at this point. If we need to patch something
in OpenStack then we should do so using a fork. This brings clarity to
any patches that we may need in the future.

Signed-off-by: Kevin Carter <kevin.carter@rackspace.com>

### CODE REVIEW

**Comment by cloudnull** [comment]
recheck_cit_swift

**Comment by cloudnull** [comment]
recheck_cit_ceph

**Comment by odyssey4me** [comment]
The only time this was used IIRC was for the kilo release in order to patch nova.

**Comment by alextricity25** [comment]
I think it would be good to have a release note here saying that this is being deprecated.

**Pull request merged**
