### PR TITLE
Remove unrequired vars file include

### PR DESCRIPTION
**Pull request by andymcc**
Move the cinder_service_port to maas defaults and remove the vars file
include for cinder default vars.

Fixes: #534

### CODE REVIEW

**Comment by d34dh0r53** [comment]
:+1:

**Comment by prometheanfire** [comment]
:+1: needs rebase

**Comment by git-harry** [comment]
@andymcc there seem to be three different approaches to OpenStack service ports in the MaaS templates

- a variable with a specified default (cinder_service_port)
- a variable with an unspecified default (keystone_service_port)
- hardcoded in the template (everything else)

**Comment by andymcc** [comment]
@git-harry sure, which is why only the cinder vars file had been included, because they're not consistent - but I'm not too sure what you're recommending though - we can change it to be in line with the others, but then we are essentially changing functionality for something.

I've rebased and made a new PR https://github.com/rcbops/rpc-openstack/pull/582
Going to close this.

**Pull request closed without merging**
