### PR TITLE
Update OSA SHA.

### PR DESCRIPTION
**Pull request by d34dh0r53**
This updates the OSA SHA for `master` as of (`03-25-2016`).

Closes: #927
Closes: #925 
Closes: #897

### CODE REVIEW

**Comment by prometheanfire** [comment]
recheck_upgrade

**Comment by prometheanfire** [comment]
recheck_upgrade

    04:28:43 TASK: [rpc_maas | Zero entities with label {{ inventory_hostname }}{{ maas_fqdn_extension }} exist] *** 
    04:28:43 failed: [jrpcaioiad-431] => {"failed": true}
    04:28:43 msg: Zero entities with the label jrpcaioiad-431 exist. Entities should be created as part of the hardware provisioning process, if missing, please consult the internal documentation for associating one with the device.

**Comment by prometheanfire** [comment]
recheck_upgrade

verify_maas failed
    Rate limit has been reached (50000 operations in 24 hours)

**Comment by d34dh0r53** [comment]
recheck_upgrade

**Comment by d34dh0r53** [comment]
recheck_upgrade

**Comment by hughsaunders** [comment]
recheck_upgrade

**Comment by prometheanfire** [comment]
:+1:

**Comment by sigmavirus24** [comment]
:+1:

**Pull request merged**
