### PR TITLE
Update f5-monitor token parser to accept signed tokens.

### PR DESCRIPTION
**Pull request by dpham-rs**
Update f5-monitor token parser to accept signed tokens.
 * Changed default monitor behavior to no longer log for debugs.

Identical to pull request #628 which I closed prematurely.

### CODE REVIEW

**Comment by d34dh0r53** [comment]
Looks good, can you squash these commits though?

**Comment by sigmavirus24** [comment]
@dpham-rs if you want help squashing these commits, ping me via email and we can set up a vidyo call to go over this.

**Comment by sigmavirus24** [comment]
@d34dh0r53 this has been updated. Tests pass. I'm :+1:. Thoughts?

**Comment by Apsu** [comment]
Can one of the admins verify this patch?

**Comment by sigmavirus24** [comment]
@Apsu admins as in?

**Pull request closed without merging**
