### PR TITLE
Frank/liberty backport 742

### PR DESCRIPTION
**Pull request by Frank-ZhangXin**
Backport bug 742 patch to Liberty 12.2

Connects #742

### CODE REVIEW

**Comment by Frank-ZhangXin** [comment]
@git-harry Met conflicts when did liberty backport. Please point out where I did wrong, thanks!

**Comment by Frank-ZhangXin** [comment]
Sorry I choose wrong base and corrected it, thanks for attention.

**Comment by Frank-ZhangXin** [comment]
recheck_all

**Comment by git-harry** [comment]
recheck_upgrade

**Comment by git-harry** [comment]
recheck_upgrade unrelated tempest failures

**Comment by git-harry** [comment]
The commit message was missing the cherry pick line so I've updated the patch.

**Comment by tomc603** [comment]
👍 for backport

**Comment by Apsu** [comment]
Looks good to me 👍

**Pull request merged**
