### PR TITLE
Allow users to resume upgrade execution by using resume.sh wrapper

### PR DESCRIPTION
**Pull request by rackertom**
This update includes a wrapper script written by Evan which receives a list of commands to execute on stdin. If an error occurs while executing a step, the script informs the user and gives instructions for resuming.

Closes: #324

### CODE REVIEW

**Comment by Apsu** [comment]
Looks about right

**Comment by nrb** [comment]
Two small things that are mostly clerical - It'd be preferable to have this squashed, and also remove the issue number from the commit message.

The code looks good and makes sense to me, though.

**Comment by prometheanfire** [comment]
do we care about licensing?

**Comment by prometheanfire** [comment]
other then that and squashing I like it

**Comment by mancdaz** [comment]
sorry to come in late on this, but wouldn't it be possible to just have all this logic in the upgrade script and have a '--resume' flag that we pass if we need to resume? Otherwise we just have wrappers wrapping wrappers all over the place

resume.sh > upgrade.sh > run-upgrade.sh / deploy.sh

**Comment by nrb** [comment]
Yeah, the concept was that we make resume.sh generic enough to use elsewhere...however, I think if this isn't going to make 11.0.0, we should just move the logic to an Ansible playbook, at this point.

**Comment by rackertom** [comment]
The more I think about this approach, the less I like it. This method means we need to make changes in two places many times which we will mess up. In addition, there are tons of corner cases where this won't work (loops, if statements, etc.).

:-1:

**Comment by d34dh0r53** [comment]
Abandoned

**Pull request closed without merging**
