### PR TITLE
RO-4194 Update pike dependencies

### PR DESCRIPTION
**Pull request by rpc-jenkins-svc**
Automated dependency update pull request, see individual commits for details.

Issue: [RO-4194](https://rpc-openstack.atlassian.net/browse/RO-4194)

### CODE REVIEW

**Comment by d34dh0r53** [comment]
recheck_xenial_no_artifacts_swift_deploy

**Comment by d34dh0r53** [comment]
recheck_xenial_no_artifacts_swift_deploy

**Comment by chundu** [comment]
recheck_xenial_no_artifacts_swift_deploy

**Comment by d34dh0r53** [comment]
There is a issue upstream where both whitelist and blacklist cannot be specified in the same tempest run.  I'm looking into fixes but they will invalidate this pull so I'm going to close it.

**Pull request closed without merging**
