### PR TITLE
RI-314: add timeout for calls to apt

### PR DESCRIPTION
**Pull request by prometheanfire**
Adding the timeout to the only apt update or install call in our playbooks.

Issue: [RI-314](https://rpc-openstack.atlassian.net/browse/RI-314)

### CODE REVIEW

**Comment by prometheanfire** [comment]
recheck_xenial_no_artifacts_swift_deploy

**Comment by prometheanfire** [comment]
recheck_xenial_no_artifacts_swift_deploy

**Comment by prometheanfire** [comment]
recheck_all

**Comment by prometheanfire** [comment]
OK, I didn't think the apt-key reached out, but I guess it has to.

**Comment by mendeni** [comment]
Have all comments been sufficiently addressed @odyssey4me @cjloader ?

**Pull request merged**
