### PR TITLE
Add playbook to deploy elk

### PR DESCRIPTION
**Pull request by cloudnull**
The new elk tooling has been released and is now production ready. This
playbook ensures were using the new elk tooling for all of our
deployments automatically without additional user interactions.

Signed-off-by: Kevin Carter <kevin.carter@rackspace.com>
(cherry picked from commit 256c2b0fc9ac6133632471ae9ccdaa7c283b8b6d)

### CODE REVIEW

**Comment by cloudnull** [comment]
recheck_xenial_no_artifacts_swift_deploy

**Comment by cloudnull** [comment]
recheck_release

**Comment by prometheanfire** [comment]
recheck_release
recheck_xenial_no_artifacts_swift_deploy

**Comment by cloudnull** [comment]
recheck_xenial_no_artifacts_swift_deploy

**Pull request merged**
