### PR TITLE
Use trace instead of verbose

### PR DESCRIPTION
**Pull request by hughsaunders**
I find it much easier to undertsand bash's trace mode (-x) output
rather than verbose mode (-v).

### CODE REVIEW

**Comment by prometheanfire** [comment]
recheck_cit_release

**Comment by prometheanfire** [comment]
```bash
11:01:08 Traceback (most recent call last):
11:01:08   File "/usr/local/bin/rpc-differ", line 11, in <module>
11:01:08     sys.exit(run_rpc_differ())
11:01:08   File "/usr/local/lib/python2.7/dist-packages/rpc_differ/rpc_differ.py", line 331, in run_rpc_differ
11:01:08     ROLE_REQ_FILE
11:01:08   File "/usr/local/lib/python2.7/dist-packages/osa_differ/osa_differ.py", line 192, in get_roles
11:01:08     with open(filename, 'r') as f:
11:01:08 IOError: [Errno 2] No such file or directory: '/root/.osa-differ/rpc-openstack/ansible-role-requirements.yml'
```

**Comment by hughsaunders** [comment]
^ That looks like a @cloudnull issue.

**Comment by prometheanfire** [comment]
recheck_cit_release

**Comment by odyssey4me** [comment]
Looks like the release job is failing due to a known issue: https://rpc-openstack.atlassian.net/browse/RE-1190

**Pull request merged**
