### PR TITLE
RO-4034 Update OSA SHA for apt_repo fixes

### PR DESCRIPTION
**Pull request by odyssey4me**
In order to bring the fixes in to ensure that apt_repository
changes are properly applied and the cache updated, the OSA
SHA is being bumped. See the following bug for more details:

https://bugs.launchpad.net/openstack-ansible/+bug/1750656

Issue: [RO-4034](https://rpc-openstack.atlassian.net/browse/RO-4034)

### CODE REVIEW

**Comment by prometheanfire** [comment]
recheck_cit-artifact

**Comment by prometheanfire** [comment]
recheck_cit_artifact

**Comment by mattt416** [comment]
recheck_cit_artifact

**Comment by odyssey4me** [comment]
recheck_cit_artifact

**Pull request merged**
