### PR TITLE
MaaS: Swift time-sync validation and alarming

### PR DESCRIPTION
**Pull request by antonym**
Validating and alarming on time-sync with swift-recon.

Connects rcbops/u-suk-dev#1217

### CODE REVIEW

**Comment by antonym** [comment]
I set the time drift threshold to 30 seconds which is up for debate.  The swift-recon check will grab the metrics from the host that's the most out of sync and return that time.

Multinode output:

```
(swift-14.0.7) root@swift1:~/rpc-openstack/rpcd/playbooks/roles/rpc_maas/files/plugins# swift-recon --time
===============================================================================
--> Starting reconnaissance on 3 hosts (object)
===============================================================================
[2017-02-22 23:19:21] Checking time-sync
!! http://172.29.244.141:6000/recon/time current time is 2017-02-22 23:19:21, but remote is 2017-02-02 21:19:20, differs by 1735200.51 sec
!! http://172.29.244.142:6000/recon/time current time is 2017-02-22 23:19:21, but remote is 2017-02-16 21:19:23, differs by 525597.56 sec
1/3 hosts matched, 0 error[s] while checking hosts.
===============================================================================
(swift-14.0.7) root@swift1:~/rpc-openstack/rpcd/playbooks/roles/rpc_maas/files/plugins# ./swift-recon.py time
status okay
metric time_sync_total uint64 3
metric time_sync_errors uint64 0
metric time_sync_success uint64 1
metric time_sync_time_differ uint64 1735200
```

AIO Node Output:

```
(maas-r13.1.0rc1) root@rpc-openstack:/usr/lib/rackspace-monitoring-agent/plugins# swift-recon --time
===============================================================================
--> Starting reconnaissance on 1 hosts (object)
===============================================================================
[2017-02-22 23:30:56] Checking time-sync
1/1 hosts matched, 0 error[s] while checking hosts.
===============================================================================
(maas-r13.1.0rc1) root@rpc-openstack:/usr/lib/rackspace-monitoring-agent/plugins# ./swift-recon.py time
status okay
metric time_sync_total uint64 1
metric time_sync_errors uint64 0
metric time_sync_success uint64 1
metric time_sync_time_differ uint64 0
```

**Comment by antonym** [comment]
Digging into error:

```
 {"changed": false, "cmd": " . /openstack/venvs/maas-r13.1.0rc1/bin/activate\n  /opt/rpc-openstack/scripts/rpc-maas-tool.py verify-local", "delta": "0:00:30.897128", "end": "2017-02-23 01:56:34.571287", "failed": true, "failed_when_result": true, "rc": 1, "start": "2017-02-23 01:56:03.674159", "stderr": "", "stdout": "The following alarms have critera that could not be parsed: Alarm: swift_time_sync_check--jramcp-307-28022-swift-proxy-container-57fda26c Criteria: :set consecutiveCount=3\nif (metric[\"time_sync_time_differ\"] > 30) {\n    return new AlarmStatus(CRITICAL, \"Time synchonization error\");\n Error: Cannot parse alarm criteria: swift_time_sync_check--jramcp-307-28022-swift-proxy-container-57fda26c Error: parse error: failed to match 'endOfLine' at line=4, col=0, pos=135", "stdout_lines": ["The following alarms have critera that could not be parsed: Alarm: swift_time_sync_check--jramcp-307-28022-swift-proxy-container-57fda26c Criteria: :set consecutiveCount=3", "if (metric[\"time_sync_time_differ\"] > 30) {", "    return new AlarmStatus(CRITICAL, \"Time synchonization error\");", " Error: Cannot parse alarm criteria: swift_time_sync_check--jramcp-307-28022-swift-proxy-container-57fda26c Error: parse error: failed to match 'endOfLine' at line=4, col=0, pos=135"], "warnings": []}
```

**Comment by antonym** [comment]
Rebased

**Comment by major** [comment]
@antonym I didn't see this one get backported. Did I miss it?

**Comment by antonym** [comment]
Going to do those this morning now that you merged the ones it was dependent on.

**Pull request merged**
