### PR TITLE
RE-721 Implement pre_merge_test hook (newton)

### PR DESCRIPTION
**Pull request by odyssey4me**
This patch implements the RPC Release Engineering pre_merge_hook
as documented in [1] making use of the existing job definition
in the rpc-gating repo.

For the most part it intentionally does not change how the job
is executed - it is meant to be a simple transfer of all logic
from rpc-gating into the rpc-openstack repository so that the
RPC-O team can own the entire test execution in a branched
repository.

The Jenkinsfile is removed as it is unused.

The job which uses this hook is defined in https://github.com/rcbops/rpc-gating/pull/462

[1] https://rpc-openstack.atlassian.net/wiki/spaces/RE/pages/19005457/RE+for+Projects

Issue: [RE-721](https://rpc-openstack.atlassian.net/browse/RE-721)

### CODE REVIEW

**Comment by odyssey4me** [comment]
recheck_cit_issue

**Comment by odyssey4me** [comment]
recheck_issue_link

**Comment by odyssey4me** [comment]
recheck_cit_artifact

**Comment by odyssey4me** [comment]
recheck_xenial_swift_deploy

**Comment by odyssey4me** [comment]
The ``xenial_swift_deploy`` test result was executed using the adjusted jobs from https://github.com/rcbops/rpc-gating/pull/462 to show that this PR delivers a working test set.

**Comment by odyssey4me** [comment]
@hughsaunders Yes I've removed the job after testing it to prevent it interfering with other PR's.

**Comment by hughsaunders** [comment]
Hmm, on second thoughts, this modifies bootrstrap-aio, which will probably break existing jobs, and possibly the upgrade jobs that will be left over?

**Comment by odyssey4me** [comment]
@hughsaunders The existing jobs didn't break as far as I could see. The ``trusty-deploy-swift`` job appears to be failing normally in tempest, and tje ``xenial-deploy-swift`` job passed just fine.

**Comment by odyssey4me** [comment]
recheck_ xenial_swift_deploy

**Comment by odyssey4me** [comment]
Current failures appear to be due to https://rpc-openstack.atlassian.net/browse/RO-2796

**Comment by odyssey4me** [comment]
recheck_cit_artifact - https://rpc-openstack.atlassian.net/browse/RO-2796 has been resolved

The minorupgrade jobs have been removed by https://github.com/rcbops/rpc-gating/commit/01f05822fdbd9910677c4123c5c3686b199f442a

**Pull request merged**
