### PR TITLE
Update OSA SHA to OSA tag 12.0.8

### PR DESCRIPTION
**Pull request by git-harry**
Update openstack-ansible submodule SHA to pull in the latest fixes from
OSA. This includes the fix to address compute instance build failures
due to the Neutron ml2 port security extension being enabled on a
deployment with existing Neutron networks.

Closes-issue: https://github.com/rcbops/rpc-openstack/issues/906

### CODE REVIEW

**Comment by prometheanfire** [comment]
I don't think we should consider #906 closed until we remove the workaround

**Comment by git-harry** [comment]
@prometheanfire issue 906 isn't specifically for tracking the port security issue. We should probably have a separate one if we want to do that.

**Comment by hughsaunders** [comment]
:+1:

**Comment by prometheanfire** [comment]
:+1:

**Pull request merged**
