### PR TITLE
Update SHA to allow Swift to clean up nodes

### PR DESCRIPTION
**Pull request by prometheanfire**
This SHA update includes an update to Swift that allows it to remove
zero weight object nodes.

Related-Bug: #878

### CODE REVIEW

**Comment by prometheanfire** [comment]
recheck_ceph
recheck_upgrade

**Comment by prometheanfire** [comment]
recheck_upgrade

**Comment by git-harry** [comment]
The upgrade appears to be failing because /usr/share/spice-html5/ on the nova_console container is not getting updated. It looks the repo update task [1] fails to correctly pull in the new commits.

[1] https://github.com/openstack/openstack-ansible/blob/12.0.12/playbooks/roles/os_nova/tasks/nova_console_spice_install.yml#L41

**Comment by git-harry** [comment]
@prometheanfire I'm looking to use [1] to update the SHA. While it is an older SHA it I don't believe it will suffer from the same issue, see previous comment, as this one. I wish to get a release tagged today and on the face of it this does not appear to be something that is likely to get resolved till next week at the earliest. If you would like to take a look at this now I'd be happy to switch back to this commit if you can resolve the problem.

[1] https://github.com/rcbops/rpc-openstack/pull/1057

**Comment by git-harry** [comment]
Closing in favour of https://github.com/rcbops/rpc-openstack/pull/1057 based on the upgrade failure this pull request is experiencing, see https://github.com/rcbops/rpc-openstack/issues/1058.

**Comment by Frank-ZhangXin** [comment]
👍

**Comment by d34dh0r53** [comment]
👍

**Pull request merged**
