### PR TITLE
Deleted the old MaaS files

### PR DESCRIPTION
**Pull request by cloader89**
This change does some minor housekeeping and deletes unused MaaS files
and the test-maas.yml file.

Connects #1209

### CODE REVIEW

**Comment by Apsu** [comment]
RPC-AIO-Liberty-PR: Fail

**Comment by ameserole** [comment]
`tempest.lib.exceptions.ServerFault: Got server fault`
recheck_swift

**Comment by evrardjp** [comment]
👍

**Comment by tomc603** [comment]
I like it. 👍

**Comment by git-harry** [comment]
This has left behind everything in maas/testing which doesn't do anything without test-maas.yml

**Pull request merged**
