### PR TITLE
Add MaaS checks for processes status (#1366)

### PR DESCRIPTION
**Pull request by cloader89**
This adds a MaaS check script to check by fully qualified or basename
if processes are running on a host or within a container on a host.
Additionally, MaaS checks for filebeat, elasticsearch and rsyslog are
added using the process check script.

Connects #1236
(cherry picked from commit 2870f4e)

### CODE REVIEW

**Comment by alextricity25** [comment]
recheck_all

**Comment by cloader89** [comment]
recheck_all

**Comment by cloader89** [comment]
recheck_swift recheck_upgrade

**Comment by git-harry** [comment]
👎 The commit message does not reference the original commmit.

To cherry-pick a commit into your current branch you should do:

```
git cherry-pick -x commit
```

Adding '-x' appends a line to the commit message referencing the original commit.

**Comment by git-harry** [comment]
👎 The commit message does not reference the original commmit.

To cherry-pick a commit into your current branch you should do:

```
git cherry-pick -x commit
```

Adding '-x' appends a line to the commit message referencing the original commit.

**Comment by sigmavirus24** [comment]
recheck_all

**Comment by cloader89** [comment]
recheck_swift recheck_ceph

**Comment by sigmavirus24** [comment]
:+1: Straightforwad backport

**Comment by Frank-ZhangXin** [comment]
LGTM 👍

**Pull request merged**
