### PR TITLE
ASC-225 add qtest upload to pre_merge_test/post

### PR DESCRIPTION
**Pull request by zreichert**
Issue: [ASC-225](https://rpc-openstack.atlassian.net/browse/ASC-225)

### CODE REVIEW

**Comment by zreichert** [comment]
Depends on https://github.com/rcbops/rpc-gating/pull/675

**Comment by mattt416** [comment]
The master and pike system MNAIOs are in a bad shape atm (unrelated issues), so testing this along-side https://github.com/rcbops/rpc-openstack/pull/2894/ [here](https://rpc.jenkins.cit.rackspace.net/job/PM_rpc-openstack-master-xenial_no_artifacts-swift-system/1/). Once that job completes we can nuke PM_rpc-openstack-master-xenial_no_artifacts-swift-system.

**Comment by mattt416** [comment]
Hi @zreichert, from the log of the test build:

```
23:51:11 bash: /var/lib/jenkins/workspace/PM_rpc-openstack-master-xenial_no_artifacts-swift-system/rpc-openstack/gating/pre_merge_test/post_send_junit_to_qtest.sh: Permission denied
[Pipeline] echo
23:51:13 Post-Merge Test (post) failed with return code 126```

**Comment by mattt416** [comment]
Hi @zreichert , some bashate failures here:

```
12:23:09 [E] E010: The "do" should be on same line as while: 'while IFS=  read -r -d $'\0' FILE'
12:23:09  - /var/lib/jenkins/workspace/PR_rpc-openstack-master-container-bashate-tox-test/rpc-openstack/gating/pre_merge_test/post_send_junit_to_qtest.sh : L34
12:23:09 [E] E010: The "do" should be on same line as for: 'for i in "${xml_files[@]}"'
12:23:09  - /var/lib/jenkins/workspace/PR_rpc-openstack-master-container-bashate-tox-test/rpc-openstack/gating/pre_merge_test/post_send_junit_to_qtest.sh : L42
12:23:09 Running bashate on /var/lib/jenkins/workspace/PR_rpc-openstack-master-container-bashate-tox-test/rpc-openstack/gating/pre_merge_test/post
12:23:09 2 bashate error(s) found
```

**Comment by zreichert** [comment]
@mattt416 Just fixed the bashate failures.

**Comment by mattt416** [comment]
recheck_cit_release

**Comment by zreichert** [comment]
@mattt416  @odyssey4me How can I help get this across the line?  https://github.com/rcbops/rpc-openstack/pull/2905 is the same commit to Pike

**Pull request merged**
