### PR TITLE
Remove legacy ELK env.d file and ensure new version is used [master]

### PR DESCRIPTION
**Pull request by odyssey4me**
The legacy env.d file for elk is incomplete. It also puts the
elk containers into the log_hosts group, resulting in unused
ELK containers and haproxy back-ends being configured without
the associated services.

This patch does the following:

Removes the legacy ELK env.d file.
Ensures that the ELK deployment playbook copies over the
new elk env.d file from the openstack-ansible-ops repo.
Removes the duplicated README information informing the
deployer how to deploy the new ELK stack, replacing it
with the use of the playbook to remove the element of
human error. This was done because the instructions were
missing the addition of the new host groups into the
inventory and the copy of the new env.d file.
Also, when building an environment, there should be no situation
where the resulting build has a haproxy back-end that is down.
Recently some implementations were merged which did this,
causing the use of snapshot AIO images to fail due to the
failed back-ends in haproxy.

To prevent this happening again, we ensure that part of the
AIO PR/PM test is to do the same check and to fail if there
is a back-end down.

Issue: [RI-538](https://rpc-openstack.atlassian.net/browse/RI-538)

### CODE REVIEW

**Comment by odyssey4me** [comment]
The failure here will go away once 
https://review.openstack.org/622473 merges.

**Comment by mendeni** [comment]
recheck_bionic_no_artifacts_swift_deploy

**Comment by mendeni** [comment]
recheck_xenial_no_artifacts_swift_deploy

**Comment by d34dh0r53** [comment]
recheck_bionic_no_artifacts_swift_deploy

**Comment by odyssey4me** [comment]
With thanks to https://github.com/rcbops/rpc-openstack/pull/3357/files#diff-4b2a015225363d3a6e1fa1663aad98ea the logging services are now being deployed by force for the AIO. I would argue that this is way over the top and that this should be opt-in, and not deployed on the AIO due to resource constraints. I've registered https://rpc-openstack.atlassian.net/browse/RI-632 to express that.

**Comment by cjloader** [comment]
recheck_all

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by odyssey4me** [comment]
recheck_whisperer

**Pull request merged**
