### PR TITLE
Make RPC Support role Standalone Swift Friendly

### LINKED ISSUE #221: Standalone Swift - ERROR (EndpointNotFound): internalURL endpoint for compute service not found
The `rpc_support` role assumes Nova is installed, and tries registering a support keypair. In a Standalone Swift configuration, this will fail as there are no Nova endpoints to communicate with.

```
TASK: [rpc_support | Add rpc_support key to nova] ***************************** 
skipping: [163f7de7-infra1]
skipping: [163f7de7-object1]
skipping: [163f7de7-object3]
skipping: [163f7de7-infra1_keystone_container-23f8c901]
skipping: [163f7de7-infra1_swift_proxy_container-fa8061b9]
skipping: [163f7de7-object2]
skipping: [163f7de7-infra1_galera_container-22c355d4]
skipping: [163f7de7-infra1_memcached_container-469b23e0]
skipping: [163f7de7-infra1_rabbit_mq_container-bcf9683e]
<172.29.239.239> ESTABLISH CONNECTION FOR USER: root
skipping: [163f7de7-infra1_repo_container-e6a7a307]
<172.29.239.239> REMOTE_MODULE command . /root/openrc nova keypair-add --pub-key /root/.ssh/rpc_support.pub rpc_support #USE_SHELL
<172.29.239.239> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-m
ic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=120 172.29.239.239 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'
failed: [163f7de7-infra1_utility_container-4df0fd1f] => {"changed": true, "cmd": ". /root/openrc\n nova keypair-add --pub-key /root/.ssh/rpc_support.pub rpc_support", "delta": "0:00:00.631306", "end": "2015-07-06 21:06:09.953687", "rc": 1
, "start": "2015-07-06 21:06:09.322381", "warnings": []}
stderr: ERROR (EndpointNotFound): internalURL endpoint for compute service not found
```

### PR DESCRIPTION
**Pull request by mattt416**
Only create support keypair if nova service is present. Only create support security group if neutron service is present.

Fixes #221

(cherry picked from commit e739459a1cd1fc97de103fd92f390b514be61fdd)

### CODE REVIEW

**Comment by nrb** [comment]
In order to minimize impact on QE, I'm going to set this as blocked and push it to Kilo 11.1.0

**Comment by nrb** [comment]
I am +1 on this.

**Comment by d34dh0r53** [comment]
recheck

**Comment by nrb** [comment]
Looks like this needs to be rebased before the travis checks will work.

fwiw, I don't know that 'recheck' works on Travis.

**Comment by byronmccollum** [comment]
I missed this in my initial patch (keys laying around from partially run `support_key_pair.yml`), but the `distribute_auth_key.yml` and `retrieve_auth_key.yml` includes need the same fix applied. I'll put together a new pull request against master for this.

**Comment by git-harry** [comment]
@byronmccollum will you rebase this patch so travis gets a nudge.

**Comment by byronmccollum** [comment]
This is @mattt416 's pull request.

**Comment by git-harry** [comment]
Whoops! Sorry @byronmccollum 

@mattt416 do it!

**Comment by git-harry** [comment]
This was already fixed by https://github.com/rcbops/rpc-openstack/pull/425

**Comment by mattt416** [comment]
WHATDYOUDO

**Pull request closed without merging**
