### PR TITLE
MaaS: Split process_checks for host and container

### PR DESCRIPTION
**Pull request by antonym**
Splits process_checks.py into process_check_host.py and process_check_container.py to get around the lxc package requirement on hosts without lxc.  Also changes the checks using process_checks to choose one or the other depending on the situation.

process_check_container.py is a copy of the original process_check.py script, and process_check_host.py has had the container things related to needing the lxc library stripped out.

Connects rcbops/rpc-openstack#2026

### CODE REVIEW

**Comment by prometheanfire** [comment]
How tested is it 'in prod'?

**Comment by antonym** [comment]
@prometheanfire if 'in prod' you mean the lab, then yes.  :)  

The reason the process_check got reworked originally was because where it was searching for the process names before would get chopped off by a 15 character kernel limit, which breaks when searching for most swift processes.  It can be pretty easily tested by running the plugin to check on a random service and see if it identifies if it's running.  Then you can stop the service and rerun the check and see if it identifies it as down.  You'll just need to run the _host or _container script based on the process you want to check.

**Comment by prometheanfire** [comment]
yep, that was all

**Comment by mkam** [comment]
I reran the maas-setup.yml on a multi-node AIO that was failing previously, and it failed at the same part as before:
https://rpc.jenkins.cit.rackspace.net/job/OnMetal_Multi_Node_AIO/203/consoleFull
```
[maas] FAILED - RETRYING: TASK: rpc_maas : Install pip packages to venv (1 retries left).
[maas] changed: [swift2] => (item=python-novaclient<7.0.0)
[maas] changed: [swift3] => (item=python-novaclient<7.0.0)
[maas] changed: [cinder2] => (item=python-novaclient<7.0.0)
[maas] changed: [swift1] => (item=python-novaclient<7.0.0)
[maas] changed: [cinder1] => (item=python-novaclient<7.0.0)
[maas] changed: [swift2] => (item=python-memcached)
[maas] changed: [swift3] => (item=python-memcached)
[maas] changed: [cinder2] => (item=python-memcached)
[maas] changed: [swift1] => (item=python-memcached)
[maas] changed: [infra3] => (item=rackspace-monitoring-cli)
[maas] failed: [loadbalancer1] (item=lxc-python2) => {"cmd": "/openstack/venvs/maas-r13.1.0rc1/bin/pip install lxc-python2", "failed": true, "item": "lxc-python2", "msg": "stdout: Collecting lxc-python2\n  Using cached lxc-python2-0.1.zip\nBuilding wheels for collected packages: lxc-python2\n  Running setup.py bdist_wheel for lxc-python2: started\n  Running setup.py bdist_wheel for lxc-python2: finished with status 'error'\n  Complete output from command /openstack/venvs/maas-r13.1.0rc1/bin/python -u -c \"import setuptools, tokenize;__file__='/tmp/pip-build-kD8WQP/lxc-python2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" bdist_wheel -d /tmp/tmp2CGTM_pip-wheel- --python-tag cp27:\n  running bdist_wheel\n  running build\n  running build_py\n  creating build\n  creating build/lib.linux-x86_64-2.7\n  creating build/lib.linux-x86_64-2.7/lxc\n  copying lxc/__init__.py -> build/lib.linux-x86_64-2.7/lxc\n  running build_ext\n  building '_lxc' extension\n  creating build/temp.linux-x86_64-2.7\n  x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c lxc.c -o build/temp.linux-x86_64-2.7/lxc.o\n  lxc.c:27:30: fatal error: lxc/lxccontainer.h: No such file or directory\n   #include <lxc/lxccontainer.h>\n                                ^\n  compilation terminated.\n  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1\n  \n  ----------------------------------------\n  Running setup.py clean for lxc-python2\nFailed to build lxc-python2\nInstalling collected packages: lxc-python2\n  Running setup.py install for lxc-python2: started\n    Running setup.py install for lxc-python2: finished with status 'error'\n    Complete output from command /openstack/venvs/maas-r13.1.0rc1/bin/python -u -c \"import setuptools, tokenize;__file__='/tmp/pip-build-kD8WQP/lxc-python2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" install --record /tmp/pip-eiRml_-record/install-record.txt --single-version-externally-managed --compile --install-headers /openstack/venvs/maas-r13.1.0rc1/include/site/python2.7/lxc-python2:\n    running install\n    running build\n    running build_py\n    creating build\n    creating build/lib.linux-x86_64-2.7\n    creating build/lib.linux-x86_64-2.7/lxc\n    copying lxc/__init__.py -> build/lib.linux-x86_64-2.7/lxc\n    running build_ext\n    building '_lxc' extension\n    creating build/temp.linux-x86_64-2.7\n    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c lxc.c -o build/temp.linux-x86_64-2.7/lxc.o\n    lxc.c:27:30: fatal error: lxc/lxccontainer.h: No such file or directory\n     #include <lxc/lxccontainer.h>\n                                  ^\n    compilation terminated.\n    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1\n    \n    ----------------------------------------\n\n:stderr:   Failed building wheel for lxc-python2\nCommand \"/openstack/venvs/maas-r13.1.0rc1/bin/python -u -c \"import setuptools, tokenize;__file__='/tmp/pip-build-kD8WQP/lxc-python2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" install --record /tmp/pip-eiRml_-record/install-record.txt --single-version-externally-managed --compile --install-headers /openstack/venvs/maas-r13.1.0rc1/include/site/python2.7/lxc-python2\" failed with error code 1 in /tmp/pip-build-kD8WQP/lxc-python2/\n"}
```

I think it's because even though some hosts don't have the container checks, it still attempts to install lxc-python2 on all of them.

**Comment by alextricity25** [comment]
There probably is a different way, but the only way I can think of fixing this quickly is to move the installation of ``lxc-python2`` to it's own task, and out of the ``maas_pip_packages`` list.
The task can be added here: https://github.com/rcbops/rpc-openstack/blob/master/rpcd/playbooks/roles/rpc_maas/tasks/package_install.yml, and will install ``lxc-python2`` based on whether ``inventory_hostname`` is in ``groups['lxc_hosts']``

I initally was thinking to add a jinja conditional statement inside the maas role's ``defaults/main.yml`` variable file, but I'm not sure if Ansible can resolve the ``inventory_hostname`` magic variable inside variable files. i.e.
```
maas_pip_packages:
  - cryptography
  - ipaddr
{% if inventory_hostname in groups['lxc_hosts'] %}
  - lxc-python2
{% endif %}
  - lxml
  - psutil<=1.2.1
  - rackspace-monitoring-cli
  - python-cinderclient
  - python-glanceclient
  - python-heatclient
  - python-keystoneclient
  - python-magnumclient
  - python-neutronclient
  - python-novaclient<7.0.0
  - python-memcached
  - requests
  - swift
  - waxeye
```
I don't think Ansible renders this jinja inside the variables file on a per host basis, so it probably won't work to do it this way.

**Comment by antonym** [comment]
Pushed up an update that should hopefully address.

**Comment by antonym** [comment]
recheck_ceph
recheck_swift

**Comment by alextricity25** [comment]
@mkam is running these changes though the multi-node-aio job. Once that's finished and has ran setup-maas and verify-maas successfully, I'll approve these changes.

**Comment by antonym** [comment]
recheck_ceph
recheck_swift

**Comment by alextricity25** [comment]
# ## **To the person who merges this: Please squash these commits before merging :)**

**Comment by antonym** [comment]
Yeah, I'll squash before we merge, left it separate to make the new additions easier to see.

**Comment by antonym** [comment]
Squashed and found a quick bug where i forget the rename the register of the new pip install.  Fixed that and pushed.

**Comment by odyssey4me** [comment]
A convention we've used in OSA is to have the pip_packages list only contain universal packages that need to be in the venv, then to have a set of _optional_pip_packages vars with items that should be installed into the venv based on the particular needs or configuration.

Examples:
https://github.com/openstack/openstack-ansible-os_neutron/blob/master/defaults/main.yml#L625-L644

The optional pip packages will be built by the repo server, but not installed into the venv. There then needs to be a task which installs the package into the venv which is only applied to the right host group or based on the particular configuration in question.

Example:
https://github.com/openstack/openstack-ansible-os_neutron/blob/master/tasks/neutron_install.yml#L121

**Comment by alextricity25** [comment]
It looks like the multi-node-aio job has completed the setup-maas and verify-maas playbook: https://rpc.jenkins.cit.rackspace.net/view/Multi-Node%20AIO/job/OnMetal_Multi_Node_AIO_master-xenial/33/console

Nice!
I'm going to go ahead and approve this. Feel free to merge it once the gate jobs finish here.

**Pull request merged**
