### PR TITLE
Kilo sync with master

### PR DESCRIPTION
**Pull request by prometheanfire**
mostly maas things

### CODE REVIEW

**Comment by sigmavirus24** [comment]
lolnope. :-1:

**Comment by prometheanfire** [comment]
why were these things not backported @git-harry @jacobwagner @d34dh0r53 and the external author of prometheanfire/rpc-openstack/commit/70fde5458b31e070cec5da0c170d340f2a065171

**Comment by prometheanfire** [comment]
also, lolnope til we have at least some discussion about the patches :P

**Comment by git-harry** [comment]
@prometheanfire the MaaS monitoring work was considered outside the scope of the initial kilo release.

**Comment by prometheanfire** [comment]
that's fine, now that kilo is out anything keeping us from merging?

**Comment by sigmavirus24** [comment]
> Keeping us from merging

Merging this pull request? The fact that it violates our backport policy.

Merging these commits? No pull request has been sent that adheres to our backport policy.

**Comment by prometheanfire** [comment]
merging these individual commits separately

This (PR) is here as a place to discuss why they were not backported.

**Comment by prometheanfire** [comment]
ok, review the following

#419
#420 
#421 
#422 
#423 
#424 
#425 
#426 
#427

**Comment by prometheanfire** [comment]
looks like we've sync'd so going to close

**Pull request closed without merging**
