### PR TITLE
Add task to restart lsync after repo-build - kilo-backport

### PR DESCRIPTION
**Pull request by d34dh0r53**
This is a straightforward backport that should have been created when I did the initial commit.

### CODE REVIEW

**Comment by git-harry** [comment]
@d34dh0r53 I think it's worthwhile to use -x when cherry picking, it makes tracking things easier.

**Comment by d34dh0r53** [comment]
@git-harry agree, I'll start using it.

**Comment by prometheanfire** [comment]
:+1:

**Comment by prometheanfire** [comment]
:+1: still need another though

**Comment by stevelle** [comment]
what # is the original issue

**Pull request closed without merging**
