### PR TITLE
[Magnum] Resolving issues with deployment

### PR DESCRIPTION
**Pull request by chrishultin**
Resolving the following issues:
os_magnum role cannot be found
RabbitMQ variables not being set
Magnum settings added multiple times
Unsupported 'checksum' parameter

### CODE REVIEW

**Comment by chrishultin** [comment]
recheck_upgrade

**Comment by chrishultin** [comment]
recheck_upgrade

**Comment by chrishultin** [comment]
Updated the title

**Comment by chrishultin** [comment]
recheck_upgrade

**Comment by chrishultin** [comment]
recheck_upgrade

**Comment by alextricity25** [comment]
Unfortunately, our upgrade job for mitaka is broken. Until https://github.com/rcbops/u-suk-dev/issues/1065 is resolved this won't merge.

**Comment by alextricity25** [comment]
recheck_upgrade

**Pull request merged**
