### PR TITLE
Update SHAs for RC3.

### PR DESCRIPTION
**Pull request by d34dh0r53**
This updates the liberty SHAs to HEAD of master as of (`2016-03-25`)
for 12.0.0RC3.

Closes: #897
Closes: #925

### CODE REVIEW

**Comment by prometheanfire** [comment]
:+1:

**Comment by nrb** [comment]
The SHA is correct, but the commit message is wrong, I think - it's the SHA bump for Liberty.

**Comment by prometheanfire** [comment]
@nrb fixed commit message

**Comment by tomc603** [comment]
:+1: Looks good

**Comment by nrb** [comment]
:+1:

**Pull request merged**
