### PR TITLE
Update OSA SHA to tip of stable/mitaka

### PR DESCRIPTION
**Pull request by git-harry**
This update addresses the following issues:

- https://github.com/rcbops/rpc-openstack/issues/1483
- https://github.com/rcbops/u-suk-dev/issues/517
- https://github.com/rcbops/rpc-openstack/issues/1432

Connected https://github.com/rcbops/u-suk-dev/issues/579

(cherry picked from commit 5393d8cb36246b15f5c88f7cafe2a274acf4a1f9)

### CODE REVIEW

**Comment by git-harry** [comment]
recheck_all

**Comment by git-harry** [comment]
recheck_all maas failures

**Comment by alextricity25** [comment]
:+1:

**Comment by d34dh0r53** [comment]
👍

**Pull request merged**
