### PR TITLE
create distro specific maas process check symlink

### PR DESCRIPTION
**Pull request by prometheanfire**
Xenial and Trusty both support different levels of cgroup functionality.
This has caused us to need different behavior for checking the status of
processes within containers.  In this commit we allow for both ways,
using a symlink to link to the correct version based on the Ubuntu
version installed.

Connects https://github.com/rcbops/u-suk-dev/issues/1101

### CODE REVIEW

**Comment by alextricity25** [comment]
Going to test this on my AIO

**Comment by alextricity25** [comment]
recheck_ceph
recheck_xenial

**Comment by alextricity25** [comment]
Trusty maas job: http://jenkins.propter.net/job/JJB-RPC-AIO_master-ceph-periodic/80/
xenial maas job: http://jenkins.propter.net/job/JJB-RPC-AIO_master-xenial-periodic/43/

Let's make sure they both pass before merging this.

**Comment by alextricity25** [comment]
Again, let's make sure these MaaS jobs finish successfully before merging:
Trusty maas job: http://jenkins.propter.net/job/JJB-RPC-AIO_master-ceph-periodic/80/
xenial maas job: http://jenkins.propter.net/job/JJB-RPC-AIO_master-xenial-periodic/43/

**Comment by prometheanfire** [comment]
The trusty job failed, going to recheck as I don't think it's my fault.

17:53:16 Variable files: "-e @/etc/openstack_deploy/user_osa_secrets.yml -e @/etc/openstack_deploy/user_osa_variables_defaults.yml -e @/etc/openstack_deploy/user_osa_variables_overrides.yml -e @/etc/openstack_deploy/user_rpco_secrets.yml -e @/etc/openstack_deploy/user_rpco_variables_defaults.yml -e @/etc/openstack_deploy/user_rpco_variables_overrides.yml -e @/etc/openstack_deploy/user_zzz_gating_variables.yml "
17:53:17 ERROR! Syntax Error while loading YAML.
17:53:17 
17:53:17 
17:53:17 The error appears to have been in '/etc/openstack_deploy/user_zzz_gating_variables.yml': line 23, column 41, but may
17:53:17 be elsewhere in the file depending on the exact syntax problem.
17:53:17 
17:53:17 The offending line appears to be:
17:53:17 
17:53:17     snapshot: True
17:53:17 cinder_cinder_conf_overrides:    DEFAULT:        default_volume_type: cephcinder_service_backup_driver: cinder.backup.drivers.cephcinder_service_backup_program_enabled: true
17:53:17                                         ^ here
17:53:17 Build step 'Execute shell' marked build as failure

**Comment by prometheanfire** [comment]
xenial passed though, we have that going for us, which is nice.

**Comment by prometheanfire** [comment]
http://jenkins.propter.net/job/JJB-RPC-AIO_master-ceph-periodic/83/

**Comment by alextricity25** [comment]
Newest trust job with maas: http://jenkins.propter.net/job/JJB-RPC-AIO_master-swift-periodic/83/

**Comment by alextricity25** [comment]
FYI - This will need a rebase

**Comment by alextricity25** [comment]
trusty maas job: http://jenkins.propter.net/job/JJB-RPC-AIO_master-swift-periodic/85/
The xenial maas job: http://jenkins.propter.net/job/JJB-RPC-AIO_master-xenial-periodic/45/

**Pull request merged**
