### PR TITLE
Bump OSA SHA as of 2016-02-12

### PR DESCRIPTION
**Pull request by mancdaz**
This commit brings the OSA SHA forward to that at 2016-02-12.  

We also remove the patch to nova for the image-cache issue, as OSA
bumped it's SHA's for nova in ```c9a64de9272aaa3db93901f0c3321c2933c028b3```
to include the [upstream backport](https://review.openstack.org/#/c/269421)

OSA commits included in this SHA bump:

```52c7bba8e5b9541a8cbe79b6c4cce72362273bf4 Add cap for ansible-lint
c6dd670ea88df4cdf82ed89beb674b62157be979 Merge "Fix failing tests in defcore test set" into kilo
43b01a7897bfa1d4d6880b5f62d5110646987b8f Updated config parsing for listOPS
397b76a4f39e08ba19f8d4aadaa5e38776912a6a Merge "Update bashate lint checks re: E005, E006, E040" into kilo
4b218c829d19d77326f6e3c5dc8554d05d9b63ae Update bashate lint checks re: E005, E006, E040
c9a64de9272aaa3db93901f0c3321c2933c028b3 Updates all repo SHAs to open up work on 11.2.10
9793c5eafafda03af0075af3598f855a486883e7 Add filter & lookup plugins to tests
3770bb5564dbb5e2a3805573b4079d6e555a4ad7 Merge "Update plugin for and document per host overrides" into kilo
534eba1fbc63b505a46a645536df6ecbcc0a1a93 Merge "Update ceph repo" into kilo
f8f04fe5deb3cf78a9d6758b8fb0d871a078a5da Update plugin for and document per host overrides
6aafeb78c33aa16c8f3d6b49729d067b631a6e45 Merge "Set hard requirements for pip" into kilo
f08a2f9705fdae96298fb90421192e98b6d6d436 Merge "Revise all lint tests and add consolidated 'linters' tox environment" into kilo
fb4b6a82b8f509308b6674aabe4a05e4df37704c Revise all lint tests and add consolidated 'linters' tox environment
d12611af606b9c6303b2aad42e8ed63d4c088518 Set hard requirements for pip
e7e3ed5ae34de6dc28535d51f3ca793ea24ffefc Update Defcore test list function
4c8bba81c97684d73dd6cd1d7eb69b8c0fe44719 Update plumlib.ini with connector type
69149153d5eb3b1579e28440a4cff75f7de834ef Fix failing tests in defcore test set
454883210247235faa89c8d947d8a4eaef886b90 Update ceph repo
261b7d0ce95e12314d337079449aabeaf224353f Merge "set unique galera server-id" into kilo
72bd0bab30ea1486fd86226d21677f18ab0e424f Merge "[DOC] - Remove references to Kibana" into kilo
78c52b76cbc4822260c9e1c3f067be7b75f2376e Merge "Convert available and minimum disk sizes to bytes." into kilo
f206627cfe773d1baca631d529cc20b2e95c0bcc Merge "Implement tunable heat api and engine worker overrides" into kilo
a619361d94eda45d56b3e7f177feac67ae475564 [DOC] - Remove references to Kibana
0908c1f1d3e79816cb8c906e87eacca614cb370f Convert available and minimum disk sizes to bytes.
b91424664912459939d0b414d947df05d3e7c9a3 Add ECMP support config for PGLib
87be7b8a58429ba3389e07b468a46fa48a33b291 Update openstack_release version to 11.2.9
d0bb38042e1367d53d3fce206ed1d26bcbc9d432 set unique galera server-id
8932f03aac288b92ab3feb34ae0ddb8701b7c056 Implement tunable heat api and engine worker overrides```

Addresses: #828

### CODE REVIEW

**Comment by mancdaz** [comment]
recheck - cirros image uploads problem (again - thanks jenkins)

**Comment by mancdaz** [comment]
maybe this waits until after 11.1.4 ? It does however mean that no new commits to kilo rpc-o would gate until this goes in...

**Comment by d34dh0r53** [comment]
@mancdaz I am fine with pinning for kilo and the PR but we will need to bump the OSA SHA again before `r11.1.4` so that we can pull in [`27656`](https://review.openstack.org/#/c/276561/1), an absolute necessity for `r11.1.4`.

**Comment by d34dh0r53** [comment]
:+1:

**Comment by mancdaz** [comment]
@d34dh0r53 OK, probably easiest to sit on this until that merges, and then just update this PR with the new osa sha.

**Comment by prometheanfire** [comment]
so, given that https://review.openstack.org/#/c/276561 was needed and it came after this sha I think this should be changed to reflect it.  https://github.com/openstack/openstack-ansible/commit/0504bcc1942d504bf440fa57ce3d685c57f193e2 is what we should pin to.

**Comment by mancdaz** [comment]
I am now ooo for a week. Can somebody please update this commit/PR as described.

/cc @prometheanfire @d34dh0r53

**Comment by prometheanfire** [comment]
I already did, just needs +1s again (I ammended your commit, stills shows under your name, yay github).

**Comment by d34dh0r53** [comment]
re :+1:

**Comment by prometheanfire** [comment]
:+1:

**Comment by nrb** [comment]
+1

**Pull request merged**
