### PR TITLE
LA-404 OSA OPS SHA BUMP

### PR DESCRIPTION
**Pull request by evrardjp**
Includes:
- LA-383 fix
- LA-396 fix
- LA-405 fix

Issue: [LA-404](https://rpc-openstack.atlassian.net/browse/LA-404)

### CODE REVIEW

**Comment by evrardjp** [comment]
Updated with :

- LA-405 fix

**Comment by evrardjp** [comment]
Updated with LA-389.

**Comment by evrardjp** [comment]
I need to update this with the new patches from @prometheanfire

**Comment by evrardjp** [comment]
Updated.

**Comment by odyssey4me** [comment]
recheck_cit_artifact
recheck_cit_trusty_leapfrogupgrade_swift
recheck_cit_trusty_minorupgrade_swift
recheck_cit_xenial_minorupgrade_swift

**Comment by evrardjp** [comment]
Needs to be updated with LA-438's research.

**Comment by evrardjp** [comment]
Updated!

**Comment by evrardjp** [comment]
recheck_cit_trusty_leapfrogupgrade_swift

**Comment by evrardjp** [comment]
rebased!

**Comment by evrardjp** [comment]
recheck_cit_trusty_leapfrogupgrade_swift

**Comment by evrardjp** [comment]
Darn failed again. Will investigate more after lunch.

**Comment by Frank-ZhangXin** [comment]
recheck_cit_trusty_leapfrogupgrade_swift

**Comment by evrardjp** [comment]
Most recent failure failed on kibana selenium, so not linked at all to leapfrog, but to our gating.
Previous failure was in tempest, so I am investigating the run.

**Comment by evrardjp** [comment]
Tempest issue is:
```
Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File \"/openstack/venvs/tempest-r14.2.0/tempest/lib/common/utils/test_utils.py\", line 84, in call_and_ignore_notfound_exc
        return func(*args, **kwargs)
      File \"/openstack/venvs/tempest-r14.2.0/tempest/lib/services/compute/floating_ips_client.py\", line 74, in delete_floating_ip
        resp, body = self.delete(url)
      File \"/openstack/venvs/tempest-r14.2.0/tempest/lib/common/rest_client.py\", line 307, in delete
        return self.request('DELETE', url, extra_headers, headers, body)
      File \"/openstack/venvs/tempest-r14.2.0/tempest/lib/services/compute/base_compute_client.py\", line 48, in request
        method, url, extra_headers, headers, body, chunked)
      File \"/openstack/venvs/tempest-r14.2.0/tempest/lib/common/rest_client.py\", line 665, in request
        resp, resp_body)
      File \"/openstack/venvs/tempest-r14.2.0/tempest/lib/common/rest_client.py\", line 829, in _error_checker
        message=message)
    tempest.lib.exceptions.ServerFault: Got server fault
    Details: Unexpected API Error. Please report this at http://bugs.launchpad.net/nova/ and attach the Nova API log if possible.
    <class 'nova.exception.InstanceInfoCacheNotFound'>
```

in other words, the usual suspect. Let's recheck and see how it goes.

**Comment by evrardjp** [comment]
If that fails again today, could you check on why? If it's on tempest again, checking at the issue in more details would revolve around checking that the migrations happened correctly. (Seeing in the output log that nothing was skipped for example).

Thanks a ton!

**Comment by Frank-ZhangXin** [comment]
recheck_cit_trusty_leapfrogupgrade_swift

**Comment by claco** [comment]
recheck_cit_trusty_leapfrogupgrade_swift

**Comment by evrardjp** [comment]
selenium issues again.

**Comment by evrardjp** [comment]
recheck_cit_trusty_leapfrogupgrade_swift

**Pull request merged**
