### PR TITLE
UG-633 [newton] Backport artifact job fixes

### PR DESCRIPTION
**Pull request by odyssey4me**
This PR backports the appropriate non-ocata patches from https://github.com/rcbops/rpc-openstack/pull/2337

### CODE REVIEW

**Comment by alextricity25** [comment]
recheck_cit_xenial_deploy_swift

**Comment by alextricity25** [comment]
recheck_cit_artifact_trusty_container
recheck_cit_artifact_trusty_python
recheck_cit_artifact_xenial_container

**Comment by odyssey4me** [comment]
I'll have to debug those Container build problems and push up an additional patch to resolve them. I'm guessing (from not reviewing the logs) that the SHA has been bumped and therefore the keystone/repo_server patches for the roles need updating.

**Comment by odyssey4me** [comment]
recheck_cit_artifact_trusty_apt
recheck_cit_artifact_xenial_apt

**Comment by odyssey4me** [comment]
recheck_cit_artifact_trusty_apt
recheck_cit_artifact_xenial_apt

**Comment by odyssey4me** [comment]
The minorupgrade and lint tests are expected to fail for this patch, so if everything else passes it's free to merge.

**Pull request merged**
