### PR TITLE
This fix to rpc_support role will install host packages not inside the containers

### PR DESCRIPTION
**Pull request by BjoernT**
Closes-Bug: #834

### CODE REVIEW

**Comment by prometheanfire** [comment]
recheck

**Comment by prometheanfire** [comment]
recheck

**Comment by prometheanfire** [comment]
recheck - timeout

**Comment by prometheanfire** [comment]
recheck - again...

**Comment by prometheanfire** [comment]
ok, :+1:  :D

**Comment by d34dh0r53** [comment]
:+1:

**Pull request merged**
