### PR TITLE
Fix file mode for added maas plugin

### PR DESCRIPTION
**Pull request by stevelle**
This plugin was added recently but did not have the mode set
correctly. It gets fixed by the maas role but shoudln't be incorrect
in the first place.

Resolves: #486

### CODE REVIEW

**Comment by git-harry** [comment]
+1

**Comment by d34dh0r53** [comment]
:+1:

**Comment by rackertom** [comment]
@stevelle If you can get this committed, I'll backport it to Kilo today.

**Comment by stevelle** [comment]
rebased

**Pull request merged**
