### PR TITLE
Update openstack-ansible SHA

### PR DESCRIPTION
**Pull request by git-harry**
This commit updates the OSA SHA, this resolves the following issues:

Issue: https://github.com/rcbops/rpc-openstack/issues/1037

### CODE REVIEW

**Comment by git-harry** [comment]
recheck_swift

**Comment by git-harry** [comment]
recheck_ceph

**Comment by git-harry** [comment]
recheck_upgrade

**Comment by prometheanfire** [comment]
closed in favor of #1054 which merged

**Pull request closed without merging**
