### PR TITLE
update OSA sha to fix absolute requirements

### PR DESCRIPTION
**Pull request by prometheanfire**
This includes a needed fix from 'Fix typo in upgrade script'.

### CODE REVIEW

**Comment by d34dh0r53** [comment]
:+1:

**Comment by git-harry** [comment]
What does absolute requirements refer to? What's wrong with them?

**Comment by d34dh0r53** [comment]
@git-harry it refers to the commit that the SHA points to http://git.openstack.org/cgit/openstack/openstack-ansible/commit/?h=liberty&id=0e50db67247c3718f85bc5bae8369c7d00eb578d

**Comment by d34dh0r53** [comment]
Do not merge, I want to get https://review.openstack.org/#/c/293821/4 into RC1

**Comment by d34dh0r53** [comment]
Supersceded by #958

**Pull request closed without merging**
