### PR TITLE
[master] Update OSA SHA

### PR DESCRIPTION
**Pull request by alextricity25**
OpenStack-Ansible Diff Generator
================================

This report shows changes from `78eddadcd31b911158dda0eb50a41a31e8be6ec7` to `c7ae97addd51cbdae8c37d130630f6f2e18981d4` in OpenStack-Ansible.

This report also includes the changes that were made in OpenStack projects and OpenStack-Ansible roles between these two OpenStack-Ansible commits.

openstack-ansible
-----------------

9 commits were found in [openstack-ansible](https://github.com/openstack/openstack-ansible) from `78eddadc` to `c7ae97ad`:

<table>
<col width="57%" />
<col width="42%" />
<tbody>
<tr class="odd">
<td align="left"><a href="https://github.com/openstack/openstack-ansible/commit/785e7431eccfafba8f388e4e8006e16082bfea85">785e7431</a></td>
<td align="left">Updated from global requirements</td>
</tr>
<tr class="even">
<td align="left"><a href="https://github.com/openstack/openstack-ansible/commit/f1be2f3b166412237e6e0f942fd297868a12f636">f1be2f3b</a></td>
<td align="left">Updated from global requirements</td>
</tr>
<tr class="odd">
<td align="left"><a href="https://github.com/openstack/openstack-ansible/commit/3ece814c79cc595af66b5065c81f2aa6b76a6569">3ece814c</a></td>
<td align="left">Update all SHAs for 14.2.1</td>
</tr>
<tr class="even">
<td align="left"><a href="https://github.com/openstack/openstack-ansible/commit/ace72d6db776cd2d35ee3a52048e0d02fe0b954e">ace72d6d</a></td>
<td align="left">SHA Bump for plugins repo to fix endpoint upgrades</td>
</tr>
<tr class="odd">
<td align="left"><a href="https://github.com/openstack/openstack-ansible/commit/a319e2d1e82b5b22fdba08c4a0ac2fef7e1da26c">a319e2d1</a></td>
<td align="left">Update Ansible to 2.1.5.0</td>
</tr>
<tr class="even">
<td align="left"><a href="https://github.com/openstack/openstack-ansible/commit/d4089f1621a9a075830c916c8cf64253b2821bd1">d4089f16</a></td>
<td align="left">Bump Keepalived</td>
</tr>
<tr class="odd">
<td align="left"><a href="https://github.com/openstack/openstack-ansible/commit/7266928a3f5afa11fd7d38460ec7d8b1e681d05a">7266928a</a></td>
<td align="left">Fix pip_links for LB terminated SSL environments</td>
</tr>
<tr class="even">
<td align="left"><a href="https://github.com/openstack/openstack-ansible/commit/a7f86a7cc75e20a7e9386e0e6d5c41cd0f416272">a7f86a7c</a></td>
<td align="left">Add vagrantfile for AIO testing</td>
</tr>
<tr class="odd">
<td align="left"><a href="https://github.com/openstack/openstack-ansible/commit/e99a4633ce3b56b0b0b7149ae774152378503c33">e99a4633</a></td>
<td align="left">Provide example of using veth pairs for br-vlan</td>
</tr>
</tbody>
</table>

Release Notes
-------------

#### New Features

-   Add support for the cinder v3 api. This is enabled by default, but can be disabled by setting the `cinder_enable_v3_api` variable to `false`.
-   The `cinder_sigkill_timeout` was introduced to control the time between sending a SIGTERM signal and a SIGKILL signal when stopping or restarting services. This can help in letting long-lived sessions drain while preventing new ones from starting before a restart. Default is 120 seconds (was harcoded to 300 seconds).
-   The `cinder_restart_wait` variable has been added to control the time between restarts of cinder services. Default is 5 seconds (was hardcoded to 150 seconds).
-   Haproxy-server role allows to set up tunable parameters. For doing that it is necessary to set up a dictionary of options in the config files, mentioning those which have to be changed (defaults for the remaining ones are programmed in the template). Also "maxconn" global option made to be tunable.
-   Add support for `neutron` as an `enabled_network_interface`.
-   The `ironic_neutron_provisioning_network_name` and `ironic_neutron_cleaning_network_name` variable can be set to the name of the neutron network to use for provisioning and cleaning. The ansible tasks will determine the appropriate UUID for that network. Alternatively, `ironic_neutron_provisioning_network_uuid` or `ironic_neutron_cleaning_network` can be used to directly specify the UUID of the networks. If both `ironic_neutron_provisioning_network_name` and `ironic_neutron_provisioning_network_uuid` are specified, the specified UUID will be used. If only the provisioning network is specified, the cleaning network will default to the same network.

#### Upgrade Notes

-   The `cinder_sigkill_timeout` was introduced to control the time between sending a SIGTERM signal and a SIGKILL signal when stopping or restarting services. This can help in letting long-lived sessions drain while preventing new ones from starting before a restart. Default is 120 seconds (was harcoded to 300 seconds).
-   The `cinder_restart_wait` variable has been added to control the time between restarts of cinder services. Default is 5 seconds (was hardcoded to 150 seconds).
-   During the keepalived role upgrade the keepalived process will restart and introduce a brief service disruption.

#### Critical Issues

-   A bug that caused the Keystone credential keys to be lost when the playbook is run during a rebuild of the first Keystone container has been fixed. Please see launchpad bug 1667960 for more details.

#### Other Notes

-   The keepalived role was updated, and now includes an optional way to configure vrrp scripts timeouts. See also: [VRRP timeout PR on keepalived role](https://github.com/evrardjp/ansible-keepalived/commit/0b2d13a13c1a03e14ac6f67286811ca1bf1928ac).

#### New Features

-   The `galera_client` role will default to using the `galera_repo_url` URL if the value for it is set. This simplifies using an alternative mirror for the MariaDB server and client as only one variable needs to be set to cover them both.
-   Add `get_networks` command to the neutron library. This will return network information for all networks, and fail if the specified `net_name` network is not present. If no `net_name` is specified network information will for all networks will be returned without performing a check on an existing `net_name` network.
-   The default behaviour of `ensure_endpoint` in the keystone module has changed to update an existing endpoint, if one exists that matches the service name, type, region and interface. This ensures that no duplicate service entries can exist per region.
-   The repo server file system structure has been updated to allow for multiple Operating systems running multiple architectures to be run at the same time and served from a single server without impacting pools, venvs, wheel archives, and manifests. The new structure follows the following pattern \$RELEASE/\$OS\_TYPE-\$ARCH and has been applied to *os-releases*, *venvs*, and *pools*.
-   The deployer can now define an environment variable `GROUP_VARS_PATH` with the folders of its choice (separated by the colon sign) to define an user space group\_vars folder. These vars will apply but be (currently) overriden by the OpenStack-Ansible default group vars, by the set facts, and by the user\_\* variables. If the deployer defines multiple paths, the variables found are merged, and precedence is increasing from left to right (the last defined in GROUP\_VARS\_PATH wins)
-   The deployer can now define an environment variable `HOST_VARS_PATH` with the folders of its choice (separated by the colon sign) to define an user space host\_vars folder. These vars will apply but be (currently) overriden by the OpenStack-Ansible default host vars, by the set facts, and by the user\_\* variables. If the deployer defines multiple paths, the variables found are merged, and precedence is increasing from left to right (the last defined in HOST\_VARS\_PATH wins)

#### Upgrade Notes

-   The repo server file system structure has been updated to allow for multiple Operating systems running multiple architectures to be run at the same time and served from a single server without impacting pools, venvs, wheel archives, and manifests. The new structure follows the following pattern \$RELEASE/\$OS\_TYPE-\$ARCH and has been applied to *os-releases*, *venvs*, and *pools*.

#### Deprecation Notes

-   The variables `galera_client_apt_repo_url` and `galera_client_yum_repo_url` are deprecated in favour of the common variable `galera_client_repo_url`.
-   The `update` state for the `ensure_endpoint` method of the `keystone` module is now deprecated, and will be removed in the Queens cycle. Setting state to `present` will achieve the same result.

#### New Features

-   The new provider network attribute `sriov_host_interfaces` is added to support SR-IOV network mappings inside Neutron. The provider\_network adds new items network\_sriov\_mappings and network\_sriov\_mappings\_list to the provider\_networks dictionary. Multiple interfaces can be defined by comma separation.
-   Neutron SR-IOV can now be optionally deployed and configured. For details about the what the service is and what it provides, see the [SR-IOV Installation Guide](http://docs.openstack.org/developer/openstack-ansible-os_neutron/configure-network-services.html#sr--iov-support-optional) for more information.
-   Added new variable `tempest_volume_backend_names` and updated templates/tempest.conf.j2 to point `backend_names` at this variable

#### Known Issues

-   There is currently an Ansible bug in regards to `HOSTNAME`. If the host `.bashrc` holds a var named `HOSTNAME`, the container where the `lxc_container` module attaches will inherit this var and potentially set the wrong `$HOSTNAME`. See [the Ansible fix](https://github.com/ansible/ansible/pull/22246) which will be released in Ansible version 2.3.

#### Upgrade Notes

-   Gnocchi service endpoint variables were not named correctly. Renamed variables to be consistent with other roles.

#### Deprecation Notes

-   Removed `tempest_volume_backend1_name` and `tempest_volume_backend1_name` since `backend1_name` and `backend2_name` were removed from tempest in commit 27905cc (merged 26/04/2016)

OpenStack-Ansible Roles
-----------------------

### apt\_package\_pinning

No commits were found in [apt\_package\_pinning](https://github.com/openstack/openstack-ansible-apt_package_pinning) between the OpenStack-Ansible commits provided.

### pip\_install

2 commits were found in [pip\_install](https://github.com/openstack/openstack-ansible-pip_install) from `dc91246e` to `f36af2d8`:

<table>
<col width="59%" />
<col width="40%" />
<tbody>
<tr class="odd">
<td align="left"><a href="https://github.com/openstack/openstack-ansible-pip_install/commit/f36af2d8b8b58b67368c03a60728a5231a0f6afa">f36af2d8</a></td>
<td align="left">Resolve user_external_repo deprecation warnings</td>
</tr>
<tr class="even">
<td align="left"><a href="https://github.com/openstack/openstack-ansible-pip_install/commit/9d2442963f35f409cc2adc6c21bb4ee00e454210">9d244296</a></td>
<td align="left">Fix documentation for external repos and keys</td>
</tr>
</tbody>
</table>

### galera\_client

No commits were found in [galera\_client](https://github.com/openstack/openstack-ansible-galera_client) between the OpenStack-Ansible commits provided.

### galera\_server

1 commit was found in [galera\_server](https://github.com/openstack/openstack-ansible-galera_server) from `8a8ff1c2` to `933da4ea`:

<table>
<col width="60%" />
<col width="39%" />
<tbody>
<tr class="odd">
<td align="left"><a href="https://github.com/openstack/openstack-ansible-galera_server/commit/933da4ea255e963814e8e9b7488ff8e1c6621125">933da4ea</a></td>
<td align="left">Upgrade: Make removal list distribution-specific</td>
</tr>
</tbody>
</table>

### ceph\_client

No commits were found in [ceph\_client](https://github.com/openstack/openstack-ansible-ceph_client) between the OpenStack-Ansible commits provided.

### haproxy\_server

3 commits were found in [haproxy\_server](https://github.com/openstack/openstack-ansible-haproxy_server) from `c35d6326` to `996d3c11`:

<table>
<col width="60%" />
<col width="39%" />
<tbody>
<tr class="odd">
<td align="left"><a href="https://github.com/openstack/openstack-ansible-haproxy_server/commit/996d3c1114409b5534c0389496867f67fb618a19">996d3c11</a></td>
<td align="left">Allow cert validation for hatop download to be disabled</td>
</tr>
<tr class="even">
<td align="left"><a href="https://github.com/openstack/openstack-ansible-haproxy_server/commit/b343107638983655166db763742987d91381f029">b3431076</a></td>
<td align="left">Fix service configs task</td>
</tr>
<tr class="odd">
<td align="left"><a href="https://github.com/openstack/openstack-ansible-haproxy_server/commit/903b86539f4825ff73538bbaf11c28de64e62bfd">903b8653</a></td>
<td align="left">Added Haproxy global tunables</td>
</tr>
</tbody>
</table>

### keepalived

16 commits were found in [keepalived](https://github.com/evrardjp/ansible-keepalived) from `2.1.1` to `2.6.0`:

<table>
<col width="57%" />
<col width="42%" />
<tbody>
<tr class="odd">
<td align="left"><a href="https://github.com/evrardjp/ansible-keepalived/commit/0b2d13a13c1a03e14ac6f67286811ca1bf1928ac">0b2d13a1</a></td>
<td align="left">Adding timeout attribute for check script (#41)</td>
</tr>
<tr class="even">
<td align="left"><a href="https://github.com/evrardjp/ansible-keepalived/commit/e815ac3321fa18b346680366ad155e784298821e">e815ac33</a></td>
<td align="left">Add SUSE support</td>
</tr>
<tr class="odd">
<td align="left"><a href="https://github.com/evrardjp/ansible-keepalived/commit/afb581f7fb6f1f35cf525949035a68540d52b4a7">afb581f7</a></td>
<td align="left">Fix parsing issues for the rise, fall and interval</td>
</tr>
<tr class="even">
<td align="left"><a href="https://github.com/evrardjp/ansible-keepalived/commit/80300b30700f36da391f862b81ae21cde4fcc4cc">80300b30</a></td>
<td align="left">keepalived do not need epel.</td>
</tr>
<tr class="odd">
<td align="left"><a href="https://github.com/evrardjp/ansible-keepalived/commit/eee53046b62f65c22ffb959897b83b1725f83a12">eee53046</a></td>
<td align="left">Fix latest service name</td>
</tr>
<tr class="even">
<td align="left"><a href="https://github.com/evrardjp/ansible-keepalived/commit/83fd224942832e525c9f78a09af88ea1ea77e893">83fd2249</a></td>
<td align="left">Add SELinux module for keepalived's ping cmd</td>
</tr>
<tr class="odd">
<td align="left"><a href="https://github.com/evrardjp/ansible-keepalived/commit/8066a0530bcab87ed6fb6c74960a6d3a78e6d0a3">8066a053</a></td>
<td align="left">Add CentOS 7 support</td>
</tr>
<tr class="even">
<td align="left"><a href="https://github.com/evrardjp/ansible-keepalived/commit/f5f4209d3557ddd9e0f27aa5b2470a35c10464bd">f5f4209d</a></td>
<td align="left">extended README.md with links to official GIT repo with documentation and exampl</td>
</tr>
<tr class="odd">
<td align="left"><a href="https://github.com/evrardjp/ansible-keepalived/commit/19aac686b40b324fdb7db549f20fa93c06adbd92">19aac686</a></td>
<td align="left">added optional virtual_server config</td>
</tr>
<tr class="even">
<td align="left"><a href="https://github.com/evrardjp/ansible-keepalived/commit/4f3516b39df4fdd7d85f2e749ba32cbbde9eb5a6">4f3516b3</a></td>
<td align="left">Remove ansible&lt;2.2 apt cache hack</td>
</tr>
<tr class="odd">
<td align="left"><a href="https://github.com/evrardjp/ansible-keepalived/commit/466067051fd88a6e7a0d64dcadf2974edd15ceb9">46606705</a></td>
<td align="left">Fix linting issues for ansible-lint 3.4.1</td>
</tr>
<tr class="even">
<td align="left"><a href="https://github.com/evrardjp/ansible-keepalived/commit/1e050d53b48d87114d0df46d1e5a8dbe72853eaf">1e050d53</a></td>
<td align="left">Fix typo in update apt condititional</td>
</tr>
<tr class="odd">
<td align="left"><a href="https://github.com/evrardjp/ansible-keepalived/commit/db89f04a8433ff5aef1f9f6fe7cd06b79a387fe9">db89f04a</a></td>
<td align="left">Ensure keepalived is enabled on boot</td>
</tr>
<tr class="even">
<td align="left"><a href="https://github.com/evrardjp/ansible-keepalived/commit/5e074bdab85bf0d6823267e558739ee34faa2a69">5e074bda</a></td>
<td align="left">Simplify README.md</td>
</tr>
<tr class="odd">
<td align="left"><a href="https://github.com/evrardjp/ansible-keepalived/commit/1fc760301867612b72cb8b1fd529d76ed2cb83c9">1fc76030</a></td>
<td align="left">Make sure the docs has no undefined variables</td>
</tr>
<tr class="even">
<td align="left"><a href="https://github.com/evrardjp/ansible-keepalived/commit/eec8c70c9e8e506e77bf6baeb5ca2b8a26853260">eec8c70c</a></td>
<td align="left">added optional track_interface option</td>
</tr>
</tbody>
</table>

### lxc\_container\_create

No commits were found in [lxc\_container\_create](https://github.com/openstack/openstack-ansible-lxc_container_create) between the OpenStack-Ansible commits provided.

### lxc\_hosts

No commits were found in [lxc\_hosts](https://github.com/openstack/openstack-ansible-lxc_hosts) between the OpenStack-Ansible commits provided.

### memcached\_server

No commits were found in [memcached\_server](https://github.com/openstack/openstack-ansible-memcached_server) between the OpenStack-Ansible commits provided.

### openstack-ansible-security

No commits were found in [openstack-ansible-security](https://github.com/openstack/openstack-ansible-security) between the OpenStack-Ansible commits provided.

### openstack\_hosts

No commits were found in [openstack\_hosts](https://github.com/openstack/openstack-ansible-openstack_hosts) between the OpenStack-Ansible commits provided.

### os\_keystone

1 commit was found in [os\_keystone](https://github.com/openstack/openstack-ansible-os_keystone) from `1210ef99` to `637b2e35`:

<table>
<col width="59%" />
<col width="40%" />
<tbody>
<tr class="odd">
<td align="left"><a href="https://github.com/openstack/openstack-ansible-os_keystone/commit/637b2e3526444815c795dbc3c8f2847559c13936">637b2e35</a></td>
<td align="left">Rebuild credential-key repo during keystone[0] rebuild</td>
</tr>
</tbody>
</table>

### openstack\_openrc

No commits were found in [openstack\_openrc](https://github.com/openstack/openstack-ansible-openstack_openrc) between the OpenStack-Ansible commits provided.

### os\_aodh

No commits were found in [os\_aodh](https://github.com/openstack/openstack-ansible-os_aodh) between the OpenStack-Ansible commits provided.

### os\_ceilometer

No commits were found in [os\_ceilometer](https://github.com/openstack/openstack-ansible-os_ceilometer) between the OpenStack-Ansible commits provided.

### os\_cinder

4 commits were found in [os\_cinder](https://github.com/openstack/openstack-ansible-os_cinder) from `c158191b` to `f60d5c72`:

<table>
<col width="59%" />
<col width="40%" />
<tbody>
<tr class="odd">
<td align="left"><a href="https://github.com/openstack/openstack-ansible-os_cinder/commit/f60d5c72f82979e56ac20d6b1a73b4561671d37e">f60d5c72</a></td>
<td align="left">Do a whole word grep</td>
</tr>
<tr class="even">
<td align="left"><a href="https://github.com/openstack/openstack-ansible-os_cinder/commit/ada2bfdf20c1e0e9a501b8a2a07dfd63f4b2c111">ada2bfdf</a></td>
<td align="left">Adjust cinder init restart times, provide variable</td>
</tr>
<tr class="odd">
<td align="left"><a href="https://github.com/openstack/openstack-ansible-os_cinder/commit/3147cfdbff50d94b0bafbd51b5a7f6d76e6a93ac">3147cfdb</a></td>
<td align="left">Add git to stable/newton Trusty installs</td>
</tr>
<tr class="even">
<td align="left"><a href="https://github.com/openstack/openstack-ansible-os_cinder/commit/f45d3abf18f9dbfd6800b30d8d91b2737cdc326e">f45d3abf</a></td>
<td align="left">Add support for cinder v3 api</td>
</tr>
</tbody>
</table>

### os\_glance

No commits were found in [os\_glance](https://github.com/openstack/openstack-ansible-os_glance) between the OpenStack-Ansible commits provided.

### os\_gnocchi

No commits were found in [os\_gnocchi](https://github.com/openstack/openstack-ansible-os_gnocchi) between the OpenStack-Ansible commits provided.

### os\_heat

No commits were found in [os\_heat](https://github.com/openstack/openstack-ansible-os_heat) between the OpenStack-Ansible commits provided.

### os\_horizon

No commits were found in [os\_horizon](https://github.com/openstack/openstack-ansible-os_horizon) between the OpenStack-Ansible commits provided.

### os\_ironic

2 commits were found in [os\_ironic](https://github.com/openstack/openstack-ansible-os_ironic) from `dce259e4` to `8d6bb21f`:

<table>
<col width="59%" />
<col width="40%" />
<tbody>
<tr class="odd">
<td align="left"><a href="https://github.com/openstack/openstack-ansible-os_ironic/commit/8d6bb21fc9c5c09ef069c6412721781876156d6a">8d6bb21f</a></td>
<td align="left">Add ldlinux.c32 to the tftp directory</td>
</tr>
<tr class="even">
<td align="left"><a href="https://github.com/openstack/openstack-ansible-os_ironic/commit/5d46ee5ebf5c005a567698bbd11d5a80cf0ce3a5">5d46ee5e</a></td>
<td align="left">Add support for neutron network names for cleaning/provisioning</td>
</tr>
</tbody>
</table>

### os\_magnum

No commits were found in [os\_magnum](https://github.com/openstack/openstack-ansible-os_magnum) between the OpenStack-Ansible commits provided.

### os\_neutron

No commits were found in [os\_neutron](https://github.com/openstack/openstack-ansible-os_neutron) between the OpenStack-Ansible commits provided.

### os\_nova

1 commit was found in [os\_nova](https://github.com/openstack/openstack-ansible-os_nova) from `2d234d77` to `a17358a6`:

<table>
<col width="58%" />
<col width="41%" />
<tbody>
<tr class="odd">
<td align="left"><a href="https://github.com/openstack/openstack-ansible-os_nova/commit/a17358a63c896ed48fb8aaac06f27134eed4a5f1">a17358a6</a></td>
<td align="left">Fix default live migration configuration</td>
</tr>
</tbody>
</table>

### os\_rally

2 commits were found in [os\_rally](https://github.com/openstack/openstack-ansible-os_rally) from `6697689e` to `8567b47e`:

<table>
<col width="59%" />
<col width="40%" />
<tbody>
<tr class="odd">
<td align="left"><a href="https://github.com/openstack/openstack-ansible-os_rally/commit/8567b47ec4ed6ee707073928402a65bd5968cdb7">8567b47e</a></td>
<td align="left">Bring consistency to tags</td>
</tr>
<tr class="even">
<td align="left"><a href="https://github.com/openstack/openstack-ansible-os_rally/commit/82bbbeff2eba0f33de8c9cd2a4860acaff266d82">82bbbeff</a></td>
<td align="left">Update missing database exception text</td>
</tr>
</tbody>
</table>

### os\_sahara

No commits were found in [os\_sahara](https://github.com/openstack/openstack-ansible-os_sahara) between the OpenStack-Ansible commits provided.

### os\_swift

No commits were found in [os\_swift](https://github.com/openstack/openstack-ansible-os_swift) between the OpenStack-Ansible commits provided.

### os\_tempest

1 commit was found in [os\_tempest](https://github.com/openstack/openstack-ansible-os_tempest) from `cbabcbb4` to `0a576810`:

<table>
<col width="59%" />
<col width="40%" />
<tbody>
<tr class="odd">
<td align="left"><a href="https://github.com/openstack/openstack-ansible-os_tempest/commit/0a576810ae61862185eea478b00d2fafad85a8f4">0a576810</a></td>
<td align="left">Retry the cirros image download</td>
</tr>
</tbody>
</table>

### plugins

2 commits were found in [plugins](https://github.com/openstack/openstack-ansible-plugins) from `751ebf63` to `22ac1e9c`:

<table>
<col width="58%" />
<col width="41%" />
<tbody>
<tr class="odd">
<td align="left"><a href="https://github.com/openstack/openstack-ansible-plugins/commit/22ac1e9cfb7e46239ca433330e720711ddc0ca3f">22ac1e9c</a></td>
<td align="left">Add Packages file parsing lookup</td>
</tr>
<tr class="even">
<td align="left"><a href="https://github.com/openstack/openstack-ansible-plugins/commit/811062b54a1946e0a42e317d9e4470955c99a7c1">811062b5</a></td>
<td align="left">Always update existing matching endpoints</td>
</tr>
</tbody>
</table>

### rabbitmq\_server

No commits were found in [rabbitmq\_server](https://github.com/openstack/openstack-ansible-rabbitmq_server) between the OpenStack-Ansible commits provided.

### repo\_build

No commits were found in [repo\_build](https://github.com/openstack/openstack-ansible-repo_build) between the OpenStack-Ansible commits provided.

### repo\_server

No commits were found in [repo\_server](https://github.com/openstack/openstack-ansible-repo_server) between the OpenStack-Ansible commits provided.

### rsyslog\_client

1 commit was found in [rsyslog\_client](https://github.com/openstack/openstack-ansible-rsyslog_client) from `fa9904c7` to `56ca566e`:

<table>
<col width="60%" />
<col width="39%" />
<tbody>
<tr class="odd">
<td align="left"><a href="https://github.com/openstack/openstack-ansible-rsyslog_client/commit/56ca566ef024603b2fbfd3d0b7af6d844e26884a">56ca566e</a></td>
<td align="left">Fix remote logging template</td>
</tr>
</tbody>
</table>

### rsyslog\_server

No commits were found in [rsyslog\_server](https://github.com/openstack/openstack-ansible-rsyslog_server) between the OpenStack-Ansible commits provided.

### sshd

No commits were found in [sshd](https://github.com/willshersystems/ansible-sshd) between the OpenStack-Ansible commits provided.

### bird

No commits were found in [bird](https://github.com/logan2211/ansible-bird) between the OpenStack-Ansible commits provided.

### etcd

No commits were found in [etcd](https://github.com/logan2211/ansible-etcd) between the OpenStack-Ansible commits provided.

### unbound

No commits were found in [unbound](https://github.com/logan2211/ansible-unbound) between the OpenStack-Ansible commits provided.

### resolvconf

No commits were found in [resolvconf](https://github.com/logan2211/ansible-resolvconf) between the OpenStack-Ansible commits provided.

Connects https://github.com/rcbops/rpc-openstack/issues/2125

### CODE REVIEW

**Comment by cloader89** [comment]
recheck_all

**Comment by alextricity25** [comment]
recheck_all

**Comment by alextricity25** [comment]
recheck_cit_all

**Comment by major** [comment]
Ceph error:
```
fatal: [ramcp-89-42a5_ceph_mon_container-174ac33e]: FAILED! => {"failed": true, "msg": "The conditional check 'check_firewall and item.rc == 0 and mon_group_name is defined and mon_group_name in group_names and nmapexist.rc == 0' failed. The error was: error while evaluating conditional (check_firewall and item.rc == 0 and mon_group_name is defined and mon_group_name in group_names and nmapexist.rc == 0): 'dict object' has no attribute 'rc'\n\nThe error appears to have been in '/etc/ansible/roles/ceph.ceph-common/tasks/checks/check_firewall.yml': line 27, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: fail if monitor port is filtered\n  ^ here\n"}
```

**Comment by cloader89** [comment]
recheck_cit_ceph

**Comment by cloader89** [comment]
``fatal: [ramsp-82-fe96_rabbit_mq_container-4a45cf15]: FAILED! => {"failed": true, "msg": "The conditional check 'cinder_backends['lvm'] is defined' failed. The error was: error while evaluating conditional (cinder_backends['lvm'] is defined): 'cinder_backends' is undefined\n\nThe error appears to have been in '/opt/rpc-openstack/rpcd/playbooks/roles/rpc_maas/tasks/main.yml': line 71, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- include: ensure_local_checks.yml\n  ^ here\n"} ``

**Comment by alextricity25** [comment]
Blocked by: https://github.com/rcbops/u-suk-dev/issues/1552

**Comment by alextricity25** [comment]
recheck_cit_swift
recheck_cit_xenial

**Comment by alextricity25** [comment]
recheck_cit_ceph

**Comment by cloader89** [comment]
Update on ceph issue: There was a task being run that Ansible 2.1.5 could not handle. We disabled the check_firewall in the ceph role.

https://github.com/rcbops/rpc-openstack/pull/2145

**Comment by cjloader** [comment]
recheck_cit_all

**Comment by cjloader** [comment]
recheck_cit_swift
recheck_cit_ceph

**Comment by alextricity25** [comment]
Now we are getting a different error, but it's consistent across all three cit jobs for this PR:
```
fatal: [ramcp-117-2152_rabbit_mq_container-84beb0fc]: FAILED! => {"failed": true, "msg": "The conditional check 'cinder_backends['lvm'] is defined' failed. The error was: error while evaluating conditional (cinder_backends['lvm'] is defined): 'cinder_backends' is undefined\n\nThe error appears to have been in '/opt/rpc-openstack/rpcd/playbooks/roles/rpc_maas/tasks/main.yml': line 71, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- include: ensure_local_checks.yml\n  ^ here\n"}
```

**Comment by alextricity25** [comment]
recheck_cit_all

**Comment by alextricity25** [comment]
recheck_cit_xenial

**Comment by alextricity25** [comment]
Need one more review on this one, please :)

**Pull request merged**
