### PR TITLE
[Backport Mitaka-13.1] Adds check for neutron service venv

### PR DESCRIPTION
**Pull request by dankolbrs**
This checks all neutron services to ensure using the proper
virtual environment for the openstack release. Reports fail
on any neutron service not running via correct venv.

This cherry pick includes correcting variable used of
"neutron_venv_bin" which had a bad copy/pasta using swift
variable.

Connects rcbops/u-suk-dev#857

(cherry picked from commit fc40fa13146d4e685e97733bcd495dd38a61eac0)

### CODE REVIEW

**Comment by git-harry** [comment]
recheck_cit_upgrade

**Comment by dankolbrs** [comment]
failure on upgrade was maas setup.

recheck_cit_upgrade

**Comment by dankolbrs** [comment]
recheck_cit_all

**Comment by dankolbrs** [comment]
recheck_cit_all

**Comment by alextricity25** [comment]
recheck_cit_upgrade

**Comment by mattt416** [comment]
recheck_cit_upgrade

**Comment by dankolbrs** [comment]
Looks like tempest cinder_backup fail, which is resolved https://github.com/rcbops/rpc-gating/pull/163 and build 113 reported as a successful build.

recheck_cit_upgrade

**Comment by dankolbrs** [comment]
`jenkinsapi.custom_exceptions.JenkinsAPIException: Unable to iterate nodes` failure, [existing issue](https://github.com/rcbops/u-suk-dev/issues/1649)

recheck_cit_upgrade

**Comment by dankolbrs** [comment]
recheck_cit_upgrade

**Comment by dankolbrs** [comment]
recheck_cit_upgrade

**Comment by dankolbrs** [comment]
recheck_cit_upgrade - Tempest defcore cinder_backup fail

**Comment by dankolbrs** [comment]
recheck_cit_upgrade - selenium failure

**Comment by dankolbrs** [comment]
Cinder failure related to #2258

**Comment by dankolbrs** [comment]
recheck_cit_upgrade - rolling the dice

**Comment by dankolbrs** [comment]
recheck_cit_upgrade - Fail was not from cinder, and was a jenkins error:
```
Resuming build at Thu May 18 16:55:09 GMT 2017 after Jenkins restart
Waiting to resume part of RPC-AIO_mitaka-upgrade-pr #129: ???
Waiting to resume part of RPC-AIO_mitaka-upgrade-pr #129: There are no nodes with the label ‘rpc-jenkins-n02.prod.dfw1.cit.rackspace.net-9082c1d1’
Waiting to resume part of RPC-AIO_mitaka-upgrade-pr #129: There are no nodes with the label ‘rpc-jenkins-n02.prod.dfw1.cit.rackspace.net-9082c1d1’
Waiting to resume part of RPC-AIO_mitaka-upgrade-pr #129: There are no nodes with the label ‘rpc-jenkins-n02.prod.dfw1.cit.rackspace.net-9082c1d1’
Waiting to resume part of RPC-AIO_mitaka-upgrade-pr #129: There are no nodes with the label ‘rpc-jenkins-n02.prod.dfw1.cit.rackspace.net-9082c1d1’
Waiting to resume part of RPC-AIO_mitaka-upgrade-pr #129: rpc-jenkins-n02.prod.dfw1.cit.rackspace.net-9082c1d1 is offline
Ready to run at Thu May 18 16:55:31 GMT 2017
Timeout set to expire in 4 hr 10 min
Cannot contact rpc-jenkins-n02.prod.dfw1.cit.rackspace.net-9082c1d1: java.io.IOException: remote file operation failed: /var/lib/jenkins/workspace/RPC-AIO_mitaka-upgrade-pr@2/rpc-gating/playbooks at hudson.remoting.Channel@187fc218:Channel to /10.24.58.41: hudson.remoting.ChannelClosedException: channel is already closed
Aborted by Melissa Kam
Could not connect to rpc-jenkins-n02.prod.dfw1.cit.rackspace.net-9082c1d1 to send interrupt signal to process
```

**Comment by dankolbrs** [comment]
recheck_cit_upgrade

**Comment by dankolbrs** [comment]
recheck_cit_upgrade

**Comment by dankolbrs** [comment]
recheck_cit_upgrade - `TEMPEST FAIL scenario defcore cinder_backup (308 tests)`

**Comment by dankolbrs** [comment]
recheck_cit_upgrade - cinder_backup has been disabled on gating, this should pass now

**Comment by dankolbrs** [comment]
The commit 5c845d2c58d7b843eeada89ba31eb2f85d9979be was added as it was found in an AIO, the host is included in the `neutron_all` group. The previous method of `inventory_hostname in groups['utility'][0]` would result in what was expected to run on the utility container to be attempted on the AIO host. This would then fail tests intended for the utility node due to the host not having the openstack client or openrc file required.

**Comment by dankolbrs** [comment]
Updated commit message

**Comment by dankolbrs** [comment]
Merged for test-requirements fix which resolves Travis build issue ^

**Comment by dankolbrs** [comment]
recheck_cit_upgrade - unrelated failure.
```TASK: [rsyslog_client | Update apt if needed] ********************************* 
[0;31mfailed: [ramup-151-d5ef] => {"failed": true}[0m
[0;31mmsg: Could not fetch updated apt files[0m
[0;31m
FATAL: all hosts have already failed -- aborting[0m```

**Comment by dankolbrs** [comment]
closing this in preference to #2225

**Pull request closed without merging**
