### PR TITLE
RO-4367 Update master dependencies

### PR DESCRIPTION
**Pull request by rpc-jenkins-svc**
Automated dependency update pull request, see individual commits for details.

Issue: [RO-4367](https://rpc-openstack.atlassian.net/browse/RO-4367)

### CODE REVIEW

**Comment by prometheanfire** [comment]
recheck_cit_xenial_no_artifacts_swift_deploy

**Comment by prometheanfire** [comment]
recheck-cit_xenial_no_artifacts_swift_deploy

**Comment by prometheanfire** [comment]
recheck_xenial_no_artifacts_swift_deploy

**Comment by prometheanfire** [comment]
recheck_xenial_no_artifacts_swift_deploy

**Comment by prometheanfire** [comment]
recheck_xenial_no_artifacts_swift_deploy

**Comment by mattt416** [comment]
Re-checking this again is probably not going to help until the following is resolved:

```14:20:30 TASK [logstash : Deploy Logstash configuration files] **************************
14:20:31 changed: [aio1_logstash_container-6eb3813c] => (item=01-input.conf)
14:20:32 changed: [aio1_logstash_container-6eb3813c] => (item=02-general.conf)
14:20:33 changed: [aio1_logstash_container-6eb3813c] => (item=03-nova.conf)
14:20:34 changed: [aio1_logstash_container-6eb3813c] => (item=04-neutron.conf)
14:20:34 changed: [aio1_logstash_container-6eb3813c] => (item=05-glance.conf)
14:20:35 changed: [aio1_logstash_container-6eb3813c] => (item=06-cinder.conf)
14:20:36 changed: [aio1_logstash_container-6eb3813c] => (item=07-libvirt.conf)
14:20:37 changed: [aio1_logstash_container-6eb3813c] => (item=08-apache.conf)
14:20:37 changed: [aio1_logstash_container-6eb3813c] => (item=09-heat.conf)
14:20:38 changed: [aio1_logstash_container-6eb3813c] => (item=10-mysql.conf)
14:20:39 changed: [aio1_logstash_container-6eb3813c] => (item=11-auth.conf)
14:20:40 changed: [aio1_logstash_container-6eb3813c] => (item=12-logstash.conf)
14:20:41 changed: [aio1_logstash_container-6eb3813c] => (item=13-swift.conf)
14:20:41 changed: [aio1_logstash_container-6eb3813c] => (item=14-keystone.conf)
14:20:43 changed: [aio1_logstash_container-6eb3813c] => (item=15-beaver.conf)
14:20:43 changed: [aio1_logstash_container-6eb3813c] => (item=16-elasticsearch.conf)
14:20:44 changed: [aio1_logstash_container-6eb3813c] => (item=17-rabbitmq.conf)
14:20:45 changed: [aio1_logstash_container-6eb3813c] => (item=18-ceph.conf)
14:20:45 changed: [aio1_logstash_container-6eb3813c] => (item=19-nginx.conf)
14:20:46 changed: [aio1_logstash_container-6eb3813c] => (item=20-magnum.conf)
14:20:47 changed: [aio1_logstash_container-6eb3813c] => (item=21-octavia.conf)
14:20:48 changed: [aio1_logstash_container-6eb3813c] => (item=98-traceback.conf)
14:20:48 failed: [aio1_logstash_container-6eb3813c] (item=99-output.conf) => {"changed": false, "item": "99-output.conf", "msg": "AnsibleError: An unhandled exception occurred while templating '{{ hostvars[groups['elasticsearch'][0]]['container_address'] }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'first_found'. Error was a <class 'ansible.errors.AnsibleLookupError'>, original message: No file was found when using with_first_found. Use the 'skip: true' option to allow this task to be skipped if no files are found"}```

**Comment by cjloader** [comment]
recheck_xenial_no_artifacts_swift_deploy

**Comment by cjloader** [comment]
recheck_release

**Pull request merged**
