### PR TITLE
RO-2433 Remove untested role from rpco

### PR DESCRIPTION
**Pull request by cloudnull**
The openstack-ops role is untested and under active development. Until
this role can be stabalized, is no longer being force pushed against
and has some testing it should not be part of the rpco product
offering. If this role is being used by folks in the support
organization it can cloned and installed as needed outside the confinds
of the RPCO prodcut offering.

Signed-off-by: Kevin Carter <kevin.carter@rackspace.com>

### CODE REVIEW

**Comment by mattt416** [comment]
Is the plan to remove this all the way down?  We'll probably want to adjust https://github.com/rcbops/rpc-gating/blob/master/rpc_jobs/rpc_aio.yml#L95 accordingly before this merges otherwise we'll get periodic failures as a result.

**Comment by cloudnull** [comment]
@mattt416 I'd say yes we would want to remove this all of the way down. If we're not using this and its not being developed by engineering/has no testing then it should be completely excised from the code base. We can re-introduce this role and its bits once we have a stable-ish role to consume.

**Comment by major** [comment]
@BjoernT or @npawelek -- Do either of you know who maintains or owns the openstack-ops repository? We've had some issues with disappearing SHAs that have blocked the RPC-O gates for extended periods.

I'm inclined to take this role out until we figure out a good way to test commits in that repo.

**Comment by BjoernT** [comment]
Yes take it out. Maintaining is on me.

**Comment by odyssey4me** [comment]
The rpc-gating PR to remove all traces of the support role and holland testing is here: https://github.com/rcbops/rpc-gating/pull/405

**Comment by odyssey4me** [comment]
For the record, a card has been registered to make this new testing gap clear: https://rpc-openstack.atlassian.net/browse/RO-2440

**Comment by major** [comment]
recheck_cit_xenial_deploy_swift

The new changes to gating should help this change pass.

**Comment by odyssey4me** [comment]
recheck_cit_artifact

**Pull request merged**
