### PR TITLE
Adding new F5 upgrade script from RPC10 to RPC 11

### PR DESCRIPTION
**Pull request by hughsaunders**
This script will generate tmsh commands to execute the changes
necessary in order to migration to RPC11

### CODE REVIEW

**Comment by hughsaunders** [comment]
This is a rebase of @BjoernT's pr #819

**Comment by hughsaunders** [comment]
@BjoernT legit lint fail

**Comment by prometheanfire** [comment]
This depends on #833 (same commit via rebase), #833 can/should merge first but this can merge immediately after so we don't have to wait on rebase/aio (avoids waiting 2-3 hours), like upstream's dependant reviews.

**Comment by prometheanfire** [comment]
recheck - cirros fail

    18:08:48 TASK: [os_tempest | Ensure cirros image] **************************************

**Comment by d34dh0r53** [comment]
```ansible
19:24:10 TASK: [os_tempest | Ensure cirros image] ************************************** 
19:24:10 failed: [jrpcaioiad-511_utility_container-ccc26af4] => {"failed": true, "parsed": false}
19:24:10 OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
19:24:10 debug1: Reading configuration data /etc/ssh/ssh_config
19:24:10 debug1: /etc/ssh/ssh_config line 19: Applying options for *
19:24:10 debug1: auto-mux: Trying existing master
19:24:10 debug1: mux_client_request_session: master session id: 2
19:24:10 Traceback (most recent call last):
19:24:10   File "<stdin>", line 1848, in <module>
19:24:10   File "<stdin>", line 1845, in main
19:24:10   File "<stdin>", line 1765, in route
19:24:10   File "<stdin>", line 1818, in create_image
19:24:10   File "/usr/local/lib/python2.7/dist-packages/glanceclient/v1/images.py", line 319, in create
19:24:10     data=image_data)
19:24:10   File "/usr/local/lib/python2.7/dist-packages/glanceclient/common/http.py", line 265, in post
19:24:10     return self._request('POST', url, **kwargs)
19:24:10   File "/usr/local/lib/python2.7/dist-packages/glanceclient/common/http.py", line 230, in _request
19:24:10     raise exc.from_response(resp, resp.text)
19:24:10 glanceclient.exc.HTTPException: 504 Gateway Time-out: The server didn't respond in time. (HTTP N/A)
19:24:10 
19:24:10 
19:24:10 FATAL: all hosts have already failed -- aborting
```

**Comment by d34dh0r53** [comment]
recheck - cirros fail again

**Comment by prometheanfire** [comment]
recheck - cirros fail

**Comment by prometheanfire** [comment]
:+1: this should go into 11.1.4 imo

**Comment by prometheanfire** [comment]
is https://github.com/rcbops/rpc-openstack/issues/482 and https://github.com/rpcdocs/docs-issues/issues/100 fixed by this?

**Comment by d34dh0r53** [comment]
:+1:

**Comment by BjoernT** [comment]
d34dh0r53: yes it will fix docs issue 100

**Pull request merged**
