### PR TITLE
Update f5-monitor.sh to monitor keystonev3

### PR DESCRIPTION
**Pull request by prometheanfire**
The f5-monitors need updating for mitaka, so we do that here.

Connects https://github.com/rcbops/u-suk-dev/issues/264

### CODE REVIEW

**Comment by andymcc** [comment]
👍 change LGTM.

**Comment by andymcc** [comment]
Oh 1 tiny change - can you change the commit message to have f5-monitor.sh rather than f5-moonitor.sh

**Comment by evrardjp** [comment]
yup it boothers me too.
The rest is doing what it needs to be doing.

**Comment by prometheanfire** [comment]
now with less moo

**Comment by sigmavirus24** [comment]
👍

**Comment by git-harry** [comment]
Did this change get validated in a hardware lab? I can find no comment anywhere confirming that happened.

**Comment by prometheanfire** [comment]
yes, http://ip:port/v3

**Pull request merged**
