### PR TITLE
Update pre_redeploy.sh

### PR DESCRIPTION
**Pull request by weezer**
add --force into the ansible-galaxy cmd to make sure we have the roles we need, and avoid roles already exist error.

### CODE REVIEW

**Comment by evrardjp** [comment]
recheck_cit_trusty_leapfrogupgrade_swift

**Comment by evrardjp** [comment]
Depends on https://github.com/rcbops/rpc-openstack/pull/2411

**Comment by weezer** [comment]
LGTM

**Comment by evrardjp** [comment]
Depends on https://github.com/rcbops/rpc-openstack/pull/2414

**Comment by evrardjp** [comment]
recheck_cit_trusty_leapfrogupgrade_swift

**Comment by evrardjp** [comment]
recheck_cit_artifact_xenial_apt

**Comment by evrardjp** [comment]
recheck_cit_trusty_leapfrogupgrade_swift

**Comment by evrardjp** [comment]
Finally passed!

**Pull request merged**
