### PR TITLE
Ensure rackspace-monitoring-agent restarts delegate to physical hosts

### LINKED ISSUE #588: `rackspace-monitoring-agent` service restart fails in containers
The change introduced in PR #572 ensures handlers are flushed, and thus `rackspace-monitoring-agent` is restarted. Previously, the agent restarts were delegated to the physical host for containers, as the agent is only installed on the physical hosts. This critical piece is missing, so agent restarts lead to the playbooks failing.

```
TASK: [rpc_maas | Restart rackspace-monitoring-agent service] ***************** 
changed: [5d551fe2-compute1]
changed: [5d551fe2-infra1]
changed: [5d551fe2-logger1]
changed: [5d551fe2-block1]
changed: [5d551fe2-object1]
failed: [5d551fe2-infra1_nova_cert_container-6e52f1f6] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-infra1_galera_container-2aee94aa] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-infra1_glance_container-46b0a4f4] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-infra1_galera_container-3eee7389] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-infra1_neutron_agents_container-a8007a22] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-infra1_rabbit_mq_container-579777da] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-infra1_cinder_scheduler_container-6cdcc1a7] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-infra1_nova_api_metadata_container-0afa7103] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-infra1_rabbit_mq_container-b8942266] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-infra1_keystone_container-e2b0fd59] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-infra1_nova_console_container-3031e036] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-infra1_memcached_container-3ceef055] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-infra1_nova_scheduler_container-33b8cedf] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-infra1_nova_api_os_compute_container-fa0608ae] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-infra1_rabbit_mq_container-4c8cd600] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-infra1_heat_engine_container-8dcc1e57] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-infra1_utility_container-ef61a275] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-infra1_neutron_server_container-134435a6] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-infra1_nova_conductor_container-320a04a8] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-logger1_elasticsearch_container-18eb911f] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-infra1_swift_proxy_container-dcdf6a6e] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-infra1_cinder_api_container-ff64047c] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-logger1_logstash_container-8a6f4648] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-infra1_horizon_container-756d77de] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-infra1_galera_container-145e0889] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-logger1_kibana_container-95912198] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-infra1_repo_container-edc74fa2] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-infra1_heat_apis_container-caadbfbd] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
failed: [5d551fe2-logger1_rsyslog_container-f8c4d90a] => {"failed": true}
msg: no service or tool found for: rackspace-monitoring-agent
```

### PR DESCRIPTION
**Pull request by byronmccollum**
Fixes #588

### CODE REVIEW

**Comment by byronmccollum** [comment]
I might change `delegate_to` to `when: is_metal is true`...

**Comment by git-harry** [comment]
+1

**Comment by byronmccollum** [comment]
Rebased

**Comment by byronmccollum** [comment]
Rebased

**Comment by d34dh0r53** [comment]
:+1:

**Pull request merged**
