### PR TITLE
OSA SHA bump to Mitaka

### PR DESCRIPTION
**Pull request by mancdaz**
This is using the current head of stable/mitaka for OSA, and includes the minimum change necessary to make rpc-o master switch over to using OSA mitaka.

Connects https://github.com/rcbops/u-suk-dev/issues/160

### CODE REVIEW

**Comment by git-harry** [comment]
The commit message will need updating before this is merged.

**Comment by d34dh0r53** [comment]
```
16:50:50 TASK: [galera_client | Add galera apt-keys] *********************************** 
16:50:50 ok: [jrpcaioiad-3b0] => (item={'key_name': 'mariadb', 'hash_id': '0xcbcb082a1bb943db', 'keyserver': 'hkp://keyserver.ubuntu.com:80', 'fallback_keyserver': 'hkp://p80.pool.sks-keyservers.net:80'})
16:51:03 failed: [jrpcaioiad-3b0_neutron_agents_container-046b01e6] => (item={'key_name': 'mariadb', 'hash_id': '0xcbcb082a1bb943db', 'keyserver': 'hkp://keyserver.ubuntu.com:80', 'fallback_keyserver': 'hkp://p80.pool.sks-keyservers.net:80'}) => {"attempts": 5, "cmd": "apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv CBCB082A1BB943DB", "failed": true, "item": {"fallback_keyserver": "hkp://p80.pool.sks-keyservers.net:80", "hash_id": "0xcbcb082a1bb943db", "key_name": "mariadb", "keyserver": "hkp://keyserver.ubuntu.com:80"}, "rc": 2}
16:51:03 stderr: gpg: requesting key 1BB943DB from hkp server keyserver.ubuntu.com
16:51:03 gpg: no valid OpenPGP data found.
16:51:03 gpg: Total number processed: 0
16:51:03 
16:51:03 stdout: Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.9xD9MzGXR5 --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv CBCB082A1BB943DB
16:51:03 gpgkeys: key CBCB082A1BB943DB can't be retrieved
16:51:03 
16:51:03 msg: Task failed as maximum retries was encountered
16:51:03 failed: [jrpcaioiad-3b0_neutron_server_container-2c2e729a] => (item={'key_name': 'mariadb', 'hash_id': '0xcbcb082a1bb943db', 'keyserver': 'hkp://keyserver.ubuntu.com:80', 'fallback_keyserver': 'hkp://p80.pool.sks-keyservers.net:80'}) => {"attempts": 5, "cmd": "apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv CBCB082A1BB943DB", "failed": true, "item": {"fallback_keyserver": "hkp://p80.pool.sks-keyservers.net:80", "hash_id": "0xcbcb082a1bb943db", "key_name": "mariadb", "keyserver": "hkp://keyserver.ubuntu.com:80"}, "rc": 2}
16:51:03 stderr: gpg: requesting key 1BB943DB from hkp server keyserver.ubuntu.com
16:51:03 gpg: no valid OpenPGP data found.
16:51:03 gpg: Total number processed: 0
16:51:03 
16:51:03 stdout: Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.iG3AQcfKpF --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv CBCB082A1BB943DB
16:51:03 gpgkeys: key CBCB082A1BB943DB can't be retrieved
16:51:03 
16:51:03 msg: Task failed as maximum retries was encountered
16:51:03 
16:51:03 FATAL: all hosts have already failed -- aborting
```
Keyserver issues, I'm seeing the same thing in my testing, will try again in a few as this is usually temporary.

**Comment by git-harry** [comment]
recheck_all

**Comment by d34dh0r53** [comment]
recheck_all

**Comment by d34dh0r53** [comment]
Failing on SSH, everything worked locally for me.

**Comment by d34dh0r53** [comment]
recheck_all

**Comment by d34dh0r53** [comment]
MaaS is failing to add a keystone user:

```
22:27:55 TASK: [rpc_maas | Create keystone user for monitoring] ************************ 
22:27:55 skipping: [jrpcaioiad-30_elasticsearch_container-1c528255]
22:27:55 skipping: [jrpcaioiad-30_nova_cert_container-91709d63]
22:27:55 skipping: [jrpcaioiad-30_neutron_server_container-a76968c5]
22:27:55 skipping: [jrpcaioiad-30_neutron_agents_container-6e431a80]
22:27:55 skipping: [jrpcaioiad-30_nova_api_os_compute_container-a22d3aaf]
22:27:55 skipping: [jrpcaioiad-30_nova_conductor_container-d82f661f]
22:27:55 skipping: [jrpcaioiad-30_ceph_osd_container-b0105c1a]
22:27:55 skipping: [jrpcaioiad-30_rsyslog_container-3062a266]
22:27:55 skipping: [jrpcaioiad-30_ceph_mon_container-b12ca565]
22:27:55 skipping: [jrpcaioiad-30_horizon_container-e568a342]
22:27:55 skipping: [jrpcaioiad-30_cinder_scheduler_container-bd602e36]
22:27:55 skipping: [jrpcaioiad-30_repo_container-e8dcfee1]
22:27:55 skipping: [jrpcaioiad-30_nova_api_metadata_container-87ed9b8f]
22:27:55 skipping: [jrpcaioiad-30_nova_console_container-b3a23eca]
22:27:55 skipping: [jrpcaioiad-30_galera_container-b7b27df5]
22:27:55 skipping: [jrpcaioiad-30_ceph_osd_container-e5d2ee8d]
22:27:55 skipping: [jrpcaioiad-30_ceph_mon_container-7b1ddbf8]
22:27:55 skipping: [jrpcaioiad-30_memcached_container-fb1e78ac]
22:27:55 skipping: [jrpcaioiad-30_heat_engine_container-93b0dc02]
22:27:55 skipping: [jrpcaioiad-30_nova_scheduler_container-8621138b]
22:27:55 skipping: [jrpcaioiad-30_keystone_container-89de8c02]
22:27:55 skipping: [jrpcaioiad-30_logstash_container-212d7524]
22:27:55 skipping: [jrpcaioiad-30_glance_container-ff1cc2fb]
22:27:55 skipping: [jrpcaioiad-30_kibana_container-d49ebb5a]
22:27:55 skipping: [jrpcaioiad-30_cinder_api_container-68506bc8]
22:27:55 skipping: [jrpcaioiad-30_ceph_osd_container-324b0064]
22:27:55 skipping: [jrpcaioiad-30_rabbit_mq_container-5ddeba40]
22:27:55 skipping: [jrpcaioiad-30_ceph_mon_container-86a74acb]
22:27:55 skipping: [jrpcaioiad-30_heat_apis_container-bc22e308]
22:27:56 skipping: [jrpcaioiad-30]
22:27:56 failed: [jrpcaioiad-30_utility_container-26d4a433] => {"failed": true, "parsed": false}
22:27:56 OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
22:27:56 debug1: Reading configuration data /etc/ssh/ssh_config
22:27:56 debug1: /etc/ssh/ssh_config line 19: Applying options for *
22:27:56 debug1: auto-mux: Trying existing master
22:27:56 debug1: Control socket "/jenkins/.ansible/cp/ansible-ssh-172.29.238.169-22-root" does not exist
22:27:56 debug1: Connecting to 172.29.238.169 [172.29.238.169] port 22.
22:27:56 debug1: fd 3 clearing O_NONBLOCK
22:27:56 debug1: Connection established.
22:27:56 debug1: permanently_set_uid: 0/0
22:27:56 debug1: identity file /root/.ssh/id_rsa type 1
22:27:56 debug1: identity file /root/.ssh/id_rsa-cert type -1
22:27:56 debug1: identity file /root/.ssh/id_dsa type -1
22:27:56 debug1: identity file /root/.ssh/id_dsa-cert type -1
22:27:56 debug1: identity file /root/.ssh/id_ecdsa type -1
22:27:56 debug1: identity file /root/.ssh/id_ecdsa-cert type -1
22:27:56 debug1: identity file /root/.ssh/id_ed25519 type -1
22:27:56 debug1: identity file /root/.ssh/id_ed25519-cert type -1
22:27:56 debug1: Enabling compatibility mode for protocol 2.0
22:27:56 debug1: Local version string SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.7
22:27:56 debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.7
22:27:56 debug1: match: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.7 pat OpenSSH_6.6.1* compat 0x04000000
22:27:56 debug1: SSH2_MSG_KEXINIT sent
22:27:56 debug1: SSH2_MSG_KEXINIT received
22:27:56 debug1: kex: server->client aes128-ctr hmac-md5-etm@openssh.com zlib@openssh.com
22:27:56 debug1: kex: client->server aes128-ctr hmac-md5-etm@openssh.com zlib@openssh.com
22:27:56 debug1: sending SSH2_MSG_KEX_ECDH_INIT
22:27:56 debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
22:27:56 debug1: Server host key: ECDSA c6:a3:66:a8:39:f8:e4:27:b9:fd:8f:a4:2d:c0:01:7d
22:27:56 debug1: Host '172.29.238.169' is known and matches the ECDSA host key.
22:27:56 debug1: Found key in /root/.ssh/known_hosts:5
22:27:56 debug1: ssh_ecdsa_verify: signature correct
22:27:56 debug1: SSH2_MSG_NEWKEYS sent
22:27:56 debug1: expecting SSH2_MSG_NEWKEYS
22:27:56 debug1: SSH2_MSG_NEWKEYS received
22:27:56 debug1: SSH2_MSG_SERVICE_REQUEST sent
22:27:56 debug1: SSH2_MSG_SERVICE_ACCEPT received
22:27:56 debug1: Authentications that can continue: publickey
22:27:56 debug1: Next authentication method: publickey
22:27:56 debug1: Offering RSA public key: /root/.ssh/id_rsa
22:27:56 debug1: Server accepts key: pkalg ssh-rsa blen 279
22:27:56 debug1: key_parse_private2: missing begin marker
22:27:56 debug1: read PEM private key done: type RSA
22:27:56 debug1: Enabling compression at level 6.
22:27:56 debug1: Authentication succeeded (publickey).
22:27:56 Authenticated to 172.29.238.169 ([172.29.238.169]:22).
22:27:56 debug1: setting up multiplex master socket
22:27:56 debug1: channel 0: new [/jenkins/.ansible/cp/ansible-ssh-172.29.238.169-22-root]
22:27:56 debug1: control_persist_detach: backgrounding master process
22:27:56 debug1: forking to background
22:27:56 debug1: Entering interactive session.
22:27:56 debug1: multiplexing control connection
22:27:56 debug1: channel 1: new [mux-control]
22:27:56 debug1: channel 2: new [client-session]
22:27:56 debug1: Sending environment.
22:27:56 debug1: Sending env LANG = en_US.UTF-8
22:27:56 debug1: Sending command: /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'
22:27:56 debug1: mux_client_request_session: master session id: 2
22:27:56 Traceback (most recent call last):
22:27:56   File "<stdin>", line 2922, in <module>
22:27:56   File "<stdin>", line 1304, in main
22:27:56   File "<stdin>", line 460, in command_router
22:27:56   File "<stdin>", line 715, in ensure_user
22:27:56   File "<stdin>", line 580, in _get_domain_from_vars
22:27:56   File "<stdin>", line 587, in _get_domain
22:27:56   File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v3/domains.py", line 60, in list
22:27:56     return super(DomainManager, self).list(**kwargs)
22:27:56   File "/usr/local/lib/python2.7/dist-packages/keystoneclient/base.py", line 75, in func
22:27:56     return f(*args, **new_kwargs)
22:27:56   File "/usr/local/lib/python2.7/dist-packages/keystoneclient/base.py", line 383, in list
22:27:56     self.collection_key)
22:27:56   File "/usr/local/lib/python2.7/dist-packages/keystoneclient/base.py", line 124, in _list
22:27:56     resp, body = self.client.get(url, **kwargs)
22:27:56   File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 173, in get
22:27:56     return self.request(url, 'GET', **kwargs)
22:27:56   File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 331, in request
22:27:56     resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
22:27:56   File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 98, in request
22:27:56     return self.session.request(url, method, **kwargs)
22:27:56   File "/usr/local/lib/python2.7/dist-packages/positional/__init__.py", line 94, in inner
22:27:56     return func(*args, **kwargs)
22:27:56   File "/usr/local/lib/python2.7/dist-packages/keystoneclient/session.py", line 420, in request
22:27:56     raise exceptions.from_response(resp, method, url)
22:27:56 keystoneauth1.exceptions.http.Unauthorized: The request you have made requires authentication. (HTTP 401) (Request-ID: req-eded2264-ff6d-418e-82ac-49734557c74f)
22:27:56 debug1: client_input_channel_req: channel 2 rtype exit-status reply 0
22:27:56 debug1: channel 2: free: client-session, nchannels 3
22:27:56 debug1: channel 1: free: mux-control, nchannels 2
22:27:56 
```

MaaS is unauthorized, not sure why.

**Comment by evrardjp** [comment]
recheck_all

**Comment by evrardjp** [comment]
-- Build timeout

**Comment by d34dh0r53** [comment]
recheck_all

**Comment by d34dh0r53** [comment]
So locally I'm getting the following error:

```
TASK: [Verify Checks & Alarms are registered] *********************************
failed: [d34d-1174] => {"attempts": 10, "changed": false, "failed": true, "failed_when_result": true, "rc": 1, "stdout_lines": ["Traceback (most recent call last):", "  File \"/root/.ansible/tmp/ansible-tmp-1466531524.06-176688763513993/rpc-maas-tool.py\", line 29, in <module>", "    import concurrent.futures", "ImportError: No module named concurrent.futures"]}
stderr: OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 172.29.236.100 closed.

stdout: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1466531524.06-176688763513993/rpc-maas-tool.py", line 29, in <module>
    import concurrent.futures
ImportError: No module named concurrent.futures

msg: Task failed as maximum retries was encountered

FATAL: all hosts have already failed -- aborting
```
And it's taking about 20 minutes to throw that error.

**Comment by d34dh0r53** [comment]
So I'm really not sure what it causing this to timeout.  Locally when I run `verify-maas` I'm seeing slightly different output at the very beginning of the play:

#### Local Run
```
openstack-ansible verify-maas.yml
Variable files: "-e @/etc/openstack_deploy/user_conf_files.yml -e @/etc/openstack_deploy/user_extras_secrets.yml -e @/etc/openstack_deploy/user_extras_variables.yml -e @/etc/openstack_deploy/user_secrets.yml -e @/etc/openstack_deploy/user_variables.yml "

PLAY [Verify MaaS setup] ******************************************************

GATHERING FACTS ***************************************************************
ok: [d34d-1174]

TASK: [Verify Checks & Alarms are registered] *********************************
```
Whereas in the gate we just see this:
#### Gate Run
```
22:33:00 + openstack-ansible --forks 4 verify-maas.yml
22:33:00 Variable files: "-e @/etc/openstack_deploy/user_conf_files.yml -e @/etc/openstack_deploy/user_extras_secrets.yml -e @/etc/openstack_deploy/user_extras_variables.yml -e @/etc/openstack_deploy/user_secrets.yml -e @/etc/openstack_deploy/user_variables.yml "
22:53:00 Build timed out (after 20 minutes). Marking the build as aborted.
22:53:00 Build was aborted
````

@hughsaunders do you have any idea what is suppressing the ansible output from the beginning of the play?  I was hoping that by dropping the timeouts of the two steps of the play we would see the failure output of `verify-maas` but that doesn't seem to be the case.

**Comment by evrardjp** [comment]
Found the gate issue with @hughsaunders. 
I'll send a separate commit to fix it. We'll need to rebase.

I found an issue with cinder checks in maas too - same procedure.

**Comment by evrardjp** [comment]
recheck_all

**Comment by hughsaunders** [comment]
So.. This is failing is because there aren't enough nodes in the rabbitm

```
--- 2016-06-22 13:27:43.830390 ---
All expected checks and alarms are present
--- 2016-06-22 13:31:03.209968 ---
Checks and Alarms with failures:
 - Entity:enV35ee3GG:jrpcaioiad-5dd
   ! Check:agent.plugin:chhXjGE934:rabbitmq_status--jrpcaioiad-5dd-rabbit-mq-container-3bbc4d02: Completed:False Status:error cluster too small
     ! Alarm:alChYXQfge:rabbitmq_fd_used_alarm_status-jrpcaioiad-5dd-rabbit-mq-container-3bbc4d02:CRITICAL
     ! Alarm:alGdcrRUX2:rabbitmq_disk_free_alarm_status--jrpcaioiad-5dd-rabbit-mq-container-3bbc4d02:CRITICAL
     ! Alarm:alKajwUQSt:rabbitmq_socket_used_alarm_status--jrpcaioiad-5dd-rabbit-mq-container-3bbc4d02:CRITICAL
     ! Alarm:alWE1crIyx:rabbitmq_proc_used_alarm_status--jrpcaioiad-5dd-rabbit-mq-container-3bbc4d02:CRITICAL
     ! Alarm:alWfgX0KZV:rabbitmq_qgrowth_excl_notifications--jrpcaioiad-5dd-rabbit-mq-container-3bbc4d02:CRITICAL
     ! Alarm:alqVkPct2X:rabbitmq_msgs_excl_notifications--jrpcaioiad-5dd-rabbit-mq-container-3bbc4d02:CRITICAL
     ! Alarm:alvQEx3RAn:rabbitmq_max_channels_per_conn--jrpcaioiad-5dd-rabbit-mq-container-3bbc4d02:CRITICAL
     ! Alarm:alxAyhdVxp:rabbitmq_mem_alarm_status--jrpcaioiad-5dd-rabbit-mq-container-3bbc4d02:CRITICAL
--- 2016-06-22 13:34:27.851938 ---
Checks and Alarms with failures:
 - Entity:enV35ee3GG:jrpcaioiad-5dd
   ! Check:agent.plugin:chhXjGE934:rabbitmq_status--jrpcaioiad-5dd-rabbit-mq-container-3bbc4d02: Completed:False Status:error cluster too small
     ! Alarm:alChYXQfge:rabbitmq_fd_used_alarm_status-jrpcaioiad-5dd-rabbit-mq-container-3bbc4d02:CRITICAL
     ! Alarm:alGdcrRUX2:rabbitmq_disk_free_alarm_status--jrpcaioiad-5dd-rabbit-mq-container-3bbc4d02:CRITICAL
     ! Alarm:alKajwUQSt:rabbitmq_socket_used_alarm_status--jrpcaioiad-5dd-rabbit-mq-container-3bbc4d02:CRITICAL
     ! Alarm:alWE1crIyx:rabbitmq_proc_used_alarm_status--jrpcaioiad-5dd-rabbit-mq-container-3bbc4d02:CRITICAL
     ! Alarm:alWfgX0KZV:rabbitmq_qgrowth_excl_notifications--jrpcaioiad-5dd-rabbit-mq-container-3bbc4d02:CRITICAL
     ! Alarm:alqVkPct2X:rabbitmq_msgs_excl_notifications--jrpcaioiad-5dd-rabbit-mq-container-3bbc4d02:CRITICAL
     ! Alarm:alvQEx3RAn:rabbitmq_max_channels_per_conn--jrpcaioiad-5dd-rabbit-mq-container-3bbc4d02:CRITICAL
     ! Alarm:alxAyhdVxp:rabbitmq_mem_alarm_status--jrpcaioiad-5dd-rabbit-mq-container-3bbc4d02:CRITICAL
```

**Comment by d34dh0r53** [comment]
recheck_all

**Comment by mancdaz** [comment]
The affinity for galera and rabbit containers in the openstack_user_config.yml.aio in osa changed from 3 in liberty to 1 in mitaka. For the rpc-o gate we will need to either change the maas test to expect 1, or edit the affinity back to 3.

**Comment by d34dh0r53** [comment]
@mancdaz one of the changes in this PR is to change the affinity back to 3

**Comment by d34dh0r53** [comment]
I've been trying to recreate the error with little success, I'm not actually registering any rabbitmq checks on my AIO when running `setup-maas`.  Based on the rabbitmq artifact logs it looks like all three nodes are happily running in the cluster, I have a feeling that none of the checks are registering and it's alerting on everything related to rabbit.

@hughsaunders is there any way to look at what checks are registered in MaaS while the gate is running?

**Comment by evrardjp** [comment]
@d34dh0r53 my latest commit should fix this. 
The check is doing its work correctly, but with latest osa mitaka hostname changes, we need to adapt the check. This was documented into the commit message.

**Comment by evrardjp** [comment]
recheck_ceph

**Comment by d34dh0r53** [comment]
```
14:44:36 TASK: [galera_client | Add galera apt-keys] *********************************** 
14:45:08 failed: [jrpcaioiad-899] => (item={'key_name': 'mariadb', 'hash_id': '0xcbcb082a1bb943db', 'keyserver': 'hkp://keyserver.ubuntu.com:80', 'fallback_keyserver': 'hkp://p80.pool.sks-keyservers.net:80'}) => {"attempts": 5, "cmd": "apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv CBCB082A1BB943DB", "failed": true, "item": {"fallback_keyserver": "hkp://p80.pool.sks-keyservers.net:80", "hash_id": "0xcbcb082a1bb943db", "key_name": "mariadb", "keyserver": "hkp://keyserver.ubuntu.com:80"}, "rc": 2}
14:45:08 stderr: gpg: requesting key 1BB943DB from hkp server keyserver.ubuntu.com
14:45:08 gpg: no valid OpenPGP data found.
14:45:08 gpg: Total number processed: 0
14:45:08 
14:45:08 stdout: Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.raTIMZrlBx --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv CBCB082A1BB943DB
14:45:08 gpgkeys: key CBCB082A1BB943DB can't be retrieved
14:45:08 
14:45:08 msg: Task failed as maximum retries was encountered
14:45:09 failed: [jrpcaioiad-899_cinder_scheduler_container-46098f63] => (item={'key_name': 'mariadb', 'hash_id': '0xcbcb082a1bb943db', 'keyserver': 'hkp://keyserver.ubuntu.com:80', 'fallback_keyserver': 'hkp://p80.pool.sks-keyservers.net:80'}) => {"attempts": 5, "cmd": "apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv CBCB082A1BB943DB", "failed": true, "item": {"fallback_keyserver": "hkp://p80.pool.sks-keyservers.net:80", "hash_id": "0xcbcb082a1bb943db", "key_name": "mariadb", "keyserver": "hkp://keyserver.ubuntu.com:80"}, "rc": 2}
14:45:09 stderr: gpg: requesting key 1BB943DB from hkp server keyserver.ubuntu.com
14:45:09 gpg: no valid OpenPGP data found.
14:45:09 gpg: Total number processed: 0
14:45:09 
14:45:09 stdout: Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.YbozAjg0tU --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv CBCB082A1BB943DB
14:45:09 gpgkeys: key CBCB082A1BB943DB can't be retrieved
14:45:09 
14:45:09 msg: Task failed as maximum retries was encountered
14:45:09 failed: [jrpcaioiad-899_cinder_api_container-41b1641f] => (item={'key_name': 'mariadb', 'hash_id': '0xcbcb082a1bb943db', 'keyserver': 'hkp://keyserver.ubuntu.com:80', 'fallback_keyserver': 'hkp://p80.pool.sks-keyservers.net:80'}) => {"attempts": 5, "cmd": "apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv CBCB082A1BB943DB", "failed": true, "item": {"fallback_keyserver": "hkp://p80.pool.sks-keyservers.net:80", "hash_id": "0xcbcb082a1bb943db", "key_name": "mariadb", "keyserver": "hkp://keyserver.ubuntu.com:80"}, "rc": 2}
14:45:09 stderr: gpg: requesting key 1BB943DB from hkp server keyserver.ubuntu.com
14:45:09 gpg: no valid OpenPGP data found.
14:45:09 gpg: Total number processed: 0
14:45:09 
14:45:09 stdout: Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.vndq4CB0l8 --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv CBCB082A1BB943DB
14:45:09 gpgkeys: key CBCB082A1BB943DB can't be retrieved
14:45:09 
14:45:09 msg: Task failed as maximum retries was encountered
14:45:09 
14:45:09 FATAL: all hosts have already failed -- aborting
```

Key-Server Error, should be temporary.

**Comment by d34dh0r53** [comment]
recheck_ceph

**Comment by Apsu** [comment]
RPC-AIO-Ceph-Liberty-PR: Fail

**Comment by evrardjp** [comment]
@Apsu thanks for the ping, I'll investigate right away.

**Comment by evrardjp** [comment]
recheck_ceph

**Comment by Apsu** [comment]
RPC-AIO-Ceph-Liberty-PR: Pass

**Comment by alextricity25** [comment]
:+1:

**Comment by sigmavirus24** [comment]
🎉

**Comment by sigmavirus24** [comment]
Seriously though, 👍 but I haven't tested it. My 👀 best not deceive me.

**Comment by evrardjp** [comment]
@sigmavirus24 it's probably gonna be deceiving, but now we can do real work :p

**Pull request merged**
