### PR TITLE
This fix will add a F5 upgrade script for liberty only - novnc, closes #771

### LINKED ISSUE #771: Make novnc the default console in RPC13 and later
For more info see

https://review.openstack.org/#/c/228197/

### PR DESCRIPTION
**Pull request by BjoernT**
This PR will add a F5 upgrade script to add the new VIPS and pools necessary to migrate to RPC12 from RPC11. Currently this compromises only the addition of NoVNC console support.

Product milestone still open, I heard we want to target this for 12.2

Related-Bug: #771

### CODE REVIEW

**Comment by prometheanfire** [comment]
not sure how this is related to #771

**Comment by prometheanfire** [comment]
@BjoernT ?

**Comment by prometheanfire** [comment]
so this needs to target wherever novnc targets?

**Comment by BjoernT** [comment]
correct

**Comment by nrb** [comment]
Can we get a more detailed commit message? What/why is being upgraded for Liberty and why is it only there?

**Comment by BjoernT** [comment]
@nrb Is the commit message now ok for you ?

**Comment by nrb** [comment]
@BjoernT Yep, the content of the commit message is more clear, thanks.

**Comment by BjoernT** [comment]
Updated format of the commit message

**Comment by prometheanfire** [comment]
Thanks for updating the commit message.  The first word of the title should be in the imperative present tense.  Add instead of adding, but I still like it :P

**Comment by prometheanfire** [comment]
https://github.com/rcbops/rpc-openstack/blob/master/CONTRIBUTING.md#commits-pull-requests-and-reviews

**Comment by BjoernT** [comment]
@prometheanfire 
??? what now. Is my mood not imperative enough ;-)
I got the link already from git-harry yesterday.

**Comment by prometheanfire** [comment]
it's imperative, but not present (time wise).  Adding is 'present perfect' tense, Add is simply 'present' tense.

**Comment by BjoernT** [comment]
@prometheanfire You just brought it to a new level...

**Comment by prometheanfire** [comment]
thanks, these are just the kernel commit guidelines and we've coppied them

:+1:

**Comment by BjoernT** [comment]
lol http://www.wired.com/wp-content/uploads/blogs/wiredenterprise/wp-content/uploads//2012/06/Screen-shot-2012-06-18-at-10.32.45-AM.png

**Comment by prometheanfire** [comment]
ya, just like that, used to have that as my wallpaper

**Comment by BjoernT** [comment]
Yeah that was an epic topic

**Comment by prometheanfire** [comment]
recheck_upgrade

**Comment by prometheanfire** [comment]
failed on 17:14:37 TASK: [os_tempest | Ensure cirros image] **************************************

**Comment by prometheanfire** [comment]
recheck_upgrade - 21:00:05 tempest.scenario.test_dashboard_basic_ops.TestDashboardBasicOps.test_basic_scenario[dashboard,id-4f8851b1-0e69-482b-b63b-84c6e76f6c80]

**Comment by git-harry** [comment]
:-1: 

This seems so be a partial implementation of the enabling of noVNC. The commit message is misleading because it implies that it is required by a Kilo to Liberty upgrade and the name of the script also implies that. The original f5-config.py script is not modified so I'm not clear on how a new deployment is supposed to have it's F5 correctly configured.

**Comment by BjoernT** [comment]
Moved into master branch

**Pull request closed without merging**
