### PR TITLE
[backport-13.1] UG-543 Verifies Orchestration

### PR DESCRIPTION
**Pull request by dankolbrs**
Adds verification Orchestration service post upgrade in existing
test format. Also includes Orchestration in pre-upgrade check.

(cherry picked from commit 69269b40cd47e48d89d5938f3be5ab9989aaaf47)

Also includes a change for preupgrade to use `heat service-list`
as the openstack version available in liberty does not include
full orchestration support.

### CODE REVIEW

**Comment by dankolbrs** [comment]
recheck_cit_upgrade
recheck_cit_majorupgrade
- mirror fails

**Comment by dankolbrs** [comment]
recheck_cit_upgrade
recheck_cit_majorupgrade

**Comment by mattt416** [comment]
This looks like a legitimate failure:

```
TASK: [rpc_pre_upgrade | Gather orchestration service list] ******************* 
[0;31mfailed: [localhost -> rammp-13-b7b7_utility_container-63658709] => {"changed": true, "cmd": "source ~/openrc; openstack orchestration service list --insecure", "delta": "0:00:00.827288", "end": "2017-06-02 15:29:16.532870", "rc": 2, "start": "2017-06-02 15:29:15.705582", "warnings": []}[0m
[0;31mstdout: openstack: 'orchestration' is not an openstack command. See 'openstack --help'.
Did you mean one of these?
  configuration show[0m
[0;31m
FATAL: all hosts have already failed -- aborting[0m
```

**Comment by dankolbrs** [comment]
hm.. in testing I found it true for liberty, but worked after upgrade to mitaka.

**Comment by dankolbrs** [comment]
recheck_cit_ceph - TEMPEST FAIL scenario defcore (304 tests)

**Pull request merged**
