### PR TITLE
Add MaaS Alarms for swift replication time

### PR DESCRIPTION
**Pull request by andymcc**
Add a rate increase alarm for object/container/account replication
Add an average time threshold alarm for object/container/account
replication.

Closes-Issue: #655

### CODE REVIEW

**Comment by prometheanfire** [comment]
where were these check values sourced from, are they sane defaults?

**Comment by andymcc** [comment]
@prometheanfire not particularly, we don't have well calculated defaults since we haven't got any production data to go by - but as a start this will work and we can adjust the defaults at a later point if they turn out to be flawed.

**Comment by tomc603** [comment]
Given we have no historical data to base these on, and that we need to start somewhere, I'm OK with this. :+1:

**Comment by d34dh0r53** [comment]
:+1:

**Pull request merged**
