### PR TITLE
update ceph shas

### LINKED ISSUE #797: Ceph SHA bump for ceph #506
Just a reminder to bump the SHA once https://github.com/ceph/ceph-ansible/issues/506 has been merged. The desired commit is
https://github.com/mattt416/ceph-ansible/commit/0dab4084467a0194abaa2cd20496962c00f0d49c 

- [x] Liberty #811
- [x] Kilo #820

### PR DESCRIPTION
**Pull request by prometheanfire**
closes #797

### CODE REVIEW

**Comment by prometheanfire** [comment]
recheck

**Comment by d34dh0r53** [comment]
Sorry, after lunch tired/distractedness caused me to merge this, rather than revert I'm going to ask for forgiveness.  Besides this is a straightforward backport so :+1:

**Comment by nrb** [comment]
Forgiveness granted, though I lack context as to what was actually being accomplished with these SHA bumps in either liberty or kilo. The initial issue only says to update SHAs, not what issue is being addressed by doing so.

**Comment by prometheanfire** [comment]
we wanted this

https://github.com/mattt416/ceph-ansible/commit/0dab4084467a0194abaa2cd20496962c00f0d49c

**Pull request merged**
