### PR TITLE
Add bash syntax check to lint script

### PR DESCRIPTION
**Pull request by hughsaunders**
This addition loops over all (ba)sh scripts and runs a bash syntax check
on them. This should help catch some scripting errors.

Also removes the localhost only inventory as it wasn't working as
expected. Ansible was not recieving the input properly and was
generating the skeleton inventory itself. I have made this expclicit by
passing /dev/null as the inventory.

### CODE REVIEW

**Comment by hughsaunders** [comment]
That didn't go well then :(

**Comment by hughsaunders** [comment]
Better, turns out the travis ci version of grep reads stdin if no path is specified, even when -r is given.

**Comment by nrb** [comment]
Could this be done with bashate, like it is upstream? Looks like there's a WIP here: https://github.com/rcbops/rpc-openstack/pull/465

**Comment by sigmavirus24** [comment]
+1 in my opinion for bashate.

**Comment by hughsaunders** [comment]
Opinion seems to go in favour of bashate and @d34dh0r53's #465, so closing this pr.

**Pull request closed without merging**
