### PR TITLE
Deploy.sh has the option to install rally

### PR DESCRIPTION
**Pull request by vhe182**
###### For each pull request, update the branch line to reference it.
- [x] master
- [ ] mitaka-13.1
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [x] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been created or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [x] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [x] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [x] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

Connects https://github.com/rcbops/rpc-openstack/issues/1705

### CODE REVIEW

**Comment by alextricity25** [comment]
This will also need to be backported to the newton-14.0 branch, right?

**Comment by vhe182** [comment]
True, @alextricity25, this needs to be backported to Newton.  I'll add that issue now

**Comment by alextricity25** [comment]
This PR needs to resolve merge conflicts before it can merge.

**Comment by vhe182** [comment]
@alextricity25 Thanks for the notice, I'll fix this today.

**Comment by vhe182** [comment]
@alextricity25 All good to go.

**Comment by alextricity25** [comment]
@vhe182 Thanks!
We'll just need one more review on this PR, then we can merge it.

**Comment by vhe182** [comment]
@besanradwan or @meteorfox willing to review?

**Pull request merged**
