### PR TITLE
Update SHA to allow Swift to clean up nodes

### PR DESCRIPTION
**Pull request by prometheanfire**
This SHA update includes an update to Swift that allows it to remove
zero weight object nodes.

Related-Bug: #878
(cherry picked from commit 8e1c34760ccd8cf43bd4a122444141b2da994857)
Signed-off-by: Matthew Thode <mthode@mthode.org>

### CODE REVIEW

**Comment by prometheanfire** [comment]
recheck_upgrade

**Comment by prometheanfire** [comment]
recheck_upgrade

**Comment by git-harry** [comment]
Closing in favour of https://github.com/rcbops/rpc-openstack/pull/1057 based on the upgrade failure this pull request is experiencing, see https://github.com/rcbops/rpc-openstack/issues/1058.

**Comment by d34dh0r53** [comment]
:+1:

**Comment by tomc603** [comment]
Nice. 👍

**Pull request merged**
