### PR TITLE
Disable upgrade.sh for r13.0.0

### PR DESCRIPTION
**Pull request by git-harry**
The next major release is the first in RPCO with support for Mitaka. The
release will not support upgrading from Liberty. The purpose of this
commit is to prevent any unintended consequenses from mistakenly running
upgrade.sh on an existing deployment.

Connects rcbops/u-suk-dev#158

### CODE REVIEW

**Comment by prometheanfire** [comment]
do we want to exit 1 here?

**Comment by prometheanfire** [comment]
Oh, to make sure it yells at people who run it.  :+1: then

**Comment by git-harry** [comment]
New commit required due to need to rebase.

**Comment by evrardjp** [comment]
Not tested but looks good to me
👍

**Comment by sigmavirus24** [comment]
👍 looks great to me.

**Pull request merged**
