### PR TITLE
[backport-14.0] UG-543 Verifies Orchestration

### PR DESCRIPTION
**Pull request by dankolbrs**
Adds verification Orchestration service post upgrade using exiting
testing style. Also includes Orchestration in pre-upgrade check.

(cherry picked from commit 69269b40cd47e48d89d5938f3be5ab9989aaaf47)

### CODE REVIEW

**Comment by mattt416** [comment]
recheck_cit_ceph

**Comment by dankolbrs** [comment]
recheck_cit_ceph
unrelated failure
```
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/rcbops/rpc-gating
```

**Comment by dankolbrs** [comment]
refresh_cit_upgrade - build completed successfully but not updating status

**Comment by dankolbrs** [comment]
refresh_cit_ceph -build completed successfully but not updating status

**Comment by dankolbrs** [comment]
successful build failed to update status. Closing and reopening PR

**Comment by dankolbrs** [comment]
recheck_cit_swift - tempest fail

**Pull request merged**
