### PR TITLE
RO-4397 Update rocky dependencies

### PR DESCRIPTION
**Pull request by rpc-jenkins-svc**
Automated dependency update pull request, see individual commits for details.

Issue: [RO-4397](https://rpc-openstack.atlassian.net/browse/RO-4397)

### CODE REVIEW

**Comment by antonym** [comment]
recheck_container_ansible-lint_tox-test
recheck_container_ansible-syntax_tox-test

**Comment by antonym** [comment]
```
2019-02-19T11:29:00-0600 awk: cannot open /var/lib/jenkins/workspace/PR_rpc-openstack-rocky-container-ansible-lint-tox-test/rpc-openstack/.gitreview (No such file or directory)
2019-02-19T11:29:00-0600 ERROR: InvocationError for command '/bin/bash -c /var/lib/jenkins/workspace/PR_rpc-openstack-rocky-container-ansible-lint-tox-test/rpc-openstack/tests/common/test-ansible-lint.sh' (exited with code 2)

2019-02-19T11:28:57-0600 awk: cannot open /var/lib/jenkins/workspace/PR_rpc-openstack-rocky-container-ansible-syntax-tox-test/rpc-openstack/.gitreview (No such file or directory)
2019-02-19T11:28:57-0600 ERROR: InvocationError for command '/bin/bash -c /var/lib/jenkins/workspace/PR_rpc-openstack-rocky-container-ansible-syntax-tox-test/rpc-openstack/tests/common/test-ansible-syntax.sh' (exited with code 2)
```

**Comment by antonym** [comment]
@odyssey4me I'm guessing https://github.com/openstack/openstack-ansible-tests/commit/bb9d690eb09360fe03bf16bcfa0ffa2e2e8f5826#diff-10ec9b386ddcaeee06b0c1284d336b57R53 changed the behavior... do we need to alter the working_dir here locally?

**Comment by odyssey4me** [comment]
@antonym I would recommend just pinning openstack-ansible-tests. Its use in OSA is going to be removed, most likely by the release of Stein. Trying to use it for RPC-O lint testing is a ticking time bomb.

**Comment by antonym** [comment]
recheck_bionic_no_artifacts_swift_deploy
recheck_container_ansible-lint_tox-test
recheck_container_ansible-syntax_tox-test

**Pull request merged**
