### PR TITLE
switch from sudo to become (fixes lint)

### PR DESCRIPTION
**Pull request by prometheanfire**

### CODE REVIEW

**Comment by hughsaunders** [comment]
recheck - this job was waiting too long for a node

**Comment by prometheanfire** [comment]
recheck

has to be on another line

**Comment by hughsaunders** [comment]
recheck 

Failed on hash sum mismatch and pycrypto install, I don't think they are related.

**Comment by hughsaunders** [comment]
:+1:

**Comment by mancdaz** [comment]
:+1:

**Pull request merged**
