### PR TITLE
ASC-387 update qtest publish

### PR DESCRIPTION
**Pull request by zreichert**
Issue: [ASC-387](https://rpc-openstack.atlassian.net/browse/ASC-387)

### CODE REVIEW

**Comment by zreichert** [comment]
recheck_xenial_no_artifacts_swift_deploy

**Comment by zreichert** [comment]
recheck_xenial_no_artifacts_swift_deploy

**Comment by mattt416** [comment]
recheck_issue_link

**Comment by chundu** [comment]
This PR won't impact product and only impacts system test result upload. Merge it for now.

**Pull request merged**
