### PR TITLE
Update SHAs for r11.1.2

### PR DESCRIPTION
**Pull request by d34dh0r53**
This PR updates the `openstack-ansible`, `ceph-common`, `ceph-mon`
and `ceph-osd` to:

* `openstack-ansible` version 11.2.8
* `ceph-common` master
* `ceph-mon` master
* `ceph-osd` master

### CODE REVIEW

**Comment by prometheanfire** [comment]
neat

**Comment by prometheanfire** [comment]
:+1:

**Comment by byronmccollum** [comment]
Should this go into master first?

**Comment by d34dh0r53** [comment]
Nope, master is `liberty`

**Comment by byronmccollum** [comment]
Oh, I was talking about the Ceph SHAs...

**Comment by d34dh0r53** [comment]
Yeah, Ceph SHAs will go into master once #578 merges.

**Comment by odyssey4me** [comment]
@d34dh0r53 does that new tag even build? It looks to me like the carried BDM patch needs an update. See https://github.com/openstack/openstack-ansible/blob/11.2.8/playbooks/defaults/repo_packages/openstack_services.yml#L96 vs https://github.com/rcbops/rpc-openstack/blob/kilo/rpcd/patches/nova-lp-bug-1457527.patch#L36

As part of carrying that patch, you have have to continually keep the review rebased in nova - and then also update that patch every time, otherwise RPC will never be using an updated nova SHA - it'll stay static.

**Comment by byronmccollum** [comment]
The patch does not apply.

```
PLAY [Patch upstream files] *************************************************** 

TASK: [patcher | Apply patch files] ******************************************* 
failed: [127.0.0.1] => (item=nova-lp-bug-1457527.patch) => {"failed": true, "item": "nova-lp-bug-1457527.patch"}
msg: 1 out of 1 hunk FAILED


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/patcher.retry

127.0.0.1                  : ok=0    changed=0    unreachable=0    failed=1   
```

**Comment by byronmccollum** [comment]
Opened #774

**Pull request merged**
