### PR TITLE
ASC-951 add molecule results to artifacts

### PR DESCRIPTION
**Pull request by zreichert**

### CODE REVIEW

**Comment by ryan-rs** [comment]
recheck_release

**Comment by ryan-rs** [comment]
recheck_xenial_no_artifacts_swift_deploy

**Comment by ryan-rs** [comment]
recheck_xenial_no_artifacts_swift_deploy

**Comment by odyssey4me** [comment]
FYI master is currently blocked upstream. The fix is https://review.openstack.org/600025 which is blocked due to an opensuse mirror issue. It's being worked on and will hopefully be resolved today.

**Comment by odyssey4me** [comment]
recheck_xenial_no_artifacts_swift_deploy upstream is now unblocked

**Comment by ryan-rs** [comment]
:shipit:

**Pull request merged**
