### PR TITLE
Configure maas to use artifacted repo

### PR DESCRIPTION
**Pull request by odyssey4me**
Connects https://github.com/rcbops/u-suk-dev/issues/1657

### CODE REVIEW

**Comment by odyssey4me** [comment]
recheck_cit_swift

**Comment by odyssey4me** [comment]
recheck_cit_artifact_trusty_Apt

**Comment by odyssey4me** [comment]
@evrardjp Sure, once I've confirmed that it works properly I'll submit patches to rpc-o master and rpc_maas to ensure that the changes endure.

**Comment by evrardjp** [comment]
alternatively we could rebase on master.

**Comment by evrardjp** [comment]
Keeping the user variables change in a commit, having a commit in rpc-maas, rebase on master, bump of the sha of rpc-maas in a-r-r in a different commit, that's it!

**Comment by evrardjp** [comment]
Waiting the linked changes to happen, but looks good!

**Comment by odyssey4me** [comment]
@evrardjp The linked changes? This will have no effect until the rpc-maas change merges, and even then it won't affect anything until this branch is rebased. The deploy fails now, so merging this changes nothing and there is therefore no reason to wait for anything else. :)

**Comment by evrardjp** [comment]
Agreed with you there.

**Comment by odyssey4me** [comment]
OK, instead of rebasing on master (which is a little complicated right now), I'll cherry-pick the rpc-maas inception into this branch then adjust the rpc-maas role SHA once the other patch merges.

**Comment by evrardjp** [comment]
Yeah good.

**Comment by odyssey4me** [comment]
recheck_cit_artifact_trusty_Apt

**Pull request merged**
