### PR TITLE
Remove variables that are already set as defaults

### PR DESCRIPTION
**Pull request by prometheanfire**
This is a cleanup patch

### CODE REVIEW

**Comment by cloudnull** [comment]
:+1:  however the gate looks very angry

**Comment by cloudnull** [comment]
recheck_cit_all

**Comment by git-harry** [comment]
recheck_container_ansible-lint_tox-test
recheck_container_ansible-syntax_tox-test
recheck_container_bashate_tox-test
recheck_container_pep8_tox-test
recheck_container_releasenotes_tox-test

**Comment by prometheanfire** [comment]
recheck_xenial_no_artifacts_swift_deploy

**Comment by prometheanfire** [comment]
recheck_xenial_no_artifacts_swift_deploy

**Comment by cjloader** [comment]
01:03:58 failed: [aio1_utility_container-ca1fc7eb -> localhost] (item={u'url': u'http://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img', u'checksum': u'sha256:e137062a4dfbb4c225971b67781bc52183d14517170e16a3841d16f962ae7470', u'name': u'cirros', u'format': u'qcow2'}) => {"attempts": 5, "changed": false, "extra_data": null, "item": {"checksum": "sha256:e137062a4dfbb4c225971b67781bc52183d14517170e16a3841d16f962ae7470", "format": "qcow2", "name": "cirros", "url": "http://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img"}, "msg": "HttpException: 503: Server Error for url: http://172.29.236.100:9292/images/detail, <html><body><h1>503 Service Unavailable</h1>\nNo server is available to handle this request.\n</body></html>\n"}

recheck_xenial_no_artifacts_swift_deploy

**Comment by odyssey4me** [comment]
recheck_xenial_no_artifacts_swift_deploy

**Comment by prometheanfire** [comment]
recheck_xenial_no_artifacts_swift_deploy

same error as cam's stuff, gating issue?

**Comment by odyssey4me** [comment]
The task failing is the upload to glance. It looks like glance is returning a 503, so it's broken.

**Comment by prometheanfire** [comment]
looks like we set image cache dir to None, and then had caching enabled.  So I removed that override as there's no justification for it anymore.

```
commit 041416cff486b245a3b4ae03bb52f82ad1b436ba
Author: Bjoern Teipel <bjoern.teipel@rackspace.com>
Date:   Mon May 23 09:24:10 2016 -0500

    Disable glance image cache

    The glance image cache is now disabled, primarily to prevent container
    filesystems to fill up with temporary glance operations like uploading
    images from cinder into glance.

    Closes-Bug: #1005
```

**Comment by prometheanfire** [comment]
review approved, merging, will backport to rocky

**Pull request merged**
