### PR TITLE
Add monitoring for holland backups

### PR DESCRIPTION
**Pull request by BjoernT**
The MaaS plugin `holland_local_check.py` is added to
monitor the status of previous holland backups.
The plugin expects at least one completed backupset
for the previous day. Holland is running local Galera
Backups on each container once daily.
The metrics `holland_backup_size` (Mega Bytes) and
`holland_backup_status` (Boolean) are provided to
monitor holland.

Connects #1506

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/staging.horse/build-010bb61afa/docs/private-cloud/release-notes/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/staging.horse/build-4a4938be18/docs/private-cloud/release-notes/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/staging.horse/build-fd87a411e8/docs/private-cloud/release-notes/).

**Comment by BjoernT** [comment]
recheck_all

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/staging.horse/build-ebf27983f3/docs/private-cloud/release-notes/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/staging.horse/build-9e349303c7/docs/private-cloud/release-notes/)

**Comment by d34dh0r53** [comment]
```
19:21:33 failed: [jrpcaioiad-b43] => {"attempts": 5, "changed": false, "cmd": ". /openstack/venvs/maas-r13.1.0rc1/bin/activate\n /opt/rpc-openstack/scripts/rpc-maas-tool.py verify-local", "delta": "0:00:31.792523", "end": "2016-10-26 19:21:32.984147", "failed": true, "failed_when_result": true, "rc": 1, "start": "2016-10-26 19:21:01.191624", "stdout_lines": ["The following metrics are required by alarms but not produced by any checks: set(['holland_backup_status'])", "The following checks failed to execute or didn't return 'okay' as their status: [('holland_local_check--jrpcaioiad-b43-galera-container-ab52f086', 'status error Could not find Holland backup from 20161025\\n'), ('holland_local_check--jrpcaioiad-b43-galera-container-227f4241', 'status error Could not find Holland backup from 20161025\\n'), ('holland_local_check--jrpcaioiad-b43-galera-container-15dd5948', 'status error Could not find Holland backup from 20161025\\n')]"], "warnings": []}
19:21:33 stdout: The following metrics are required by alarms but not produced by any checks: set(['holland_backup_status'])
19:21:33 The following checks failed to execute or didn't return 'okay' as their status: [('holland_local_check--jrpcaioiad-b43-galera-container-ab52f086', 'status error Could not find Holland backup from 20161025\n'), ('holland_local_check--jrpcaioiad-b43-galera-container-227f4241', 'status error Could not find Holland backup from 20161025\n'), ('holland_local_check--jrpcaioiad-b43-galera-container-15dd5948', 'status error Could not find Holland backup from 20161025\n')]
19:21:33 
19:21:33 FATAL: all hosts have already failed -- aborting
```

I'm not sure that we do Holland backups in the gate, perhaps @hughsaunders can verify.

**Comment by BjoernT** [comment]
@d34dh0r53 We can actually add a holland bk test case so we have backup during gating or we need to exclude this check from the verify-maas.yml

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/staging.horse/build-78e5fbb716/docs/private-cloud/release-notes/)

**Comment by BjoernT** [comment]
recheck_ceph

Died with ```
19:36:33 After this operation, 136 MB of additional disk space will be used.
19:36:33 WARNING: The following packages cannot be authenticated!
19:36:33   qpress
````

**Comment by BjoernT** [comment]
recheck_all

**Comment by BjoernT** [comment]
The issue is related to
```
W: GPG error: https://repo.percona.com trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9334A25F8507EFA5
```
possibly caused after updating the fingerprint for percona repo inside the galera server role

**Comment by cloader89** [comment]
@BjoernT The sha has been updated recently, a rebase couldn't hurt if you want to try, this error was happening 2 weeks ago.

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/staging.horse/build-5510af265b/docs/private-cloud/release-notes/)

**Comment by BjoernT** [comment]
recheck_all

**Comment by BjoernT** [comment]
recheck_all

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/staging.horse/build-d3b752d9ba/docs/private-cloud/release-notes/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/staging.horse/build-1ffe92e394/docs/private-cloud/release-notes/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/staging.horse/build-8394dc1d43/docs/private-cloud/release-notes/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/staging.horse/build-07c6676e1c/docs/private-cloud/release-notes/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/staging.horse/build-dea3fb534a/docs/private-cloud/release-notes/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/staging.horse/build-e7f1de1081/docs/private-cloud/release-notes/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/staging.horse/build-b6377a887e/docs/private-cloud/release-notes/).

**Comment by BjoernT** [comment]
recheck_ceph

Failed to validate the SSL certificate for monitoring.api.rackspacecloud.com:443

**Comment by BjoernT** [comment]
recheck_all

**Comment by alextricity25** [comment]
This is blocked by some issues we are having with the maas account we use in our gating: https://github.com/rcbops/u-suk-dev/issues/809

**Comment by BjoernT** [comment]
@alextricity25 Thank I knew this already, I had informed the Maas team yesterday since the gate jobs of this PR ran into it virtually first

**Comment by BjoernT** [comment]
recheck_all

**Comment by BjoernT** [comment]
recheck_all

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/staging.horse/build-0711e0cc8c/docs/private-cloud/release-notes/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/staging.horse/build-9dc8f1a89a/docs/private-cloud/release-notes/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/staging.horse/build-e9edf77b51/docs/private-cloud/release-notes/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/staging.horse/build-10b185f8ea/docs/private-cloud/release-notes/).

**Comment by BjoernT** [comment]
recheck_swift

**Comment by BjoernT** [comment]
recheck_all

**Comment by BjoernT** [comment]
@alextricity25 Please review. I tested it in my hardware lab

**Pull request merged**
