### PR TITLE
RO-3857 Fix tempest test results file name

### PR DESCRIPTION
**Pull request by git-harry**
Issue: [RO-3857](https://rpc-openstack.atlassian.net/browse/RO-3857)

### CODE REVIEW

**Comment by git-harry** [comment]
recheck_release

**Comment by odyssey4me** [comment]
I think the release job failure has a number of cards reporting it.

**Comment by git-harry** [comment]
recheck_artifact

**Comment by git-harry** [comment]
Tempest results now shown: https://rpc.jenkins.cit.rackspace.net/job/PR_rpc-openstack-master-xenial_no_artifacts-swift-deploy/54/testReport/

**Pull request merged**
